### ISSUE TITLE
Using updateFile with larger files seems problematic

### ISSUE THREAD

**Issue by richtera** [octokit/octokit.js#1000]
In order to use updateFile you have to have access to the SHA of the file, but getContent is limited to 1M. There doesn't seem to be a way to download the SHA of a file except using getDownload which seems a bit of an overkill since we don't really need to download the file. Is there a method which just downloads the metadata for a file location? This would allow calling of updateFile to put in a new commit even if the file is larger than 1M.

**Comment by gr2m** [comment]
I don’t know out of my head. Could you ask https://github.com/support? They are very nice and responsive. Please let me know what you find out! With the next major breaking release of `@octokit/rest` we will have plugin support so we could implement an updateFile method that works better for larger files, even if it needs several requests internally

**Comment by richtera** [comment]
@gr2m I figured out how to use getReference and getTree to get the SHA to update the file without trying to get it's content just to get the SHA also. Thanks.

**Comment by gr2m** [comment]
Can you share a code snippet on how you did it for future reference?
