### ISSUE TITLE
rename of .getOrganizationMemberships

### ISSUE THREAD

**Issue by ORESoftware** [octokit/octokit.js#1017]
Sorry for the boring question, I was using `require('github')`...I am upgrading a package of mine to octokit. I was using `.getOrganizationMemberships`, but that method is gone. Is there a new method for that one? 

Also, an aside - my Github username is "oresoftware"...I have a lot of repos under that user name...how do I get the repos for that user instead of for an org? To get org repos, I used:

```js
github.repos.getForOrg({org}
```

is there a way to get repos for a user, something like this?

```js
github.repos.getForUser({user})
```

Please lmk, sorry for the lame question :(

**Comment by ORESoftware** [comment]
I see the `index.d.ts` for this version:

  "types": "index.d.ts",
  "version": "15.11.2"

but given that d.ts file, I still can't figure out where `getOrganizationMemberships` went, or how to repos for a user instead of an org.

**Comment by gr2m** [comment]
> I am upgrading a package of mine to octokit. I was using `.getOrganizationMemberships`, but that method is gone. Is there a new method for that one? 

I think [`.users.getOrgMemberships`](https://octokit.github.io/rest.js/#api-Users-getOrgMemberships) is the method you are looking for?

> is there a way to get repos for a user, something like this?

Yes, [`.repos.getForUser()`](https://octokit.github.io/rest.js/#api-Repos-getForUser) is the method you are looking for. You have to pass in the username as parameter

```js
const result = await octokit.repos.getForUser({username: 'ORESoftware'})
```

If you want to get all repositories for the currently authenticated user, you can just use [`.repos.getAll()`](https://octokit.github.io/rest.js/#api-Repos-getAll)

**Comment by ORESoftware** [comment]
thanks, looks like it's

```js
.orgs.getOrgMemberships 
```

not

```js
.users.getOrgMemberships 
```

but I will double check...looks like the typescript types are wrong :(

external TS types are *always* out of sync, it's better to just write the library in typescript, tbh, it's not that much work IMO, and fairly enjoyable.

**Comment by ORESoftware** [comment]
anyway I think this is good will close
