### ISSUE TITLE
docs bug - how to use SSH

### ISSUE THREAD

**Issue by ORESoftware** [octokit/octokit.js#1020]
A quick search does not yield info about SSH in the readme - is there a way to auth using SSH for this library?

**Comment by ORESoftware** [comment]
In other words, right now I am using:

```js
 github.authenticate({
        type: 'basic',
        username: username,
        password: password
      });
```

but I am looking for a way to do this with ssh, something like:

```js
 github.authenticate({
        type: 'ssh',
   });
```

and it could pick up my ssh keys from my env? The main problem is that typing in my plaintext password into a command line tool is a huge security problem. Nobody using my tool will want to type their password in like that, it's a huge red flag.

**Comment by gr2m** [comment]
I disagree, there are plenty of CLI tools where you have to enter your password. It uses the login to generate an authentication token afterwards. If people feel uncomfortable with that, you can explain how they can generate a personal access token with the right scopes and then pass that token instead. We will not add a new type `ssh` to login, but you will be able to create a plugin for that once we release the next major version, which will have a plugin API. Feel free to add further questions, but I’ll close this issue for now

**Comment by ORESoftware** [comment]
idk, ssh is probably the most common auth method at the command line for developers, please reconsider?

**Comment by gr2m** [comment]
how do you use SSH to authenticate against the REST API? I don’t think that is supposted

**Comment by ORESoftware** [comment]
Doesn't look like it's supported, but I am not sure why in theory it wouldn't work, I would need to learn more about how SSH works.

**Comment by willemneal** [comment]
One way that github could do is let you send your email signed with your key.  They already have your key on file so it would just return your secret token as if you had sent your password.
