### ISSUE TITLE
Repos - Create missing ability to create under Organization 

### ISSUE THREAD

**Issue by Trish-Adams** [octokit/octokit.js#1025]
I am trying to understand if octokit rest.js has the ability to create a repository under and organization instead of under a user... 
The documentation mentions creating for organization, but doesn't provide any parameters to actually accomplish this. https://octokit.github.io/rest.js/#api-Repos-create
Am I missing something?  
The Ruby library provides an organization parameter for this purpose -
https://github.com/octokit/octokit.rb/blob/master/lib/octokit/client/repositories.rb#L148

I tried to add organization to my request, but it is still created under a specific User

```
const result = await octokit.repos.create({
              name: req.payload.repoName,
              description: req.payload.description,
              private: 'true',
              organization: req.payload.organization
            })
```

**Comment by gr2m** [comment]
`octokit.repos.create` can be used to create a repository for the currently authenticated user. What you are looking for is [`octokit.repos.createForOrg()`](https://octokit.github.io/rest.js/#api-Repos-createForOrg), could you please give that a try?

**Comment by Trish-Adams** [comment]
You are very right!  Thanks so much - my bad :)
