### ISSUE TITLE
Use a module for requests ?

### ISSUE THREAD

**Issue by nojhamster** [octokit/octokit.js#103]
I'd like to suggest using a module like node-request to handle requests. That would relieve node-github of connections matters like how to deal with proxies or which protocol to use. It's especially useful when dealing with proxies as it supports tunneling and manages by itself to choose the good settings. (in my case a https-over-http tunnel for github api calls)

**Comment by JELaVallee** [comment]
Did this ever get a PR?

I have a corp proxy that requires passing user/secret to the proxy and current release doesn't appear to support such.  Would like to get a consistent work-around as #102 doesn't solve this particular issue (as far as I can tell).

**Comment by abtris** [comment]
You can use our https://github.com/apiaryio/node-github/tree/production version.

**Comment by quocvu** [comment]
+1

We usually deploy our apps behind a VIP
