### ISSUE TITLE
Troubles posting comment to a pull request using GitHub app API

### ISSUE THREAD

**Issue by ondrejmirtes** [octokit/octokit.js#1030]
Hello,
I am trying to post a comment to a pull request on behalf of GitHub app and I get this error:

```
Could not resolve to a node with the global id of 'MDExOlB1bGxSZXF1ZXN0MjE3NTE5NzYw'
```

I enabled debug messages in Octokit, so this is the full output:

```
Posting comment to PR #8073
  octokit:rest REQUEST: { timeout: 0,
  agent: undefined,
  method: 'post',
  url: 'https://api.github.com/repos/slevomat/slevomat/issues/8073/comments',
  headers:
   { accept: 'application/vnd.github.squirrel-girl-preview',
     'user-agent': 'octokit/rest.js v15.11.4',
     authorization: 'token xxx },
  body:
   { body: 'Foo' } } +583ms
{ {"message":"Validation Failed","errors":[{"resource":"IssueComment","code":"unprocessable","field":"data","message":"Could not resolve to a node with the global id of 'MDExOlB1bGxSZXF1ZXN0MjE3NTE5NzYw'."}],"documentation_url":"https://developer.github.com/v3/issues/comments/#create-a-comment"}
```

The code looks like this:

```
await appInstallation.issues.createComment({
	owner: payload.repository.owner.name,
	repo: payload.repository.name,
	number: pullRequest.number,
	body: 'Foo',
});
```

I checked that I have both PR and issues write permissions. What am I doing wrong?

**Comment by gr2m** [comment]
This all looks right to me 🤔 

Could you try a curl command? 

```bash
curl -X POST -H "Accept: application/vnd.github.squirrel-girl-preview" -H"Authorization: token xxx" https://api.github.com/repos/slevomat/slevomat/issues/8073/comments -d '{"body": "foo"}'
```

If that gives you the same result, can you send the curl command with the error message to support? https://github.com/support They will forward it to the API team. Support is great and very responsive :)

**Comment by ondrejmirtes** [comment]
Yes, it's a problem with their API, the support responded to me that they are working to it and that meanwhile I can fix it with "repository metadata" permissions :) Thank you!

**Comment by JJ** [comment]
Is this fixed now?

**Comment by gr2m** [comment]
@JJ make sure your app have read access to the repository metadata permission. It will save you a lot of headache.

**Comment by JJ** [comment]
@gr2m It does have. The problem is that apparently no one without write access to the repository can't create anything there. This causes actions/first-interaction#10, for instance,  as well as actions/labeler#12. I wouldn't say this is a feature, but looks more like a bug.

**Comment by gr2m** [comment]
That sounds it's an unrelated issue. The original issue was about a GitHub App, the issues you linked are about GitHub Actions?

**Comment by JJ** [comment]
Right, the error message is different. Thanks for answering anyway.
