### ISSUE TITLE
mergeable_state missing from from PullRequestGetResponse type

### ISSUE THREAD

**Issue by parshap** [octokit/octokit.js#1038]
I started getting a new TypeScript compile errors after upgrading to the latest @octokit/rest. It looks like at some point many actual TypeScript type definitions were added here in `index.d.ts` instead of using `any`. One field I use is `mergeable_state` from pull request objects. This field is not included in the `PullRequestGetResponse` type definition in `index.d.ts` and is thus now causing an error for me.

I noticed that this field is [*not* documented in the REST API](https://developer.github.com/v3/pulls/#get-a-single-pull-request), even though the field is returned. It [*is* documented in the GraphQL API](https://developer.github.com/v4/enum/mergestatestatus/). [This community post](https://platform.github.community/t/documentation-about-mergeable-state/4259/4) shed some light on this for me.

It seems like the type definitions here are automatically generated based on the REST API docs, so perhaps the right thing to do is make sure this property is documented in the REST API docs, which would then fix the type definition here too.

**Comment by gr2m** [comment]
Thanks Parsha!

> It seems like the type definitions here are automatically generated based on the REST API docs, so perhaps the right thing to do is make sure this property is documented in the REST API docs, which would then fix the type definition here too.

Correct 👌 

Can you work around it somehow for the time being?

**Comment by parshap** [comment]
Yes, I'm using a `// @ts-ignore` comment for now to disable type checking on that line.

**Comment by parshap** [comment]
Are the REST API docs hosted on a repo somewhere? I'm happy to send a PR for the fix.

**Comment by parshap** [comment]
I've sent a help request to support. Thanks!

> To summarize, the response at https://developer.github.com/v3/pulls/#response-1 should include a mergeable_state key, right?

Yes, that's correct.

**Comment by gr2m** [comment]
Thank you! I’m sure they will ask the docs team to fix it now, I’ll set myself a reminder to check after Universe. Probably everyone at GItHub is quite occupied with preparing things for it: https://githubuniverse.com/.

For the time being, this is not blocking for you as you have a workaround, right?

**Comment by parshap** [comment]
Correct, I am not blocked. Thank you for checking!

**Comment by gr2m** [comment]
> To summarize, the response at https://developer.github.com/v3/pulls/#response-1 should include a mergeable_state key, right?

Looks like it was fixed. Can you check if the problem still occurs in [v16](https://github.com/octokit/rest.js/releases/tag/v16.0.0)?

**Comment by gr2m** [comment]
this should be resolved in v16. Please reopen if not

**Comment by parshap** [comment]
Excellent, thank you. I haven't had a chance to validate yet, but if I find any issues once I do I will re-open.
