### ISSUE TITLE
Deprecation of users.getInstallations

### ISSUE THREAD

**Issue by br0wn** [octokit/octokit.js#1063]
Method `users.getInstallations` was deprecated in commit 4744f95202373b92730a64081049235e3fab21e2. Was this intentional? As the API is still stated in [Github API docs](https://developer.github.com/v3/apps/#list-installations-for-user) without any notice of deprecation.

If so, isn't it so that aliasing it to `apps.getInstallations` won't work since they use different type of tokens (user to server vs JWT) ?

**Comment by gr2m** [comment]
No I think everything is correct. The reason why `users.getInstallations` got deprecated in favor of `apps.getInstallations` is that the REST API endpoint is also documented in the GitHub Apps section. It is still the same endpoint. The docs state 

> You must use a user-to-server OAuth access token, created for a user who has authorized your GitHub App, to access this endpoint.

I don’t think that API endpoint can be used with  JSON Web Token? Am I missing something?

**Comment by gr2m** [comment]
Ahh okay, there is https://developer.github.com/v3/apps/#find-installations (`GET /app/installations`) and https://developer.github.com/v3/apps/#list-installations-for-user (`GET /user/installations`) but the latter is not in the `lib/routes.json` file, I’m investigating
