### ISSUE TITLE
Issue with included node-fetch

### ISSUE THREAD

**Issue by x8x** [octokit/octokit.js#1066]
Having this problem https://github.com/bitinn/node-fetch/issues/502 .
What about switching to axios ?

**Comment by gr2m** [comment]
We use node-fetch to minimize the bundle size for browser usage. 

But you will be able to replace the entire request logic to your liking, I’m figuring this out right now. Would something like that work for you?

```js
const axios = require('axios');
github.hooks((request, options) => {
  return axios(options)
})
```

`request` in the above method is the original request method which would use node-fetch. 

But even better would be to help `node-fetch` to get the issue resolved ;)

I’ll close the issue but feel free to continue commenting, I will reopen it if it becomes actionable

**Comment by x8x** [comment]
Right, better would be a `node-fetch` fix! :+1:
Will use your `axios` snippet in the meantime.
Thanks!
