### ISSUE TITLE
unable to verify first certificate

### ISSUE THREAD

**Issue by TPiddy** [octokit/octokit.js#1067]
```
try {
        octokit.authenticate({ type: 'token', token: OAUTH.token });
        const result = await octokit.pullRequests.create(params);
        return kit
            .response(result)
            .code(201)
            .type(MimeTypes.JSON);
    } catch (error) {
        throw Boom.internal(error.message, error);
    }
```

params are well-formed, but I'm not 100% sure why I'm getting this issue....

When I go into our enterprise Github via browser, the projects are listed as ORG_CODE / REPO_NAME
so I've put those in the "owner" and "repo" fields of the PR. 

My octokit invocation is pulled from the tutorial:

```
octokit = require('@octokit/rest')({
            timeout: 0, // 0 means no request timeout
            headers: {
                accept: 'application/vnd.github.v3+json',
                'user-agent': 'octokit/rest.js v1.2.3', // v1.2.3 will be current version
            },

            // custom GitHub Enterprise URL
            baseUrl: 'enterprise url',

            // Node only: advanced request options can be passed as http(s) agent
            agent: undefined,
        });
```

and I'm still getting 500: unable to verify first certificate

**Comment by gr2m** [comment]
The enterprise URL, does it end with `/api/v3`?

The code looks good to me otherwise ...

Maybe isolate the code, run just this

```js
octokit = require('@octokit/rest')({
            timeout: 0, // 0 means no request timeout
            headers: {
                accept: 'application/vnd.github.v3+json',
                'user-agent': 'octokit/rest.js v1.2.3', // v1.2.3 will be current version
            },

            // custom GitHub Enterprise URL
            baseUrl: 'enterprise url',

            // Node only: advanced request options can be passed as http(s) agent
            agent: undefined,
        });
octokit.authenticate({ type: 'token', token: process.env.TOKEN });
await octokit.pullRequests.create(params);
```

and run it with `TOKEN=<your token here> node your-script.js` and see if you still get the error?

**Comment by TPiddy** [comment]
@gr2m I suspected it may be a URL issue, but even after correcting my issue I still get this problem....

I've even called https://*hostname*/api/v3?access_token=*token* and I get a valid response...

**Comment by TPiddy** [comment]
Ok, was able to successfully create one using POSTman with the SSL cert verification turned off...

Not sure if that helps? I'm also behind a corporate firewall so that may be causing problems.

**Comment by TPiddy** [comment]
@g2rm is there any way to turn off SSL cert verification with the library?

**Comment by TPiddy** [comment]
Yep, that did it... thanks for all your help :)

**Comment by TPiddy** [comment]
Ok, now I'm stuck again... I'm getting 'no commits between *copy* and *develop*'.... 
The API is not exactly clear on what should go in to "head" and "base"... is it the name of the branch? The full ref?

**Comment by TPiddy** [comment]
When I do a comparison of the two branches in question using the GUI it shows the exact difference I am expecting to see...

**Comment by TPiddy** [comment]
since original issue is resolved, closing ticket

**Comment by axel3rd** [comment]
Comment put here because this issue is many given in searches engines ...

**Use case**:
- Octokit used included in third part (sample: AWS lambda) that you cannot modify
- GitHub Enterprise (GHE) with certificate from custom certification chains (=> not known at client runtime)
- Possible error message(s):
  - *unable to verify the first certificate*
  - *self signed certificate in certificate chain*

> is there any way to turn off SSL cert verification with the library?

Via NodeJs directly and **[NODE_TLS_REJECT_UNAUTHORIZED](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value)** environment variable (=> easy to set at any runtime):

```
NODE_TLS_REJECT_UNAUTHORIZED=0
```

Yes it is insecure, it logs a warning, but sometimes .... could help 😁.
