### ISSUE TITLE
pull request fails with 'no commits between <head> and <base>'

### ISSUE THREAD

**Issue by TPiddy** [octokit/octokit.js#1070]
I'm trying to create a pull request and it's failing with no commits between `head` and `base` branch names.

I can, however, create the pull request in POSTman using the same parameters. 

```
const octokit = getOctokit();

    const params: PullRequestsCreateParams = {
        owner: getRepoOwner(currentProject.repositoryUrl),
        repo: getRepoName(currentProject.repositoryUrl),
        head: currentProject.rootBranch,
        base: currentProject.contentBranch,
        title: request.payload['title'],
        body: request.payload['body'],
        maintainer_can_modify: false
    };

    try {
        octokit.authenticate({ type: 'token', token: OAUTH.token });
        const result = await octokit.pullRequests.create(params);
        return kit
            .response(result)
            .code(201)
            .type(MimeTypes.JSON);
    } catch (error) {
        throw Boom.internal(error.message, error);
    }
```

**Comment by gr2m** [comment]
I created pull requests before with `@octokit/rest`, it should work :) 

If you run your script in Node, can you run it setting the `DEBUG` environment variable to `octokit*`? E.g. `DEBUG=octokit* node my-script.js`. That should log the request being sent so you can compare to the request you send with POSTman

**Comment by TPiddy** [comment]
Yep, turns out I'm an idiot.... had the base / head reversed in my code but not in POSTman
