### ISSUE TITLE
Request new method: getStatus (not getStatuses)

### ISSUE THREAD

**Issue by tunnckoCore** [octokit/octokit.js#1088]
Seems like there is no `getStatus`, but there is `getStatuses`.

What i'm requesting is https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref

```
GET /repos/:owner/:repo/commits/:ref/status
```

It returns the state of all statuses combined.

So later you can just check `response.state === success` if you care to do something if all statuses are passed.

In my scenario, it is the following

1. If `response.state === success`, OK
2. If `response.state === pending`, loop over `response.statuses` to check further each individual status

In my case I care if all CI statuses are OK, but if the `status` as a whole is `success` too, then that's okey too.

**Comment by gr2m** [comment]
I think what you are looking for is https://octokit.github.io/rest.js/#api-Repos-getCombinedStatusForRef, does that work for you?

**Comment by tunnckoCore** [comment]
Ah, yea. Good catch.
