### ISSUE TITLE
For github app Authentication what is the token?

### ISSUE THREAD

**Issue by inyee786** [octokit/octokit.js#1101]
I want to post  comments on issue via github bot, i am trying to authenticate it with the bot , but i don't know what to put in token  

// GitHub app
```
octokit.authenticate({
  type: 'app',
  token: 'secrettoken123'
});

octokit.issues.createComment({
	owner: 'inyee786',
	repo: 'percona-dashboard',
	number: 10,
	body: 'Foo',
});
```

**Comment by gr2m** [comment]
Hi Intakhab, what you need is an installation token. For that you use the [`octokit.apps.createInstallationToken({installation_id})
`](https://octokit.github.io/rest.js/#api-Apps-createInstallationToken) method. You first need to authenticate as app using a bearer token

```js
const appId = <your app id here>
const privateKey = <content for your app’s private key here>
const installationId = <id of installation>
const jsonwebtoken = require('jsonwebtoken')
const now = Math.floor(Date.now() / 1000)
const payload = {
  iat: now, // Issued at time
  exp: now + 60, // JWT expiration time
  iss: appId
}
const bearer = jsonwebtoken.sign(payload, privateKey, {algorithm: 'RS256'})
```

Than use that bearer token to authenticate as the application

```js
octokit.authenticate({
  type: 'app',
  token: bearer
});
```

Now you can receive an installation token

```js
const { data: { token } } = await octokit.apps.createInstallationToken({installation_id})
```

Now you have the token to authenticate as the app installation

```js
octokit.authenticate({
  type: 'token',
  token
})
```

Finally, you can create the comment

```js
octokit.issues.createComment({
	owner: 'inyee786',
	repo: 'percona-dashboard',
	number: 10,
	body: 'Foo',
})
```

We are working on making this all simpler with [`@octokit/app`](https://github.com/octokit/app.js/pull/6). 

If you are building a GitHub app that listens to webhooks from GitHub, I recommend to check out https://probot.github.io/

**Comment by inyee786** [comment]
In "privateKey" do I have to put all the content of the private-key.pem file?

How can I get the installation id at first time??
{{installation_id}}

**Comment by inyee786** [comment]
Thanks, @gr2m for the quick reply, 

I want to use probot but,
i have a scenario where i have  to post a comment on pull request when the build is complete for that i have set  the context and i don't know how to set the context

**Comment by gr2m** [comment]
do you have all you need now? Can we close the issue?

**Comment by johnsonsamuel** [comment]
I am getting the following error 

10:17:19.510Z ERROR probot: You must authenticate via a GitHub App.
  HttpError: You must authenticate via a GitHub App.
      at response.text.then.message (/file.js:66:23)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)


```const Octokit = require("@octokit/rest");

const octokit = Octokit({auth: "personalToken"}); 

any thoughts ?

**Comment by gr2m** [comment]
The error says that for the request you want to make, you need to authenticate as a GitHub app, but you pass a personal access token to `Octokit`. See https://github.com/octokit/auth.js#readme for a list of all existing authentication strategies.
