### ISSUE TITLE
Typings and documentation not consistent with routes.js

### ISSUE THREAD

**Issue by mamodom** [octokit/octokit.js#1103]
As you can see in [this runkit](https://runkit.com/mamodom/octokit-rest-bug) I'm using [this](https://octokit.github.io/rest.js/#api-Repos-uploadAsset) method which fails as you can see in the previously linked runkit.

These docs are consistent with the typescript typings (included below), which in hindsight made sense once I saw [this](https://github.com/octokit/rest.js/blob/f54006738edfb7ef494d97f23ca6b7a49b934a80/scripts/README.md)

By digging deeper I saw  [here](https://github.com/octokit/rest.js/blob/v15.17.0/lib/routes.json#L10193) that `Content-Type` and `Content-Length` were expected inside a `headers` object.

In js I could just ignore the documentation error and pass these values inside the `headers` object, but in typescript I get a compilation error:

```
Argument of type '{ url: string; name: string; file: string; headers: { 'Content-Length': number; 'Content-Type': string; }; }' is not assignable to parameter of type 'ReposUploadAssetParams'.
  Object literal may only specify known properties, and 'headers' does not exist in type 'ReposUploadAssetParams'.
```

If docs and typings are generated based on `lib/routes.json` why aren't they consistent with [this route](https://github.com/octokit/rest.js/blob/v15.17.0/lib/routes.json#L10193) ? (This might be the source of the error)

**Comment by gr2m** [comment]
Hey @mamodom I’m sorry for the inconsistencies with the docs & typescript definitions. You could do me a big favor to check if the problem still exists in

1. https://github.com/octokit/rest.js/pull/1094 – this PR is deprecating lots of methods and I would like it to still work with Typescript. I think there is a bug in the current `master` that you just run into yourself, I’d love to get it fixed, but I need help, I’m not using TYpescript myself. See https://github.com/octokit/rest.js/pull/1094#issuecomment-437601203
2. https://github.com/octokit/rest.js/pull/1052 – this is the upcoming v16. Everything is now generated from @octokit/routes so there should be no inconsistencies here

Thanks a lot!

**Comment by gr2m** [comment]
> If docs and typings are generated based on lib/routes.json why aren't they consistent with this route ? (This might be the source of the error)

Sorry I missed to answer your question here. The reason is that `lib/routes.json` is in fact not fully generated from `@octokit/routes` in v15 / current master. Instead, updates from @octokit/routes are merged into `lib/routes.json` as we maintained deprecations and aliases in `lib/routes.json`. But I will move these into `@octokit/routes` for future deprecations, so starting with v16 everything is generated from @octokit/rest. You can test it by installing the `next` branch (but you’ll need to build the typescript definitions yourself, as these are run automatically before the release to npm)

**Comment by mamodom** [comment]
Hey @gr2m Thanks for the quick reply, 

I'll find some time tomorrow to check if the problem still exists in these branches.

Also thanks for the explanation [here](https://github.com/octokit/rest.js/issues/1103#issuecomment-437726338). during my quick digging I wasn't aware of `@octokit/routes`

**Comment by gr2m** [comment]
Hey Maximo, v16 is released now: https://github.com/octokit/rest.js/releases/tag/v16.0.0

The endpoint methods, API docs and typings should all be in sync now, they are all fully generated from `@octokit/routes`.

**Comment by mamodom** [comment]
Hey @gr2m I've spent a couple of hours checking out the changes. There are still a few problems, I'll create separate issues for each of them.

**Comment by gr2m** [comment]
Thanks a lot, I see the notifications. I’ll have a look at them
