### ISSUE TITLE
 Property 'listRepos' does not exist on type.

### ISSUE THREAD

**Issue by SergioFaya** [octokit/octokit.js#1123]
I am using octokit to get the repos of a given user but when calling listRepos I get the following error.
```
[ts] Property 'listRepos' does not exist on type '{ addRepoToInstallation(params: AppsAddRepoToInstallationParams, callback?: Callback<Response<AppsAddRepoToInstallationResponse>>): Promise<Response<AppsAddRepoToInstallationResponse>>; ... 16 more ...; removeRepoFromInstallation(params: AppsRemoveRepoFromInstallationParams, callback?: Callback<...>): Promise<...>; }'.
```
Can it be an error with the type file or with my tsconfig file? I am quite new to typescript and I am wondering if it can be that I missconfigured something.

This is the function invocation_
![image](https://user-images.githubusercontent.com/15983833/48726505-dff82600-ec2f-11e8-9b58-556f14993ab7.png)

This is the config file in case it is needed:
```
//tsconfig.json
{
    "compilerOptions": {
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "newLine": "LF",
        "preserveConstEnums": true,
        "removeComments": true,
        "noUnusedLocals": false,
        "noUnusedParameters": true,
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es6",
        "pretty": true,
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dst",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        },
        "lib": [
            "es2015",
            "dom"
        ]
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules/*"
        ]
}
```

**Comment by SergioFaya** [comment]
Yeah, I was using version 15.17, I updated now to version 16 and when I run `tsc` everything works fine. 
Thanks.

To avoid get confused with versions in the future, is there a way to get notified when the version changes or you have some nightly builds or something?

**Comment by gr2m** [comment]
I’d recommend to subscribe to https://github.com/octokit/rest.js/issues/620 to stay in the loop :)
