### ISSUE TITLE
Missing functions under octokit.users

### ISSUE THREAD

**Issue by lera222** [octokit/octokit.js#1125]
according to the [docs](https://octokit.github.io/rest.js/#api-Users-getAuthenticated) there should be a function called `octokit.users.getAuthenticated`. However, running the following code, yields an `UnhandledPromiseRejectionWarning: TypeError: octokit.users.getAuthenticated is not a function` error.

``` js
     octokit.authenticate({
        type: 'token',
        token: access_token
    });

    const user = await octokit.users.getAuthenticated();

```

here's the full list of the members I'm getting for `octokit.users`

```
acceptRepoInvite
addEmails
addRepoToInstallation
blockUser
checkBlockedUser
checkFollowing
checkIfOneFollowersOther
createGpgKey
createKey
declineRepoInvite
deleteEmails
deleteGpgKey
deleteKey
demote
editOrgMembership
followUser
get
getAll
getBlockedUsers
getById
getContextForUser
getEmails
getFollowers
getFollowersForUser
getFollowing
getFollowingForUser
getForUser
getGpgKey
getGpgKeys
getGpgKeysForUser
getInstallationRepos
getInstallations
getKey
getKeys
getKeysForUser
getMarketplacePurchases
getMarketplaceStubbedPurchases
getOrgMembership
getOrgMemberships
getOrgs
getPublicEmails
getRepoInvites
getTeams
promote
removeRepoFromInstallation
suspend
togglePrimaryEmailVisibility
unblockUser
unfollowUser
unsuspend
update

```
running version `15.17.0`

**Comment by gr2m** [comment]
I’m sorry for the trouble, the docs are already for v16. To install it you need to run

```
npm install @ocotkit/rest@next
```

Could you give that a try please?

**Comment by lera222** [comment]
yep, that does the trick. Thank!

btw, man, what a great responsiveness @gr2m ! I'm highly impressed.

I thought it might have been a version issue, but couldn't have imagined that `getAuthenticated()` had not been there from day one. how new is actually?

**Comment by gr2m** [comment]
Happy to help :) It’s 4 days old: https://github.com/octokit/rest.js/releases/tag/v16.0.0. 

I listed all the method renames here, I hope they are more consistent and clear now: https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations

**Comment by lera222** [comment]
@gr2m everything makes so much more sense now, thanks again :)
