### ISSUE TITLE
TypeError: merge.all is not a function

### ISSUE THREAD

**Issue by dooleyb1** [octokit/octokit.js#1129]
Just updated to `"@octokit/rest": "^16.0.1",` and as soon as I call `npm start` to start up my ReactJS project I encounter the following error in browser.

`TypeError: merge.all is not a function`

The project was working fine previous to this update and no further changes were made. Any idea what is causing this issue?

**Comment by gr2m** [comment]
The update from v15 to v16 had plenty of breaking changes, hence the major version bump from 15 to 16. The release notes include information on what changed and how to upgrade: https://github.com/octokit/rest.js/releases/tag/v16.0.1

**Comment by dooleyb1** [comment]
Okay I see, will perform the suggestions in these notes and report back.

**Comment by gr2m** [comment]
I’m pretty sure that it will resolve your issue :) If not, please reopen

**Comment by gr2m** [comment]
The problem was with a sub dependency, it has been resolved, it has been resolved via https://github.com/octokit/endpoint.js/releases/tag/v3.1.1. 

You can check if you have that version or higher with `npm ls @octokit/endpoint`. If not, delete package-lock.json and node_modules and reinstall

**Comment by andymckay** [comment]
I found the distributions on the releases page had the `merge.all` error. So I cloned the source and built it, but noticed that I had the same source and endpoint 3.1.0:

```
➜  rest.js git:(master) ✗ npm ls @octokit/endpoint
@octokit/rest@0.0.0-semantically-released /Users/andymckay/sandboxes/rest.js
├─┬ @octokit/request@2.2.0
│ └── @octokit/endpoint@3.1.0 
└─┬ semantic-release@15.12.1
  └─┬ @semantic-release/github@5.2.5
    └─┬ @octokit/rest@16.0.3
      └─┬ @octokit/request@2.1.2
        └── @octokit/endpoint@3.1.0  deduped
➜  rest.js git:(master) ✗ npm install @octokit/endpoint      
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ @octokit/endpoint@3.1.1
updated 2 packages in 9.472s
➜  rest.js git:(master) ✗ npm ls @octokit/endpoint           
@octokit/rest@0.0.0-semantically-released /Users/andymckay/sandboxes/rest.js
├── @octokit/endpoint@3.1.1 
├─┬ @octokit/request@2.2.0
│ └── @octokit/endpoint@3.1.1  deduped
└─┬ semantic-release@15.12.1
  └─┬ @semantic-release/github@5.2.5
    └─┬ @octokit/rest@16.0.3
      └─┬ @octokit/request@2.1.2
        └── @octokit/endpoint@3.1.1  deduped
➜  rest.js git:(master) ✗ npm run-script build
```

And then the version in `dist` worked successfully.

**Comment by colmjude** [comment]
I had the same issue when trying to use a version downloaded from the [releases page](https://github.com/octokit/rest.js/releases).

So thanks @andymckay for the solution. Cloning and building local worked for me too.
