### ISSUE TITLE
Hook API: pass `endpoint` to the hooks `options`

### ISSUE THREAD

**Issue by pvdlg** [octokit/octokit.js#1131]
Related to https://github.com/semantic-release/github/pull/123.

In order to determine how much to throttle we need to know:
1. The [rate limit](https://developer.github.com/v3/rate_limit/#get-your-current-rate-limit-status) category
2. If the API call would trigger a notification (as GitHub further limit those calls)

For 1. we would need to know which endpoint/command was called in the hook callback (for example `repos.get`, `repos.createRelease` etc...).

Then we could figure out 2. by calling `github.[endpoint].[command].endpoint().method` to know if the request is a `GET` or `POST`. But to do that we also need to know which endpoint/command was called.

So ideally the `options` object passed to the hook callback would contains something like `{endpoint: 'repos.get'}` or `{endpoint: 'repos', command: 'get'}`.

**Comment by gr2m** [comment]
> But to do that we also need to know which endpoint/command was called

I was wondering about that. I think it might be enough to check the URL? We could check if options.url is e.g. 

- `/repos/:owner/:repo/issues`
- `/repos/:owner/:repo/issues/:number/comments`
- `/repos/:owner/:repo/pulls`

and probably a few more, but it’s a limited list. I asked the GitHub folks if they could give me the list of endopints that cause notifications but it’s not easy to find out for them from the code. I plan to maintain a list of these URLs to address this issue, too: https://github.com/octokit/routes/issues/298

I think the combination of `options.method === 'POST' and urls.include(options.url)` should do to check if the request would trigger a notification?

**Comment by pvdlg** [comment]
To check if the call is going to trigger a notification we just use the method (`GET` will not trigger a notification, anything else might).

The thing that could be added is a better to determine the rate limit category.
Currently there is only 3 categories (`search`, `core` and `graphql`) so I guess we could parse the URL to figure out if it's a `search` request or not. But maybe we could add the limit category to the `options`.

**Comment by pvdlg** [comment]
So in order to determine the [rate limit category](https://developer.github.com/v3/rate_limit/#understanding-your-rate-limit-status), what do you suggest? Parsing `options.url`? Or would you add `rateLimit` property that would contains either `core`, `search` or `graphql` (or any other GitHub might add in the future)?

**Comment by gr2m** [comment]
> or in options directly.

We can’t put it in `options.*` directly because it would be passed as query parameter or in the request body, depending on the method. Hence the special `options.request.*`, they will be ignored in the actual request and can be used for meta information, see https://github.com/octokit/request.js#octokitrequest

> Looking at the `url` is fine for now as there is only 3 categories. As there is multiple [search endpoints](https://developer.github.com/v3/search) we could do something like that: `const category = options.url..startsWith('/search') ? 'search' : 'core'`.

sounds great!

**Comment by gr2m** [comment]
Can we close the issue?

**Comment by pvdlg** [comment]
Yes I think so as there is only a limited number of rate limit category we can use the `options.url`.
If GitHub were to add more category that might be great to have that in `options.request` though.
