### ISSUE TITLE
Typings for Webhook payloads

### ISSUE THREAD

**Issue by julien-c** [octokit/octokit.js#1132]
According to the [Webhook API doc](https://developer.github.com/webhooks/#payloads), webhook payloads mostly mirror the structure of the REST API's `Events`, so I was wondering if one could use the type information contained in this repo to type webhooks?

This issue is related to https://github.com/octokit/webhooks.js/issues/30 (on webhook.js) – which sounds awesome – but I guess aims to solve my issue in a more short-term and hackish way (how to reuse defined types for mostly similar structures).

(cc @bkeepers)

**Comment by gr2m** [comment]
Salut Julien 👋

> use the type information contained in this repo to type webhooks

I honestly don’t know, but maybe worth investigating? I’ll look into `@octokit/webhooks` soon, it only got neglected as we focused on getting `@octokit/rest` v16 out

**Comment by gr2m** [comment]
I’ve created https://github.com/octokit/webhooks, might that be useful somehow? It includes the example payloads from the documentation

**Comment by julien-c** [comment]
sounds good to me @gr2m
