### ISSUE TITLE
OS version undetectable on Microsoft Azure - throws "Command failed: wmic os get Caption" error

### ISSUE THREAD

**Issue by katherdx** [octokit/octokit.js#1145]
I am trying to get the archive link from my node js application.This is working fine in my local machine but i am getting error in azure private app service. 

```js
octokit.repos.getArchiveLink({ owner, repo, archive_format, ref})
```
 
on executing this command in azure private app service I am getting the following error:

```
{ Error: Command failed: wmic os get Caption
Access is denied.
    at makeError (D:\home\site\wwwroot\node_modules\execa\index.js:172:9)
    at Function.module.exports.sync (D:\home\site\wwwroot\node_modules\execa\index.js:341:15)
    at module.exports.release (D:\home\site\wwwroot\node_modules\windows-release\index.js:34:24)
    at module.exports (D:\home\site\wwwroot\node_modules\os-name\index.js:39:18)
    at getUserAgentNode (D:\home\site\wwwroot\node_modules\universal-user-agent\index.js:6:51)
    at restEndpoint (D:\home\site\wwwroot\node_modules\@octokit\rest\lib\endpoint\index.js:27:48)
    at restRequest (D:\home\site\wwwroot\node_modules\@octokit\rest\lib\request\index.js:7:26)
  code: 1,
  stdout: '',
  stderr: 'Access is denied.\r\n',
  failed: true,
  signal: null,
  cmd: 'wmic os get Caption',
  timedOut: false } 
```

**Comment by gr2m** [comment]
I do not think that this is related to octokit. Could you please ask the Azure support what the "wmic os get Caption" means? 

The `.getArchiveLink` method is handling a redirect to where the actual File is stored and then downloads its content which in your case is a zipfile. 

I’ll close the issue ones we find out if there is something we can do about it on our side

**Comment by 102** [comment]
As a workaround, azure users can downgrade to `{"@octokit/rest": "~15.11.4"}` (the latest version without `universal-user-agent`)

Related issue in underlying package https://github.com/sindresorhus/windows-release/issues/10

@gr2m, is there a chance that replacement/removal of this dependency will be a proper issue to have?

**Comment by gr2m** [comment]
> As a workaround, azure users can downgrade to `{"@octokit/rest": "~15.11.4"}` (the latest version without `universal-user-agent`)

@102 could you please make a separate issue with more details about why it fails on Azure? I assume it fails at some point in https://github.com/sindresorhus/os-name/blob/master/index.js, maybe create an issue there if that’s the case and mention me? I’m happy to make changes to make it not fail on Azure

**Comment by gr2m** [comment]
Ah sorry, I see that the issue was already created at https://github.com/sindresorhus/windows-release/issues/10, I’ll watch it. I’ll try to work around it for the time being

**Comment by gr2m** [comment]
If the `Command failed: wmic os get Caption` error is thrown, what should we set the version to? Maybe `Windows <version undetectable>` or just `Windows`?

**Comment by 102** [comment]
> If the `Command failed: wmic os get Caption` error is thrown, what should we set the version to? Maybe `Windows <version undetectable>` or just `Windows`?

I think the version that explicitly states that something went wrong is preferable.

Btw, looks like `windows-release` pre-2.0 does not depend on `wmic` executable, https://github.com/sindresorhus/windows-release/blob/v1.1.1/index.js (if it can somehow help)

**Comment by gr2m** [comment]
The usage of `wmic` was introduced for Windows Server detection: https://github.com/sindresorhus/windows-release/pull/7

We won’t get the explicit version in this case. We could say `Windows Server` though?

**Comment by 102** [comment]
This should definitely work fine for azure's case, but won't work for desktop win ≥7 with `wmic` disabled (does it matter anyway?)

**Comment by gr2m** [comment]
Don’t think so :) But also telling from https://github.com/sindresorhus/windows-release/pull/7 it looks like the `wmic` workaround is explicitly for Windows Server, other versions are detected by the previous code

**Comment by gr2m** [comment]
so `Windows <version undetectable>` then? I mean this is an edge case anyway and maybe Sindre will come up with something better, they are much smarter than me :)

**Comment by 102** [comment]
`Windows <version undetectable>` looks good to me

Btw, thanks for the great support, you're amazing!
