### ISSUE TITLE
TypeScript typings  not updated for new paginate and endpoint.merge methods

### ISSUE THREAD

**Issue by cliffkoh** [octokit/octokit.js#1159]
The TypeScript typings published with octokit/rest.js do not reflect the `.endpoint.merge` method and the `.paginate` method (even though the old `hasNextPage` and related methods have been removed).

Package version: @octokit/rest@16.2.0

**Comment by gr2m** [comment]
Hi Cliff, thanks for reporting the isuse! Would you mind sending a pull request? 

In the longer term we will likely rewrite all the Octokit libraries to Typescript, I wanted to start with https://github.com/octokit/endpoint.js actually, but I didn’t get to it yet. Always happy to help others contribute if you are interested :)

**Comment by cliffkoh** [comment]
Hey @gr2m, thanks for the quick triage. I don't presently have bandwidth for this atm (and so am resorting to a very ugly cast to any for now with a TODO to remove) but at the very least I promise I am not doing a private fix in a fork :)

**Comment by gr2m** [comment]
Hey @cliffkoh I added new Typescript definitions

Pagination: 

https://github.com/octokit/rest.js/blob/06b20695fdc2dfabe672818692e8adf3b2cdf4bf/scripts/templates/index.d.ts.tpl#L158-L171

`.request` and `.request.endpoint`

https://github.com/octokit/rest.js/blob/06b20695fdc2dfabe672818692e8adf3b2cdf4bf/scripts/templates/index.d.ts.tpl#L79-L89

`.endpoint.merge()` is still missing, but can you check if the others work for you?

**Comment by cliffkoh** [comment]
Thanks! Is this part of the 16.7.0 release?

(Also out of curiosity, is there something about .merge in particular that caused it to not be part of this fix?)

**Comment by gr2m** [comment]
Yes, it's all in 16.7.0.

> (Also out of curiosity, is there something about .merge in particular that caused it to not be part of this fix?)

No reason, I just forgot about it :) The reason so many Typescript definitions were added is the upgrade of Probot to the v16: https://github.com/probot/probot/pull/774. And probot itself is written in Typescript.

By the way I plan to rewrite all the Octokit libraries to Typescript, starting with `@ocotkit/endpoint`: https://github.com/octokit/endpoint.js/issues/23. Typescript is still new to me and I could use any help I can get :)

**Comment by gr2m** [comment]
@cliffkoh  could you check if it works for you now?

**Comment by cliffkoh** [comment]
It works :) Sorry for the delay, I was on vacation.
