### ISSUE TITLE
Calling `endpoint.merge` in 16.2.0 results in deprecation warning

### ISSUE THREAD

**Issue by cliffkoh** [octokit/octokit.js#1160]
I'm seeing an issue where calling endpoint.merge on an endpoint method (as documented in readme.md) calls into octokit-pagination-methods's legacy `hasNextPage`, which results in a deprecate warning...

(I am having a hard time finding where merge is implemented so I can manually verify this - but this behavior I am reporting is based on observing the callstack at the point where the deprecation warning is generated)

**Comment by gr2m** [comment]
can you please run `npm ls @octokit/endpoint`? And see what version it shows? The problem was fixed in https://github.com/octokit/endpoint.js/releases/tag/v3.1.1

**Comment by cliffkoh** [comment]
![image](https://user-images.githubusercontent.com/1003246/50034786-4fed9800-ffb3-11e8-9f54-3259d9174b31.png)
)

Which would explain the issue I'm seeing :) 

The thing is, package.json in @octokit/rest asks for 2.2.0

![image](https://user-images.githubusercontent.com/1003246/50034676-db1a5e00-ffb2-11e8-91c1-d117c40cdf69.png)

**Comment by gr2m** [comment]
can you check `npm ls @octokit/endpoint` please, not `npm ls @octokit/request`?

**Comment by cliffkoh** [comment]
Arghhh my bad. @octokit/request is 3.1.1. 

Let me double and triple check. I'm debugging TS source code so it might *very* well be that the callstack I am seeing is incorrect because the source file being run (on disk) is old.

Sorry for a potential false alarm. Doing the double and triple check right now to eliminate PEBCAK (this is my leading theory for the bug atm).
