### ISSUE TITLE
bug: result of `repos.listForOrg` does not include `topics`

### ISSUE THREAD

**Issue by Jan-Jan** [octokit/octokit.js#1165]
If I compare using `/api/v3/orgs/${org}/repos` vs `octokit.repos.listForOrg({ org })` (where, eg, `const org = 'myOrg'`), the only difference is that the `ocktokit` result does not include `topics`.

The documentation https://developer.github.com/v3/repos/#list-organization-repositories clearly shows `topics` being included in the result.

Here is the proof https://runkit.com/jan-jan/5c19f6c1dd42f5001299674d

I'm using `@octokit/rest` `^16.0.0`.

**Comment by gr2m** [comment]
See the note on top of the page

![image](https://user-images.githubusercontent.com/39992/50234799-542b0400-036b-11e9-9282-c1a8a7296781.png)

We don't set optional preview headers, you can set them as needed

```js
octokit.repos.listForOrg({
  headers: {
    accept: 'application/vnd.github.mercy-preview+json'
  },
  org
})
```

I asked the GitHub Docs team to move the note about the two previews into the respective endpoint sections, that way they will be added to our docs at http://octokit.github.io/rest.js, as these are built using https://github.com/octokit/routes

**Comment by gr2m** [comment]
sorry didn't mean to close :) Let me know if that works ^^

**Comment by gr2m** [comment]
I’ll close as I’m certain that will resolve your problem. But please feel free to comment if you have more questions
