### ISSUE TITLE
i.all is not a function

### ISSUE THREAD

**Issue by Escarnope** [octokit/octokit.js#1167]
While trying to use it in the browser, I get this

`octokit-rest.min.js:formatted:158 Uncaught TypeError: i.all is not a function
    at e.exports (octokit-rest.min.js:formatted:158)
    at e (octokit-rest.min.js:formatted:351)
    at Object.<anonymous> (octokit-rest.min.js:formatted:347)
    at t (octokit-rest.min.js:formatted:11)
    at Object.<anonymous> (octokit-rest.min.js:formatted:334)
    at t (octokit-rest.min.js:formatted:11)
    at Object.<anonymous> (octokit-rest.min.js:formatted:328)
    at t (octokit-rest.min.js:formatted:11)
    at Object.<anonymous> (octokit-rest.min.js:formatted:142)
    at t (octokit-rest.min.js:formatted:11)
e.exports @ octokit-rest.min.js:formatted:158
e @ octokit-rest.min.js:formatted:351
(anonymous) @ octokit-rest.min.js:formatted:347
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:334
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:328
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:142
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:314
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:309
t @ octokit-rest.min.js:formatted:11
(anonymous) @ octokit-rest.min.js:formatted:71
(anonymous) @ octokit-rest.min.js:formatted:72
(index):24 Uncaught TypeError: Octokit is not a constructor
    at (index):24`

**Comment by gr2m** [comment]
Thank you @Escarnope for reporting the issue, I was able to reproduce the problem with the latest `octokit-rest.min.js` from https://github.com/octokit/rest.js/releases/tag/v16.3.0

When testing with the un-minidied version I get "merge.all is not a function" which I was hoping we resolved via https://github.com/octokit/rest.js/issues/1129

I’ll give this another look

**Comment by gr2m** [comment]
This has been resolved meanwhile, I just tested it with https://github.com/octokit/rest.js/releases/tag/v16.9.0 and could no longer reproduce the problem. Please let me know if the problem still occurs for you
