### ISSUE TITLE
I am trying to upgrade from 15.18.1 to 16.3 and I don't see any good docs

### ISSUE THREAD

**Issue by richtera** [octokit/octokit.js#1168]
I am unable to find good references about all the API method and properties that have been renamed. Pulling in 16.3 destroys most of my current code, but I have not found any docs that have a good way to lookup the changes. Is there such a thing or are there suggestions? Seems the whole PR part of the API is completely different and even normal references and updates seem to work different. Not quite sure how to proceed.

**Comment by gr2m** [comment]
we put release notes into GitHub’s release notes. Does that help? https://github.com/octokit/rest.js/releases/tag/v16.0.1

**Comment by wolfy1339** [comment]
I've done the transition myself. You should update to the latest v15 version, run your app and fix any deprecation warnings from Octokit. Then you'll be good to go to use v16
