### ISSUE TITLE
Annotations not validating correctly when using the Checks API

### ISSUE THREAD

**Issue by NickColley** [octokit/octokit.js#1170]
Cross posting this issue from the Probot repo, see https://github.com/probot/probot/issues/790

Will update if I figure it out...

**Comment by NickColley** [comment]
My issue was due to supplying `start_column` and `end_column` with a endline that spanned multiple lines.

https://developer.github.com/v3/checks/runs/

> Omit this parameter if start_line and end_line have different values.

Which may be related to the other person's issue... perhaps since they were missing the `end_column`.

**Comment by gr2m** [comment]
🤔 Thanks @nickcolley, sounds to me as if the error message could have been more helpful. I’ll try to create a minimal test case to share it with support

**Comment by corasan** [comment]
Yup, this was exactly my issue. Thank you @nickcolley!

**Comment by JohnHandley** [comment]
This just saved me from a pit of despair, thank you @nickcolley
