### ISSUE TITLE
missing docs for pulls (.create) etc

### ISSUE THREAD

**Issue by jakebolam** [octokit/octokit.js#1191]
The documentation for the whole `pulls` namespace appears to be missing: https://octokit.github.io/rest.js/ (create) for example

The command on the API works tho:
```
github.pulls.create({
            owner: this.owner,
            repo: this.repo,
            title,
            body,
            head: branchName,
            base: 'master',
            maintainer_can_modify: true
})
```

**Comment by gr2m** [comment]
Are you looking for https://octokit.github.io/rest.js/#api-Pulls?

**Comment by gr2m** [comment]
We are working on improving the docs, they are a relict from times when this package was still `node-github`. I recommend to subscribe to #620 for updates

**Comment by jakebolam** [comment]
Will do thankyou. Yep that is the one.

I got confused when searching for `pull` or `pulls` didn't show the results I was expecting
<img width="375" alt="screen shot 2019-01-11 at 12 20 42 pm" src="https://user-images.githubusercontent.com/3534236/51013054-60396880-159b-11e9-9bac-191ba75ffae5.png">

<img width="618" alt="screen shot 2019-01-11 at 12 19 50 pm" src="https://user-images.githubusercontent.com/3534236/51013045-56b00080-159b-11e9-9270-60a3d4d1d3f7.png">

**Comment by gr2m** [comment]
The docs are really bad, I know. I’m working on a new docs page and I’ll make sure it has a better search
