### ISSUE TITLE
octokit.authorization.create() not found anymore

### ISSUE THREAD

**Issue by bhaidar** [octokit/octokit.js#1194]
Hello,
I am new to Node JS and octokit. I am trying to conncet to Github with basic authentication and then getting a token by following an article online. The code below taken from the article doesn't seem to work anymore!

````
 octokit.authenticate(_.extend({ type: 'basic', }, credentials));
 const response = await octokit.authorization.create({
        scopes: ['user', 'public_repo', 'repo', 'repo:status'],
        note: 'ginits, the command-line tool for initalizing Git repos'
      });
````

I get this error: `TypeError: octokit.authorization.create is not a function`

Appreciate your feedback.

**Comment by gr2m** [comment]
Hi Bilal, thanks for creating the issue! I’m sorry for the problem you run into, that is unfortunately something that happens often, articles get out of date and don’t get updated. I wish they also mentioned the version they used when writing the article.

When that happens, I would look for the changelogs of a project. Sometimes there is a `CHANGELOG.md` file, in our case we have all changes documented in the [release notes](https://github.com/octokit/rest.js/releases).

We changed a lot of method names as part of the upgrade from v15 to v16, please see the release notes at https://github.com/octokit/rest.js/releases/tag/v16.0.1.

In your case, `octokit.authorization.create()` was renamed to `octokit.oauthAuthorizations.createAuthorization()`.

**Comment by gr2m** [comment]
I’m fairly sure that it will work, let me know if it does not!

But thanks for opening the issue, it made me think that the method really shouldn’t be called  `createAuthorization()`, but just `create()`. I’ll look into that

**Comment by vijayalakshmimannay** [comment]
TypeError: octokit.authenticate is not a function

**Comment by gr2m** [comment]
@vijayalakshmimannay can you please create a new issue? This is unrleated. Please make sure you use the latest version of `@octokit/rest`

**Comment by vijayalakshmimannay** [comment]
i am sending my file in two mails, due to file contains larger size.
