### ISSUE TITLE
new Octokit({auth})

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1207]
The current `octokit.authenticate` method is problematic in that it can change the type authentication within the same Octokit instance. I don’t see a valid use case where I would create an Octokit instance for a user and then later would change the authentication to a GitHub app. I would create separate Octokit instances instead.

To address that I issue, I would suggest to add an `auth` option to the constructor.

```js
const clientWithAuth = new Octokit({
  auth: 'token secret123'
})
```

The `auth` option can be

1. A string

   The value will be passed as value for the `Authorization` header,
   see [authentication](https://developer.github.com/v3/#authentication).

   ```js
   new Octokit({
     auth: 'token secret123'
   })
   ```

2. As object with the properties `username`, `password`, `on2fa`.

   `on2fa` is an asynchronous function that must resolve with two-factor
   authentication code sent to the user.

   ```js
   new Octokit({
     auth: {
       username: 'octocat',
       password: 'secret',
       async on2fa () {
         // example: ask the user
         return prompt('Two-factor authentication Code:')
       }
     }
   })
   ```

3. An object with the properties `client_id` and `client_secret`

   OAuth applications can authenticate using their `client_id` and `client_secret`
   in order to [increase the unauthenticated rate limit](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications).

4. A function

   Must resolve with a string which then will be passed as value for the
   `Authorization` header. The function will be called before each request and
   can be asynchronous.

   ```js
   new Octokit({
     auth () {
       return 'token secret123'
     }
   })
   ```

There is a special case for OAuth applications, when `client_id` and `client_secret` is passed as Basic Authorization instead of query parameters. The only routes where that applies share the same URL though: `/applications/:client_id/tokens/:access_token`. It should be easy enough to implement an exception within Octokit. The endpoints are

   1. [Check an authorization](https://developer.github.com/v3/oauth_authorizations/#check-an-authorization)
   1. [Reset an authorization](https://developer.github.com/v3/oauth_authorizations/#reset-an-authorization)
   1. [Revoke an authorization for an application](https://developer.github.com/v3/oauth_authorizations/#revoke-an-authorization-for-an-application)

For the record, I tested if these endpoints really require client_id & client_secret to be passed as Basic authorization or if they can also be passed as query arguments like recommended in the REST API docs for [Increasing the unauthenticated rate limit for OAuth applications](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications).

This will deprecate the `octokit.authenticate` method. Please let me know if I am missing any relevant use cases which are not well supported with this new API.

Related: #898

**Comment by hipstersmoothie** [comment]
I am seeing issues with the new auth method. I can switch between my branch `old` and `updates` and see different rate limiting results.

With `old` it works fine and give no errors. With `updates` it errors our immediately. Switching back and forth it will work most of the time on `old` until i hit the actual authed rate limit. 

To me it seems like the new auth method isn't actually auth-ing me

https://github.com/intuit/auto/tree/old
https://github.com/intuit/auto/tree/updates

---

EDIT: nvm my build was cached or something 🤦‍♂️

**Comment by gr2m** [comment]
done via https://github.com/octokit/rest.js/releases/tag/v16.13.0

**Comment by TimDurward** [comment]
@gr2m Spent a bit trying to figure out why my async 2fa function wasn't working for authentication. The documents mention to use `async on2Fa` but it needs to be `async on2fa` . :)

You'll get an error like
```
HttpError: 2FA required, but options.on2fa is not a function.
```

re: https://github.com/octokit/rest.js#authentication

**Comment by gr2m** [comment]
oh my 🤦‍♂️ would you like to send a pull request? I can also do it if you are busy, just let me know

**Comment by TimDurward** [comment]
@gr2m Sure, I'll get to it this evening!

**Comment by NetOpWibby** [comment]
I'm getting `TypeError: octokit is not a constructor` when doing:

```js
new octokit({
  auth: `token ${process.env.GITHUB_OAUTH_TOKEN}`
});
```

Previously, this worked fine:

```js
octokit.authenticate({
  type: "oauth",
  token: process.env.GITHUB_OAUTH_TOKEN
});
```

**Comment by NetOpWibby** [comment]
I realized my issue was the extra `()` at the end of my require: `const octokit = require("@octokit/rest")();`

Whoops. Still, thanks for the help @gr2m.

**Comment by jayeshsir** [comment]
Appreciate your help resolving this.

#### This says: `HttpError: Bad credentials`

```
const passport = require("passport");
const GitHubStrategy = require("passport-github2");
const GitHubAPI = require("@octokit/rest");

module.exports = function(app, db, onLoginSuccess) {
  passport.use(
    new GitHubStrategy(
      {
        clientID: process.env.GITHUB_CLIENT_ID,
        clientSecret: process.env.GITHUB_CLIENT_SECRET,
        callbackURL: `${process.env.ROOT_URL}/login/github/callback`
      },
      function(accessToken, refreshToken, profile, done) {
        const id = `github-${profile.username}`;
        const user = {
          _id: id,
          "strategies.github": {
            profile,
            refreshToken,
            accessToken
          },

          updatedAt: new Date()
        };

        const github = new GitHubAPI({
          userAgent: "somestring",
          previews: [],
          protocol: "https",
          host: "api.github.com",
          pathPrefix: "",
          request: {
            agent: undefined,
            timeout: 0
          },
          auth: `token accessToken`
        });
        // github.authenticate({ type: "oauth", token: accessToken });

        github.users
          // create the user on the DB with the email.
          .listEmails({
            user: profile.username
          })
          .then(emails => {
            const { data } = emails;
            if (data[0]) {
              user.email = data[0].email;
            }

            return db
              .collection("users")
              .updateMany({ _id: id }, { $set: user }, { upsert: true });
          })
          .then(() => done(null, user))
          .catch(ex => done(ex));
      }
    )
  );

  const loginScopes = ["user:email"];

  app.get(
    "/login/github",
    passport.authenticate("github", { scope: loginScopes })
  );

  app.get("/login/github/callback", passport.authenticate("github"), function(
    req,
    res
  ) {
    onLoginSuccess(req, res);
  });
};

```

#### This works but shows `Error: octokit.authenticate() is deprecated. Use "auth" constructor option instead.`

```
const passport = require("passport");
const GitHubStrategy = require("passport-github2");
const GitHubAPI = require("@octokit/rest");

const githubOptions = {
  auth: undefined,
  userAgent: "somestring",
  previews: [],
  protocol: "https",
  host: "api.github.com",
  pathPrefix: "",
  request: {
    agent: undefined,
    timeout: 0
  }
};

module.exports = function(app, db, onLoginSuccess) {
  passport.use(
    new GitHubStrategy(
      {
        clientID: process.env.GITHUB_CLIENT_ID,
        clientSecret: process.env.GITHUB_CLIENT_SECRET,
        callbackURL: `${process.env.ROOT_URL}/login/github/callback`
      },
      function(accessToken, refreshToken, profile, done) {
        const id = `github-${profile.username}`;
        const user = {
          _id: id,
          "strategies.github": {
            profile,
            refreshToken,
            accessToken
          },

          updatedAt: new Date()
        };

        const github = new GitHubAPI(githubOptions);
        github.authenticate({ type: "oauth", token: accessToken });

        github.users
          // create the user on the DB with the email.
          .listEmails({
            user: profile.username
          })
          .then(emails => {
            const { data } = emails;
            if (data[0]) {
              user.email = data[0].email;
            }

            return db
              .collection("users")
              .updateMany({ _id: id }, { $set: user }, { upsert: true });
          })
          .then(() => done(null, user))
          .catch(ex => done(ex));
      }
    )
  );

  const loginScopes = ["user:email"];

  app.get(
    "/login/github",
    passport.authenticate("github", { scope: loginScopes })
  );

  app.get("/login/github/callback", passport.authenticate("github"), function(
    req,
    res
  ) {
    onLoginSuccess(req, res);
  });
};
```

**Comment by gr2m** [comment]
Set the `auth` option as described at https://github.com/octokit/rest.js/#authentication

**Comment by lvnilesh** [comment]
Thanks @gr2m an example that resolves @jayeshsir issue above would be very helpful. Much appreciated and thanks for giving us octokit/rest.js

**Comment by gr2m** [comment]
Most of @jayeshsir code is express or password. If you can reduce that to a code example that only uses `@octokit/rest` then I’d be happy to look at it

**Comment by zeke** [comment]
Nice change! 👍

I always thought that old behavior was odd.

**Comment by akmalick** [comment]
Spent last 10 hours non-stop, but to no avail.
Stackoverflow was of no help. It has just 29 questions tagged under "probot" of which 2 are by me.

[Token passed to createTokenAuth is not a string : octokit, auth-token](https://stackoverflow.com/questions/61058382/token-passed-to-createtokenauth-is-not-a-string-octokit-auth-token)

`ERROR probot: [@octokit/auth-token] Token passed to createTokenAuth is not a string`

Building a GitHub App using probot and nodejs.
My code : 


```
/**
 * This is the main entrypoint to your Probot app
 * @param {import('probot').Application} app
 */


const{Octokit} = require("@octokit/rest");
        const{createAppAuth} = require("@octokit/auth-token");

         console.log('PRIVATE_KEY',process.env.PRIVATE_KEY_PATH);
         console.log('-------------TypeOf token ----', typeof process.env.PRIVATE_KEY_PATH)

         const appOctokit = new Octokit({
           authStrategy:createAppAuth,
           auth:{
             id:12345,
             privateKey: process.env.PRIVATE_KEY_PATH,
            //  privateKey: 'token ${process.env.PRIVATE_KEY_PATH}'
            }
         });

```

Also referenced https://github.com/octokit/rest.js/issues/1562 but didn't find much help,seems like it is still not resolved.

**Comment by gr2m** [comment]
```js
privateKey: process.env.PRIVATE_KEY_PATH
```

You cannot set `privateKey` to the path of a `*.key` file, it has to be the contents of the file

**Comment by akmalick** [comment]
@gr2m Thanks for guiding me through and your response to the StackOverflow question . I'm back on track.
