### ISSUE TITLE
Uncaught TypeError: octokit.repos.getForOrg is not a function from README example

### ISSUE THREAD

**Issue by BarbourSmith** [octokit/octokit.js#1209]
In the README file the example 

```
const octokit = new Octokit()

// Compare: https://developer.github.com/v3/repos/#list-organization-repositories
octokit.repos.getForOrg({
  org: 'octokit',
  type: 'public'
}).then(({data, headers, status}) => {
  // handle data
})
```

is given [here](https://github.com/octokit/rest.js#browser), however if I run that example I get the error 

> Uncaught TypeError: octokit.repos.getForOrg is not a function

When I inspect the ocotokit object it does not have a getForOrg method, and that method is also not listed in [the rest.js documentation](https://octokit.github.io/rest.js/), am I doing something wrong or is the README out of date?

**Comment by BarbourSmith** [comment]
I also want to add that this is an awesome project, and that issue in no way affected my use case for which this is a perfect solution so thank you to everyone who has contributed.

**Comment by wolfy1339** [comment]
The README is probably out of date. If you search the docs for the API url, you will find it's new name

**Comment by gr2m** [comment]
Thank you @BarbourSmith for reporting that issue! A lot of methods have been changed with the current version to better align with GitHub’s REST API documentation, the full list of name changes is here: https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations

In this case, the correct method name is `octokit.repos.listForOrg`.

Would you like to send a pull request to fix it? I made a similar pull request a while ago to fix another code example (https://github.com/octokit/rest.js/pull/1163), but totally miss this one 🤦‍♂️

**Comment by BarbourSmith** [comment]
It would be an honor and a pleasure to create a pull request. #1212 created.

I tested it to be sure that the updated method name worked and it works like a charm. Thanks @gr2m 👍
