### ISSUE TITLE
Octokit.search.issuesAndPullRequests is not a function

### ISSUE THREAD

**Issue by Axel-Coud** [octokit/octokit.js#1217]
It properly worked before the lasts patches, took a screenshot on node debugger environment to show you exactly how it looks, as you can see the search property only misses the function i use (issuesAndPullRequests) any ideas about where it comes from ?

![image](https://user-images.githubusercontent.com/28571027/51540742-7a0a6380-1e57-11e9-9ca4-c01362151eb2.png)

**Comment by gr2m** [comment]
The function exists, here is a runkit notebook checking for that

https://runkit.com/gr2m/octokit-rest-js-1217/1.0.0

I tested it with Typescript, too

![image](https://user-images.githubusercontent.com/39992/51552761-2895b080-1e26-11e9-83fc-0c2d59775f6c.png)

What version are you using? `.search.issuesAndPullRequests` was introduced in [v16.9.0](https://github.com/octokit/rest.js/compare/v16.8.1...v16.9.0)

**Comment by Axel-Coud** [comment]
It happened on 16.13.1, reverted to 16.12.0, now properly works. Both ran on node 11.6.0.

**Comment by Axel-Coud** [comment]
FIXED : 
Just ran some tests and completely erased my project's node_modules before any npm install or yarn install this time.
The search property had the issuesAndPullRequests function as it should be.
Kind of weird since i had it for numerous patches now but anyway, sorry for the troubles.
