### ISSUE TITLE
Alternative to pullRequests.getAll() ?

### ISSUE THREAD

**Issue by khromov** [octokit/octokit.js#1218]
We're using an older version of the `github` package that exposes the `pullRequests.getAll()` method. 

Is there some suggested way to iterate over all pull requests using the now available `pulls.list()` instead?

**Comment by gr2m** [comment]
`octokit.pulls.list()` works exactly the same way that `octokit.pullRequests.getAll()` worked before.

We describe how to paginate results in the README: https://github.com/octokit/rest.js#pagination

Does that help?

**Comment by khromov** [comment]
@gr2m Thank you, that helps!
