### ISSUE TITLE
projects.listColumns requires admin access

### ISSUE THREAD

**Issue by kkjeer** [octokit/octokit.js#1221]
Making a call such as `const columns = await octokit.projects.listColumns({ project_id: 1 });` results in a 403 error with the message "Must have admin rights to Repository". This is the case even when the caller is the repository owner.

I didn't see anything about admin access in the docs (https://octokit.github.io/rest.js/#api-Projects-listColumns) - is there a way to make this call without hitting the admin issue?

**Comment by yairgo** [comment]
@kkjeer I'm using the github api over curl and running into this same issue, is there something you found out that resolved this?

**Comment by kkjeer** [comment]
@yairgo my issue was that I was calling the API with the wrong project id - once I replaced the project_id with correct value then it worked for me.
