### ISSUE TITLE
OAuth access token work in parameter rather than header

### ISSUE THREAD

**Issue by huanggm** [octokit/octokit.js#1238]
I have got a OAuth access token, and I can use it in parameter. But when I use it in header, it doesn't work.

https://jsfiddle.net/a1w2ny6v/11/

It must be something that I missed.

**Comment by huanggm** [comment]
Finally, I got the answer.
Parameter: access_token=81683f2f2888d2c442eee367375e77fe2be6eede
Header: Authorization: token 81683f2f2888d2c442eee367375e77fe2be6eede
I am really newcomer to this.

**Comment by gr2m** [comment]
Note that you can use `@octokit/rest` in the browser, too. It’s using fetch internally. Glad that you got it to work
