### ISSUE TITLE
feature request: push multiple files to repo

### ISSUE THREAD

**Issue by shaunwarman** [octokit/octokit.js#1256]
Feature request to be able push multiple files to github via the createFile / updateFile API. This may be more of an ask for a high level library that sits on top of the REST API. But hoping to put this here if anyone else felt it was needed or if there are better ways to do this.

I've ran across a couple of great links that seems to:

```
1. Create blobs for each file
2. Create a tree which defines the folder structure for the files
3. Create a commit for the tree
4. Update your branch to point to the new commit
```

Useful Links:
https://github.com/philschatz/octokat.js/issues/97#issuecomment-194455401
https://gist.github.com/StephanHoyer/91d8175507fcae8fb31a#file-github-js

**Comment by gr2m** [comment]
I created a plugin that does what you want, but specifically in the context of creating a pull request:
https://github.com/gr2m/octokit-create-pull-request

Does that help?

**Comment by shaunwarman** [comment]
Thanks! This looks great. I think I can re-use a lot of functionality here. It may seem odd, but I'd like to push files directly to a particular repo. So the createFile / updateFile APIs may be last thing to swap out there instead of creating the pull request.

**Comment by gr2m** [comment]
Let me know if you have any questions! I’d be great if you could publish that functionality as a plugin that others can benefit from. I want to make a list of community plugins and would love to list yours :)

**Comment by shaunwarman** [comment]
Perfect, I'll share what I come up with tonight!

**Comment by gr2m** [comment]
I’ll close the issue, but please keep us posted 👀
