### ISSUE TITLE
Remove Hard Error from authentication-deprecated/authenticate.js for Backward Compatibility

### ISSUE THREAD

**Issue by stanvarlamov** [octokit/octokit.js#1266]
`https://github.com/octokit/rest.js/blob/master/plugins/authentication-deprecated/authenticate.js` throws the Deprecation message as a hard error:
```
state.octokit.log.warn(new Error('octokit.authenticate() is deprecated. Use "auth" constructor option instead.'))
``` 
It appears that the intend was generating a Warning. Please remove the `new Error` to allow professional teams using this library to plan the transition.

**Comment by gr2m** [comment]
the messages are not interfering with code execution, the errors are not thrown, just logged, so your "professional team" should be just find continuing with the transition.

I will however change the wording, instead of the `Error` prefix, it will say `Deprecation`, and it will only be logged once. But other than that it will behave the same.

**Comment by stanvarlamov** [comment]
Yes, my error was with another b-c issue: `octokit.repos.getContent` was changed to `octokit.repos.getContents` at some point, apparently. Closing

**Comment by gr2m** [comment]
Make sure to read the release notes for migrating to new breaking versions: https://github.com/octokit/rest.js/releases/tag/v16.0.1

`octokit.repos.getContent` is one of the methods that got deprecated in v15.18.0:
https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations

**Comment by stanvarlamov** [comment]
It's pretty brutal when code written against the latest at the time version of a secondary utility package breaks down flat after a routine update less than 5 mo down the road. Luckily, the changes are "minor", so manageable after all
