### ISSUE TITLE
Missing example in documentation or searching for repos by topic not supported?

### ISSUE THREAD

**Issue by BarbourSmith** [octokit/octokit.js#1282]
It is indicated in the documentation [here](https://octokit.github.io/rest.js/#api-Search-repos) that it is possible to constrain a repo search by topics, but then it says 

> You can search for multiple topics by adding more topic: instances, and including the mercy-preview header. For example:

But there isn't actually an example there. I gave it a go and didn't see any effect from searching by topic, but maybe I was just doing it wrong. 

Is this just in the documentation because its pulling directly from the [GitHub api documentation](https://developer.github.com/v3/search/#search-repositories)? 

Is limiting a repo search to a topic possible, and if so how do I do it?

**Comment by gr2m** [comment]
> Is this just in the documentation because its pulling directly from the GitHub api documentation?

Yes

> Is limiting a repo search to a topic possible, and if so how do I do it?

You use the `q` parameter

```js
await octokit.search.repos({
  q: 'topic:react'
})
```

**Comment by BarbourSmith** [comment]
Thank you! That is exactly what I needed to know. If I wanted to make a pull request to propose adding an example to the documentation is that something I can do?
