### ISSUE TITLE
repos.getCommits should not have page and is possibly missing some options

### ISSUE THREAD

**Issue by lalitkapoor** [octokit/octokit.js#129]
According to the Github API docs pagination doesn't work the same as everywhere else for getting commits. Pagination in this case is based on the sha values in the link header.

> A special note on pagination: Due to the way Git works, commits are paginated based on SHA instead of page number. Please follow the link headers as outlined in the pagination overview instead of constructing page links yourself.

http://developer.github.com/v3/repos/commits/#list-commits-on-a-repository

The link header adds a query param for `last_sha` and `top`, so maybe we should accept those as options.

**Comment by kaizensoze** [comment]
I think as of https://developer.github.com/changes/2014-05-09-improved-pagination-for-the-repository-commits-api/ this is no longer an issue.
