### ISSUE TITLE
Property 'mergeable' does not exist on type 'Response<PullRequestsCreateResponse>'

### ISSUE THREAD

**Issue by yingren-wang** [octokit/octokit.js#1296]
Hi, I want to get the mergeable value of a new pull request by using the response of creating a pull request. According to [REST API v3 page](https://developer.github.com/v3/pulls/#create-a-pull-request), there suppose to have a value called `mergeable` but in my code, it says this property doesn't exist.

my code:

```js
const newPullRequest = {
      "title" : "title",
      "head" : "head", // push from
      "base" : "base", // push into
      "owner" : "ownerName",
      "repo" : "repoName"
    }
const resultCreatePR = await context.github.pullRequests.create(newPullRequest)
var mergeableStatus = resultCreatePR.mergeable
```

I tried to use get pullRequest then get the value of `mergeable` but it shows in the terminal saying that Property 'mergeable' does not exist on type 'Response<PullRequestsGetResponse>' either.

my versions:

`node -v` v10.15.1
`octokit/rest` @16.21.0
`npm -v` 6.9.0

Thank you

**Comment by gr2m** [comment]
I think you have a bug in your code. Try this

```diff
- const resultCreatePR = await context.github.pullRequests.create(newPullRequest)
+ const { data: resultCreatePR } = await context.github.pullRequests.create(newPullRequest)
```

**Comment by yingren-wang** [comment]
Thank you for your response, how my code looks like now: 
<pre>
const { data: resultCreatePR } = await context.github.pullRequests.create(newPullRequest)
var mergeableStatus = resultCreatePR.mergeable
console.log(resultCreatePR)
console.log(mergeableStatus)</pre>
However it's still not working with red line under `mergeable` saying the same error... Is that possible that somewhere else messes up?

I am not sure the reason why you made that change, did you do that because the `resultCreatePR` looks like the following?
 <pre>{ data:
    { ...
      mergeable: false/true/null,
      ...
    }
}</pre>

Also, for `context.github.pullRequests.create`, I have a red line under `pullRequest` in the code saying this property doesn't exist on type 'GitHubAPI' but it still can create a pull request successfully with no error showing in the terminal. I tried to use `.pulls.create` instead, in this case, there's no error in the code but in the terminal.

**Comment by gr2m** [comment]
It works for me 🤔 

![image](https://user-images.githubusercontent.com/39992/55193831-4ef90480-5165-11e9-8444-6f457f8f000c.png)

Looks like the type definitions are for `octokit.pulls.*` only, not for `octokit.pullRequests.*` (it’s an alias). 

> I am not sure the reason why you made that change

In this example, `resultCreatePR` is the response, which has `data` and `headers` properties. 

```js
const resultCreatePR = await context.github.pullRequests.create(newPullRequest)
```

You really want this

```js
const response = await context.github.pullRequests.create(newPullRequest)
const resultCreatePR = response.data
```

**Comment by yingren-wang** [comment]
It seems it works for me in code editor as well: ![image](https://user-images.githubusercontent.com/46463357/55194443-b1f39700-5177-11e9-8d15-ab92a24aa2a4.png) However, when it runs, it doesn't work in the terminal:
![image](https://user-images.githubusercontent.com/46463357/55194499-d9e2fa80-5177-11e9-8cb9-e79e6d458b95.png)


For the problem relates to `.pulls` and `.pullRequests`, if I change it to ".pulls", it looks like this in the terminal: 
![image](https://user-images.githubusercontent.com/46463357/55194586-2595a400-5178-11e9-88da-6fa2baa54ccf.png)
It doesn't have any red line in the code editor though:
![image](https://user-images.githubusercontent.com/46463357/55194798-a48adc80-5178-11e9-94eb-01a8ca3905cc.png)

I am using GitHub enterprise for this if it helps

:confused:

**Comment by yingren-wang** [comment]
Update: I thought I had `mergeable` before but actually I didn't. I used the variable name `mergeable` somewhere else in the program later, that's why it is available after `resultcreatePR.`. You can see that you have other values like `merge_commit_sha` but I don't.

Also, now I have
```
const Octokit = require('@octokit/rest')
const octokit = new Octokit()
...
const resultCreatePR = aqait.pulls.create(newPullRequest)
```
but it's still not working. Deprecation error is returned in the terminal:
![image](https://user-images.githubusercontent.com/46463357/55252928-f5a2db00-5221-11e9-9694-82e304841ed0.png)

Thank you

**Comment by gr2m** [comment]
What probot version are you using? The latest is 9.1.1

**Comment by yingren-wang** [comment]
It seems working now!
Thank you so much!!
