### ISSUE TITLE
Request for feedback: expose current authentication in public API

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1298]
Being able to access the current authorization token has been increasingly requested. I’ve been reluctant to make it too easy due to security concerns.

I think that the security concerns are unwarranted. There are ways today to access the current authorization if 3rd party code gets access to the `octokit` client API.

A common use case is the usage of an external request library such as [lokka](https://github.com/kadirahq/lokka) for GraphQL requests, while still using octokit for others.

It would probably be an asynchronous method which would resolve with an object that includes a `token` property, so that other properties can be added in future, such as `scopes` for oauth tokens. I would not expose username/password, private keys (apps) or client secrets (oauth).

The API could look something like this

```js
const auth = await octokit.getAuthentication()
auth.token // current token passed in authorization header
```

**Comment by gr2m** [comment]
This is what I think `await octokit.getAuthentication()` (or however it’s going to end up being called) could return, based on used authentication. I would never expose

- Private keys for GitHub apps
- Client secret for OAuth apps
- password for Basic authentication

But I think it is safe to expose

- App id or installation id for GitHub apps
- Client id for OAuth apps
- username for Basic authentication

However Octokit only implements Basic and OAuth authentication, it does not have access to app/installation IDs. The app ID can however be retrieved using [`await octokit.apps.getAuthenticated({})`](https://octokit.github.io/rest.js/#api-Apps-getAuthenticated), there is no such API for an installation

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th align=left>Authentication</th>
      <th align=left width=100%><code>await octokit.getAuthentication()</code></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td valign=top>Basic</td>
      <td>
        <pre>{
  type: 'basic',
  username,
  token,
  id // authorization token id so it can be deleted after a one-time usage
}</pre>
      </td>
    </tr>
    <tr>
      <td valign=top>App</td>
      <td>
        <pre>{
  type: 'app',
  token // JWT
}</pre>
      </td>
    </tr>
    <tr>
      <td valign=top>Installation</td>
      <td>
        <pre>{
  type: 'installation',
  token
}</pre>
      </td>
    </tr>
    <tr>
      <td valign=top>Token</td>
      <td>
        <pre>{
  type: 'token',
  token
}</pre>
      </td>
    </tr>
    <tr>
      <td valign=top>OAuth <em>(client id/secret)</em></td>
      <td>
        <pre>{
  type: 'oauth',
  clientId
}</pre>
      </td>
    </tr>
  </tbody>
</table>

I don’t see a need to expose token scopes, it can received with existing APIs when needed (for oauth and personal access tokens, this does not work for installations)

```js
octokit.request('HEAD /').then(({headers}) => {
  headers['x-oauth-scopes'] // string with comma separated scopes, e.g. "admin:org, repo, user"
})
```

I’m thinking of adding an additional `.header` property which will have the `token` or `bearer` prefix so it can directly be passed as authorization header

**Comment by tcbyrd** [comment]
>  there is no such API for an installation

Yeh this is a tough one since the only way to know the installation ID is to know some other piece of data to look it up (user, org, or repository). What I've wanted there is a way to just pass the currently stored token. So in probot/webhooks, what is the current token being used by `context.github`? That way you at least already know the installation ID from `context.payload.installation.id` and can retrieve the token it's using. Do you think that's best done in Probot or could it be part of `@octokit/webhooks.js`?

**Comment by gr2m** [comment]
> So in probot/webhooks, what is the current token being used by `context.github`?

Whatever the internal `@octokit/app` instance returns when calling [`await app.getInstallationAccessToken({ installationId })`](https://github.com/octokit/app.js#authenticating-as-an-installation)

> That way you at least already know the installation ID

I’m wondering, what would you need the installation ID for?

**Comment by tcbyrd** [comment]
> I'm wondering, what would you need the installation ID for?

Don't need the installation ID since it's already available as `context.payload.installation.id`. Just want a way to pass along the token being used in that context.
