### ISSUE TITLE
Provide documentation for migrating from github package

### ISSUE THREAD

**Issue by stsvilik** [octokit/octokit.js#1305]
I found it frustrating to go through breaking changes `@octokit/rest.js` introduced while migrating from `github` package. If you're taking over that space, then at least provide transition documentation highlighting what has changed.

**Comment by gr2m** [comment]
It’s all documented in detail in the release notes

- https://github.com/octokit/rest.js/releases/tag/v14.0.0 (renamed to `@octokit/rest`)
- https://github.com/octokit/rest.js/releases/tag/v15.0.1
- https://github.com/octokit/rest.js/releases/tag/v16.0.1

We are working on new documentation which will include a dedicated section upgrade migrations. But it will include the same content as the "Breaking changes" sections in the release notes
