### ISSUE TITLE
Does anyone know why emoji images are no longer accessible?

### ISSUE THREAD

**Issue by channg** [octokit/octokit.js#1311]
https://developer.github.com/v3/emojis/

I can't access the image address

**Comment by gr2m** [comment]
The example response in the documentation seems to be outdated. You can get the working URLs at https://api.github.com/emojis, or with

```js
const Octokit = require('@octokit/rest')
const octokit = new Octokit()

octokit.emojis.get()
	.then(response => console.log(response.data))
```

**Comment by gr2m** [comment]
Maybe let support know about the outdated response, you can send a message at https://github.com/contact :)
