### ISSUE TITLE
Pushing binary content in a tree

### ISSUE THREAD

**Issue by opyate** [octokit/octokit.js#1313]
Following #1308, I'm now wondering how to push a tree containing images, or non-text content type. It seems as if content negotiation isn't happening automatically on file extension, and the docs at https://octokit.github.io/rest.js/#api-Git-createTree don't show any obvious option to do this either.

Here's the last bit of the example above modified:

```
import * as fs from 'fs'

function getImageAsBase64(file) {
  const bitmap = fs.readFileSync(file)
  return new Buffer(bitmap).toString('base64')
}

const main = async () => {
  const owner = 'opyate'
  const repo = 'deleteme2'
  const base = 'master'
  const head = 'master'
  const changes = {
    files: {
      'foo.png': getImageAsBase64('/path/to/image.png')
    },
    commit: 'Image from octokit'
  }
  return await push({ owner, repo, base, head, changes })
}
```

And the resulting image is just the base64 string:
https://github.com/opyate/deleteme2/blob/master/foo.png

_Originally posted by @opyate in https://github.com/octokit/rest.js/issues/1308#issuecomment-480621236_

**Comment by gr2m** [comment]
Do you think this is a problem with https://github.com/gr2m/octokit-create-pull-request or with the `.git.createTree()`? Could you maybe reduce the test case to just use [`.git.createTree()`](https://octokit.github.io/rest.js/#api-Git-createTree)?

**Comment by opyate** [comment]
Here's the test case:

```
import * as Octokit from '@octokit/rest'
import * as fs from 'fs'

let _octokit = null

const octokit = (): Octokit => {
  if (_octokit === null) {
    _octokit = new Octokit({
      auth: '<redacted>'
    })
  }
  return _octokit
}

async function push ({ owner, repo, base, head, changes }) {
  let response

  if (!base) {
    response = await octokit().repos.get({ owner, repo })
    // tslint:disable-next-line:no-parameter-reassignment
    base = response.data.default_branch
  }

  response = await octokit().repos.listCommits({
    owner,
    repo,
    sha: base,
    per_page: 1
  })
  let latestCommitSha = response.data[0].sha
  const treeSha = response.data[0].commit.tree.sha

  response = await octokit().git.createTree({
    owner,
    repo,
    base_tree: treeSha,
    tree: Object.keys(changes.files).map(path => {
      // get around some type thing...
      const mode: "100644" | "100755" | "040000" | "160000" | "120000" = "100644"
      const type: "blob" | "tree" | "commit" = "blob"
      return {
        path,
        mode,
        content: changes.files[path],
        type
      }
    })
  })
  const newTreeSha = response.data.sha

  response = await octokit().git.createCommit({
    owner,
    repo,
    message: changes.commit,
    tree: newTreeSha,
    parents: [latestCommitSha]
  })
  latestCommitSha = response.data.sha

  return await octokit().git.updateRef({
    owner,
    repo,
    sha: latestCommitSha,
    ref: `heads/${head}`,
    force: true
  })
}

function getImageAsBase64(file: string) {
  // read binary data
  const bitmap = fs.readFileSync(file)
  // convert binary data to base64 encoded string
  const b64 = bitmap.toString('base64')
  return `data:image/${file.split('.').pop()};charset=utf-8;base64,${b64}`
}

const main = async () => {
  const owner = 'opyate'
  const repo = 'deleteme2'
  const base = 'master'
  const head = 'master'
  const changes = {
    files: {
      'foo.png': getImageAsBase64('/path/to/image.png')
    },
    commit: 'Image from octokit'
  }
  return await push({ owner, repo, base, head, changes })
}

main().then(result => {
  console.log(result)
}).catch(err => {
  console.error(err)
})
```

The resulting base64 converts back to an image (over [here](https://codebeautify.org/base64-to-image-converter), for instance).

**Comment by rexxars** [comment]
You can't pass base64 data to the tree API, I discovered. You'll have to first create blobs and use the returned sha sum in the `createTree` call  (replacing  `content` for `sha`)

**Comment by opyate** [comment]
@rexxars Thanks for the suggestion.

**Comment by seanmcilvenna** [comment]
@rexxars what about if you need to push 100's of files in a single commit, which may or may not be binary? I'm trying to figure out how to push 230 files for a commit, which is a folder structure of html files (some are binary images). If I do 100+ requests to the Git Blob API, then GitHub rejects > 100 due to "suspected abuse". So, I was trying to make a single tree with all 230 files, but I don't know how to store binary files in the tree...

**Comment by rexxars** [comment]
> @rexxars what about if you need to push 100's of files in a single commit, which may or may not be binary? I'm trying to figure out how to push 230 files for a commit, which is a folder structure of html files (some are binary images). If I do 100+ requests to the Git Blob API, then GitHub rejects > 100 due to "suspected abuse". So, I was trying to make a single tree with all 230 files, but I don't know how to store binary files in the tree...

I don't know, unfortunately. Maybe GitHub could shed some light.

**Comment by gr2m** [comment]
I've put it on my backlog, I hope to get back to it soon. I'd like https://github.com/gr2m/octokit-create-pull-request  to work with binary files out-of-the box, too

**Comment by seanmcilvenna** [comment]
@gr2m can you describe what you intend to do to get this working? I'm curious how the POST requests work for trees with binary content. Or another approach?

**Comment by gr2m** [comment]
I don't know out of my head, I'll have to investigate myself. I'd appreciate anyone who would investigate, too, and share their findings with us. 

A good place to look for previous questions/answers or ask about the REST API in general is https://github.community/t5/GitHub-API-Development-and/bd-p/api

**Comment by seanmcilvenna** [comment]
This is what I know:

You can create a tree _with_ the content specified, but it only works (as far as I can tell) for non-binary content; it treats base64 content as a plain string and the content of the file ends up being a base64 string when it results in a commit.

You can create blobs with binary content, but you have to create separate requests for each file when using blobs. I would love if the GIT API had a way to create multiple blobs as part of a single HTTP request... But, I'm not aware of any way to do that.

**Comment by gr2m** [comment]
@seanmcilvenna for the time being, you should be fine with "100+ requests to the Git Blob API" as long as you use the [throttling plugin](https://github.com/octokit/plugin-throttling.js/)

**Comment by seanmcilvenna** [comment]
How much throttling would 230 files require??
In my initial tests, I had to throttle down to 3 requests per second to not get rejected by GitHub.
At 230 files, that would be roughly 70 seconds. Seems a little unreasonable.
I can't find the documentation on how many requests are allowed per time period... but I THINK it was like 100 requests per minute, or something like that. That would imply that I couldn't do do this same export twice in a row without waiting a while...
It all seems pretty odd for enterprise level services.

**Comment by gr2m** [comment]
There are two limits for requests: rate limits & abuse limits. Rate limits are transparent, you can send X requests per hour, usually 5k if you are authenticated.

The rules for abuse limits are not public. They are constantly changing and dynamic. We have implemented several strategies to avoid hitting abuse limits and do retry requests when you hit it. 

> 70 seconds. Seems a little unreasonable.

It really depends on your use case. If it's running somewhere in the background, it does not really matter, does it? Maybe not all 230 files are binary, in which case you wouldn't need to create a blobs for all of them.

Alternatively you can always fall back to use the `git` API instead of the REST API to make these changes.

**Comment by gr2m** [comment]
For reference, here is how to create a commit with a binary file using the [Create a blob](https://developer.github.com/v3/git/blobs/#create-a-blob) API

```js
const TOKEN = process.env.GITHUB_TOKEN;
const OWNER = "gr2m";
const REPO = "pull-request-test";
const BRANCH = "other-branch";
const FILE_PATH = "/Users/gregor/Desktop/abc.JPG";

const octokit = require("@octokit/rest").plugin(require("."))({
  auth: `token ${TOKEN}`
});

main();

async function main() {
  const owner = OWNER;
  const repo = REPO;
  const branch = BRANCH;

  const {
    data: [
      {
        sha: latestCommitSha,
        commit: {
          tree: { sha: latestCommitTreeSha }
        }
      }
    ]
  } = await octokit.repos.listCommits({
    owner,
    repo,
    sha: branch,
    per_page: 1
  });

  console.log(
    "Last commit sha on %s branch: %s (tree: %s)",
    branch,
    latestCommitSha,
    latestCommitTreeSha
  );

  const {
    data: { sha: newBlobSha }
  } = await octokit.request("POST /repos/:owner/:repo/git/blobs", {
    owner,
    repo,
    content: require("fs").readFileSync(
      FILE_PATH,
      "base64"
    ),
    encoding: "base64"
  });

  console.log("Blob created: %s", newBlobSha);

  const {
    data: { sha: newTreeSha }
  } = await octokit.request("POST /repos/:owner/:repo/git/trees", {
    owner,
    repo,
    base_tree: latestCommitTreeSha,
    tree: [
      {
        path: `test-${Math.random()
          .toString(36)
          .substr(2)}.jpg`,
        mode: "100644",
        sha: newBlobSha
      }
    ]
  });

  console.log("tree created: %s", newTreeSha);

  const { data: commit } = await octokit.git.createCommit({
    owner,
    repo,
    message: "test",
    tree: newTreeSha,
    parents: [latestCommitSha]
  });

  console.log(`commit created`);
  console.log(commit);
}
```

I tried to set `encoding` in the `Create a tree` API, but no luck, it's being ignored and set to `utf8` as far as I can tell

```js

  const {
    data: { sha: newTreeSha }
  } = await octokit.request("POST /repos/:owner/:repo/git/trees", {
    owner,
    repo,
    base_tree: latestCommitTreeSha,
    tree: [
      {
        path: `test-${Math.random()
          .toString(36)
          .substr(2)}.jpg`,
        mode: "100644",
        content: require("fs").readFileSync(
          FILE_PATH,
          "base64"
        ),
        encoding: "base64"
      }
    ]
  });
```

I've asked why that is and will comment here when I find out more

**Comment by seanmcilvenna** [comment]
yah, this is the approach I tried to take. unfortunately, I just have too many files to push. creating the blobs ends up getting rejected due to suspected abuse (because there are too many requests). I need to figure out a better way to create blobs/trees with potentially 100's of files.

**Comment by gr2m** [comment]
Did you try using the [throttling plugin](https://github.com/octokit/plugin-throttling.js/)?

**Comment by cstenkamp** [comment]
Is there any update on this? It is really annoying that I cannot add multiple files (some of which binary) simultaneously in on single request using the data-API.

**Comment by gr2m** [comment]
it's not possible with a single request. But you can use https://github.com/gr2m/octokit-create-pull-request, which abstracts the requests away and provides a single method to create pull requests with multiple file changes, both text & binary
