### ISSUE TITLE
TypeError: Cannot read property 'gists' of null

### ISSUE THREAD

**Issue by shanalikhan** [octokit/octokit.js#1314]
When user is not authenticated.
And API sends call to read the public GIST.

Get the following error:
> TypeError: Cannot read property 'gists' of null

```
this.github.gists.get({ gist_id: GIST });
```

**Comment by gr2m** [comment]
Where does `this.github` come from?

I am not able to reproduce the issue: https://runkit.com/gr2m/octokit-rest-js-1314

**Comment by shanalikhan** [comment]
Got it, thanks
