### ISSUE TITLE
Basic auth does not work for creating a personal access token

### ISSUE THREAD

**Issue by protoEvangelion** [octokit/octokit.js#1319]
`version: 16.23.4`

While 2fa with basic auth works to create a developer token on github, basic auth only does not succeed. This works in the `authentication-deprecated` plugin.  Here is the method in question `octokit.oauthAuthorizations.createAuthorization(payload)`

The below was tested on an account without 2fa enabled.

When I use ``new Octokit({ auth: `${answers.username}:${answers.password}` })`` and then call the method above, it throws this error: `Bad credentials`.

But when I append "basic " in front of the auth param like ``new Octokit({ auth: `basic ${answers.username}:${answers.password}` })`` and then call the method above, it throws this error: `Requires authentication`.

Here is the minimal to reproduce the error fully. 

```javascript
const nock = require('nock')
const octokit = require('@octokit/rest')
const inquirer = require('inquirer')

;(async function createNewOathToken() {
    let octokit

    const answers = await inquirer.prompt([
        {
            type: 'input',
            message: 'Enter your GitHub user',
            name: 'username',
        },
        {
            type: 'password',
            message: 'Enter your GitHub password',
            name: 'password',
        },
        {
            type: 'confirm',
            message: 'Do you have 2FA enabled on your GitHub account?',
            name: '2FAEnabled',
        },
    ])

    if (answers['2FAEnabled']) {
        octokit = new Octokit({
            auth: {
                username: answers.username,
                password: answers.password,
                async on2fa() {
                    const { code } = await inquirer.prompt([
                        {
                            type: 'input',
                            message: 'Enter your Two-factor GitHub authenticator code',
                            name: 'code',
                        },
                    ])

                    return code
                },
            },
        })
    } else {
        octokit = new Octokit({ auth: `${answers.username}:${answers.password}` })
    }

    const payload = {
        note: `your token`,
        scopes: ['user', 'public_repo', 'repo', 'repo:status', 'delete_repo', 'gist'],
    }

    try {
        var { data } = await octokit.oauthAuthorizations.createAuthorization(payload)
    } catch (err) {
        throw new Error(`Error creating GitHub token\n${err.message}`)
    }
})()
```

**Comment by gr2m** [comment]
I’m looking into it! I think you’ll be interested in https://github.com/octokit/rest.js/pull/1293#issuecomment-479671368

**Comment by gr2m** [comment]
``new Octokit({ auth: `${answers.username}:${answers.password}` })`` is a wrong usage, is it documented that way somewhere?

These should all work

```js
new Octokit({
  auth: {
    username: answers.username,
    password: answers.password
  }
})
// or
new Octokit({
  auth: btoa(`${answers.username}:${answers.password}`)
})
// or
new Octokit({
  auth: 'basic ' + btoa(`${answers.username}:${answers.password}`)
})
```

**Comment by gr2m** [comment]
Here is a test case https://runkit.com/gr2m/octokit-rest-js-1319/1.0.0

**Comment by protoEvangelion** [comment]
Wow 🤦‍♂️ I tried that first option initially but I think I was doing something else wrong thus causing the error.   

Anyways, that first option resolves this issue!

Thanks for your quick work and making it look easy haha 😉

**Comment by CasperBroekhuizen** [comment]
I have a issue similar to the issue mentioned above, however this issue is not resolved for me.
My application was working fine until last weekend.

Even when running the most simple code using an import from the pika cdn:
```javascript
import { Octokit } from 'https://cdn.pika.dev/@octokit/rest'

var user = prompt("Username", "");
var pass = prompt("Password", "");

new Octokit({
  auth: {
    username: user,
    password: pass
  }
})
```

I get the following error:
`rest.js:993 Uncaught Error: [@octokit/auth-token] Token passed to createTokenAuth is not a string`

This error started from me when using the createbasicauth function from https://github.com/octokit/auth-basic.js , which works fine until one tries to pass token options such as scopes.

**Comment by protoEvangelion** [comment]
@CasperBroekhuizen I would recommend opening a new issue for this since it's been about a year since I opened this & things have likely changed.

**Comment by gr2m** [comment]
@CasperBroekhuizen  as @protoEvangelion suggests, please always open a new issue. More often than not, your issue does look similar, but it's unrelated to the original issue.

In your case: `@octokit/rest` was upgraded from v16 to v17. The CDN URL `https://cdn.pika.dev/@octokit/rest` will always give you the latest version. Try to replace it with `https://cdn.pika.dev/@octokit/rest/v16`. You'll see some deprecation messages, address them, then replace the URL with `https://cdn.pika.dev/@octokit/rest/v17`, to upgrade to the latest version. See all release notes at https://github.com/octokit/rest.js/releases/v17.0.0

**Comment by CasperBroekhuizen** [comment]
Thank you both @protoEvangelion and @gr2m, I will look at the provided release notes. 
I believe this will resolve my issues as I noticed the CDN was updated two days ago.

My apologies however for awakening such an old issue. The date of 14th of April aligned quite nicely with when my problems started. However I should've paid more attention to the year indicator.  🤦‍♂️
