### ISSUE TITLE
Typescript: add "@deprecated" jsDoc comment to deprecated methods 

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1322]
For example, `.licenses.list()` was deprecated and renamed to `.licenses.listCommonlyUsed()` in [v16.17.0](https://github.com/octokit/rest.js/releases/tag/v16.17.0).

```ts
  licenses: {
    listCommonlyUsed: {
      (params?: Octokit.EmptyParams): Promise<
        Octokit.Response<Octokit.LicensesListCommonlyUsedResponse>
      >;

      endpoint: Octokit.Endpoint;
    };

    list: {
      (params?: Octokit.EmptyParams): Promise<
        Octokit.Response<Octokit.LicensesListResponse>
      >;

      endpoint: Octokit.Endpoint;
    };
```

There should be a deprecation comment above the `list: {` line

**Comment by ajafff** [comment]
This should not only be done for deprecated methods:
* There are deprecated properties that currently have a `// Deprecated` comment
* Some properties like `IssuesCreateParams.assignee` have a JSDoc comment like `**This field is deprecated.**`
