### ISSUE TITLE
[FR] Add the capability to get Projects from a private org 

### ISSUE THREAD

**Issue by TheDers** [octokit/octokit.js#1340]
Hi there,

I've done a bit of research and testing, and it doesn't appear possible to grab a list of projects from a repo within a private organization.
Issue #968 allows me to grab a list of private repos, but I am unable to then grab the projects from those repos. Since this is all happening within a private organization that the user is part of, I can't use the octokit.projects.listForRepo command, as they do not show up in here.

My motivation for this FR is to automatically create new projects in a repo that lives within a private organization. If this can be achieved some other way sorry I missed it.

**Comment by gr2m** [comment]
Thanks Anders, I’ll dig into this one and try to reproduce the problem. I think `octokit.projects.listForRepo()` should work as expected here, I'm surprised that it does not for private repositories. What is the error that you receive?

**Comment by TheDers** [comment]
Hey Gregor, I'm getting a 404 error when attempting to pass Owner and Repo params.
The URL that is being hit is https://api.github.com/repos/TheDers/:repo/projects which should be correct, the issue here is that the repo i'm choosing isn't a repo that I've forked or created in my personal organization, rather it's a repo that exists in the private organization that I'm a part of and have access to.

I tried forking one of the repos from this private org and that appears to work, even if the fork is private.   However this isn't a reasonable expectation for my use case.

**Comment by gr2m** [comment]
how do you authenticate the request? If you use a personal access token, does it include the `read:org` scope?

**Comment by TheDers** [comment]
Yes I'm using a personal access token. It has all permissions other than delete repo.

**Comment by TheDers** [comment]
One other clarification. I'm also using the method `octokit.repos.listForOrg` which is correctly grabbing the repo list from my private org. 
In `octokit.projects.listForRepo` i'm providing the repo name i.e. `repo : 'repoName'`. Is that correct or should I be providing the repo ID?

**Comment by gr2m** [comment]
I just tested `octokit.projects.listForRepo()` to retrieve projects for a private repository in an organization and it worked just as expected ¯\\\_(ツ)\_/¯ I’m not sure what the problem might be. My best guess would be something with the token?

If we can’t figure it out I’d send a message to GitHub support. You can provide a curl example so they can reproduce it more easily (replace `OWNER`, `REPO` and `TOKEN`)

```sh
curl https://api.github.com/repos/OWNER/REPO/projects \
    -H'Authorization: token TOKEN' \
    -H'Accept: application/vnd.github.inertia-preview+json' 
```

Just make sure that you get the same result with the `curl` command as you do with Octokit

> In octokit.projects.listForRepo i'm providing the repo name i.e. repo : 'repoName'. Is that correct or should I be providing the repo ID?

That is correct.

**Comment by TheDers** [comment]
Ok thanks for confirming it works for you. Now I know it's just a problem on my side and not a limitation of the tool 😄

**Comment by TheDers** [comment]
@gr2m  Actually I got it to work. The problem was that the username I was originally providing was my  own username, but once I passed the organization name instead it worked.
