### ISSUE TITLE
[Question] Is there a way to check if a file exists in a repo?

### ISSUE THREAD

**Issue by MVrachev** [octokit/octokit.js#1345]
I don't see an API endpoint for that...

**Comment by gr2m** [comment]
I’d use [`octokit.repos.getContents()`](https://octokit.github.io/rest.js/#octokit-routes-repos-get-contents) with the `HEAD` method

```js
try {
  await octokit.repos.getContents({
    method: 'HEAD',
    owner,
    repo,
    path
  })
  // file exists
} catch (error) {
  if (error.status === 404) {
    // file does not exist
  } else {
    // handle connection errors
  }
}
```

If the response is successful, the `path` exists. If it fails with `error.status === 404`,

**Comment by MVrachev** [comment]
Thank you for your detailed response!

That will work but that means that there is no such API endpoint? You should handle it that way?

**Comment by gr2m** [comment]
There is no dedicated REST API endpoint to check if a file exist that I’d know of. 

You could create an Octokit plugin, it would look sth like this

```js
const MyOctokit = require('@octokit/request')
  .plugin((octokit) => {
    octokit.checkIfFileExists = async ({ owner, repo, path }) => {
      try {
        await octokit.repos.getContents({
          method: 'HEAD',
          owner,
          repo,
          path
        })
        return true
      } catch (error) {
        if (error.status === 404) {
          return false
        }

        throw error
      }
    }
  })

const octokit = new MyOctokit()
octokit.checkIfFileExists({ owner: 'octokit', repo: 'rest.js', path: 'lib/core.js' })
  .then(doesExist => {
    if (doesExist) {
      // path exists
    } else {
      // does not exist
    }
  })
```

**Comment by MVrachev** [comment]
Again, thank you for your answer and information.

It helped me. 😊

**Comment by gr2m** [comment]
Anytime :)

**Comment by gr2m** [comment]
Not directly, you would need to retrieve the PR's branch name first, then look if the file exists

**Comment by johnsonsamuel** [comment]
> Not directly, you would need to retrieve the PR's branch name first, then look if the file exists

thanks :)
