### ISSUE TITLE
Unable to use `accept: application/octet-stream` when `previews` set

### ISSUE THREAD

**Issue by dominykas** [octokit/octokit.js#1348]
I'm trying to use `repos.getReleaseAsset()`, but it seems the `accept` header from `previews` overrides the `headers: { accept }` I pass into the method.

I think this is fairly recent - it definitely used to work. Or am I missing some non-obvious way to override it?

**Comment by dominykas** [comment]
So I think [I have a failing test](https://github.com/dominykas/endpoint.js/commit/b1574b7700750076f7091fb48d5dd328ee992590) for the issue, but I'm not sure about the fix.

**Comment by gr2m** [comment]
Thanks @Dominykas I’ll look into it

**Comment by dominykas** [comment]
Thanks!

**Comment by szul** [comment]
@dominykas @gr2m I can't tell if this issue is resolved or not. Do you have a gist to a working `getReleaseAsset()` example that downloads the release assets? When I set the accept header I get an XML-infused failure message:

```
UnhandledPromiseRejectionWarning: HttpError: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>token [TOKEN_VALUE_IS_DISPLAYED_HERE]</ArgumentValue>...</Error>
```

This is with the latest `@octokit/rest` and the simple example below (where req is a Express request object):

```javascript
const tag = req.body.release.tag_name;
const octo = new Octokit({
        auth: process.env.GITHUB_TOKEN
});
const release = await octo.repos.getReleaseByTag({
        owner: '<OWNER_NAME>',
        repo: '<REPO_NAME>',
        tag: tag
});
const result = await octo.repos.getReleaseAsset({
        owner: '<OWNER_NAME>',
        repo: '<REPO_NAME>',
        asset_id: release.data.assets[0].id,
        headers: {
            accept: 'application/octet-stream'
        }
});
```

It looks like adding the `headers` to `getReleaseAsset()` is interfering with the `auth` in the `Octokit()` instantiation.

**Comment by gr2m** [comment]
> Only one auth mechanism allowed

This error is unrelated. Unfortunately there is not much we can do about it. The implementation of `fetch` posts the same authorization header in the case of a 302 redirect, even if the host name changes. Then Amazon S3 complaints that the `Authorization` header is not allowed.

I've mentioned a workaround here: https://github.com/octokit/rest.js/issues/967#issuecomment-477800969

**Comment by szul** [comment]
@gr2m Thanks. I actually just went with a `request-promise` call and used the `TOKEN@api.github.com` URI structure to get this working. I was hoping for a fix to use the SDK. I appreciate you following up.
