### ISSUE TITLE
URL-encode parameters in request paths

### ISSUE THREAD

**Issue by Eddman** [octokit/octokit.js#1355]
There are multiple endpoints where you can pass parameters directly to URL, but these can contain characters that change the URL meaning. For example:
```
GET /repos/:owner/:repo/compare/:base...:head
GET /repos/:owner/:repo/git/refs/:ref
etc.
```
`:base`, `:head` and `:ref` parameters are branch names that support characters like `/` and `#`. If we do not URL encode these as `%2F` and `%23` we're changing the URL and Github fails to respond.

Noticed in `@octokit/rest@16.25.0`.

**Comment by gr2m** [comment]
Thanks for the bug report Adam. Ideally it would be fixed in https://github.com/octokit/endpoint.js but only if it does not blow up the bundle size too much. I wonder if we can `encodeURIComponent(value)` in general for URL parameters? The only exception I can think of right now is `:path`

- [Get contents](https://developer.github.com/v3/repos/contents/#get-contents) (`GET /repos/:owner/:repo/contents/:path)`
- [Create a file](https://developer.github.com/v3/repos/contents/#create-a-file) (`PUT /repos/:owner/:repo/contents/:path)`
- [Update a file](https://developer.github.com/v3/repos/contents/#update-a-file) (`PUT /repos/:owner/:repo/contents/:path)`
- [Delete a file](https://developer.github.com/v3/repos/contents/#delete-a-file) (`DELETE /repos/:owner/:repo/contents/:path)`

And even then all characters but `/` should be encoded. I created a `#test` file to check my theory:

1. without encoding: https://api.github.com/repos/gr2m/sandbox/contents/#test - returns files of the root directory
2. with encoding: https://github.com/gr2m/sandbox/blob/latest/%23test - returns `#test` file

**Comment by gr2m** [comment]
Also

- [Upload a release asset](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) - `POST :upload_url` 

But that's a weird one anyway

**Comment by gr2m** [comment]
I double checked

- [Get team by name](https://developer.github.com/v3/teams/#get-team-by-name) - `GET /orgs/:org/teams/:team_slug`

But `team_slug` is guaranteed to not include `/` or other special characters

**Comment by Eddman** [comment]
The ones with branch are also a bit complex as they have `heads/` prefix which is required and the `/` has to be there (not encoded).

For now I use `encodeURIComponent`. It should be fine as it is part of the JS spec and therefor available in every environment including NodeJS.

**Comment by gr2m** [comment]
> Ideally it would be fixed in <https://github.com/octokit/endpoint.js>

After thinking some more about it, I wouldn't fix it in `@octokit/endpoint.js`. I try to keep it as little magic as possible, it should be clear to users that the URL parameters need to be encoded.

I'll try to add it to `@octokit/rest` though. This is going to be a breaking change, even though a small one

**Comment by gr2m** [comment]
Hi @Eddman, 

I know it's been a while, but I finally got around to test the two endpoints. They worked without any problems or URL encoding on my side

Example 1

```js
const octokit = new Octokit();
const options = octokit.request.endpoint(
  "GET /repos/:owner/:repo/git/refs/:ref",
  {
    owner: "octokit",
    repo: "rest.js",
    ref: "heads/greenkeeper/@octokit/plugin-rest-endpoint-methods-3.0.0"
  }
);
console.log(options);

main();

async function main() {
  const { data } = await octokit.request(options);
  console.log(data);
}
```

Example 2 

```js
const octokit = new Octokit();

const options = octokit.request.endpoint(
  "GET /repos/:owner/:repo/compare/:base...:head",
  {
    owner: "octokit",
    repo: "rest.js",
    base: "master",
    head: "greenkeeper/@octokit/plugin-rest-endpoint-methods-3.0.0"
  }
);
console.log(options);

main();

async function main() {
  const { data } = await octokit.request(options);
  console.log(data);
}
```

Tthe `/` seems not to be a problem? 

The `#` however is causing problems

```js
const options = octokit.request.endpoint(
  "GET /repos/:owner/:repo/git/refs/:ref",
  {
    owner: "gr2m",
    repo: "sandbox",
    ref: "heads/#baby"
  }
);
console.log(options);

main();

async function main() {
  const { data } = await octokit.request(options);
  console.log(data);
}
```

Is returning all branches, not just the `#baby` branch. So I might look into encoding the `#` sign in URL parameters. I think query parameters are encoded already anyway

**Comment by gr2m** [comment]
URL parameters are encoded by default now, at least when using the `{param}` notation. The `:param` notation is deprecated and will be removed in future

**Comment by stefankeil** [comment]
> Thanks for the bug report Adam. Ideally it would be fixed in https://github.com/octokit/endpoint.js but only if it does not blow up the bundle size too much. I wonder if we can `encodeURIComponent(value)` in general for URL parameters? The only exception I can think of right now is `:path`
> 
> * [Get contents](https://developer.github.com/v3/repos/contents/#get-contents) (`GET /repos/:owner/:repo/contents/:path)`
> * [Create a file](https://developer.github.com/v3/repos/contents/#create-a-file) (`PUT /repos/:owner/:repo/contents/:path)`
> * [Update a file](https://developer.github.com/v3/repos/contents/#update-a-file) (`PUT /repos/:owner/:repo/contents/:path)`
> * [Delete a file](https://developer.github.com/v3/repos/contents/#delete-a-file) (`DELETE /repos/:owner/:repo/contents/:path)`
> 
> And even then all characters but `/` should be encoded. I created a `#test` file to check my theory:
> 
> 1. without encoding: https://api.github.com/repos/gr2m/sandbox/contents/#test - returns files of the root directory
> 2. with encoding: https://github.com/gr2m/sandbox/blob/latest/%23test - returns `#test` file

Hi @gr2m, 
I was stumbling across this topic. I'm agreeing that `/` should not be escaped from `:path` as you mentioned, but it's still the case. 
In the test it seems to be expected https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/d6ba795ef852432035a39a2fea977e1656c9939e/test/typescript.test.ts#L35
Any idea or plans to change that?

**Comment by gr2m** [comment]
you shouldn't use the `:path` notion, use `{path}` instead. We will drop support for `:path` soon.

Encoding URL parameters such as `path` is the correct behavior, so we are not going to change it.
