### ISSUE TITLE
repos.compareCommits type

### ISSUE THREAD

**Issue by Kinrany** [octokit/octokit.js#1369]
Right now `octokit.repos.compareCommits` ([docs]) returns `Promise<Response<any>>`.

I was going to try to contribute better typings, but couldn't find the types for any of the other methods. This repo has virtually no `.ts` or `.d.ts` files :0

[docs]: https://octokit.github.io/rest.js/#octokit-routes-repos-compare-commits

**Comment by wolfy1339** [comment]
Hey @Kinrany ! Thanks for the feedback. The typings are automatically generated via a script, which is why you cannot find any typescript definitions.
The typings are based off of the official GitHub docs. I'll leave this to other team members that know a little more on how they're generated

**Comment by gr2m** [comment]
Hi @Kinrany,

most of the TypeScript definitions are generated, just like the endpoint methods such as `octokit.repos.compareCommits`, from [octokit/routes](https://github.com/octokit/routes). 

The script to generate them is `npm run build:ts`, which in turn runs `node scripts/generate-types`.

Here is the template file: [scripts/templates/index.d.ts.tpl](https://github.com/octokit/rest.js/blob/79651d916db294aed4fd5ab08f6e46bcef35d515/scripts/templates/index.d.ts.tpl). And here is [the script](https://github.com/octokit/rest.js/blob/79651d916db294aed4fd5ab08f6e46bcef35d515/scripts/generate-types.js) file which loads the definitions from `octokit/routes` and generates the `index.d.ts` file which is published together with the code to npm

**Comment by wolfy1339** [comment]
I think I've spotted the problem, in the [@octokit/routes definition](https://github.com/octokit/routes/blob/master/routes/api.github.com/repos/compare-commits.json) the `requests` key should probably be the `responses` key

**Comment by gr2m** [comment]
Yes looks like it 🤔 I wonder why it parses https://developer.github.com/v3/repos/commits/#response-3 as a request instead of a response

**Comment by copperwall** [comment]
I did some poking around `index.d.ts` and it looks like the return value is now

```ts
Promise<Octokit.Response<Octokit.ReposCompareCommitsResponse>>;
```

I tried doing a `git bisect` in this repo to see where exactly that changed, but I couldn't find a commit between May and now that caused the types to generated with an `any` response. Maybe the fixing change was made in `@octokit/routes`?

**Comment by gr2m** [comment]
I only recently started to track changes of index.d.ts in `git`, before it was generated right before publishing to npm. There have also been lots of changes in `octokit/routes` in between as we migrated to OpenAPI, so the problem might have likely be resolved meanwhile. 

I checked it and it looks good to me, too

<img width="510" alt="image" src="https://user-images.githubusercontent.com/39992/67594526-61e2b000-f719-11e9-95cd-f14fbc50c2cc.png">

Thanks for having a look at it @copperwall!

@Kinrany if there is still a problem with the latest version, please let me know
