### ISSUE TITLE
updateRef with force=true closes open PRs referencing ref

### ISSUE THREAD

**Issue by bcoe** [octokit/octokit.js#1373]
When I execute the following API call:

```js
await this.octokit.git.updateRef({
          owner: this.owner,
          repo: this.repo,
          // TODO: remove the replace logic depending on the outcome of:
          // https://github.com/octokit/rest.js/issues/1039.
          ref: refName.replace('refs/', ''),
          sha: options.sha,
          force: true
});
```
I notice that open PRs referencing `ref` appear to be closed; I've been able to work around this by immediately reopening the PR, but this behavior seems odd (and creates some noise in the issue history).

Any chance I'm misunderstanding the API? My goal is to reset the branch to `master`, and force new commits on top of it.

**Comment by gr2m** [comment]
Hmm this sounds like it’s a question better suited for https://github.com/support. Happy to help setup a simple reproducible test case. 

Could you describe the steps? Maybe make a quick screencast? What ever is easiest for you

**Comment by bcoe** [comment]
@gr2m here's a reproduction in code:

## Reproduction

The [code here](https://github.com/googleapis/release-please/blob/master/src/github.ts#L269) reproduces the issue being described.

Here's an issue that demonstrates the [behavior in action](https://github.com/googleapis/release-please/pull/151) note that the PR is `closed` immediately before the `force push`.

So, summarizing:

1. open a PR pointing to a specific ref.
2. update the ref that the above PR points to, forcing the `ref` to point at the `sha` at the head of `master`.
3. add a couple files to the branch;.

_when I have some cycles I can try to create an isolated reproduction for you._

**Comment by gr2m** [comment]
I was able to reproduce it here https://github.com/gr2m/octokit-rest.js-issue-1373/pull/1

What is it you are trying to achieve? If you set the branch of the pull request’s head to point to the head of the master branch, wouldn’t that make the two branches equal?

Are you trying to rebase the PR on latest master?

**Comment by bcoe** [comment]
@gr2m the goal is to make the PR equal to the latest master, at which point it will have several files committed (diverging the branch from master).

The idea is an evergreen PR that reflects what the next release of the project would look like, without constantly closing the prior PR.

**Comment by gr2m** [comment]
That is basically a rebase on latest master & force-push, right?

I’m not sure how that would be accomplished with the current APIs, but something I wanted to look into it anyway.

**Comment by gr2m** [comment]
I haven’t looked into it in detail, but maybe have a look at https://github.com/tibdex/github-rebase? It sounds like it does what you need if I understand you correctly

**Comment by bcoe** [comment]
@gr2m thank you for the pointer, I'll take a look and see if this prevents the additional `close`.

**Comment by gr2m** [comment]
@bcoe did you figure it out?

**Comment by bcoe** [comment]
@gr2m I never dug into this further unfortunately, although it's still something we'd like to figure out on our end.

**Comment by nekolab** [comment]
> 1. open a PR pointing to a specific ref.
> 2. update the ref that the above PR points to, forcing the ref to point at the sha at the head of master.
> 3. add a couple files to the branch;.

Hi team, I can still reproduce the issue by following the steps above. It's really annoying when you want to have a PR tracking the newest master. Shall we fix this issue?

**Comment by wolfy1339** [comment]
It sounds like an issue with the GitHub API endpoint itself and not Octokit.

**Comment by nekolab** [comment]
Filed a bug report here: https://github.com/orgs/community/discussions/148491
