### ISSUE TITLE
Unable to update file using octokit.repos.updateFile

### ISSUE THREAD

**Issue by alexandruluca** [octokit/octokit.js#1374]
Hi. I am not able to update a file using ```octokit.repos.updateFile```
Below is code I am using. Please note, first I am getting the sha of the file using ```octokit.repos.getContents``` and then I'm passing it to updateFile.

```    
let res = await octokit.repos.getContents({
            owner,
            path: 'package.json',
            repo,
            ref: 'refs/heads/feature/some-feature-branch'
    }); // this call succeeds

    await octokit.repos.updateFile({
        owner,
        repo,
        path: 'package.json',
        message: 'test',
        content: Buffer.from('new content').toString('base64'),
        sha: res.data.sha
    });
```
The second call fails with 
```
HttpError: package.json does not match b1be3740c6f923d7f29d9ab4937
e3338bc915c77
```
Please note, If in the first call I use "refs/heads/develop" as a ref, then the second call is successfull. But my intention is to update the file on a feature branch, not on the develop branch.

What am I missing? Am I doing something wrong here?

**Comment by gr2m** [comment]
Try to pass the `branch` option, see https://octokit.github.io/rest.js/#octokit-routes-repos-update-file

**Comment by alexandruluca** [comment]
I completely missed that. I confirm it works, thanks a lot

**Comment by gaoshuai2020** [comment]
There is no `updateContent` API.

**Comment by gr2m** [comment]
It's `octokit.repos.createOrUpdateFileContents()`, see https://octokit.github.io/rest.js/v18#repos-create-or-update-file-contents.

If you have questions how things work, please start a discussion at https://github.com/octokit/rest.js/discussions
