### ISSUE TITLE
Can't install @octokit/rest anymore

### ISSUE THREAD

**Issue by 104gogo** [octokit/octokit.js#1376]
When ran `npm i @octokit/rest`, I had got some error messages as follow.
```
Error: GET https://registry.npm.taobao.org/@octokit/rest/download/@octokit/rest-16.27.0.tgz response 404 status
```
Oh, I can't install and run my project, the worse I don't kwon which packages dependencies this package..

So I need some help！

**Comment by gr2m** [comment]
It looks like you use a custom npm registry: https://registry.npm.taobao.org. It does exist on the main registry: https://registry.npmjs.org/@octokit%2frest

> "latest":"16.27.0"

But it looks like it exist on https://registry.npm.taobao.org/@octokit%2frest as well now, maybe it was just a hiccup? Please check in with the people in charge of https://registry.npm.taobao.org

**Comment by 104gogo** [comment]
Thank you, it works again.
