### ISSUE TITLE
Add headers to the type definition for requests 

### ISSUE THREAD

**Issue by billytrend** [octokit/octokit.js#1377]
The headers field here works but is not included in the type definitions. I have a few use cases for it, eg for request correlation

```
await github.repos.get({
  owner: "octocat",
  repo: "Hello-World",
  headers: { "x-correlation-id": Math.random() },
})
```

It would also be nice to have plugin support for requests like this so that we can say pass an options object to a request and handle it within a plugin.

```
await github.repos.get(
  {
    owner: "octocat",
    repo: "Hello-World",
  },
  { correlationId: Math.random() },
);
```

Let me know if this sounds good or if there is already a good way to do these things and I can look at contributing the changes required.

**Comment by gr2m** [comment]
What's the `x-correlation-id` header? I don’t think it’s mention anywhere in the docs for GitHub’s API, so I’m not sure why type definitions for it would make sense?

> It would also be nice to have plugin support for requests like this so that we can say pass an options object to a request and handle it within a plugin.

You can set custom meta options on the request option, e.g.

```js
await github.repos.get(
  {
    owner: "octocat",
    repo: "Hello-World",
    request: {
      correlationId: Math.random()
    }
  }
);
```

Then in your plugin you can define a request hook that does something with it.

See

- https://octokit.github.io/rest.js/#plugins
- https://octokit.github.io/rest.js/#hooks

Hope that helps

**Comment by billytrend** [comment]
Ah the header is just something that gets automatically picked up by our telemetry libraries. I also had a use case for sending custom cache control headers at one point. 

I think the request option is exactly what I'm looking for, thanks!! Not sure if it's in type definitions though but I'll check later.

**Comment by gr2m** [comment]
I’ll close the issue for the time being as the original question is resolved I think
