### ISSUE TITLE
Inconsistent response formats

### ISSUE THREAD

**Issue by mrchief** [octokit/octokit.js#1386]
This is similar to #497 but with different endpoints than 497.

```
const tags = await client.paginate(client.repos.listTags.endpoint.merge({ owner, repo }))
console.log({ tags })

// tags is an array of tags
```

However, for commits (listCommits, getCommit), the response is:

```
const commit = await client.repos.getCommit({ owner, repo, sha })
console.log({ commit })

// commits is now under data property 
{ status, ..., data: <commits array> }
```

However, paginating commits produces just the commits array, without the `data` wrapper

```
const commits = await client.paginate(
    client.repos.listCommits.endpoint.merge({ sha, owner, repo, since })
  )

// commits is an array of commits
```

Is this by design? If so, is this documented somewhere?

**Comment by gr2m** [comment]
That sure looks like a bug, thanks for reporting it!

We put plenty of effort to normalize responses from GitHub’s REST API. Some endpoints return an array for list responses, others return an object. You can learn more from the code at https://github.com/octokit/rest.js/blob/master/plugins/pagination/normalize-paginated-list-response.js

I’ll have a look into it, but cannot tell when yet. If you like, you could try to create a test case which reproduces the problem, you can put it in here: https://github.com/octokit/rest.js/tree/master/test/issues

**Comment by mrchief** [comment]
@gr2m Sure! Which one is the violator? I assume the `tags` call? Or basically, any call that doesn't return an object with `data` wrapper (based on [usage instructions](https://github.com/octokit/rest.js#usage))?

**Comment by gr2m** [comment]
Yes, the tags call, there should be no data wrapper

**Comment by mrchief** [comment]
> there should be no data wrapper

Are you sure? If so, 
 
 - `listCommits` and `getCommit` are the culprits as they return data wrappers
 - the readme needs an update as well

**Comment by gr2m** [comment]
Ah wait, I misunderstood your issues, sorry! I thought there was an inconsistency in the returned array of a `.paginate` call

The `.paginate()` call removes the `data` wrapper, because it's a response-specific key. Pagination is made of many responses and that is abstracted away, hence the return of just the items that were returned in previous responses in the `data` key, does that make sense?

Can you point me to a place where it’s documented otherwise?

**Comment by mrchief** [comment]
> The .paginate() call removes the data wrapper, because it's a response-specific key. Pagination is made of many responses and that is abstracted away, hence the return of just the items that were returned in previous responses in the data key, does that make sense?

Ahh I see!

> Can you point me to a place where it’s documented otherwise?

The documentation update I was referring to is moot now, given your above explanation.

Since you asked, I checked the docs for [pagination](https://octokit.github.io/rest.js/#pagination) again and I see the examples do have data/non data wrapper responses

```
octokit.paginate('GET /organizations', (response, done) => {
  if (response.data.find(issues => issue.body.includes('something'))) {
    done()
  }
  return response.data
})

const options = octokit.issues.listForRepo.endpoint.merge({ owner: 'octokit', repo: 'rest.js' })
octokit.paginate(options)
  .then(issues => {
    // issues is an array of all issue objects
  })
```

In the first example, paginate's response returns a data wrapper (`response.data`) but in the endpoint merge one, it's an array of objects.

Honestly, I didn't notice the subtle differences until now, even though I've seen the docs so many times. 

I think calling out those differences or adding a note about what you just said _might_ help. You're involved longer with this project so you probably have a better grip on what makes more sense. I'd leave it up to you to make the final call.

**Comment by gr2m** [comment]
Thanks, I’ll give it some thought and leave the issue open as a reminder
