### ISSUE TITLE
`headers` property set for objects that are passed to APIs

### ISSUE THREAD

**Issue by dessant** [octokit/octokit.js#1394]
A new `headers` property is set for the objects that are passed to APIs, this causes issues when the objects are reused for logging or other tasks.

```javascript
const Octokit = require('@octokit/rest');
const octokit = new Octokit();

const data = {
  owner: 'octokit',
  repo: 'rest.js'
};
octokit.repos.get(data).then(() => {
  console.log(data);
});
```

Output:
```
{headers: {}, owner: "octokit", repo: "rest.js"}
```

https://runkit.com/dessant/5cfe37fdd14969001b6eea3f

**Comment by gr2m** [comment]
Thanks for the great bug report 👍 I’ll look into it.

If you like to have a look yourself, it is likely a problem with https://github.com/octokit/request.js, you could start by creating a pull request with a failing test, if you like
