### ISSUE TITLE
Show deprecation message for deprecated methods

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1398]
Example:
https://octokit.github.io/rest.js/#octokit-routes-apps-find-repo-installation

![image](https://user-images.githubusercontent.com/39992/59310701-180e9700-8c5c-11e9-9228-e53e51937226.png)

It is deprecated correctly in code:
https://github.com/octokit/rest.js/blob/13f74e75aa29ccc8fde598bfc6973ab756674d56/plugins/rest-api-endpoints/routes.json#L658-L659

**Comment by copperwall** [comment]
Hey @gr2m, I'm interested in working on this!

Would checking the `isDeprecated` field returned in the endpoints type from https://octokit-routes-graphql-server.now.sh be the correct place to get information if an endpoint is deprecated or not?

I put together a little mockup for the `Remove team member` endpoint which has an `isDeprecated` value of `true`.

![Screen Shot 2019-09-29 at 1 52 29 PM](https://user-images.githubusercontent.com/2539016/65839313-b2085700-e2c0-11e9-97fa-2dc57f164745.png)

Maybe that could use a warning icon to the left of the text too or something.

Also I noticed that `findUserInstallation` is marked as deprecated in the `routes.json` file you linked, but the response from the endpoints GraphQL server doesn't have it marked as deprecated. Do you know where that endpoints query is getting the data from?
![image](https://user-images.githubusercontent.com/2539016/65839359-65714b80-e2c1-11e9-8703-1afec59c7cb2.png)

**Comment by gr2m** [comment]
It's a little confusing, there are two kinds of deprecations.

1. Endpoints that GitHub themselves deem deprecated, e.g. [Remove team member](https://developer.github.com/v3/teams/members/#remove-team-member)
  
  <img src="https://user-images.githubusercontent.com/39992/65839730-eda52000-e2c4-11e9-9a77-1327c9029e10.png">

2. Endpoints that we have to deprecate on the library level, e.g. because they have been renamed, such as `Find a user installation` -> `Get a user installation` https://github.com/octokit/rest.js/blob/492f7b6f37ee8c379f17c78db5ec1ea3130ef13b/plugins/rest-api-endpoints/routes.json#L351-L359

Ideally, we should show a deprecation for both.

The former should already have a note about it in its description as it's copied from the developer.github.com/v3 docs. But we could highlight it more like you suggest, it looks great.

The latter is where we need to add a custom deprecation message and in most cases point to the new method name, just like we do when running the code. The only exception that was deprecated without a replacement is https://github.com/octokit/rest.js/blob/492f7b6f37ee8c379f17c78db5ec1ea3130ef13b/plugins/rest-api-endpoints/routes.json#L2763-L2776 - GitHub decided to no longer document this API and plans to remove it in future.

Thank you for looking into it Chris! Please ask away if you have more questions!

**Comment by gr2m** [comment]
Oh I should add how you get the two from the GraphQL Query.

1. `isDeprecated` means it's deprecated by GitHub. 
2. In order to retrieve deprecations for an endpoint, you need to look through the `renamed` array https://github.com/octokit/rest.js/blob/492f7b6f37ee8c379f17c78db5ec1ea3130ef13b/scripts/generate-routes.js#L51-L56

**Comment by copperwall** [comment]
Awesome, thanks @gr2m! I'll let you know if I have any more questions.

**Comment by copperwall** [comment]
Oops! I forgot to add a Closes #1398 to the PR.
