### ISSUE TITLE
Cannot retrieve installationAccessToken

### ISSUE THREAD

**Issue by Milredel** [octokit/octokit.js#1399]
I want my back-end to get all PR of all repo of my organisation. I created a github app, installed it and got my installation id and my private key (pem certificate).
But when I run this code :
```js
const { App } = require("@octokit/app");
const { request } = require("@octokit/request");
const APP_ID = XXXX;
const PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nXXXXXXXXX";            
const installation_id = YYYY;
const app = new App({ id: APP_ID, privateKey: PRIVATE_KEY });
const installationAccessToken = await app.getInstallationAccessToken({
    installation_id
});
```
All I can get is this :
```
{ HttpError: 'Expiration time' claim ('exp') is too far in the future
    at response.text.then.message (/Users/Morgan/dev/ezdeploy/node_modules/@octokit/request/dist-node/index.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Am I missing something ?
Thanks for the help

**Comment by Milredel** [comment]
OK, I had time to further investigate the issue and it seems that expirationTime for the jwt is too high.
in @octokit/app/dist_node/index.js the payload is built like that :
`const payload = {
    iat: now,
    exp: now + 60 * 10,
    iss: id
  };`
10 minutes seems too much in the future. I just put 8 and I managed to retrieve my installationAccessToken...

**Comment by gr2m** [comment]
Hi @Milredel, we just fixed that very problem yesterday in https://github.com/octokit/app.js/pull/36, make sure you update `@octokit/app` to the latest version (3.0.1)
