### ISSUE TITLE
Error: Cannot find module '@octokit/request-error'

### ISSUE THREAD

**Issue by jiajiawang** [octokit/octokit.js#1400]
node: v11.9.0
npm: 6.5.0
step to reproduce:
- `npm install @octokit/request-error`
- index.js: `const Octokit = require('@octokit/rest');`
- `node index.js`

I noticed that there were no compiled js files in `node_modules/@octokit/request-error`, but only source ts files.

**Comment by dankoster** [comment]
Getting exactly the same issue. 
Also tried explicitly installing `@octokit/request-error`
Also have no .js files in `node_modules/@octokit/request-error/src` (or in /test)

**Comment by wolfy1339** [comment]
Hey guys, thanks for bringing this up to our attention. I will make sure that it gets fixed promptly

**Comment by gr2m** [comment]
Oops looks like a faulty release, I’m on it

**Comment by gr2m** [comment]
fixed via 1.0.4, sorry again :(

**Comment by dankoster** [comment]
Thanks! It's working perfectly now.
