### ISSUE TITLE
How to upload a File to a Github Issue using Github Rest Api?

### ISSUE THREAD

**Issue by kishan0071234** [octokit/octokit.js#1405]
Not able to find the Rest api to upload or attach a file to the Github Issue.

**Comment by gr2m** [comment]
I didn’t even know that you can upload files other than images to a GitHub issue. And even with images, I actually don’t know how to upload images.

Would you please ask support@github.com? You can link to this issue. Please let us know what you find out 🙏

**Comment by kishan0071234** [comment]
I have tried to add files using comments Api, but the problem is every-time it is creating unique file id and I don't know how to create it using rest api.

**Comment by gr2m** [comment]
Are you trying to create a new file as described in https://github.com/octokit/rest.js/issues/1406, or are you trying to upload a file attachment to a comment?
