### ISSUE TITLE
Not able to create file in the Github Repository using Github Rest api?

### ISSUE THREAD

**Issue by kishan0071234** [octokit/octokit.js#1406]
URL: https://api.github.com/repos/test/contents/abc.txt

BODY:

```json
{
  "message": "my commit message",
  "content": "bXkgbmV3IGZpbGUgY29udGVudHM="
}
```

ERROR:

```json
{
    "message": "Not Found",
    "documentation_url": "https://developer.github.com/enterprise/2.16/v3"
}
```

**Comment by gr2m** [comment]
Could you please share a full code example of what you are doing?

Here is the relevant documentation: https://octokit.github.io/rest.js/#octokit-routes-repos-create-file
