### ISSUE TITLE
Remove node-github module on NPM to avoid confusion

### ISSUE THREAD

**Issue by zenorocha** [octokit/octokit.js#141]
https://www.npmjs.org/package/node-github

**Comment by stefanwalther** [comment]
+1

**Comment by kaizensoze** [comment]
@mikedeboer Would it be ok/possible to take down the node-github package?

**Comment by kaizensoze** [comment]
I don't have the ability to remove the node-github package myself but I think adding a note to the top of the README is the next best option.
