### ISSUE TITLE
Vulnerability endpoint is not defined

### ISSUE THREAD

**Issue by oliikit** [octokit/octokit.js#1425]
[Endpoints](https://octokit.github.io/rest.js/#octokit-routes-repos-enable-vulnerability-alerts) `.checkVulnerabilityAlerts`, `.enableVulnerabilityAlerts`, `.disableVulnerabilityAlerts` seem to not be working. There seems to be some PRs that have addressed this (#1409, #1370), but even on `@octokit/rest` version 16.28.4, I'm receiving this error message: `ReferenceError: getSecurityAlerts is not defined` (which is different from the previous issues). This error message is the same for all three methods.

Code:
```
const Octokit = require('@octokit/rest');

const github = new Octokit({
  previews: ['dorian-preview']
});
  github.repos.checkVulnerabilityAlerts({
    owner: '',
    repo: ''
  })
```
Response: `ReferenceError: getSecurityAlerts is not defined`

**Comment by gr2m** [comment]
I cannot reproduce the problem. The code you shared throws a `HttpError: Not Found` error. Here is a reproducible test case:

https://runkit.com/gr2m/octokit-rest-js-1425

A `.repos.getSecurityAlerts()` function does not exist however. I’m not sure where that comes from.

By the way, no need to set the `dorian` preview. Previews required to use a new API are set automatically.

**Comment by oliikit** [comment]
Interesting.... it's working for me now. I've handled the errors differently and also reverted back to the old code. 😪 I'm not sure what went wrong.

I'm unsure where `.repos.getSecurityAlerts()` came from either, but that was found in my stack trace. 🤷‍♂️

> By the way, no need to set the dorian preview. Previews required to use a new API are set automatically.

Ohhh! Nice to know! It didn't say in the [docs](https://octokit.github.io/rest.js/#previews) and was trying to eliminate variables on why it wasn't working. 

Thanks for help!
