### ISSUE TITLE
createInOrg, update, createForAuthenticatedUser routes are missing is_template preview header support

### ISSUE THREAD

**Issue by davemun** [octokit/octokit.js#1432]
The `octokit.repos.createInOrg()` method supports the `is_template` parameter, but the route for that method has not included the required `Accept` header, `application/vnd.github.baptiste-preview+json`:

https://github.com/octokit/rest.js/blob/master/plugins/rest-api-endpoints/routes.json#L7211-L7266

This renders whatever you put into the `is_template` argument useless, as Github ignores the preview feature `is_template` without the required preview header. 

Docs:
https://developer.github.com/v3/repos/#create
https://octokit.github.io/rest.js/#octokit-routes-repos-create-in-org

**Comment by davemun** [comment]
It looks like https://github.com/octokit/rest.js/commit/7eeecc73630b452546157ce96e199116d47609bd added `is_template` to a couple routes, which are missing the `Accept` header as well.

* `createInOrg`
* `update`
* `createForAuthenticatedUser`

**Comment by gr2m** [comment]
It’s an optimal header so we don’t set it automatically. You can set it yourself as needed https://octokit.github.io/rest.js/#previews
