### ISSUE TITLE
on2fa is required in Octokit.Options for basic authentication

### ISSUE THREAD

**Issue by sorsaffari** [octokit/octokit.js#1434]
`on2fa` is and should be optional when creating a basic `auth` object. This is specially the case when authenticating OAuth application.

However, at the moment [as defined in `Octokit.Options`](https://github.com/octokit/rest.js/blob/master/scripts/templates/index.d.ts.tpl#L48) in the `index.d.ts` file, `on2fa` is a _required key_ on `auth`.

**Comment by wolfy1339** [comment]
Thanks for the heads up. I will personally look into it for you

**Comment by sorsaffari** [comment]
Thanks @wolfy1339. Let me know if I should submit a PR

**Comment by gr2m** [comment]
> `on2fa` is and should be optional when creating a basic `auth` object

I disagree, handling two-factor authentication is required for Basic authentication. If you know what you are doing and you are 100% sure that you don’t need it, you can just pass `on2fa () {}` at your own peril. But I would at least add do something like 

```js
    on2fa () { throw  new Error("2Fa not implemented") }
```

**Comment by sorsaffari** [comment]
To the best of my knowledge, there is no two-factor authentication when it comes to Github OAuth applications. Github requires basic authentication for authenticating OAuth apps, where `username` is the `client_id` and password is the `client_secret` and that's it.

@gr2m I understand why you consider including the `on2fa` a best practice, but I don't think best practices are meant to be enforced.

**Comment by gr2m** [comment]
Ah I see what you mean. Yes, this one exception where OAuth client_id/client_secret needs to be sent as Basic Authentication is weird. Good thing is that we’ve implemented this exception for you, you don’t need to worry about it, just pass 

```js
new Octokit({ auth: { clientId, clientSecret } })
```

And it will do the right thing based on the request URL

**Comment by sorsaffari** [comment]
Thank you @gr2m! Didn't know I could use `auth` in that way

**Comment by gr2m** [comment]
It's somewhat hidden in here: https://octokit.github.io/rest.js/#authentication

I’m reworking the way authentication works right now and hope it will make things more clear.
