### ISSUE TITLE
Why create from Issue url is list of pulls

### ISSUE THREAD

**Issue by kamontat** [octokit/octokit.js#1443]
https://github.com/octokit/rest.js/blob/6ee202d426c0dc4b89e67e73268170eb48f1e13c/plugins/rest-api-endpoints/routes.json#L5448-L5478

**Comment by kamontat** [comment]
I try to run but it always throws `422`

**Comment by kamontat** [comment]
`DEBUG github: GitHub request: POST /repos/:owner/:repo/pulls - 422 (installation=30)`

```json
params: {
  "baseUrl": "<enterprise_link>",
  "mediaType": {
    "format": "",
    "previews": []
  },
  "request": {
    "validate": {
      "base": {
        "required": true,
        "type": "string"
      },
      "draft": {
        "type": "boolean"
      },
      "head": {
        "required": true,
        "type": "string"
      },
      "issue": {
        "required": true,
        "type": "integer"
      },
      "maintainer_can_modify": {
        "type": "boolean"
      },
      "owner": {
        "required": true,
        "type": "string"
      },
      "repo": {
        "required": true,
        "type": "string"
      }
    },
    "retryCount": 1
  },
  "owner": "<name>",
  "repo": "test-project",
  "issue": 13,
  "head": "new-branch-2",
  "base": "master"
}
```

**Comment by kamontat** [comment]
@Octokit/rest.js version `16.28.7`

**Comment by gr2m** [comment]
[Creating a pull request](https://developer.github.com/v3/pulls/#create-a-pull-request) has the same path as [List pull requests](https://developer.github.com/v3/pulls/#list-pull-requests), but a different HTTP verb: `POST /repos/:owner/:repo/pulls` vs `GET /repos/:owner/:repo/pulls`

The error should include more information on why you retrieve the `422` error, I doubt it's a problem with `@octokit/rest`

**Comment by kamontat** [comment]
Any update ?

**Comment by gr2m** [comment]
I don't know what it could be. Maybe the issue `#13` does not exist? Maybe the base or head branch do not exist? The method itself works, I've used it many times.

Also note that the creation of pull requests from issues will soon be deprecated and probably removed in future. I would recommend to not depend on that feature.

**Comment by kamontat** [comment]
Ok. Thanks
