### ISSUE TITLE
Documentation search bug

### ISSUE THREAD

**Issue by imjohnbo** [octokit/octokit.js#1446]
Hi there! 👋 While using the search feature of [the docs](https://octokit.github.io/rest.js/), I noticed that searching for any of the following items results in `octokit-` being added to the url and not leading to the item being searched for.

## Items affected
<img width="977" alt="restjs docs search" src="https://user-images.githubusercontent.com/2993937/63122600-28513400-bf75-11e9-9903-fb47147c8f4b.png">

## Reproduction
![restjs docs search](https://user-images.githubusercontent.com/2993937/63122532-f9d35900-bf74-11e9-9cca-b146968b66c8.gif)

**Comment by copperwall** [comment]
Hey there 👋 I think I have a solution in #1488
