### ISSUE TITLE
npm version 15.18.2 does not have typescript bindings

### ISSUE THREAD

**Issue by emosbaugh** [octokit/octokit.js#1451]
index.d.ts is missing

https://www.npmjs.com/package/@octokit/rest/v/15.18.2

**Comment by wolfy1339** [comment]
Thanks for the report. I can confirm that it isn't present in the package files. I'm the meantime, you could just use the ones from the previous version manually in your project.

Ping @gr2m

**Comment by gr2m** [comment]
Ugh sorry my bad. We automated the release for 15.x as well, but it failed the last time so I did a manual release instead and must have forgotten the build steps. Let me fix that

**Comment by gr2m** [comment]
Should be fixed now, via 15.18.3
