### ISSUE TITLE
Update Documentation for issues.createLabel() & issues.updateLabel()

### ISSUE THREAD

**Issue by joelachance** [octokit/octokit.js#1454]
Some people are having issues with the description parameter for both [createLabel](https://octokit.github.io/rest.js/#octokit-routes-issues-create-label) & [updateLabel](https://octokit.github.io/rest.js/#octokit-routes-issues-update-label).

I propose an update to the docs where it should be noted we need to add `previews` to the Octokit instance:

```
const octokit = new Octokit({
      auth: auth,
      previews: [ 'symmetra' ],
});
```

This should allow for the description parameter to be respected.

**Comment by gr2m** [comment]
[The `symmetra` API header has been graduated](https://developer.github.com/changes/2019-12-13-graduated-previews-announced/), it's no longer necessary to set it
