### ISSUE TITLE
Add `timeZone` constructor option

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1456]
This is a follow up to https://github.com/octokit/rest.js/issues/1455. As `Octokit({headers})` is deprecated, we need to add a new option which sets the time zone header by default for all requests

see also https://developer.github.com/v3/#timezones

**Comment by copperwall** [comment]
I'm interested in working on this if that's cool with you!

**Comment by gr2m** [comment]
Absolutely :) Thanks Chris! The same option should be added to https://github.com/octokit/core.js (eventually https://github.com/octokit/rest.js will be build on top of https://github.com/octokit/core.js)

Thanks a lot for all your help
