### ISSUE TITLE
Documented API methods missing from API (octokit.orgs.listCredentialAuthorizations and octokit.orgs.removeCredentialAuthorization)

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#1458]
There are a couple of API calls documented that don't appear to be available in the API:

https://octokit.github.io/rest.js/#octokit-routes-orgs-list-credential-authorizations
https://octokit.github.io/rest.js/#octokit-routes-orgs-remove-credential-authorization

I was looking at raising a PR but it looks like routes.json may be built by a bot so perhaps not something that should be manually changed?

**Comment by gr2m** [comment]
To explain: `@octokit/rest` only includes methods for endpoints that work on api.github.com, for other endpoints there are plugins such as https://github.com/octokit/plugin-scim.js. That being said, there should be a plugin for GitHub Cloud-only endpoints.

If you run into this issue before it's resolved, you can use `octokit.request()` instead, e.g. for [List credential authorizations for an organization](https://developer.github.com/v3/orgs/#list-credential-authorizations-for-an-organization) you can do this

```js
octokit.request('GET /orgs/:org/credential-authorizations', {
  org: 'my-org-name'
})
```

**Comment by ghost** [comment]
I'd found a workaround using ```registerEndpoints()``` but the ```request()``` is probably cleaner and less likely to cause issues in the future.

I would say that technically it is an api.github.com feature, but only for enterprise cloud subscribers, perhaps merging the scim plugin with other enterprise cloud features would be sensible?

**Comment by gr2m** [comment]
> perhaps merging the scim plugin with other enterprise cloud features would be sensible

Yes, I thought about that. When you have enterprise cloud, does that always include the SCIM features?

**Comment by ghost** [comment]
According to https://developer.github.com/v3/scim/ it seems to be the case:

```
Please note that the SCIM API is available only to organizations on GitHub Enterprise Cloud with SAML SSO enabled. For more information about SCIM, see "About SCIM" in the GitHub Help documentation.
```

I imagine there might be more Enterprise Cloud specific features coming as well.

**Comment by gr2m** [comment]
All the endpoints specific to enterprise cloud now live in https://github.com/octokit/plugin-enterprise-cloud.js/, they are no longer listed in the documentation for `@octokit/rest`
