### ISSUE TITLE
HttpError stack traces are rather unhelpful

### ISSUE THREAD

**Issue by ianwremmel** [octokit/octokit.js#1467]
I'm not sure the best place to open this issue (and I'm only mostly confident it's an octokit problem rather than a me-problem or a node-fetch-problem). When octokit throws its HttpError class, I end up with very unhelpful stacktraces (see screenshot). Any idea what might be done about this and whether it's something to do with an octokit library or build process or if it's something i can change in my own build process? I had initially assumed you were using Bluebird, but as far as I can tell, that's not the case.
<img width="835" alt="Screen Shot 2019-09-16 at 8 27 15 PM" src="https://user-images.githubusercontent.com/1182361/65009374-4639ed80-d8c1-11e9-9840-68ab47bf6690.png">

**Comment by gr2m** [comment]
No we are not using bluebird, we try to stay as close to the web platform as possible to minimize bundle sizes for web browsers.

A `4xx` response is not an error as far as fetch/node-fetch are concerned, we throw the error explicitly. So it's not an error in your code, but the server probably responds with a 4xx error. If you have access to the full error object, it should tell you what the error code is, and also give you `error.request` which has all the request properties for simpler debugging.

**Comment by ianwremmel** [comment]
yep, understood. I'm not disputing whether it should be an Error, I'm trying to make the stack trace helpful. Somewhere, my code is making a call by what of octokit/rest that's returning a 4XX, but I don't know where because the stack trace gets lost in `process._tickCallback`. 

```
/app/node_modules/@octokit/request/dist-node/index.js in response.text.then.message at line 66:23
internal/process/next_tick.js in process._tickCallback at line 68:7
```

I thought current versions of node maintained stacktrace through Promise chains, so it seems like this is an issue with either your build process or my build process.

**Comment by gr2m** [comment]
Did you find out more by chance? My understanding was that with Node 12 the async stack traces got better, but I didn't look into it specifically myself. Is there anything actionable I can do? Or shall we close the issue?

**Comment by gr2m** [comment]
Thanks a lot Ian! It would also be great if you have another tool that does http requests which manages to provide better errors stacks
