### ISSUE TITLE
github.issues.createComment throwing error

### ISSUE THREAD

**Issue by mbtamuli** [octokit/octokit.js#1472]
I am using the following code
```js
    const octokit = new github.GitHub(process.env.GITHUB_TOKEN, {
      log: console
    });
    const context = github.context;
    const owner = context.payload.sender.login;
    const repoName = context.payload.repository.name;
    const body = "Hello, world! Thanks for creating the PR";
    const issueNumber = context.payload.pull_request.number;

    octokit.issues.createComment({
      owner,
      repoName,
      issueNumber,
      body
    }).then(({ data, headers, status }) => {
      // handle data
    }).catch(err => {
      console.log(err)
    });
```

Now I am able to see the issueNumber value instead of undefined in the console logs before and also from the console log in the catch block. But I am receiving the following error

```
RequestError [HttpError]: Empty value for parameter 'issue_number': undefined
    at /home/runner/work/_actions/mbtamuli/github-actions/master/dist/index.js:9940:15
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/mbtamuli/github-actions/master/dist/index.js:9912:12
    at Array.forEach (<anonymous>)
    at validate (/home/runner/work/_actions/mbtamuli/github-actions/master/dist/index.js:9889:23)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  name: 'HttpError',
  status: 400,
  headers: undefined,
  request: {
    method: 'POST',
    baseUrl: 'https://api.github.com',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.28.9 Node.js/12.4.0 (Linux 5.0; x64)'
    },
    mediaType: { format: '', previews: [] },
    request: { hook: [Function: bound bound register], validate: [Object] },
    url: '/repos/:owner/:repo/issues/:issue_number/comments',
    owner: 'mbtamuli',
    repoName: 'github-actions',
    issueNumber: 13,
    body: 'Hello, world! Thanks for creating the PR'
```

I think `octokit.pulls.createComment` is for creating code review comments as it requires the path to a file and position of the diff too.
So I am using the `octokit.issues.createComment` and passing the issue number from the payload of the PR.

Here is the GitHub Action run - https://github.com/mbtamuli/github-actions/commit/75c611f40e730c80f2f25a41c634146141d8b6c7/checks

**Comment by gr2m** [comment]
The options keys are in underscore, not camelCase. Try

```js
    octokit.issues.createComment({
      owner,
      repo: repoName,
      issue_number: issueNumber,
      body
    })
```

See https://octokit.github.io/rest.js/#octokit-routes-issues-create-comment

**Comment by mbtamuli** [comment]
Thanks. It works. :smile: 
Closing the issue.

**Comment by mbtamuli** [comment]
@gr2m Can you explain why it was not using the variables directly when passing like this
```js
octokit.issues.createComment({
      owner,
      repoName,
      issueNumber,
      body
    })
```
and then it recognizes the variables, when the correct keys are passed as you showed?

Tried it out with a simple snippet.
```js
function add(obj) {
  console.log(obj.a + obj.b);
}
```

```js
var x = 1;
var y = 3;
add({
  a: x,
  b: y
})
```

```js
var a = 1;
var b = 3;
add({
  a,
  b
})
```

But still don't know the reason.

It's not part of support, but I'm really new to JavaScript. :sweat_smile:  Thanks for the help anyways. :+1:

**Comment by gr2m** [comment]
`{ issue_number: issueNumber}` is not the same as `{ issueNumber }`

If you call your variable name `issue_number` instead of `issueNumber` then you can pass in using the shortcut syntax: `{ issue_number }
