### ISSUE TITLE
docs: search typeahead shows "undefined" for endpoint URL and does not show the method name

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1475]
The first item should show `GET /repos/:owner/:repo/git/refs/:ref` and `octokit.git.getRef()`

<img width="359" alt="image" src="https://user-images.githubusercontent.com/39992/65272274-a0aa9800-dad3-11e9-9d54-9ac94c2a8a5d.png">

This must have been caused by #1466

**Comment by copperwall** [comment]
Hey @gr2m, I'm interested in working on this! So far it looks like the data from the query used in `IndexPage` already has undefined values.

```graphql
query {
   siteSearchIndex {
      index
   }
}
```


```json
"octokit-routes-git-get-ref": {
        "id": "octokit-routes-git-get-ref",
        "name": "Get a reference",
        "scope": "git",
        "route": "GET undefined",
        "method": "git.",
        "slug": "#octokit-routes-git-get-ref",
        "type": "API method"
},
```

I'm not sure where that query information is provided from but I can look at that PR you mentioned in the description.

Edit: Oh it looks like it's coming from `@gatsby-contrib/gatsby-plugin-elasticlunr-search`, I can look into that.
