### ISSUE TITLE
octokit.pulls.get authorization 406 Not Acceptable Error

### ISSUE THREAD

**Issue by galdinorosas** [octokit/octokit.js#1480]
Hello,

I am using the auth prop in the octokit constructor (from docs) like so:

const octokit = require('@octokit/rest')({
 userAgent: "@catalog/github-automerger",
 auth: token ${process.env.GITHUB_TOKEN},
 baseUrl: "https://gecgithub01.walmart.com",
 log: console
});

const {owner, repo, pull_number} = parsePullRequestUrl(url);
const pullRequest = await octokit.pulls.get(params); // is wrapped in a try/catch

but i keep getting a 406 error, with the following request headers:

{ method: 'GET',
    url: 'https://gecgithub01.walmart.com/repos/g0r009y/automerger-test-repo/pulls/1',
    headers:
     { accept: 'application/vnd.github.v3+json',
       'user-agent': '@catalog/github-automerger octokit.js/16.28.9 Node.js/8.12.0 (Linux 3.10; x64)',
       authorization: 'token [REDACTED]' },
    request: { hook: [Function: bound bound register], validate: [Object] } } }

do you have any insight to why I keep getting a 406? I have been looking at docs/reported issues and I am pretty sure im following the recommended auth method.

**Comment by gr2m** [comment]
You have to set the full base URL, you only set the GitHub Enterprise Domain.

Can you try to set `baseUrl: "https://gecgithub01.walmart.com/api/v3",` and see if that works?

**Comment by gr2m** [comment]
By the way, you can wrap you JavaScript blocks in 

````
```js
const octokit = require('@octokit/rest')({
 userAgent: "@catalog/github-automerger",
 auth: token ${process.env.GITHUB_TOKEN},
 baseUrl: "https://gecgithub01.walmart.com",
 log: console
});
```
````

Then they will be rendered nicely on GitHub:

```js
const octokit = require('@octokit/rest')({
 userAgent: "@catalog/github-automerger",
 auth: token ${process.env.GITHUB_TOKEN},
 baseUrl: "https://gecgithub01.walmart.com",
 log: console
});
```
