### ISSUE TITLE
Webpack targeting node wrongly pick up @octokit/request/dist-web

### ISSUE THREAD

**Issue by x8x** [octokit/octokit.js#1485]
Hello, I have an issue when packaging for node.

`package.js`:
```js
{
  "scripts": {
    "build": "webpack --target node -p"
  },
  "dependencies": {
    "@octokit/rest": "^16.30.1"
  }
}
```

`src/index.js`:
```js
const Octokit = require("@octokit/rest");
const octokit = new Octokit();

octokit.repos
  .listForOrg({
    org: "octokit",
    type: "public"
  })
  .then(({ data }) => {
	console.log(data);
  });
```

Running `node src/index.js` works fine.

But running `yarn build` output this:
```
  % yarn build
yarn run v1.17.3
warning package.json: No license field
$ webpack --target node -p
Hash: b3aadfcaa886809054ff
Version: webpack 4.39.3
Time: 1960ms
Built at: 09/25/2019 7:13:28 PM
  Asset     Size  Chunks             Chunk Names
main.js  199 KiB       0  [emitted]  main
Entrypoint main = main.js
 [0] external "stream" 42 bytes {0} [built]
 [2] external "zlib" 42 bytes {0} [built]
 [9] external "url" 42 bytes {0} [built]
[10] external "http" 42 bytes {0} [built]
[14] external "https" 42 bytes {0} [built]
[15] ./src/index.js 390 bytes {0} [built]
[61] ./node_modules/@octokit/request/dist-web/index.js + 4 modules 58.2 KiB {0} [built]
     |    5 modules
    + 55 hidden modules
✨  Done in 3.02s.
```

And running the resulting bundle with `node dist/main.js` return this error:
```
  % node dist/main.js                                                                          190925-191328:62244
/dist/main.js:1
ReferenceError: navigator is not defined
    at i (/dist/main.js:1)
    at Module.<anonymous> (/dist/main.js:15:4335)
    at t (/dist/main.js:1)
    at Object.<anonymous> (/dist/main.js:1)
    at t (/dist/main.js:1)
    at Object.<anonymous> (/dist/main.js:1)
    at t (/dist/main.js:1)
    at Object.<anonymous> (/dist/main.js:1)
    at t (/dist/main.js:1)
    at Object.<anonymous> (/dist/main.js:1)
```
Sure I'm doing something wrong, but I'm wondering in the webpack logs there is this line:
```
[61] ./node_modules/@octokit/request/dist-web/index.js + 4 modules 58.2 KiB {0} [built]
```
And looking into `node_modules/@octokit/request` there is also a `dist-node`, so I'm wondering
if the error is because webpack is picking `dist-web` and if yes why so as you can see
the webpack command is targeting node.

Thank you so much!

**Comment by eak12913** [comment]
I'm experiencing the exact same issue. I was able to roll back to `16.25.0` successfully. The issue was present in `16.28.0` and `16.27.0`. I just blindly picked `16.25.0` so there may be more recent versions that also work.

Hopefully that narrows the search space a bit.

**Comment by x8x** [comment]
Thanks @eak12913 you save me the time to look for the last working one :+1: 
Meanwhile , I didn't' find anything related in the issues here but there is something maybe related on Gregor's twitter here https://twitter.com/gr2m/status/1176199758127362048 and if I understand correctly, the new shiny tool is https://github.com/octokit/octokit.js which does state to support REST and Webpack.

**Comment by gr2m** [comment]
This is a known issue. It's tricky. There is an extended discussion here: https://github.com/gr2m/universal-user-agent/issues/23 I recommend you to follow it, maybe you have suggestions for workarounds?

If you can configure webpack to ignore the `"module"` key in dependencies, that should make it work for now

> the new shiny tool is https://github.com/octokit/octokit.js which does state to support REST and Webpack.

That's just a README right now, there is no code.

**Comment by gr2m** [comment]
> I was able to roll back to 16.25.0 successfully

That might not help much, the problem is a subdependency still fits the version ranges in 16.25 and below

**Comment by eak12913** [comment]
> That might not help much, the problem is a subdependency still fits the version ranges in 16.25 and below

Yep, I noticed that as soon as I tried to use some of the other `ocktokit` libraries like `app.js` the problem manifested itself again and no amount of version switching could resolve it. From @x8x comment I came upon your discussion and am following it now.

The only work-around that I can think of for now will be to:

- add a `postinstall` script in my own `package.json`
- that script will call out to shell/whatever script that will go through my `node_modules` folder locating all instances of `universal-user-agent`
- I'll then replace: `"module": "dist-web/index.js"` -> `"module": "dist-node/index.js"`

It's not pretty but may be the path of least resistance until a proper solution is worked out.

**Comment by gr2m** [comment]
`"dist-node/index.js"` is not in ESM format, it's in commonJS, so it might cause problems.

Is there no setting for webpack to define the entry fields in the package json? It might default to something like `["browser", "module", "main"]` and yuo'd need to set it to `["main"]` as a workaround until we figure this out on our side

**Comment by eak12913** [comment]
> Is there no setting for webpack to define the entry fields in the package json? It might default to something like ["browser", "module", "main"] and yuo'd need to set it to ["main"] as a workaround until we figure this out on our side

I see the following from: https://webpack.js.org/concepts/module-resolution/#module-paths

> If the folder contains a package.json file, then fields specified in resolve.mainFields configuration option are looked up in order, and the first such field in package.json determines the file path.

I'm experimenting with this now to see if this fixes my issue as that would be a much simpler work-around.

**Comment by gr2m** [comment]
Try this one maybe? https://webpack.js.org/configuration/resolve/#resolvemainfields

```js
module.exports = {
  //...
  resolve: {
    mainFields: ['main']
  }
};
```

**Comment by x8x** [comment]
@gr2m Genius! That does fix it for me in both the short test above and in the bigger project I have. 👍
Thank you to both of you for jumping so quick on this issue!
Have a great day!

**Comment by eak12913** [comment]
Ok - so after a little bit of trial and error it seems like updating `webpack` config with the following will work BUT with a caveat:

```
    // This configures how webpack resolves module paths
    // https://webpack.js.org/configuration/resolve/
    resolve: {
...
      mainFields: ["main", "module"],
...
}
```

The caveat seems to be that while it's working from the command line, it's causing my IDE (VSCode) to have issues with resolving any of the imports.

The solution that I've got is that I first run everything **without** `mainFields...` I get the `navigator is not defined` error. Then I can put in the `mainFields` and re-run and everything seems to work (the IDE doesn't seem to notice)

**Comment by x8x** [comment]
@gr2m Hello! As others may have the same issue, wouldn't it be wiser to just add a `webpack.config.js` to the repo? Took me some time to figure out the problem/solution ;-)
This works for me, thought it may not be the full/correct solution:
```
module.exports = {
	resolve: {
		mainFields: ['main']
	}
}
```
Should I make a PR?

Thank you for your hard work!

**Comment by gr2m** [comment]
No thanks, I'm working on another solution to the problem. Please bear with me

**Comment by shanalikhan** [comment]
@gr2m is there any update on this ?
I am facing same problem in latest version of octokit.

I have tried `mainFields` but it affects other modules.

**Comment by gr2m** [comment]
There are some more workarounds described at https://github.com/gr2m/universal-user-agent/issues/23, I've also posted an update there. The good news is we have have a standard way to handle this use case coming from Node.js new module system. And I also know that the folks from Pika are looking into implementing the new standard. I cannot give you an ETA, but a fix is coming. 

For the time being I recommend to use one of the described workarounds

**Comment by swain** [comment]
@gr2m Any update on this issue?

It seems like these packages should be providing web distributions via the `package.json` `browser` field, not necessarily in the `module` field.

**Comment by gr2m** [comment]
the bundlers should respect the `browser` field. It's still a headache, but things are moving.

The problem with universal-user-agent at least should no longer be a problem, it now works the same for all platforms, there is no different code needed any more.

**Comment by swain** [comment]
@gr2m this package (among others in the ecosystem), does not provide a `browser` field, instead only providing `module` and `main` fields, using `module` for web and `main` for Node.

This explicitly breaks consumers using Node + a bundler.

It seems like in general, they should provide this:

```json
"main": "dist-node/index.js",
"module": "dist-node/index.js",
"browser: "dist-web/index.js"
```

Maybe I'm missing something?

**Comment by gr2m** [comment]
it's not a problem with this package, but with packages down the dependency tree. At least it used to be a problem because `universal-user-agent` used to have a `"browser"` key in its package.json.

You should be fine using the `"module"` key, even if it points to `dist-web`. I'm following the current changes with build tools closely. I currently use [`@pika/pack`](github.com/pikapkg/builders) which is no longer actively maintained as the pika team now focuses on snowpack/skypack. There is no consensus right now for maintainers of universal packages. No matter what I do it breaks for someone, so I'll just wait. It's a messy transition time, but we are over the mountain now with Node.js supporting ESM natively. Now the build tools have to catch up
