### ISSUE TITLE
Question about Getting a Tree for a Specific Branch

### ISSUE THREAD

**Issue by juliacalandro** [octokit/octokit.js#1489]
I am calling octokit.git.getTree in order to recursively get the file paths of all files in every subdirectory within a given directory. The problem I am running into is that I want to get the tree for a specific branch, not for master. Every approach I try seems to only yield file paths from the master branch. 

In order to get the tree_sha value that is passed into octokit.git.getTree, I am using octokit.repos.getContents and then retrieving the sha of the specific element of type 'dir' that I want. Is the tree_sha what determines whether the tree contents are from the master branch or a different branch? If so, how do I obtain the tree_sha of the directory that I want that is in the specific branch that I want? I have tried passing a ref of the branch name in various formats (i.e. 'branch-name', 'refs/heads/branch-name') to the octokit.repos.getContents call but always ultimately end up with file paths that are only present in master and not the branch that I specified.

Please let me know if it is possible to get the tree of a directory for a specific branch, and if so, how to accomplish that.

[This](https://developer.github.com/v3/git/trees/#get-a-tree) is the corresponding GitHub API documentation for octokit.git.getTree, and [this](https://developer.github.com/v3/repos/contents/#get-contents) is the corresponding GitHub API documentation for octokit.repos.getContents.

**Comment by gr2m** [comment]
👋 Julia

> In order to get the tree_sha value that is passed into octokit.git.getTree, I am using octokit.repos.getContents and then retrieving the sha of the specific element of type 'dir' that I want.

I think I would use the `octokit.repos.listCommits` API instead. I think that's the easiest way to retrieve the latest commit from a branch. The commit object includes the tree sha which you then can use with the `octokit.git.getTree()` method.

I've made a demo, does that work for you?
https://runkit.com/gr2m/octokit-rest-js-1489

**Comment by caneesh** [comment]
Comment

**Comment by caneesh** [comment]
Comment By AT

**Comment by caneesh** [comment]
Comment By AT

**Comment by caneesh** [comment]
Comment By AT

**Comment by caneesh** [comment]
Comment By

**Comment by caneesh** [comment]
Comment By AT

**Comment by caneesh** [comment]
Comment By AT

**Comment by caneesh** [comment]
Comment By

**Comment by caneesh** [comment]
Comment By AT-1

**Comment by caneesh** [comment]
Comment By AT-2

**Comment by juliacalandro** [comment]
I will try that approach and report back if it ends up working for our needs. Thanks!

**Comment by juliacalandro** [comment]
I forgot to respond, but that approach did end up working for me! Thanks :)
