### ISSUE TITLE
Commits between two tags

### ISSUE THREAD

**Issue by RaviVaranasi** [octokit/octokit.js#149]
Is there any way to get all the merge commits between two tags ?
I did not see the target tag in the api repo.getAllCommits.

**Comment by kaizensoze** [comment]
I'm not sure about only merge commits but you can pass tags to compareCommits

https://stackoverflow.com/questions/26925312/github-api-how-to-compare-2-commits/26962188#26962188

https://mikedeboer.github.io/node-github/#api-repos-compareCommits
https://developer.github.com/v3/repos/commits/#compare-two-commits
