### ISSUE TITLE
In case of a 400 response due to a validation error, include the validation error in error.message

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1497]
This is a follow up for https://github.com/probot/probot/issues/1007#issuecomment-538772566

**Comment by ram-nad** [comment]
Sir I would like to work on this feature. As I am new to this repository any guidance would be really helpful. Thank You.

**Comment by gr2m** [comment]
Sure, it's all yours @ram-nad! You can start by creating a failing test case in the [`test/issues`](https://github.com/octokit/rest.js/tree/master/test/issues) folder and submit a pull request.

**Comment by ram-nad** [comment]
Sir I got his test from your's runkit,
 ```javascript
const octokit = require("@octokit/rest")({
  auth: process.env.GITHUB_TOKEN
});

try {
    await octokit.repos.updateBranchProtection({
      mediaType: { previews: ['hellcat', 'luke-cage', 'zzzax'] },
      owner: "gr2m",
      repo: "sandbox",
      branch: "gr2m-patch-1",
      required_status_checks: { strict: true, contexts: ["wip"] },
      enforce_admins: true,
      required_pull_request_reviews: {
        required_approving_review_count: 1,
        dismiss_stale_reviews: true,
        require_code_owner_reviews: true,
        dismissal_restrictions: { users: [], teams: [] }
      },
      restrictions: { users: [], teams: [] }
    });
} catch (error) {
    console.log(error.errors)
}
```

Should i test that the error occurs by using this code?

**Comment by gr2m** [comment]
for the test, you will also need to mock an http response with [nock](https://github.com/nock/nock/), like we do with the other tests in the issue folder.

The mocked response should return a 422 status and the response body looks like this:

```json
{
  "message": "Validation Failed",
  "errors": [
    "Only organization repositories can have users and team restrictions"
  ],
  "documentation_url": "https://developer.github.com/v3/repos/branches/#update-branch-protection"
}
```
