### ISSUE TITLE
Updating a stale pull request head branch with base branch (from fork)

### ISSUE THREAD

**Issue by galdinorosas** [octokit/octokit.js#1500]
1. I am trying to update my pull request head branch with the latest changes from the base branch; the head branch repo was forked from the base branch repo.

I was told from github developers to use "/repos/:owner/:repo/merges" to update a stale pull request head branch. This is my request params i send:

```js
{
repo: my forked repo,
owner: myself,
base: pull request head branch name,
head: pull request base branch latest sha
}
```

The error I am getting is a 404 Head Does Not Exist but I know the base branch contains this latest sha. The crazy thing is that this error seems intermittent. Should I be updating my stale PR head branches in a different way?

Please let me know.

Thank You

```js
{ method: 'POST',
  baseUrl: 'https://gecgithub01.walmart.com/api/v3',
  headers: 
   { accept: 'application/vnd.github.v3+json',
     'user-agent': 'spectrum-github-automerger octokit.js/16.33.0 Node.js/8.12.0 (Linux 3.10; x64)',
     authorization: 'token #######################' },
  mediaType: { format: '', previews: [] },
  request: 
   { hook: [Function: bound bound register],
     validate: 
      { base: [Object],
        commit_message: [Object],
        head: [Object],
        owner: [Object],
        repo: [Object] } },
  url: '/repos/:owner/:repo/merges',
  owner: 'g0r009y',
  repo: 'spectrum',
  base: 'test2',
  head: '023d8a409e090d1cbf336c1d86dd29d705235755' }
```
Proof that the base pull request branch has the latest sha:
<img width="1010" alt="Screen Shot 2019-10-09 at 4 36 14 PM" src="https://user-images.githubusercontent.com/13751461/66527999-1c847880-eab3-11e9-83dd-44757e3f673f.png">

**Comment by gr2m** [comment]
hard to tell what is wrong. But maybe you can look in how it's solved in https://github.com/tibdex/github-rebase? It's using `@octokit/rest` internally

**Comment by galdinorosas** [comment]
Thanks Gregor,

I’ll look into the link you sent.

In my app I’m using all octokit, and I was just sending you the request information I’m seeing.

From your own opinion though, how would you merge across forks?

Thanks 

Galdino Rosas

**Comment by galdinorosas** [comment]
I appreciate the link, i'll look into it.

From your own personal opinion, what octokit API would you suggest to update my local pull request head branch with a forked upstream base branch?

Thanks

**Comment by gr2m** [comment]
@galdinorosas I'm very sorry I missed your follow up question!

Did you figure it out? I don't think that there is a single API call to make that work, it would be a bit more complex. But it sounds like a problem others might run into, maybe it would be worth to create a plugin?
