### ISSUE TITLE
Question about getting the repos that my Github Bot is installed on

### ISSUE THREAD

**Issue by kevo1ution** [octokit/octokit.js#1503]
Is there a better way to get the list of repos that have my Github Bot installed on them?

What I had in mind is something like getting the list of repos that a user has access to ('GET /user/repos'). My current implementation seems unnecessary. I am paginating through the list of repos of an organization ('GET /orgs/:org/repos') and then calling "GET /repos/:owner/:repo/installation" to see if an installation exists.

Also, this implementation only gets repos for an organization. Is there a way to get all repos that have my Github Bot installed on them?

**Comment by gr2m** [comment]
To find all repositories that your GitHub app is installed on, you need to 

1. Get all installtions
2. For each installtions, get all repositories.

You can see this code for reference:
https://github.com/octokit/routes/blob/master/bin/notify-users.js

Note that the code is using https://github.com/octokit/core.js, https://github.com/octokit/rest.js is not yet compatible with the `@octokit/auth-app"` used in the code above.

**Comment by kevo1ution** [comment]
Thanks! I'll try it out
