### ISSUE TITLE
getRef broken in 16.34.0? 

### ISSUE THREAD

**Issue by alannatodd** [octokit/octokit.js#1506]
I believe this change in the getRef definition has caused the functionality to break in 16.34.0 -> https://github.com/octokit/rest.js/commit/e891d4e31c41e7a6afe0c8257404bf1f51607f5e#diff-0071a9eb9e809c9aacfc547f7514add6R1066

If I do not change my code (which worked before the change last week), when using 16.34.0, I get a 404 when using `octokit.git.getRef`, but get the expected `200` if I set the octokit version back to 16.33.1

The response shows as 
16.33.1 : `"status":200, "url":"https://github.ibm.com/api/v3/repos/<Owner>/<repo>/git/refs/heads/master"`

16.34.0 : `"status":404, ... "url":"https://github.ibm.com/api/v3/repos/<Owner>/<repo>/git/ref/heads/master"`

It seems all the other functions for refs (updateRef, listRefs, etc) are still set to `"/repos/:owner/:repo/git/refs/...`

Ruby sdk still shows git/refs -> https://github.com/octokit/octokit.rb/blob/5fe41c51afe5593f165f79ca1ffde7630360e0de/lib/octokit/client/refs.rb#L35

**Comment by alannatodd** [comment]
Thanks for the explanation - I tried the plugin-enterprise-rest, but am still getting the same 404/its using git/ref/
Is there anything I need to add to the code besides the plugin reference? 
```
const Octokit = require("@octokit/rest").plugin(
  require("@octokit/plugin-enterprise-rest/ghe-2.18")
);
```

**Comment by gr2m** [comment]
Hmm I'll look into it!

For the time being, you can work around the problem by using `octokit.request` instead of `octokit.git.getRef`:

```js
octokit.request('GET /repos/:owner/:repo/git/refs/:ref', {
  repo,
  owner,
  ref
})
```

But beware that the `GET /repos/:owner/:repo/git/refs/:ref` can return one of the following

1. An object, if `:ref` directly matches an existing reference or a prefix of only a single reference
2. An array, if `:ref` matches a prefix for more than one references
3. A `404` if it doesn't match anything.

This is the reason why the endpoint was replaced, too.

**Comment by alannatodd** [comment]
Ok - thank you!

**Comment by shaunwarman** [comment]
I hit the same thing. Any extra details for the breaking change?

**Comment by gr2m** [comment]
Do you use GitHub Enterprise? If not, then you'll probably just need to update your tests

**Comment by shaunwarman** [comment]
Ya github enterprise, I went back to `16.33.1` and things are good. But interested if this reflects public API changes whereas enterprise may be behind?

**Comment by gr2m** [comment]
Okay glad you have a workaround for now. I plan to look into it on Friday

**Comment by gr2m** [comment]
Sorry I didn't get back to you :( Is this still a problem?
