### ISSUE TITLE
Proper way to add header for label endpoints?

### ISSUE THREAD

**Issue by ScottChapman** [octokit/octokit.js#1508]
I need to the header: `Accept: "application/vnd.github.symmetra-preview+jso"` so that I can get/set descriptions (plus support for emojis) for labels. Right now I am doing this:
```
const octokit = new Octokit({
  headers: {
    Accept: "application/vnd.github.symmetra-preview+jso"
  },
  auth: "token " + process.env.GHE_TOKEN
})
```
But that basically tells me that headers has been deprecated, but I'm not really clear on the alternative.

**Comment by gr2m** [comment]
Add it directly on each request as needed, using the `mediaType` option, see https://octokit.github.io/rest.js/#previews

```js
octokit.repos.get({
  owner: "octokit",
  repo: "rest.js",
  mediaType: {
    previews: ["symmetra"]
  }
});
```

Note that the preview headers that are required to access certain API endpoints are set automatically for you

**Comment by ScottChapman** [comment]
oh wow, thanks. never would have figured that out!

**Comment by gr2m** [comment]
I'd recommend to at least skim trough the first chapters of the documentation (until debugging, the rest is REST API endpoint methods)
