### ISSUE TITLE
Initialised Ocotokit object as Typescript types.

### ISSUE THREAD

**Issue by Richienb** [octokit/octokit.js#1509]
What types do I use to reference an initialised Ocotokit object?

TLDR, what is the return value of this function:
```ts
function someFunction() {
	return new Octokit()
}
```

**Comment by gr2m** [comment]
`typeof Octokit`?

`@octokt/rest` is the last lib still written in JS with external TypeScript declarations. If you don't need methods for all the endpoints, I'd recommend using https://github.com/octokit/core.js. Especially if you are looking to use it in the browser.

What's your use case?

**Comment by Richienb** [comment]
> `typeof Octokit`?

VSCode seems to treat `typeof Octokit` as if it was the class before initialisation.

> What's your use case?

I'm creating a small module that automatically sets a `userAgent` and `timeZone`.

```js
"use strict"

const Octokit = require("@octokit/rest")
const userAgent = require("ergent")
const timeZone = require("timez")

module.exports = (...data) => new Octokit({
    userAgent,
    timeZone,
    ...data,
})
```

**Comment by gr2m** [comment]
> VSCode seems to treat typeof Octokit as if it was the class before initialisation.

Hmm might be that there is some kind of problem with the way it's declared. It's not implemented as a class, only declared as such.I'd be happy to accept a PR to make it work for your use case.

I'm working towards rebuilding `@octokit/rest` on top of `@octokit/core` which should resolve the problem proper. If the TypeScript gives you too much trouble, I'd suggest to built on `@octokit/core`. I've already extracted [the pagination plugin](https://github.com/octokit/plugin-paginate-rest.js) and I'll working on extracting [the REST API endpoints plugin](https://github.com/octokit/rest.js/tree/8eb5136f7c5aa10fef7e9e581b59cfe5aa57a5d2/plugins/rest-api-endpoints) next
