### ISSUE TITLE
Incorrect type definition for payloads containing mediaTypes

### ISSUE THREAD

**Issue by diervo** [octokit/octokit.js#1510]
Most of the APIs have an incorrect definition for Typescript when using `mediaType` param.

```ts
// you must cast the object as `any` to avoid typescript errors
octokit.pulls.get({
  owner,
  repo,
  pull_number,
  mediaType: { format: "diff" }
} as any);
```

If I can I will land a PR, but just FYI

**Comment by gr2m** [comment]
It would be great if you could manage to add the correct type definitions if mediaType is used. It might also be great to only allow the `mediaType.format` option for endpoints that actually support them, but I'm not sure if we have the necessary information to make that possible in https://github.com/octokit/routes/. We might need to do that first

**Comment by trim21** [comment]
Is there any new info about this? this buf still exists in 2021.

**Comment by gr2m** [comment]
It’s not supported. It would be nice but it would take quite a lot of work and add to the maintenance overhead. We might add that in future but it’s not a priority
