### ISSUE TITLE
How can you unit test the api authentication?

### ISSUE THREAD

**Issue by manofstatic** [octokit/octokit.js#1512]
What is the appropriate way to unit test that the authentication method provided to the rest module is valid? I'm working on a codebase that previously used an old version of this module and was using Jest to mock the auth like such:

```Javascript
jest.mock('@octokit/rest', () =>
    _ => ({
          authenticate: jest.fn()
    })
)
```

And then simply checking that the same token provided to the constructor was also passed to the mock function. I've been doing some digging and it looks like no calls are actually made now when the rest module is constructed. How would you recommend I unit test construction of this rest module?

The best way I can think of is to make a call with the authenticated api, then catch that call and check for the token.

**Comment by gr2m** [comment]
You can just pass the token to the Constructor

```js
const TOKEN = 'secret123'
const octokit = new Octokit({auth: TOKEN})
```

And then check that the `Authorization` header is set correctly when you mock http calls.

For mocking http mocks you can use [`nock`](https://github.com/nock/nock/) for node.js code, or [`fetch-mock`](https://github.com/wheresrhys/fetch-mock) for both node&browser usage. You can pass a mocked `fetch` method like this

```js
const TOKEN = 'secret123'
const octokit = new Octokit({auth: TOKEN, request: { fetch }})
```

You can compare https://github.com/octokit/core.js/blob/master/test/auth.test.ts for reference

**Comment by manofstatic** [comment]
Thank you, that repo looks like exactly the reference I need.

**Comment by gr2m** [comment]
great :) Let me know if you have further questions

**Comment by manofstatic** [comment]
I've been digging a bit and I've gotten a Jest + Nock test written like so:

```Javascript
test('authenticates with the GitHub API using a personal access token', () => {
    const scope = nock((/api\.github\.com/), {
        reqheaders: {
            authorization: 'token '.concat(expectedToken)
      }
})
    .get('/user/repository_invitations')
    .reply(200);

    const githubInstance = new GitHub(req.params)
    githubInstance.api.repos.listInvitationsForAuthenticatedUser();
    expect(scope.isDone()).toBe(true)
})
```

However, this test is failing and I haven't been able to find why. Here the GitHub class is a wrapper around Octokit rest and is simply passing values in to the constructor. Using this headers matching notation, do I have to include all the headers that the request will have in order for nock to match it?

**Comment by gr2m** [comment]
> Using this headers matching notation, do I have to include all the headers that the request will have in order for nock to match it?

No, only the ones you want to require to be matched. I'll have a look at it

**Comment by gr2m** [comment]
I was not able to reproduce the problem with slightly different code:
https://runkit.com/gr2m/octokit-rest-js-1512

One thing that's wrong in your code is that you need to await the response of

```js
githubInstance.api.repos.listInvitationsForAuthenticatedUser();
```

Right now `scope.isDone()` is executed before a request was sent, due to the asynchronous nature.

Try this

```js
test('authenticates with the GitHub API using a personal access token', async () => {
    const scope = nock((/api\.github\.com/), {
        reqheaders: {
            authorization: 'token '.concat(expectedToken)
      }
})
    .get('/user/repository_invitations')
    .reply(200);

    const githubInstance = new GitHub(req.params)
    await githubInstance.api.repos.listInvitationsForAuthenticatedUser();
    expect(scope.isDone()).toBe(true)
})
```

**Comment by manofstatic** [comment]
That was exactly it, completely slipped my mind that the API calls were async. Thank you so much for your help Gregor, I really appreciate it.

**Comment by SpencerKaiser** [comment]
@gr2m ideally in my app startup process I would ping GHE to validate that the provided token works so I fail health-checks when starting my app if things are awry. Is there any way to validate that a token works aside from just calling an endpoint and making sure the response is `200`?

**Comment by gr2m** [comment]
any request would do. If you want to validate your app, I'd probably do `octokit.apps.getAuthenticated()`. You can also do `octokit.apps.getAuthenticated({ method: "HEAD" })` which is a tad more efficient because it sends a HEAD request instead of a GET request, and you are only interested in `responses.status` anyway
