### ISSUE TITLE
Wiki APIs

### ISSUE THREAD

**Issue by mittalyashu** [octokit/octokit.js#1515]
Add support for fetching Wiki data using REST APIs

**Comment by gr2m** [comment]
There are no REST APIs for Wiki pages that I am aware of. What are you trying to build? Maybe there is an alternative way

**Comment by mittalyashu** [comment]
Due to collaborative feature of GitHub, I want to host my code documentation inside Wiki and later fetch all the wiki pages and render it on the website for the end-users to consume the documentation.

**Comment by gr2m** [comment]
GitHub repository wiki's have git access, so you could download the content using git. Would that be a possible alternative? There are no REST APIs or GraphQL nodes to retrieve WIKI data, I'm afraid.

You can contact support@github.com and let them know about your use case so they can consider adding them.

**Comment by mittalyashu** [comment]
> GitHub repository wiki's have git access, so you could download the content using git. Would that be a possible alternative? There are no REST APIs or GraphQL nodes to retrieve WIKI data

I understand that, can it be considered a feature request or adding support for that in near future.

**Comment by gr2m** [comment]
> can it be considered a feature request or adding support for that in near future

That's what I would suggest to talk to support@github.com about. I can only build the library that uses existing APIs. If you require new APIs, ask support

**Comment by mittalyashu** [comment]
I see, so GitHub doesn't have any APIs for wiki.

Sure, I will talk to [support@github.com](mailto:support@github.com)

Thanks
