### ISSUE TITLE
Add more explicit types for ReposGetContentsResponse

### ISSUE THREAD

**Issue by gmurphey** [octokit/octokit.js#1516]
```
import * as Octokit from '@octokit/rest';

const octokit = new Octokit();

async function run() {
  const response = await octokit.repos.getContents({
    owner: 'gmurphey',
    repo: 'ember-did-resize-modifier',
    path: 'index.js'
  });

  console.log(response.data.content);
}

run();
```

Trying to access `response.data.content` is not compiling, I think due to the way that `ReposGetContentsResponse` is defined: 

```
  type ReposGetContentsResponse =
    | {
        _links: ReposGetContentsResponseLinks;
        content?: string;
        download_url: string | null;
        encoding?: string;
        git_url: string;
        html_url: string;
        name: string;
        path: string;
        sha: string;
        size: number;
        type: string;
        url: string;
        target?: string;
        submodule_git_url?: string;
      }
    | Array<ReposGetContentsResponseItem>;
```

I believe I can get around this by casting `response.data` as the single file response object, but since it's not a type itself, I have no way to reference it. By no means am I a TypeScript expert, so might be missing something. Appreciate all the work that's gone into this!

**Comment by guyk-yahoo** [comment]
I'm having the same problem:
```
src/routes/api.ts:119:39 - error TS2339: Property 'content' does not exist on type 'ReposGetContentsResponse'.
  Property 'content' does not exist on type 'ReposGetContentsResponseItem[]'.

119                 const data = res.data.content;
                                          ~~~~~~~
```

**Comment by wolfy1339** [comment]
It seems like a name clash with another method

**Comment by gr2m** [comment]
[`octokit.repos.getContents()`](https://developer.github.com/v3/repos/contents/#get-contents) can have different responses depending on path. I think you need to check if `res.data` is an object first (and not an array)

**Comment by gmurphey** [comment]
@gr2m to do any casting after checking the return type, though, I think we'd need more explicit types for `ReposGetContentsResponse`. Something like:

```
type ReposGetContentsObjectResponse = {
  _links: ReposGetContentsResponseLinks;
  content?: string;
  download_url: string | null;
  encoding?: string;
  git_url: string;
  html_url: string;
  name: string;
  path: string;
  sha: string;
  size: number;
  type: string;
  url: string;
  target?: string;
  submodule_git_url?: string;
}
type ReposGetContentsArrayResponse = Array<ReposGetContentsResponseItem>;
type ReposGetContentsResponse =
  | ReposGetContentsObjectResponse
  | ReposGetContentsArrayResponse;
```

Currently there's no way to access the object response type for casting.

**Comment by gr2m** [comment]
The required change would need to be done in https://github.com/octokit/rest.js/blob/master/scripts/update-endpoints/typescript.js. I won't have time to look into that particular change myself, but happy to accept a PR.

But wouldn't it work to add an `if (Array.isArray(response.data)) { /* ... */ } else { /* ... */ }`? You should check for the different types of responses anyway

**Comment by gr2m** [comment]
I've ran into this myself, and checking the response with `if (Array.isArray(response.data)) { ... }` always worked, I think this is working as expected. 

Please let me know if you see a way to improve the developer experience here.

**Comment by charliealbright** [comment]
> I've ran into this myself, and checking the response with `if (Array.isArray(response.data)) { ... }` always worked, I think this is working as expected.
> 
> Please let me know if you see a way to improve the developer experience here.

@gr2m in Typescript, this is not able to compile at all unless you add a `//@ts-ignore` above any line of code trying to access a field of `ReposGetContentsResponse`. For example:

```typescript
let data: Octokit.ReposGetContentsResponse = response.data;
if (data !== null && typeof data === 'object') {
    let yamlObj;
    try {
        //@ts-ignore
        yamlObj = yaml.safeLoad(Buffer.from(data.content, 'base64').toString()); // Does not compile unless the above line is added.
        // ...
    }
}
```

I'd like to see this changed so that developers don't have to explicitly tell the TS compiler to ignore an error.

**Comment by rodrigodiez** [comment]
Same issue here, can't access properties of the response data without a compiler error

**Comment by gr2m** [comment]
@charliealbright can you share more of your code? Note that `typeof []` returns `object`. You have to explicitly check with `Array.isArray()`

**Comment by XertroV** [comment]
> [at]gr2m in Typescript, this is not able to compile at all unless you add a //@ts-ignore above any line of code trying to access a field of ReposGetContentsResponse

@charliealbright - that's because it's not type-safe. The type is `RespObj | RespObj[]`. You need to use a typeguard and access `.content` in the correct branch.

cc @rodrigodiez 

> I'd like to see this changed so that developers don't have to explicitly tell the TS compiler to ignore an error.

Don't use typescript then - use javascript. Then you can do all the unsafe things you want. The compiler is there to _help_ you. (Presuming the library code and typings are correct - I've found cases in other projects where they are not)

Here is some working code similar to OP example:

```typescript
import * as Octokit from "@octokit/rest";

const octokit = new Octokit.Octokit();

async function run(): Promise<string> {
    const response = await octokit.repos.getContents({
        owner: "gmurphey",
        repo: "ember-did-resize-modifier",
        path: "index.js",
    });

    const r = response.data;
    type ReposGetContentsResponse = typeof r;
    type RGCRObj = ReposGetContentsResponse extends infer V ? (V extends Array<any> ? never : V) : never;
    type GetArr<T> = T extends (infer U)[] ? U[] : never;
    type RGCRArr = GetArr<ReposGetContentsResponse>;
    type RGCRArrInner = RGCRArr extends (infer U)[] ? U : never;

    return Array.isArray(r)
        ? r // the typescript compiler knows that in this branch `typeof r ~ Array<...>`
              .map((el: RGCRArrInner) => {
                  // note: `RGCRArrInner` does not have a `.contents` field
                  return el.url;  // some string
              })
              .join(",")
        : (r as RGCRObj).content || "default"; // and this branch `typeof r ~ RGCRObj`
}

console.log(run());
```

Granted, it is annoying that ReposGetContentsResponse is not exported, but that's probably because the author didn't think it'd be a good idea for users to do things with it directly. Since values of that type are in the user's code, though, the type really should be exported.

**Comment by charliealbright** [comment]
I got it working with `Array.isArray()` :+1:

**Comment by LordHaywood** [comment]
I am still having this issue with JS, 
Example is here: https://repl.it/@LordHaywood/UnequaledEnlightenedRoutes

**Comment by gr2m** [comment]
TypeScript cannot be sure that `v.data` is an array, even when you set path to "". You have to add a type guard by checking with `Array.isArray(v.data)`
