### ISSUE TITLE
Programatically create new repo from template

### ISSUE THREAD

**Issue by brunoscopelliti** [octokit/octokit.js#1518]
Hello!
I've a question / feature request.
I'm using `octokit.repos.createForAuthenticatedUser` to create new repos programatically. Is there the possibility to create a new repo from an existing template?
I would say something like:

```
octokit.repos.createForAuthenticatedUser({
  name: "foo",
  template: <Name of the template | Optional>
})
```

**Comment by gr2m** [comment]
Yes, you can use `is_template` and `template_repository` keys, but you have to set the `baptiste` preview

```js
octokit.repos.createForAuthenticatedUser({
  mediaType: { previews: ['baptiste'] },
  name: "foo",
  template: nameOfTemplateRepo
})
```

See the REST API docs: https://developer.github.com/v3/repos/#create

Does that work for you?

**Comment by brunoscopelliti** [comment]
Hi @gr2m!
Thank you for your answer.
I've tried the code you suggested (in different flavors) but it didn't work.

I've checked the docs, https://developer.github.com/v3/repos/#create-repository-using-a-repository-template

> Use the template_owner and template_repo route parameters to specify the repository to use as the template. The authenticated user must own or be a member of an organization that owns the repository. To check if a repository is available to use as a template, get the repository's information using the GET /repos/:owner/:repo endpoint and check that the is_template key is true.

```
POST /repos/:template_owner/:template_repo/generate
```

... and debugging the code it doesn't look like this is the request that it is sent.

**Comment by gr2m** [comment]
Ah, I see. I think you are looking the [`octokit.repos.createUsingTemplate()` method](https://octokit.github.io/rest.js/#octokit-routes-repos-create-using-template). The `baptiste` preview is set automatically for you as it's required to use the API

**Comment by brunoscopelliti** [comment]
Yes, exactly. Thank you very much.
