### ISSUE TITLE
TypeError: pluginFunction is not a function

### ISSUE THREAD

**Issue by EArbeitman** [octokit/octokit.js#1525]
Hi,

We recently upgraded our probot dependency to the latst version and I believe that included a change to the octokit library. When I try to build my application, I'm getting this error:

 @octokit/rest/16.28.7/node_modules/@octokit/rest/lib/constructor.js:23:11)
TypeError: pluginFunction is not a function

Any ideas?

**Comment by gr2m** [comment]
Unfortunately no, nobody else reported similar issue. If you could create a test case that reproduces the problem, I'd be happy to look into it

**Comment by cecilia-sanare** [comment]
One of our builds is throwing a similar error.

```
TypeError: pluginFunction is not a function
    at /usr/local/lib/node_modules/auto-merge/node_modules/@octokit/rest/lib/constructor.js:26:37
    at Array.forEach (<anonymous>)
    at new Octokit (/usr/local/lib/node_modules/auto-merge/node_modules/@octokit/rest/lib/constructor.js:26:11)
    at Function.openPullRequest (/usr/local/lib/node_modules/auto-merge/src/utils/github.js:9:21)
    at exports.autoMerge (/usr/local/lib/node_modules/auto-merge/src/utils/auto-merge.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'll follow up here if / when I have more information.

**Comment by cecilia-sanare** [comment]
@EArbeitman, @gr2m In my case the issue ended up being the `@octokit/plugin-enterprise-compatibility` plugin.

**Before**

```js
const Octokit = require('@octokit/rest')
  .plugin(require('@octokit/plugin-enterprise-rest/ghe-2.16'))
  .plugin(require('@octokit/plugin-enterprise-compatibility'));
```

**After**

```js
const { enterpriseCompatibility } = require('@octokit/plugin-enterprise-compatibility')

const Octokit = require('@octokit/rest')
  .plugin(require('@octokit/plugin-enterprise-rest/ghe-2.16'))
  .plugin(enterpriseCompatibility);
```

Previously the above code was working, but it randomly stopped working. Not sure if the exports changed at some point.

**Comment by gr2m** [comment]
Ouch, you are right, there is a breaking change missing for `'@octokit/plugin-enterprise-compatibility'`. I'm sorry for the trouble :( I will not revert the change now because that might break people's usage, too. The change that @nick-woodward is describing is the correct migration path to resolve the issue
