### ISSUE TITLE
Consider More Descriptive Error Messages for Unsupported Endpoints

### ISSUE THREAD

**Issue by Mike-E-angelo** [octokit/octokit.js#1528]
Newb here. 😁  I have been learning GitHub App development via (via Probot) and while everything has been working pretty cleanly, I did just now encounter a similar error to #968 with the same message while calling `context.github.issues.listEventsForRepo`:

```
19:10:08.163Z ERROR event: Resource not accessible by integration (id=03967e80-1d13-11ea-95bd-891e5c4aa344)
  HttpError: Resource not accessible by integration
      at ..\yobot\node_modules\@octokit\request\dist-node\index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Job.doExecute (..\yobot\node_modules\bottleneck\light.js:405:18)
  --
  event: {
    "event": "issue_comment.created",
    "id": "03967e80-1d13-11ea-95bd-891e5c4aa344",
    "installation": 5669572,
    "repository": "ExtendedXmlSerializer/NextRelease"
  }
19:10:08.178Z ERROR probot: Resource not accessible by integration
  HttpError: Resource not accessible by integration
      at ..\yobot\node_modules\@octokit\request\dist-node\index.js:66:23
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Job.doExecute (..\yobot\node_modules\bottleneck\light.js:405:18)
19:10:08.186Z  INFO http: POST / 500 - 293.78 ms (id=11881ea5-aa1e-4f4e-a49e-1715449f1864)
19:10:08.194Z ERROR probot: Internal Server Error
  Error: Internal Server Error
      at Request.callback (..\yobot\node_modules\superagent\lib\node\index.js:706:15)
      at IncomingMessage.<anonymous> (..\yobot\node_modules\superagent\lib\node\index.js:916:18)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Looking at [this comment specifically](https://github.com/octokit/rest.js/issues/968#issuecomment-411493042), it would seem that there are endpoints that are not supported for GitHub Apps consumption.  Do I understand this correctly?  If so, this is surprising/shocking to say the least especially when considering that everything works perfectly fine with a simple web browser call.

It would be valuable to have the error message state this as a possibility as well as the pertinent link for more information.

Thank you for any consideration (or additional context/correction on why I am encountering this error).

**Comment by gr2m** [comment]
> Resource not accessible by integration

This error usually means that you try to access and endpoint that the integration does not have permission for. A better error message might be added to Probot, I wouldn't add it to `@octokit/rest`

For `context.github.issues.listEventsForRepo` specifically, I think that indeed this endpoint is not yet enabled for GitHub Apps: https://developer.github.com/v3/activity/events/#list-repository-events. You can ask support@github.com if that is in fact the case (and why), or if the documentation is not up to date.

**Comment by Mike-E-angelo** [comment]
Thank you for your insight and assistance, @gr2m!  I have submitted this issue to Probot, as suggested: https://github.com/probot/probot/issues/1086

**Comment by gr2m** [comment]
perfect, let's continue the discussion there
