### ISSUE TITLE
Get statistics of a author

### ISSUE THREAD

**Issue by sasikanth513** [octokit/octokit.js#153]
How to get  statistics of a particular author for a repo.
May I know the method to request the following url

https://api.github.com/repos/:owner/:repo/stats/contributors

Documentation link https://developer.github.com/v3/repos/statistics/

I'm not able to find a method in the docs http://mikedeboer.github.io/node-github

**Comment by kaizensoze** [comment]
See methods around https://mikedeboer.github.io/node-github/#api-repos-getStatsContributors in doc.
