### ISSUE TITLE
Octokit.repos.update() has unexpected side effects

### ISSUE THREAD

**Issue by kevo1ution** [octokit/octokit.js#1530]
**Problem**
Any time you send an update request to https://developer.github.com/v3/repos/#edit, the settings for `Automatically delete head branches` gets set to false and unchecked.

**Recreate this bug**
```
octokit.repos.update({
  owner: 'KevinTangIsSuperCool',
  repo: 'test-default',
  has_issues: false,
})
```
To recreate this bug, on your repo enable the `Automatically delete head branches` setting. Then run the octokit update call. This request should only disable issues settings, but it also disables the `Automatically delete head branches` that we enabled. It seems that this happens on any successful update request no matter what combination of fields (has_issues, has_projects, etc.).

**Comment by gr2m** [comment]
I was not able to reproduce the problem with the following code

```js
const Octokit = require("@octokit/rest");

main();

async function main() {
  const octokit = new Octokit({
    auth: process.env.GH_TOKEN
  });

  try {
    const response = await octokit.repos.update({
      owner: "gr2m",
      repo: "sandbox",
      has_issues: false
    });

    console.log(response);
  } catch (error) {
    console.log(error);
  }
}
```

Maybe it was a temporary issue with the GitHub API that was resolved meanwhile?

**Comment by kevo1ution** [comment]
@gr2m I tried it again with your exact same code with my kevo1ution/sandbox and gh_token, and it still disables `Automatically delete head branches` setting. Did you enable the `Automatically delete head branches` option in `Settings -> Options -> Automatically delete head branches` before running the script?

**Comment by gr2m** [comment]
very odd. Yes, I'm sure I enabled the option. After running the code successfully, the option is still enabled for me. Could you please check in with support@github.com? It will help if you would send them a curl request instead, it will make it easier for them to reproduce

**Comment by kevo1ution** [comment]
I will reach out to them and update this thread when they respond. I've tried this curl command and the option still gets disabled. I've also used it with a separate account on a different repo and it still does the same thing.
```sh
curl -X PATCH \
  https://api.github.com/repos/kevo1ution/sandbox \
  -H 'Authorization: token [Personal Access Token Redacted]' \
  -d '{"has_issues": false}'
```

**Comment by kevo1ution** [comment]
@gr2m The enterprise support team responded, and they were able to reproduce the issue. They flagged it for the engineering team to fix.

**Comment by gr2m** [comment]
Any update if the issue has been resolved yet?

**Comment by carusogabriel** [comment]
I've received an email from GitHub support saying that this was fixed 2 days ago. But, I didn't have time to test it yet 😕

**Comment by gr2m** [comment]
I trust them if they say the problem is resolved, thanks :) If it pops up again, we can reopen the issue

**Comment by kevo1ution** [comment]
I just tried the curl script again, and the issue is fixed 👍
