### ISSUE TITLE
Issue with auth

### ISSUE THREAD

**Issue by absolute-music** [octokit/octokit.js#1531]
My code:

![Screenshot 2019-12-19 at 13 43 54](https://user-images.githubusercontent.com/50186369/71212174-a3995e00-2265-11ea-9ac7-3fcb8eb57411.png)
Error: 

![Screenshot 2019-12-19 at 13 44 53](https://user-images.githubusercontent.com/50186369/71212228-c0ce2c80-2265-11ea-9c32-6aab41716ed0.png)

How could I fix it?

**Comment by gr2m** [comment]
The error says that the auth option is an empty object (`{}`). Looks like `credentials.username` and `credentials.password` are undefined in your code?

**Comment by absolute-music** [comment]
It is defined

**Comment by absolute-music** [comment]
It is fixed but this problem appeared


![Screenshot 2019-12-19 at 14 13 40](https://user-images.githubusercontent.com/50186369/71214242-d04f7480-2269-11ea-8c91-d91dca2e087c.png)

my code:

![Screenshot 2019-12-19 at 14 37 55](https://user-images.githubusercontent.com/50186369/71215680-473a3c80-226d-11ea-8483-db668c2d0399.png)

**Comment by absolute-music** [comment]
I tried oauthAuthorizations it also won't work

**Comment by absolute-music** [comment]
fixed
