### ISSUE TITLE
getBlob return string instead of Octokit.GitGetBlobResponse if mediaType format is 'raw'

### ISSUE THREAD

**Issue by yanguango** [octokit/octokit.js#1532]
```
octokit.git.getBlob({
    mediaType: {format: 'raw'},
    owner: owner,
    repo: repo,
    file_sha: fileSha
})
.then(resp => resp.data)
.then(data => doSomethingWith(data));
```
In typescript, this data is supposed to be type Octokit.GitGetBlobResponse, but actually it's string.

**Comment by gr2m** [comment]
It's correct that it's a string as you set `mediaType: {format: 'raw'},`. The Typescript definition does not get altered when the mediaType format is set, you will have to cast the response yourself in TypeScript

```ts
  .then(resp => resp.data as string)
```
