### ISSUE TITLE
404 on git.getCommit organisation private repository 

### ISSUE THREAD

**Issue by harshmanvar** [octokit/octokit.js#1539]
I am using octokit with node and trying to get single commit detail

but getting 404

Generated personal access token I am the owner

On private repo it's working but for the organization's private repository not working response code 404
 
here code snippet : 

    const { IncomingWebhook } = require('@slack/client');
    const humanizeDuration = require('humanize-duration');
    const Octokit = require('@octokit/rest');
    
    
    const GITHUB_ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXX';
    
    const token = GITHUB_ACCESS_TOKEN;
    const octokit = require('@octokit/rest')({
      auth: `token ${token}`
    })
    
    module.exports.getGithubCommit = async (build, octokit) => {
        try {
            console.log("Inside Github function");
            const githubRepo   = 'XXXXXXXXXXXXXX';
            const githubBranch = 'XXXXXXXXXXXXX';
            const commitSha    = 'XXXXXXXXXXXXXXXX';
            const githubCommit = await octokit.git.getCommit({
                commit_sha: commitSha,
                owner: 'harshmanvar',
                repo: githubRepo,
            });
            console.log("Github commit value",githubCommit);
            return githubCommit;
        } catch (err) {
            console.log('error',err);
            return err;
        }
    };
    
    const githubCommit = module.exports.getGithubCommit(build, octokit);

Let me know if I am missing something.

when I tried to list repository for organization in all repository I found

    owner : [object]

    { id: 12345674890,
           node_id: 'XXXXXXXXXXXXXXXXXXXX',
           name: 'XXXXX',
           full_name: 'XXXXXXXXXXXX',
           private: true,
           owner: [Object],
           html_url: 'https://github.com/org/XXXXXXXXXXXXX',
           description: null,
           fork: false,

**Comment by gr2m** [comment]
Maybe because you have `harshmanvar` hardcoded as owner? It's hard to tell from the code you shared. It's unlikely an error with `@octokit/rest`

Can you try to run a separate script that just fetches the repository ([docs](https://octokit.github.io/rest.js/#octokit-routes-repos-get))?

```js
const GITHUB_ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXX';
const token = GITHUB_ACCESS_TOKEN;
const octokit = require('@octokit/rest')({
  auth: `token ${token}`
})
octokit.repos.get({ owner, repo }).then(console.log, console.log)
```

and see if that works?

**Comment by harshmanvar** [comment]
@gr2m  Thankyou so much for the reply. That's working also along with that I am able to get all private repositories of the organization but not able to get commit detail using SHA.

```
const githubRepo   = 'XXXXXXXXXXXXXX';
        const githubBranch = 'XXXXXXXXXXXXX';
        const commitSha    = 'XXXXXXXXXXXXXXXX';
        const githubCommit = await octokit.git.getCommit({
            commit_sha: commitSha,
            owner: 'harshmanvar',
            repo: githubRepo,
        });
        console.log("Github commit value",githubCommit);
```

**Comment by gr2m** [comment]
Are you sure that the `commitSha` is correct? Can you reproduce the problem when sending a `curl` request?

**Comment by harshmanvar** [comment]
Yes `commitSha` is correct only. I will share SS please five me a few mins.

**Comment by harshmanvar** [comment]
@gr2m  here code i am using 

```
module.exports.getGithubCommit = async (build, octokit) => {
    try {
        const all_repo = await octokit.repos.listForOrg({
            org: 'XXXXXX',
        });
        console.log('All repo',all_repo);
        const githubRepo   = 'core';
        const githubBranch = 'development';
        const commitSha    = '2dcffcb85*********************';
        const owner = 'harshmanvar';
        const githubCommit = await octokit.git.getCommit({
            commit_sha: commitSha,
            owner: owner,
            repo: githubRepo,
        });
        console.log("Github commit value",githubCommit);
        return githubCommit;
    } catch (err) {
        console.log('error',err);
        return err;
    }
};
```
Screen shot of commit : 

![Selection_043](https://user-images.githubusercontent.com/50694399/71476438-20e74480-280b-11ea-88f1-9807317bb1c3.png)

Screenshot when output all repo details

![Selection_041](https://user-images.githubusercontent.com/50694399/71476511-6dcb1b00-280b-11ea-9ca3-cafa230cabd9.png)

Screenshot when get commit 

![Selection_042](https://user-images.githubusercontent.com/50694399/71476578-bedb0f00-280b-11ea-82d3-17c6410befee.png)

I know in both repo names is different but just to confirm my git token is proper.

The weird thing i noticed, If you look in repo details screenshot inside it `owner : [object]` cloud be reason from organization repo not able to get commit detail as no value of `owner : [object]`.

While with for my other private repository in same account it's working like charm.

**Comment by gr2m** [comment]
The 404 from the screenshot tries to find  the commit in a repository that belongs to your personal account `https://api.github.com/repos/harshmanvar/...`, not an organization

**Comment by harshmanvar** [comment]
@gr2m  i want to use for organization repository. for private own repo it's working as expected.

**Comment by gr2m** [comment]
then you have to set the `owner` parameter to the name of the organization

**Comment by harshmanvar** [comment]
@gr2m  Yes that's what i am looking for. Can please inform me how to do it. It would be really helpful.

**Comment by gr2m** [comment]
In this line

```js
        const githubCommit = await octokit.git.getCommit({
            commit_sha: commitSha,
            owner: owner,
            repo: githubRepo,
        });
```

The `owner` must be set to the name of the organization. E.g. if the organization URL is https://github.com/acme-inc, then `acme-inc` is the organization name

**Comment by harshmanvar** [comment]
@gr2m  You really made my day. Thanks a lots. It's working now. Thanks...! It's working like charm.

**Comment by gr2m** [comment]
Glad to hear :)
