### ISSUE TITLE
Can't create repo hook, with correct OAuth scopes

### ISSUE THREAD

**Issue by jpsear** [octokit/octokit.js#1541]
I am trying to create a repo webhook using octokit. The code I have successfully works when authenticating as the repo owner via a token, but not with a collaborator. The scopes are correct, as far as I know.

All other operations to the repo seem to work fine (creating/updating issues and more)

The function I am using is`octokit.repos.createHook`. 

The response I get is:

```
HttpError: Not Found
status: 404
```

I am fairly sure that the token scopes are correct, as in the 404'd response I receive, the headers are as such:

```
'x-accepted-oauth-scopes': 'admin:repo_hook, repo, write:repo_hook',
'x-oauth-scopes': 'admin:org_hook, admin:repo_hook, read:org, repo',
```

Am I missing something obvious here?

Request log, for completeness:

```
{ 
  method: 'POST',
  url: 'https://api.github.com/repos/jpsear/gh-projects-test/hooks',
  headers: { 
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'octokit.js/16.34.0 Node.js/8.17.0 (macOS Catalina; x64)',
    authorization: 'token [REDACTED]',
    'content-type': 'application/json; charset=utf-8' 
  },
  body: '{"name":"web","config":{"url":"[REDACTED-BY-JPSEAR]","content_type":"json"},"events":["project","project_card","project_column","meta","issues","issue_comment","label","repository","member","milestone"],"active":true}',
  request: { hook: [Function: bound bound register], validate: [Object] } },
  documentation_url: 'https://developer.github.com/v3/repos/hooks/#create-a-hook' 
}
```

**Comment by gr2m** [comment]
Does the same request work with curl? I do not think that this is a problem with `@octokit/rest`

Try this command

```
curl -XPOST \
  -H'Authorization: token [YOUR TOKEN HERE]` \
  -H'Content-Type:  application/json; charset=utf-8' \
  -H'Accept: application/vnd.github.v3+json' \
  https://api.github.com/repos/jpsear/gh-projects-test/hooks \
  -d '{"name":"web","config":{"url":"[REDACTED-BY-JPSEAR]","content_type":"json"},"events":["project","project_card","project_column","meta","issues","issue_comment","label","repository","member","milestone"],"active":true}'
```

**Comment by jpsear** [comment]
You're absolutely right, it doesn't work as a raw request, so it's not an octokit issue. No idea why I didn't test this first.

Community thread here: https://github.community/t5/GitHub-API-Development-and/Can-t-create-repo-hook-with-correct-OAuth-scopes/m-p/42447#M3792
