### ISSUE TITLE
Add support for delete_branch_on_merge

### ISSUE THREAD

**Issue by localheinz** [octokit/octokit.js#1543]
The GitHub REST API, albeit not documented, supports enabling/disabling the setting via https://developer.github.com/v3/repos/#edit using the `delete_branch_on_merge` key.

Is there a chance we can add support here?

Also see

- https://github.com/probot/settings/issues/134#issuecomment-572804489
- https://github.com/Financial-Times/github-apps-config-next/issues/19

**Comment by gr2m** [comment]
I'm desperately waiting for it, too. Updates to the REST API methods are all automated, so once it is documented, we will get a pull request like this one: https://github.com/octokit/routes/pull/607 which in turn, once a new version was published to npm, will trigger a pull request to update `@octokit/rest`. 

For the time being, you should be able to just pass the `delete_branch_on_merge` key to the according `octokit.repos.*` methods, the additional parameter will be passed on

**Comment by localheinz** [comment]
Thank you for your feedback, @gr2m!

**Comment by localheinz** [comment]
Should be fixed soon through https://github.com/octokit/routes/pull/617.

**Comment by gr2m** [comment]
jap, I'm working on it via #1547

**Comment by localheinz** [comment]
Thank you, @gr2m!
