### ISSUE TITLE
Documentation for #octokit-routes-issues-update-label is incorrect

### ISSUE THREAD

**Issue by abhijithvijayan** [octokit/octokit.js#1544]
- https://developer.github.com/v3/issues/labels/#update-a-label
- https://octokit.github.io/rest.js/#octokit-routes-issues-update-label

The documentation has `name` property for `old label name` & `new_name` property for `the new label name`

But the typescript definition shows `name` property for `the new label name` & `current_name` as the `old label name` which is the correct one.

## Screenshots

![Screenshot from 2020-01-13 09-10-45](https://user-images.githubusercontent.com/34790378/72232069-e04a4200-35e4-11ea-940c-d305acb71f0a.png)

![Screenshot from 2020-01-13 09-15-00](https://user-images.githubusercontent.com/34790378/72232166-5cdd2080-35e5-11ea-8cee-8f3e3ba73ff0.png)

**Comment by gr2m** [comment]
Thank you @abhijithvijayan, there is probably a workaround missing for typescript that exists for the code itself. The `Update a label` is a special case as the parameters have been renamed in a way that we cannot in the client without introducing a breaking change. We will clear that app with v17 which I'm already working on. I'll try to fix that up beforehand for v16, but it's not a priority for me right now. 

If you like, feel free to look into it yourself, I'm happy to give you guidance if you want to give it a try

**Comment by gr2m** [comment]
This will be resolved with v17, see #1546 for more details and upgrade changelogs
