### ISSUE TITLE
Create a webhook, not found response.

### ISSUE THREAD

**Issue by reggi** [octokit/octokit.js#155]
I'm trying to [create a webhook](https://developer.github.com/v3/repos/hooks/#create-a-hook) using the [watchEvent](https://developer.github.com/v3/activity/events/types/#watchevent) and [repos.createHook](https://github.com/mikedeboer/node-github/blob/e5c704ec815b15540bacf6a57cf484c9ea237354/api/v3.0.0/reposTest.js#L988-L1004) function and I keep getting `notFound` error.

```
  github.repos.createHook({
    user: "reggi",
    repo: "stellar-hooks",
    name: "watch",
    active: true,
    events: [
      "user"
    ],
    config: {
      url: "http://requestb.in/1bcs4pn1",
    }
  }, function(err, gres) {

  });
});
```

I'm getting a not found error:

```
{ [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
```

Also tried something simpler, and it's not working either.

```
  github.repos.createHook({
    user: "reggi",
    repo: "stellar-hooks",
    name: "push",
    active: true,
    config: {
      url: "http://requestb.in/1bcs4pn1",
    }
  }, function(err, gres) {

  });
```

Any ideas?

**Comment by kondaramakrishna99** [comment]
I am also having the same problem. Till few minutes back, I am able to create webhooks programatically and getting payloads back. But suddenly it is throwing error response with response code:404

I checked git hub API and they said they intentionally throw 404 error instead of 403 but even than I am not able to understand why I am not getting authorized. I used all the ways given in the API to authorize the app.

Can anyone throw some light on it on how to get authorized successfully?

**Comment by kaizensoze** [comment]
@kondaramakrishna99: Do you have a code sample I can take a look at?

**Comment by kondaramakrishna99** [comment]
I am first getting OAuth2 access token from git and storing it in database.
Than I am using following code to create hook.

[post request]

String url = "https://api.github.com/repos/"+username+"/"+repo+"/hooks?access_token="+token;
 HttpPost post = new HttpPost(url);
post.addHeader("Accept", "application/json");
post.addHeader("content_type","json");

JSONObject postjson = new JSONObject();
            postjson.put("name","web");
            JSONObject config = new JSONObject();
            config.put("url",redirect_url);
            config.put("content_type","json");
            postjson.put("config",config);
            String[] events = new String[1];
            events[0]="*";
            postjson.put("events",events);

StringEntity postjsonEntity = new StringEntity(postjson.toString());
post.setEntity(postjsonEntity);
CloseableHttpResponse response = client.execute(post);

//post body json
{"name":"web","config":{"content_type":"json","url":"http://855fe5ec.ngrok.io/payload"},"events":["*"]}

Response I am getting:
Response Code : 404
json response:: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

I used the same code and I am able to create hook and I am able to get webhook payload successfully from Git.

Can you please tell me what might be the mistake with authorization?

**Comment by kondaramakrishna99** [comment]
I am first getting OAuth2 access token from git and storing it in database.
Than I am using following code to create hook.

[post request]

`String url = "https://api.github.com/repos/"+username+"/"+repo+"/hooks?access_token="+token;
HttpPost post = new HttpPost(url);
post.addHeader("Accept", "application/json");
post.addHeader("content_type","json");

JSONObject postjson = new JSONObject();
postjson.put("name","web");
JSONObject config = new JSONObject();
config.put("url",redirect_url);
config.put("content_type","json");
postjson.put("config",config);
String[] events = new String[1];
events[0]="*";
postjson.put("events",events);

StringEntity postjsonEntity = new StringEntity(postjson.toString());
post.setEntity(postjsonEntity);
CloseableHttpResponse response = client.execute(post);`

//post body json
{"name":"web","config":{"content_type":"json","url":"http://855fe5ec.ngrok.io/payload"},"events":["*"]}

Response I am getting:
Response Code : 404
json response:: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

I used the same code and I am able to create hook and I am able to get webhook payload successfully from Git.

Can you please tell me what might be the mistake with authorization?

**Comment by kondaramakrishna99** [comment]
I am first getting OAuth2 access token from git and storing it in database.
Than I am using following code to create hook.

[post request]
`String url = "https://api.github.com/repos/"+username+"/"+repo+"/hooks?access_token="+token`
`HttpPost post = new HttpPost(url);`
`post.addHeader("Accept", "application/json");`
`post.addHeader("content_type","json");`
`JSONObject postjson = new JSONObject();`
`postjson.put("name","web");`
`JSONObject config = new JSONObject();`
`config.put("url",redirect_url);`
`config.put("content_type","json");`
`postjson.put("config",config);`
`String[] events = new String[1];`
`events[0]="*";`
`postjson.put("events",events);`
`StringEntity postjsonEntity = new StringEntity(postjson.toString());`
`post.setEntity(postjsonEntity);`
`CloseableHttpResponse response = client.execute(post);`

//post body json
{"name":"web","config":{"content_type":"json","url":"http://855fe5ec.ngrok.io/payload"},"events":["*"]}

Response I am getting:
Response Code : 404
json response:: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

I used the same code and I am able to create hook and I am able to get webhook payload successfully from Git.

Can you please tell me what might be the mistake with authorization?

**Comment by kaizensoze** [comment]
I don't see any node-github library relevant code here.

**Comment by kondaramakrishna99** [comment]
I am not doing anything complicated, I am just doing a post request to this url
"https://api.github.com/repos/"+username+"/"+repo+"/hooks?access_token="+token
as given in their API.

I used OAuth2 previously and got token and than passing it as a parameter to this url for authentication.
This post request needs a payload. So passing json in the body.

I am not sure whether I am doing wrong with passing access token in the url?

**Comment by kaizensoze** [comment]
The github api misleadingly returns a 404 if the access token doesn't have permissions to create a web hook.

**Comment by kondaramakrishna99** [comment]
Thanks for you reply. This helped me to think in regard to scope of app
When I tried to authorize git through app using following url
`https://github.com/login/oauth/authorize?client_id=XXXX&scope=repo%20admin:repo_hook`

I am getting the reponse after authorization as scope="". Git intentionally giving less scope than requested and if I am requesting only repo than I getting scope of repo.

I am still looking into how to get around this problem.

**Comment by kondaramakrishna99** [comment]
@kaizensoze I am always checking whether the scope I got from git is same as the scope requested. If I do not get the requested scope, I am asking user to authorize again with higher scope.

Is it the only way to do or any other method where I can get the requested scope for the first time itself?

**Comment by animo93** [comment]
The access token should have admin:repo_hook scope . Otherwise it will throw a 404

**Comment by stockhousedev** [comment]
The Amazon CodePipeline service currently can not create GitHub web hooks. It also reports the 404 response. In this case I am not calling the API myself, just choosing from drop-down lists in the AWS console.

**Comment by gr2m** [comment]
There is nothing we can do about it, please talk to Amazon

**Comment by futurechallenger** [comment]
According to @animo93 , my problem is that i dont have the scope to set hook to a org. When I have that scope, everything's ok.

**Comment by jeckefe** [comment]
The url for auth should be 
https://github.com/login/oauth/authorize?client_id={CLIENT_ID}&redirect_uri={REDIRECT_URL}&scope=repo,admin:repo_hook&public_repo

**Comment by AdamMiltonBarker** [comment]
I have the permission:

 Full control of orgs and teams, read and write org projects
 Full control of organization hooks
 Full control of repository hooks
 Full control of private repositories
 
 'admin:org,admin:org_hook,repo,admin:repo_hook'
 
 I am able to create repos, get, etc, but I cannot get around this issue of 404. The repo I am adding a webhook to is a repo that was created via the API in the organization that I have granted permissions to. 
 
 As I have the correct permissions to perform this action, what is the fix for this?

**Comment by wolfy1339** [comment]
Please create a new issue instead of commenting on a 5 year old issue
