### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by theninj4** [octokit/octokit.js#1588]
Hey 👋 

First up - I love the work everyone's achieved here, this module is fantastic ❤️ 

Onwards to the issue at hand - it's likely we're doing something wrong and am looking for some guidance - I came in to work this morning to find a few emails from GitHub regarding our usage of their API:

---
Hi xxxxxxxxxx,

On February 4th, 2020 at 09:40 (UTC) your personal access token (xxxxxxxxxx) using xxxxxxxxxx **octokit.js/16.43.1** Node.js/10.xxxx (Linux xxxxx) was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/...snip...

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder once every 3 days for each token and User-Agent used in API calls made on your behalf.
Just one URL that was accessed with a token and User-Agent combination will be listed in the email reminder, not all.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

---

Here's how we're using this module:
```javascript
const github = require('@octokit/rest')({
  protocol: 'https',
  host: 'api.github.com',
  headers: {
    'user-agent': 'xxxxxxxx'
  }
})
github.authenticate({
  type: 'oauth',
  token: 'xxxxxxxxxxxxxxxxxxxxxx'
})
```

Are we doing something wrong here? Should we be authenticating in a different way?

**Comment by gr2m** [comment]
Hi @theninj4,

thank you for the kind words 🖤

The `github.authenticate()` method has been deprecated for quite some time now. You should see a deprecation message in your logs about it, could you check if that's the case please? You should see several deprecation messages for your code, you use several deprecated APIs and options.

With the latest version, the correct code would be this

```js
const { Octokit } = require('@octokit/rest')
const github = new Octokit({
  userAgent: 'xxxxxxxx',
  auth: 'xxxxxxxxxxxxxxxxxxxxxx'
})
```

**Comment by theninj4** [comment]
Ah! Brilliant, I'll fix all our code. We don't have any deprecation messages in any logs for the last 24 hours and I can't force anything out on the Node.js repl, although we do have a in-house 
Node.js standard-library giving us consistent org-wide logging - it's possible/probable our shenanigans are hiding the deprecation warning.

Thanks for the help! 👍

**Comment by gr2m** [comment]
That will be worth investigating. The deprecation messages will be hugely helpful when upgrading to v17 of `@octokit/rest`. Nearly every breaking change had a preceding deprecation. 

If you find out why the deprecation messages didn't show up, please let me know, maybe it's something I can do on my side if you use a standardized why to retrieve them.

I use a standard `console.warn` to log them to stdout (when using with Node.js). You can customize the methods used for logging: https://octokit.github.io/rest.js/#logging
