### ISSUE TITLE
Path prefix doesn't work with pagination

### ISSUE THREAD

**Issue by lalau** [octokit/octokit.js#160]
I am using it with a enterprise version of github that has a path prefix to use the API. I notice that when paginating there seems to be a double path prefix being used:

First the url sent [here](https://github.com/mikedeboer/node-github/blob/5d6d0a8cd47cf397e6e7c78434c5f54afaf00280/index.js#L493) already has the path prefix as given by the next url in the link header.

Then the url is assembled by adding the path prefix again [here](https://github.com/mikedeboer/node-github/blob/5d6d0a8cd47cf397e6e7c78434c5f54afaf00280/index.js#L567).

Not sure how you would want it to be fixed. One idea I have is to pass in a param from `getPage` which tells `getQueryAndUrl` to not add the path prefix again, since the page url should already have it. Or you strip out the path prefix before passing in, but that seems a bit odd.

**Comment by kaizensoze** [comment]
This should be fixed now. You just need to pass the headers to the getNextPage() method.
