### ISSUE TITLE
creating check run for pull request trigger workflow creates "(Unnamed workflow)"

### ISSUE THREAD

**Issue by devaradhanm** [octokit/octokit.js#1606]
Repro steps:
    1.) Create a workflow that triggers for push on master & any pull request.
    2.) Add an action that uses oktokit rest apis to create checkrun. For eg, mooyoul/tslint-actions
    3.) Checkin some changes directly to master & observe that the check run is created in the same workflow as the triggered one. For eg: refer [https://github.com/devaradhanm/sample-js/actions/runs/39068965](https://github.com/devaradhanm/sample-js/actions/runs/39068965)
   4.) Create a pull request with some changes & observe that the check run is created under a different workflow called "(unknown workflow)". For eg, refer [https://github.com/devaradhanm/sample-js/actions/runs/39069982](https://github.com/devaradhanm/sample-js/actions/runs/39069982) & [https://github.com/devaradhanm/sample-js/actions/runs/39070595](https://github.com/devaradhanm/sample-js/actions/runs/39070595)

**Comment by gr2m** [comment]
Can you share the code that creates the check run?

**Comment by devaradhanm** [comment]
you can refer this - https://github.com/mooyoul/tslint-actions/blob/2758a9f666b4cdae4a8312096891e41417ade498/index.ts#L40

**Comment by gr2m** [comment]
The `(Unnamed workflow)` at https://github.com/devaradhanm/sample-js/actions/runs/39070595 is not one created by Octokit, but by a GitHub Action. It seems that the according workflow file no longer exists: https://github.com/devaradhanm/sample-js/actions/runs/39070595/workflow

So I don't think there is a problem with Octokit itself here at all. Or am I missing something?

**Comment by devaradhanm** [comment]
@gr2m , https://github.com/devaradhanm/sample-js/actions/runs/39070595 is created by the tslint action using the oktokit api https://github.com/mooyoul/tslint-actions/blob/2758a9f666b4cdae4a8312096891e41417ade498/index.ts#L40

We were able to repro this issue when we tried to create check run under an action we are developing using the oktokit api as well. This only happens when the trigger type is pull_request. If the trigger type is push, this works fine - https://github.com/devaradhanm/sample-js/actions/runs/39068965

**Comment by gr2m** [comment]
This is the checkrun that you create in that line
https://github.com/devaradhanm/sample-js/runs/444995415. See the difference in the UI? This is how Check Runs look like created using the check runs API.

https://github.com/devaradhanm/sample-js/actions/runs/39070595 was created automatically from a GitHub Action workflow run. Every action run also creates a check run that is looking like this one

**Comment by devaradhanm** [comment]
@gr2m , shouldnt this be associated with the workflow https://github.com/devaradhanm/sample-js/actions/runs/39069982 instead since the check run is created under one of the actions from this workflow? This works fine & is properly associated with the correct workflow if the workflow trigger type is "push". (https://github.com/devaradhanm/sample-js/actions/runs/39068965). why is this experience not consistent with pull_request & push trigger?

If we somehow have to pass the workflow id to the octokit api, to make sure that it always creates the check run under the correct workflow, how do we do that?

**Comment by gr2m** [comment]
I really cannot help with https://github.com/devaradhanm/sample-js/actions/runs/39070595, can you ask support@github.com? They have access to request logs etc to find out why the check run is not associated with the "Node.js CI" workflow. I'm sure it has nothing to do with `@octokit/rest`

**Comment by devaradhanm** [comment]
sure. Thanks!

**Comment by paulpach** [comment]
@devaradhanm I see the same issue,  did you ever reach out to github?  what did they say?

**Comment by FireKeyz** [comment]
@devaradhanm  @paulpach  I get the same issue too. Created a workflow to create an executable for my python project & committed it into master branch. For first time the workflow ran, it was a failure, due to some issues in the command I ran, so I edited the _main.yml_ and committed to the master branch again. But, this time, the workflow name was changed to **"Unnamed workflow"** and the action was not run at all. Any update on this?

**Comment by MattWestConfigit** [comment]
Sorry to resurrect this closed issue but did any of you guys get a resolution for this?

Edit: I managed to resolve this issue. It wasn't with the rest API as such. The issue for me was that the action was using the wrong SHA when it was generating the check api request for `$octokit.checks.create`. When you are triggering the workflow using a push then the correct SHA is `$github.context.sha`. When the trigger is a pull request however the correct SHA is `$github.context.payload.pull_request.head.sha`. It is the incorrect SHA being used that causes this "ghost run".

So for example you'd need to do something like:

```
const checkRequest = {
  head_sha: getSha($github),
  ...otherProperties
};

const getSha= ( $github ) => {
  return $github.context.payload.pull_request ? $github.context.payload.pull_request.head.sha : $github.context.sha;
}

```

I hope this is helpful for anyone else that gets stuck.
