### ISSUE TITLE
Allow error response headers to be checked for two-factor authentication

### ISSUE THREAD

**Issue by henrahmagix** [octokit/octokit.js#162]
When dealing with an unknown requirement for two-factor authentication, it'll be really helpful if the response headers could be checked for `X-GitHub-OTP`. Currently I have to check the error code and then do a string match on the error message, which feels brittle even though it works.

``` js
function userRequires2FA (callback) {
    github.authorization.getAll({}, function (err, res) {
        var has2FA = false;
        if (err) {
            // Can't check the response headers on error, so do a string
            // match on the message.
            if (err.code === 401 && JSON.parse(err.message).message !== 'Must specify two-factor authentication OTP code.') {
                has2FA = true;
            } else {
                callback(err, has2FA);
            }
        }
        callback(null, has2FA);
    });
}
```

Perhaps a method could be added that would do the above: check if a two-factor authentication code is needed and return a boolean?

**Comment by kaizensoze** [comment]
Headers are now included in the HttpError object.

**Comment by henrahmagix** [comment]
Thanks!
