### ISSUE TITLE
`listRepoWorkflowRuns()`: response is no longer flattened after the 1st page

### ISSUE THREAD

**Issue by gomorizsolt** [octokit/octokit.js#1632]
Example: https://runkit.com/gomorizsolt/octokit-restjs

As is: the response isn't flattened after the 30th item:

```
Array (X items)
0: Object { id: 48027713, // ... }
1: Object { id: 48027713, // ... }
// ...
29: Object { id: 48027713, // ... }
30: Object {total_count: Y, workflow_runs: [Object {…}, ...]}
31: Object {total_count: Y, workflow_runs: [Object {…}, ...]}
// ...
// ...
```

Expected: the response is flattened(even after the 30th item):

```
Array (X items)
0: Object { id: ..., // ... }
1: Object { id: ..., // ... }
2: Object { id: ..., // ... }
3: Object { id: ..., // ... }
4: Object { id: ..., // ... }
5: Object { id: ..., // ... }
// ...
30: Object { id: ..., // ... }
31: Object { id: ..., // ... }
// ...
```

Questions:
- Is this expected? If so, what's the reason for this nesting?
- Should the array be flattened by myself by e.g. passing the optional function(even if it's an additional "overhead")?

**Comment by gr2m** [comment]
Thanks for reporting the issue Zsolt! Double thanks for providing a test case on runkit.com 💯 

I was actually not able to reproduce the problem. Can you check what version of `@octokit/plugin-paginate-rest` you have locally? You can check with

```
npm ls @octokit/plugin-paginate-rest
```

Make sure you have the latest version. The normalization is happening there. I'm testing this particular case at https://github.com/octokit/plugin-paginate-rest.js/blob/9cf714e46747643a5f8fe99a55202e2d01718fb0/test/paginate.test.ts#L737-L799

The latest version of `@octokit/plugin-paginate-rest` is 2.0.1 right now

**Comment by gomorizsolt** [comment]
Thanks for the quick response @gr2m! 

On the one hand, you're right, I'm using an outdated version of `@octokit/plugin-paginate-rest`(which is a sub-dependency of `@actions/github`):

```
└─┬ @actions/github@2.1.0
  └─┬ @octokit/rest@16.43.1
    └── @octokit/plugin-paginate-rest@1.1.2 
```

On the other hand, after creating a fresh repo with the updated dependencies(without installing `@actions/github`):

```
└─┬ @octokit/rest@17.0.0
  └── @octokit/plugin-paginate-rest@2.0.1 
```

I'm still experiencing the exact same issue(even if the `GET /repos/:owner/:repo/actions/runs` is sent).

**Comment by gr2m** [comment]
Can you use https://github.com/octokit/action.js (`@octokit/action`) instead of `@actions/github`? I do not maintain `@actions/github` and cannot help with that.

**Comment by gomorizsolt** [comment]
> On the other hand, after creating a fresh repo with the updated dependencies(without installing @actions/github):

Have you seen this? It's definitely not an issue with `@actions/github`. The response is *not* normalized in the case of `@octokit/rest` as well. It's odd you cannot reproduce the problem.

**Comment by gomorizsolt** [comment]
https://runkit.com/gomorizsolt/octokit-restjs

I've updated the RunKit with another sample which requests ALL the issues for a specific repo. This corroborates the fact that the pagination indeed works(at least in this case).

**Comment by gr2m** [comment]
When I open your runkit notebook, the results look correct, for both parts

<img width="991" alt="image" src="https://user-images.githubusercontent.com/39992/75827040-a2a0a480-5d5d-11ea-96c1-cff90ab89395.png">

I don't see the `response` array to have objects with `{ workflow_runs }` keys, they are correctly flattened

**Comment by gomorizsolt** [comment]
> All endpoint methods starting with .list* do not return all responses at once but instead return the first 30 items by default

Yea, because, by default, the first 30 items are flattened. I guess I could've been more precise in terms of the issue's description(therefore, I've updated it). If you scroll down to the 30th item, you'll find the fields we're talking about(i.e. `total_count` and `workflow_runs`).

![Képernyőfotó 2020-03-04 - 8 51 26](https://user-images.githubusercontent.com/30864202/75856876-8bad9100-5df5-11ea-8276-a579fcb089d3.png)

**Comment by gr2m** [comment]
Ah that makes sense, thank you! I have a suspicion what is going wrong. I'll look into it

**Comment by gr2m** [comment]
Make sure you have the latest version of `@octokit/plugin-paginate-rest` (2.0.2)

```
rm -rf package-lock.json node_modules
npm install
npm ls @octokit/plugin-paginate-rest
```

**Comment by gomorizsolt** [comment]
Thanks, it's fixed! 👍
