### ISSUE TITLE
Missing parameter for the GithubAction API change of 09/03

### ISSUE THREAD

**Issue by njibhu** [octokit/octokit.js#1637]
Since https://github.blog/changelog/2020-03-09-new-filter-parameter-in-workflow-jobs-api/ was deployed, the old executions are not returned anymore with the default endpoint behavior.

The `filter` argument should be added to `listJobsForWorkflowRun`. The current running solution when using typescript is :
```ts
      await octokit.actions.listJobsForWorkflowRun({
        owner,
        repo,
        run_id,
        filter: 'all' //Not supported by octokit currently
      } as any)
```

**Comment by gr2m** [comment]
The update of the endpoint methods is automated via https://github.com/octokit/routes/. This will be resolved once I've worked through the latest updates in https://github.com/octokit/routes/pull/667

**Comment by gr2m** [comment]
Also I should add that the `filter` parameter is supported by octokit, it's just the TypeScript definition that is complaining. The code will work in JavaScript without a problem.

**Comment by gr2m** [comment]
Fixed via https://github.com/octokit/rest.js/releases/tag/v17.1.0
