### ISSUE TITLE
Octokit not working as a factory function

### ISSUE THREAD

**Issue by zeke** [octokit/octokit.js#1640]
Hey @gr2m and friends 👋 

The [current usage docs](https://github.com/octokit/rest.js/blob/4d3e69a81a9b6ce904a2de1b9b9dc9276b6218f6/docs/src/pages/api/00_usage.md) indicate that `Octokit` can be invoked as a factory function without the `new` keyword:

```
const octokit = Octokit({
```

However, I see this error when omitting the `new` keyword:

```
TypeError: Class constructor OctokitWithDefaults cannot be invoked without 'new'
```

When I prepend `new`, my code works:

```
const octokit = new Octokit({
```

Here's a repro:

https://runkit.com/zeke/5e6851d9f467ae001485109e

Is the documented usage expected to work? In other words, is this a bug or an incorrect usage doc? I'd be happy to open a PR to help resolve this.

**Comment by gr2m** [comment]
Thanks Zeke! It's a documentation bug, the `new` is now required, starting with v17. Happy to review & merge a PR to fix the docs. I'll make sure to mention it in the v17 release notes

**Comment by zeke** [comment]
Surprising that it took 19 hours for that @github-actions comment to pop up. Any idea what happened there @gr2m?

**Comment by gr2m** [comment]
Nope, no idea. Sometimes internal APIs go down but the action queue is still on. @nat mentioned sth about donating idle hours for research, maybe that has something to do with it?
