### ISSUE TITLE
unable to authenticate Github App

### ISSUE THREAD

**Issue by inesgs12** [octokit/octokit.js#1646]
I'm trying to use the appId to access a private Github repo and access the tree, but keep getting a **404** HTTP Error status code:
```
const auth = createAppAuth({
          privateKey: certificate,
          id: appId,
        })
this.authApp = await auth({
          type: 'app',
        })

this.ghApp = new Octokit(this.authApp)
```

And when I console.log the this.ghApp.auth I get this: 
`console.log(this.ghApp.auth)`

Result:
```
async () => ({
     type: "unauthenticated"
})
```

The credentials are correct, they work with Octokit 15.8. I'm trying to refactor to version 17.0.0 and can't seem to get it working.

**Comment by gr2m** [comment]
This code is incorrect, I don't think that would have worked with v16 either

```js
this.ghApp = new Octokit(this.authApp)
```

Did you find that in docs somewhere?

Can you try this please?

```js
this.ghApp = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    privateKey: certificate,
    id: appId
  }
})

const appAuthentication = await this.ghApp.auth({ type: 'app' })
```

**Comment by gr2m** [comment]
> I'm trying to use the appId to access a private Github repo and access the tree

Not that for that you need an installation ID. 

```js
this.ghApp = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    privateKey: certificate,
    id: appId,
    installationId: ...
  }
})
```

Octokit will use the correct authentication method automatically based on request path. So you can just do the request after that

```
// will automatically create an installation access token and create it
this.ghApp.repos.get({owner, repo})
```

**Comment by inesgs12** [comment]
Thanks so much! I did try what you sent, but I was trying to get the tree from what was being returned from this: 
`this.ghApp.auth({ type: 'app' })`
