### ISSUE TITLE
Octokit is not a constructor 

### ISSUE THREAD

**Issue by inesgs12** [octokit/octokit.js#1647]
I keep getting the following error on Circle CI: 

`TypeError: Octokit is not a constructor`

I have updated the package to the latest version 17.1.0 
`const {Octokit} = require('@octokit/rest')`

The code is working, but the error shows up when trying to deploy.

**Comment by gr2m** [comment]
Did you figure it out? What was the problem?

**Comment by themoch** [comment]
@gr2m I had this same issue and looked at how @inesgs12 was importing.  I was using the old require of `const Octokit = require('@octokit/rest')`

it needs to be updated to `const { Octokit } = require('@octokit/rest')`

**Comment by irfanhabib** [comment]
What exactly does this syntax do:
```
const { Octokit } = require..
```

vs 
```
const Octokit = require..
```

Apologies if this is basic question, I'm not a JS developer

**Comment by gr2m** [comment]
Hi Irfan, no problem, happy to help.

```js
const Octokit = require('@octokit/rest')
```

Exports the Octokit Constructor as the root export. The export would look something like this:

```js
// @octokit/rest module
module.exports = class Octokit { ... }
```

---

```js
const { Octokit } = require('@octokit/rest')
```

Exports an Object with an `Octokit` property, which is the constructor. The export would look something like this

```js
// @octokit/rest module
module.exports = {
  Octokit: class Octokit { ... }
}
```

The reason we changed the way the export works is that the Node.js ecosystem is migrating towards [ES Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules), and that change made it easier for us to remain compatible with both, the current/old CommonJS syntax (using `require('@octokit/rest')`) and the new ES Modules syntax (using `import ... from '@octokit/rest')

The `Octokit` constructor remains the same.

Hope that helps :)
