### ISSUE TITLE
I often got the error connect ECONNREFUSED 13.250.168.23:443

### ISSUE THREAD

**Issue by lhc-up** [octokit/octokit.js#1648]
Often got this error connect ECONNREFUSED 13.250.168.23:443

**Comment by gr2m** [comment]
Are you sure that is a problem with `@octokit/rest`? I cannot really help you much unless you can create a reproducible test case. `ECONNREFUSED` sounds like a lower-level connectivity problem, likely with your GitHub Enterprise Server instance? When I open https://13.250.168.23/ I get an SSL warning, that might be the problem, too?

**Comment by BestBugMaker** [comment]
> Often got this error connect ECONNREFUSED 13.250.168.23:443

that might be a github error, I often got the same error since March.

**Comment by gr2m** [comment]
@BestBugMaker just to confirm, you get the error when using the api for github.com, or a GitHub Enterprise Server instance?

**Comment by BestBugMaker** [comment]
@gr2m the api of github.com, the OAuth login api for my third-party github app

**Comment by gr2m** [comment]
Thanks for confirming BBM :)

There is not much I can help with here unless I have a reproducible test case.

I would recommend to use the [retry plugin](https://github.com/octokit/plugin-retry.js/), which will try to re-send a request if it fails due to connection issues. Let me know if that helps

**Comment by gm3dmo** [comment]
I've noticed this problem also and have this to offer.

GitHub's IP addresses are documented and reachable via the https://docs.github.com/en/rest/reference/meta API endpoint.
The api IP addresses are in the test script below:

```
import socket

def main():

    ips = [
            "13.230.158.120",
            "18.179.245.253",
            "52.69.239.207",
            "13.209.163.61",
            "54.180.75.25",
            "13.233.76.15",
            "13.234.168.60",
            "13.250.168.23",
            "13.250.94.254",
            "54.169.195.247",
            "13.236.14.80",
            "13.238.54.232",
            "52.63.231.178",
            "18.229.199.252",
            "54.207.47.76"
           ]


    for ip in ips:
        print(ip)
        x = socket.socket()
        try:
           x.connect((ip, 443))
        except:
           print("fail ",ip)

if __name__ == "__main__":
    """ This is executed when run from the command line """
    main()
```

If you execute this as `python test.py`, you should get a result with no failures. It only fails from certain locations, where the result is:

```
13.230.158.120
18.179.245.253
52.69.239.207
13.209.163.61
54.180.75.25
13.233.76.15
13.234.168.60
13.250.168.23
('fail ', '13.250.168.23')
13.250.94.254
54.169.195.247
13.236.14.80
13.238.54.232
52.63.231.178
18.229.199.252
54.207.47.76
```

it seems like '13.250.168.23' is blocked from some locations.
