### ISSUE TITLE
Passing an array of plugins to Octokit.plugin() has been deprecated.

### ISSUE THREAD

**Issue by retorquere** [octokit/octokit.js#1654]
I'm getting

> Passing an array of plugins to Octokit.plugin() has been deprecated.

but I'm not calling that method in my code. I do see:

* @octokit/plugin-paginate-rest 2.0.2
* @octokit/plugin-request-log 1.0.0
* @octokit/plugin-rest-endpoint-methods 3.3.1

in my package-lock.json

**Comment by wolfy1339** [comment]
This package hasn't been updated to reflect that deprecation notice. It shouldn't be too long

**Comment by gr2m** [comment]
Should be fixed now 👍

**Comment by retorquere** [comment]
confirmed
