### ISSUE TITLE
Actions API schema needs updating

### ISSUE THREAD

**Issue by IAmHughes** [octokit/octokit.js#1656]
When attempting to utilize the [get-a-workflow](https://developer.github.com/v3/actions/workflows/#get-a-workflow) endpoint through [octokit](https://octokit.github.io/rest.js/v17#actions-get-workflow), I am having issues using the `:workflow_file_name` version (versus the `workflow_id`). Further discussion with @jamesmgreene led to the following discovery:

[This schema](https://github.com/octokit/routes/blob/master/openapi/api.github.com/operations/actions/get-workflow.json#L34-L40) does not allow for a `string` as described in the GitHub Documentation.

I was able to get it working with the following curl:

```.sh
curl --request GET \
  --url https://api.github.com/repos/IAmHughes/giphy-generator/actions/workflows/giphy-generator.yml
```

In Octokit I tried the following:

```
const workflowName = 'giphy-generator.yml'
const getWorkflowResponse = await github.actions.getWorkflow({
      owner,
      repo,
      workflow_file_name: workflowName
    });
```

/cc @gr2m for input ❤️

**Comment by gr2m** [comment]
That's a tricky one. When we scrape the documentation and create the Open API spec that is used to generate these endpoint methods, there is no way for us to generate route aliases like this one. Ideally, the documentation would have two sections

1. Get a workflow by workflow ID
1. Get a workflow by workflow name

There are plenty of aliases like this in GitHub's REST API, I know the API & Docs team are discussing how to approach it right now.

For the time being, with Octokit, you can use the lower level `octokit.request` method

```js
const workflowName = 'giphy-generator.yml'
const getWorkflowResponse = await github.request('GET /repos/:owner/:repo/actions/workflows/:workflow_file_name', {
      owner,
      repo,
      workflow_file_name: workflowName
    });
```

Does that work for you?

**Comment by IAmHughes** [comment]
> For the time being, with Octokit, you can use the lower level octokit.request method

Thanks, that was suggested by @jasonetco in passing as well, and that does actually also didn't work for me (error and code below). Let me know (Slack or here works) if you want me to bring this up to the docs team to try to break into sections for your scraping.

Error: `##[error]Not Found`

This is what I have:

```
const workflowName = 'giphy-generator.yml';
const getWorkflowResponse = await github.request('GET /repos/:owner/:repo/actions/workflows/:workflow_file_name', {
      owner,
      repo,
      workflow_file_name: workflowName
    });
```

That workflow does indeed exist 😢

**Comment by gr2m** [comment]
I'm looking into it

**Comment by gr2m** [comment]
It just works for me 🤔 

https://runkit.com/gr2m/octokit-rest-js-1656/1.0.0

Is this a private repo?

**Comment by gr2m** [comment]
I tested it with a private repo, too, and it just worked.

Make sure that the token you use for authentication has read access to the repository.
How do you authenticate?

Where is the `github` variable coming from in your case?

**Comment by gr2m** [comment]
Instead of using `@actions/github`, can you please try https://github.com/octokit/action.js. I cannot help with `@actions/github`. People keep running into trouble with it, I asked for it to be deprecated at https://github.com/actions/toolkit/issues/334 🤷‍♂

**Comment by gr2m** [comment]
I created a debug workflow in my sandbox repository and it just worked, too 🤔 

https://github.com/gr2m/sandbox/runs/534933415?check_suite_focus=true

Workflowfile:

```yml
# Debugging https://github.com/octokit/rest.js/issues/1656
name: PR Debug
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: node debug.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Content of `debug.js`

```js
const { Octokit } = require("@octokit/action");

run();

async function run() {
  const octokit = new Octokit();

  try {
    const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
    workflow_file_name = "debug.yml";
    const { data } = await octokit.request(
      "GET /repos/:owner/:repo/actions/workflows/:workflow_file_name",
      {
        owner,
        repo,
        workflow_file_name
      }
    );
    console.log(data);
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by gr2m** [comment]
So here is something really odd. When I set the `workflow-name` input to `sync-workflows.yml`, then it works:

https://github.com/gr2m/sync-action-workflow-across-org/runs/535009223?check_suite_focus=true#step:2:38

But when I set it to any other name, it fails

https://github.com/gr2m/sync-action-workflow-across-org/runs/535005366?check_suite_focus=true#step:2:38

Note that I created `debug.yml` for testing: https://github.com/gr2m/sync-action-workflow-across-org/blob/ec48c012f4c58cef4eb718fae89de673fc2ae364/.github/workflows/debug.yml

But when I try the same thing on my `gr2m/sandbox` repository, I can load a workflow files other than the current one

https://github.com/gr2m/sandbox/runs/534998557?check_suite_focus=true

I don't know where to go from here. I'm very confused myself ... Maybe you can dig into the requests that return a 404 and find out why they return a 404?

**Comment by gr2m** [comment]
> When attempting to utilize the [get-a-workflow](https://developer.github.com/v3/actions/workflows/#get-a-workflow) endpoint through [octokit](https://octokit.github.io/rest.js/v17#actions-get-workflow), I am having issues using the `:workflow_file_name` version (versus the `workflow_id`)

I want to get back to this one. I realized that there cannot be multiple endpoints defined, because it would cause a conflict in the OpenAPI spec. 

I think what we should do in this case is to rename the URL parameter to `:workflow_id_or_file_name`.

**Comment by IAmHughes** [comment]
@gr2m sorry for the delayed response, I didn't get a chance to play with this more yet. What were the next steps?

**Comment by gr2m** [comment]
It has been discussed last week and the agreement was to rename

```
GET /repos/:owner/:repo/actions/workflows/:workflow_id
```

to

```
GET /repos/:owner/:repo/actions/workflows/:workflow_file_name
```

There are many ID based routes that are currently not documented. But in this case, an entirely ID based route will be mentioned in the description:

```
GET /repositories/:repository_id/actions/workflows/:workflow_id
```

There will be no endpoint method for this one.

**Comment by gr2m** [comment]
The API endpoint has not been changed yet.

This should work as far as I know

```js
octokit.request("GET /repos/:owner/:repo/actions/workflows/:workflow_file_name", {owner, repo, workflow_file_name}) 
```

If it doesn't, I don't think it's an error with Octokit, but the API. 

Let me know if there is anything else I can do on my side, but I won't have time to investigate it further myself

**Comment by mudlabs** [comment]
To get the endpoint data of a given workflow you need to provide either its `id` of its `filename`.
- _`docs`_: https://docs.github.com/rest/reference/actions#get-a-workflow
> I don't _think_ GitHub exposes an environment variable for the workflow id. _(seems stupid to me)_

**Note:** `process.env.GITHUB_WORKFLOW` is the workflows `name`. If the `name` property is _NOT_ set in the workflow, it defaults to the workflows `path`.

If you don't know what the `id` or `filename` is, you can request all workflows and filter out the results for the workflow with the `name` that matches `process.env.GITHUB_WORKFLOW`.

```js
const workflows = await octokit.request("GET /repos/:owner/:repo/actions/workflows", { owner, repo });
/**
console.log(workflows.data);
{
  "total_count": 2,
  "workflows": [
    {
      "id": 2976380,
      "node_id": "MDg6V29ya2Zsb3cyOTc2Mzgw",
      "name": ".github/workflows/temp.yaml",
      "path": ".github/workflows/temp.yaml",
      "state": "active",
      "created_at": "2020-10-13T08:54:48.000Z",
      "updated_at": "2020-10-13T08:56:58.000Z",
      "url": "https://api.github.com/repos/mudlabs/simple-diff/actions/workflows/2976380",
      "html_url": "https://github.com/mudlabs/simple-diff/blob/master/.github/workflows/temp.yaml",
      "badge_url": "https://github.com/mudlabs/simple-diff/workflows/temp.yaml/badge.svg"
    },
    {
      "id": 3011818,
      "node_id": "MDg6V29ya2Zsb3czMDExODE4",
      "name": "Test Diff",
      "path": ".github/workflows/test.yaml",
      "state": "active",
      "created_at": "2020-10-15T07:37:39.000Z",
      "updated_at": "2020-10-17T08:20:52.000Z",
      "url": "https://api.github.com/repos/mudlabs/simple-diff/actions/workflows/3011818",
      "html_url": "https://github.com/mudlabs/simple-diff/blob/master/.github/workflows/test.yaml",
      "badge_url": "https://github.com/mudlabs/simple-diff/workflows/Test%20Diff/badge.svg"
    }
  ]
}
*/
```
