### ISSUE TITLE
For support. Get an access_token with username&password by api?

### ISSUE THREAD

**Issue by lhc-up** [octokit/octokit.js#1658]
Thanks fro the great project!Now I have two problems.
1:May I get auth like this:
`new Octokit({
                username: 'my username',
                password: 'my password'
  });`
2:May I get an access_token just with username and password by the octokit?I have an app,users can login with their account or token,could you please give me an example?Thank you!

**Comment by lhc-up** [comment]
Another problem:
I have a server,when I recieve the request from user,I will use octokit to get github datas.
But how can i auth every user?
Should I 'new Octokit()' when every requst arrive?

**Comment by gr2m** [comment]
You can use [`@octokit/auth-basic`](https://github.com/octokit/auth-basic.js#readme) in order to authenticate with username and password. But note that the APIs are deprecated and will be removed in future. You can use it together with Octokit like this

```js
const { Octokit } = require('@octokit/rest')
const { createBasicAuth } = require('@octokit/auth-basic')

const MyOctokit = Octokit.defaults({
  authStrategy: createBasicAuth
})

const octokit = new MyOctokit({
  auth: {
    username: 'my username',
    password: 'my password',
    async on2Fa() {
      // prompt user for the one-time password retrieved via SMS or authenticator app
      return prompt("Two-factor authentication Code:");
    },
  }
})
```

In order to just get the personal access token, you can use `@octokit/auth-basic` directly, as shown here: https://github.com/octokit/auth-basic.js#usage

```js
const auth = createBasicAuth({
  username: "octocat",
  password: "secret",
  async on2Fa() {
    // prompt user for the one-time password retrieved via SMS or authenticator app
    return prompt("Two-factor authentication Code:");
  },
});

const tokenAuthentication = await auth({ type: "token" });

// tokenAuthentication.token is the token
```

> But how can i auth every user?
> Should I 'new Octokit()' when every requst arrive?

Yeah, that's what I'd do. 

If you want to use an OAuth App instead of asking your users to authenticate using username + password, you can use https://github.com/octokit/oauth-app.js

**Comment by lhc-up** [comment]
@gr2m I get it now.Thank you very much!

**Comment by lhc-up** [comment]
'If the user has two-factor authentication enabled, the on2Fa method will be called and expected to return a time-based one-time password (TOTP) which the user retrieves either via SMS or an authenticator app, based on their account settings'.
The TOTP will returned by the 'on2Fa'?Or just remind this user to check his TOTP somewhere else?
And how can verify the TOTP code?

**Comment by gr2m** [comment]
You must return the TOTP in your own implementation of the `on2FA() {}` function. For example, when using in browsers, you can use [`window.prompt()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt), when using in a CLI, you can use a package such as [prompt](https://www.npmjs.com/package/prompt)

**Comment by gr2m** [comment]
> And how can verify the TOTP code?

You can send a request to verify it, e.g. `octokit.request("GET /user")`. But why do you want to verify it before using it? `@octokit/auth-basic` is taking care of all that for you.

**Comment by lhc-up** [comment]
Thank you very much, I seem to have doubts about this verification process, you let me understand more clear, thank you

**Comment by gr2m** [comment]
Happy to help 👍
