### ISSUE TITLE
[TypeScript] Type definitions of response bodies

### ISSUE THREAD

**Issue by whitphx** [octokit/octokit.js#1661]
Hello.
Until v16, this package had exposed types such as `IssuesGetResponse`, which is a response body of `octokit.issues.get()`, so that it could be used like below:
```typescript
import { Octokit } from '@octokit/rest';

...

const octokit = new Octokit({...});

const result = octokit.issues.get({...});
const issue: Octokit.IssuesGetResponse = result.data;
```

However, v17 does not export such types.

Have they been removed from public?
Are there any alternative exports?
If not, is it possible to export them again?

**Comment by gr2m** [comment]
duplicate of https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/47, could you follow that issue please? There are some workarounds mentioned in the thread, too.

I'm planning on working on this issue this week

**Comment by whitphx** [comment]
Oh, thank you very much 😃
