### ISSUE TITLE
bug? octokit.teams.listReposInOrg does not return topics

### ISSUE THREAD

**Issue by Lnk2past** [octokit/octokit.js#1662]
Not sure if this is a bug or not, so I apologize if it isn't!

The repo information returned by `octokit.teams.listReposInOrg` does not include the topics information, even though the linked documentation includes it: https://developer.github.com/v3/teams/#list-team-repos. I saw issue #1165 and tried to activate the preview, but this still did not work (this preview option is also not specifically mentioned in the v3/teams docs).

I am able to use `octokit.repos.listForOrg` with the preview to get the topics, but the former method mentioned does not seem to work. I can use this for a workaround, but it would be much better for my use case to just get the repos of a particular team (with the topics) from the get-go.

**Comment by gr2m** [comment]
I'm fairly sure that this is a problem with the REST API, not `@octokit/rest`. Could you do me a favor and report this issue to support: https://support.github.com/contact – they will be in a better position to investigate. If you could try a `curl` request first and share the curl requests with support, that'd be helpful. You can reference this issue.

If things are too busy right now, I can reach out to support myself, just let me know

**Comment by Lnk2past** [comment]
Thanks @gr2m , I will do that and report back here.

**Comment by Lnk2past** [comment]
I submitted a report to GitHub with some sample curl output. The output from curl also does not include the topics, and so it does seem to be an issue with the API and not `@octokit/rest`. If you want to close this then by all means; once I get a response from GitHub support I will provide an update. Thanks again!

**Comment by gr2m** [comment]
Thanks a lot!
