### ISSUE TITLE
Mismatch return type and options type

### ISSUE THREAD

**Issue by aorinevo** [octokit/octokit.js#1670]
## Context

In testing one of the pagination examples in the v17 docs, came across a typescript error.  I think this is a mismatch of return type and option type.  

### Specs
- Node v12.x
- @octokit/rest v17.2.0
- typescript v3.8.3

### Example 

See https://octokit.github.io/rest.js/v17#pagination.
```javascript
const options = octokit.issues.listForRepo.endpoint.merge({
    owner: 'octokit',
    repo: 'rest.js'
})
octokit.paginate(options)
    .then(issues => {
      // issues is an array of all issue objects
})
```

### TypeScript Error

```
No overload matches this call.
  Overload 1 of 6, '(options: EndpointOptions): Promise<PaginationResults<unknown>>', gave the following error.
    Argument of type 'EndpointDefaults' is not assignable to parameter of type 'EndpointOptions'.
      Type 'EndpointDefaults' is not assignable to type '{ method: RequestMethod; url: string; }'.
        Types of property 'url' are incompatible.
          Type 'string | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 6, '(route: string): Promise<PaginationResults<unknown>>', gave the following error.
    Argument of type 'EndpointDefaults' is not assignable to parameter of type 'string'.ts(2769)
```

### Summary
`octokit.issues.listForRepo.endpoint.merge` return type is EndpointDefaults while `octokit.paginate(options)` accepts options of type EndpointOptions.  

Any idea why this is happening?

**Comment by gr2m** [comment]
EndpointOptions is the type that is returned by `endpoint.merge()`. It is not guaranteed to have `method` and `url` set, but both are required for `octokit.paginate()`.

But in the case of the `.endpoint` key set on the REST endpoint methods such as `octokit.issues.listForRepo.endpoint`, both `method` and `url` are defaulted already, so ideally we would override the return type of `octokit.issues.listForRepo.endpoint()` and `octokit.issues.listForRepo.endpoint.merge()` to be `EndpointDefaults`. This would need to happen in https://github.com/octokit/plugin-rest-endpoint-methods.js/. Would you like to give that a try? I'll definitely look into it, but not sure when.

For the time being you should be able to do this

```ts
import { EndpointDefaults } from '@octokit/types'
const options = octokit.issues.listForRepo.endpoint.merge({
    owner: 'octokit',
    repo: 'rest.js'
}) as EndpointDefaults
```

**Comment by aorinevo** [comment]
Happy to give it a try @gr2m.

**Comment by aorinevo** [comment]
`octokit.issues.listForRepo.endpoint.merge` return type is EndpointDefaults.  To get to a working state, users can type cast the return to EndpointOptions.   Taking this into account, the code would look something like this:

```javascript
import { EndpointOptions } from '@octokit/types'
const options = octokit.issues.listForRepo.endpoint.merge({
    owner: 'octokit',
    repo: 'rest.js'
}) as EndpointOptions
octokit.paginate(options) // paginate method requires options to be of type EndpointOptions
    .then(issues => {
      // issues is an array of all issue objects
})
```

Also, confirming that the suggested workaround works with the changes described in this comment.  

Thanks again @gr2m!
