### ISSUE TITLE
Documentation of plugins mismatches expectations

### ISSUE THREAD

**Issue by brianjmiller** [octokit/octokit.js#1674]
In most places in the docs it appears the `.plugin` method was expecting to receive the export from a library as a function directly but this syntax doesn't seem to work anymore. For example:

![image](https://user-images.githubusercontent.com/95960/79593180-b2234500-80a0-11ea-9e18-35d72f94e0ae.png)

But it appears that when requiring a plugin it is wrapped in an object and passing that directly to `.plugin` will work but then causes a failure when you attempt to instantiate the returned object. Perhaps it is from a change in those underlying libraries, but given they are the ones given as examples and probably the most useful probably these docs should be updated.

For instance this code:

```
const { Octokit } = require("@octokit/rest"),
    MyOctokit = Octokit.plugin(require("@octokit/plugin-throttling")),
    octokit = new MyOctokit();
```

Results in:

> TypeError: plugin is not a function

Which is from https://github.com/octokit/core.js/blob/master/src/index.ts#L168 I believe. It looks like one section of the docs was updated, specifically the "Usage" section, see

![image](https://user-images.githubusercontent.com/95960/79593839-a97f3e80-80a1-11ea-8064-1cc921d0e4a9.png)

In any case, took me a while to figure out the issue, even if they aren't updated maybe it'll help someone else with the same problem.

**Comment by gr2m** [comment]
We updated all the modules to have named exports such as `{ throttling }` as part of our migration to TypeScript and ESM exports. 

Where did you see `Octokit.plugin(require("@octokit/plugin-throttling"))`?

**Comment by brianjmiller** [comment]
Having re-looked these are the main two:

https://octokit.github.io/rest.js/v17#throttling
https://octokit.github.io/rest.js/v17#automatic-retries

I thought there were others, but maybe I just had too many tabs open. It might be worth showing it in https://octokit.github.io/rest.js/v17#plugins but presumably it depends on the plugin implementation so it depends on your intent.
