### ISSUE TITLE
Docs: search is no longer working

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#1678]
follow up https://github.com/octokit/rest.js/issues/1329

**Comment by gr2m** [comment]
The search is working locally using indexdDB. My idea was originally to make the website work offline some day. I'm not married to the idea, I think something like https://docsearch.algolia.com/ might be a better user experience, but for that I'd change the structure of the documentation website first, have multiple pages instead of a single one.

So for now, I'd just try to fix the search as it worked before. It is hopefully just a quick fix

**Comment by copperwall** [comment]
I believe the search stopped working around the v17 changes. It looks like before that the `gatsby-source-octokit-routes` plugin was used to create `OctokitApiMethod` and `OctokitApiGroup` nodes in the schema in its [gatsby-node.js](https://github.com/octokit/rest.js/blob/37d316c692aca70ebd95447ae14d6196cdbe34d1/docs/plugins/gatsby-source-octokit-routes/gatsby-node.js) and the elasticlunr plugin index is built expecting those nodes to be there in the current [gatsby-config.js](https://github.com/octokit/rest.js/blob/master/docs/gatsby-config.js#L80).

It looks like now the group and endpoint docs are getting sourced from the  https://github.com/octokit/plugin-rest-endpoint-methods.js repo, so I think we can fix it by updating the elasticlunr config to build the index based on the new markdown content. I'll give that a try.

**Comment by gr2m** [comment]
Thanks, sound good 👍 And yes, it definitely broke around the v17 update
