### ISSUE TITLE
repos.listPublicRepos has extra, invalid params

### ISSUE THREAD

**Issue by SpencerKaiser** [octokit/octokit.js#1684]
The docs for the `repos.listPublicRepos` method suggest `per_page` and `page` are valid parameters, however, the [API docs](https://developer.github.com/v3/repos/#list-public-repositories) have no mention of those parameters and the API doesn't seem to respect them if they're included.

**Comment by gr2m** [comment]
These are pagination parameters: https://developer.github.com/v3/#pagination

**Comment by gr2m** [comment]
> the API doesn't seem to respect them if they're included

Sorry, I missed the 2nd part of your issue. You are right:

```
$ curl "https://api.github.com/repositories?per_page=1" | jq length
100
```

I'll investigate

**Comment by SpencerKaiser** [comment]
@gr2m maybe it's an older version of the API that supported that? I imagine the given the purpose of that endpoint, they might have removed that to make it more optimized; who would want many smaller requests if the payload is small anyways?

**Comment by gr2m** [comment]
Looks like it's an exception that only supports `?since`

> Pagination is powered exclusively by the `since` parameter. Use the [Link header](https://developer.github.com/v3/#link-header) to get the URL for the next page of repositories.

I'll find out if there are more endpoints such as this one. This needs to be fixed in https://github.com/octokit/routes/

**Comment by gr2m** [comment]
I'm tracking the issue here: https://github.com/octokit/routes/issues/700

**Comment by SpencerKaiser** [comment]
Awesome! Feel free to close this one then 🙂
