### ISSUE TITLE
Authorized with repo scope 👍 404 when attempting to create issue 😱

### ISSUE THREAD

**Issue by eliorivero** [octokit/octokit.js#1687]
Hi, first of all thanks for the amazing library, is really good. I'm having an issue with a GitHub OAuth app that creates GH issues.

I'm correctly authorized with `repo` scope and I can successfully do stuff like `users.getAuthenticated()` or `repos.list()`.

The issue occurs with `issues.create( issue )`. While it works fine in repos I own, it doesn't in these cases:
- a repo I don't own but I'm a collaborator with push/commit access
- someone else in a repo they own (I asked a friend to try it in a repo they own)
- someone else that owns an organization, in a repo of that org (asked another friend to test)

In these cases the user is authorized, `users.getAuthenticated()` and `repos.list()` still work, but the `issues.create( issue )` ends up in a 404. I tried adding more scopes but no luck. What could be happening here?

**Comment by gr2m** [comment]
Sometimes a GitHub OAuth App needs to be granted access to organizations that you don't have admin rights to, might that be the problem, maybe? You can check the list of OAuth apps you authorized here: https://github.com/settings/applications. Open the one for your OAuth app and see if the organization you try to create an issue in is listed in the `Organization access` section, and if an `requset` or `grant` button is shown next to it

**Comment by eliorivero** [comment]
Hi, thanks for the response!

Everything looks fine there, nothing to request or grant. The line where I'm trying to create the issues is this one
https://github.com/eliorivero/fast-issues/blob/master/index.js#L103
The rest works fine, and as mentioned, if I check the repos or authenticated data one line before, it works. The data passed to create the issues is valid as well.

**Comment by gr2m** [comment]
There is a lot going on in your app. Could you please try to create a reduced test case, ideally just a script that creates an issue using a test org and a test account?

**Comment by eliorivero** [comment]
Thanks for the response! I solved it: I was erroneously sending the current user instead of the owner of the repo where I wanted to create an issue.
