### ISSUE TITLE
Build issue with Angular 9

### ISSUE THREAD

**Issue by saikris12** [octokit/octokit.js#1688]
I am trying to add this in my angular 9 project. I installed the package using npm and tried building using ng build and below is the error I get: 

`ERROR in node_modules/@octokit/types/src/RequestRequestOptions.ts:1:23 - error TS2307: Cannot find module 'http'.

1 import { Agent } from "http";`

nodeVersion: v13.12.0
npmVersion: 6.14.4
"@octokit/rest": "^17.5.2",

**Comment by saikris12** [comment]
This was an issue with how module resolving is set up in angular with npm. Since the http module referred by octokit/restjs is a core node module, I had to add the below to my tsconfig.json file. For anyone facing the same issue with angular, add this to the **tsconfig.json** file : 

`"paths": {
      "http": ["node_modules/@types/node"]
    },`

**Comment by gr2m** [comment]
Thank you for sharing your workaround Sai!

I wonder if this is an angular-specific or if it is relevant to everyone who has a build setup for browser-based apps? I only had reports of that problem by Angular developers in the past, so I assume other frameworks/bundlers seem to handle it out-of-the-box?

**Comment by saikris12** [comment]
This is an angular specific issue and happens because of the way module resolution works in angular set up with npm. Any core node modules being used (in this case http module) must be explicitly declared in the tsconfig.json for the ng build to resolve during the compile.
