### ISSUE TITLE
Encoding issue when trying to parse YAML file from GitHub

### ISSUE THREAD

**Issue by LukeXF** [octokit/octokit.js#1689]
When I load a markdown file from GitHub I am running into a lot of errors. I think I am not using the right encoding for GitHub files through Octokit. Any suggestions on how to fix my Buffer code in Node.js? 

Is base64 and then to ascii correct for Github content? It works fine when loading it directly in my project without GitHub. I have a feeling GitHub stores their files in a different format but can't find docs on it.

```javascript
const repos = await octokit.repos.getContents({
	owner: 'owner-hidden',
	repo: 'repo-hidden',
	path: '/dinner.md'
});

// repo loads with data.content just fine
const bufferedData = Buffer.from(repos.data.content, 'base64').toString('ascii');
const ymlData = YAML.parse(bufferedData); // issue with reading this
```

The error is below, but the error doesn't necessarily matter because it works when I load it directly in my project there are no errors.

```javascript
YAMLException: the stream contains non-printable characters at line 36, column 126:
       ... auteLed spinach and ratatouille
                                           ^
```

Loading the markdown file directly in my project there was no errors:

```javascript
const fs = require('fs');
const path2 = require('path');
const file = path2.resolve(__dirname, '/dinner.md');
const content = fs.readFileSync(file);

const bufferedData = Buffer.from(content).toString('ascii');
console.log({bufferedData});
```

**Comment by gr2m** [comment]
> const bufferedData = Buffer.from(repos.data.content, 'base64').toString('ascii')

try to remove the `'ascii'` parameter:

```diff
- const bufferedData = Buffer.from(repos.data.content, 'base64').toString('ascii')
+ const bufferedData = Buffer.from(repos.data.content, 'base64').toString()
```

[`buffer.toString()`](https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end) defaults to `utf8` which is what you want

**Comment by LukeXF** [comment]
Massive thank you @gr2m, it's now 100% working. Really appreciate your help!
