### ISSUE TITLE
Is there any endpoint or way to get the contribution activity graph data for specific user?

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#1699]

**Comment by gr2m** [comment]
Is this endpoint what you are looking for?

https://developer.github.com/v3/activity/events/#list-public-events-for-a-user

Example

https://api.github.com/users/gr2m/events/public

Code

```js
octokit.activity.listPublicEventsForUser({
  username: 'gr2m'
});
```

**Comment by ghost** [comment]
I have checked this, the response is filled with necessary data as well as the links to repos or issues are API endpoints instead of GitHub URL. Also, with the cap of a maximum of 100 events per page, it is very difficult to make API calls for a year contribution and then parse it for filtering out the necessary data.

**Comment by gr2m** [comment]
> Also, with the cap of a maximum of 100 events per page, it is very difficult to make API calls for a year contribution and then parse it for filtering out the necessary data

you can paginate the results, try this

```js
const iterator = octokit.paginate.iterator(octokit.activity.listPublicEventsForUser, {
  username: 'gr2m'
});

for await (const response of iterator) {
  // handle response
}
```

As you might end up doing tons of requests, I'd recommend to use https://github.com/octokit/plugin-throttling.js/. It will help avoid hitting rate/abuse limits

**Comment by ghost** [comment]
Okay, I will give it a try. Thank you so much.

**Comment by gr2m** [comment]
Let me know if that worked for you :)

**Comment by ghost** [comment]
Working.
