### ISSUE TITLE
get a "personal access token" or "GITHUB_TOKEN" for beeing able to run "npm install" or "npm publish"

### ISSUE THREAD

**Issue by divramod** [octokit/octokit.js#1703]
hey,

we wrote a github app which acts as a ci-server.
now we want to use the new github packages functionality in our pipelines.
for beeing able to publish or install a npm package from our private github package repository, we need a ["personal access token"](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) or a [GITHUB_TOKEN.](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token).

we do like to create the "personal access token" or "GITHUB_TOKEN" programatically.
the best thing would be if we could create a new token every time we need to pull/install the npm package.

so my questions are: 
1. is it possible to create a "personal access token" with octokit/rest.js (which rights do we need to set for the app?)
2. is it possible to create a GITHUB_TOKEN with  octokit/rest.js (which rights do we need to set for the app?)
3. do you think creating the token programatically is the right approach or is the a better approach to use the github npm package registry from a pipeline run?

thx for writing octokit and thx in advance for pointing me into the right direction!

**Comment by gr2m** [comment]
There is currently no way to retrieve an OAuth Access token which you would need to publish a package to GitHubs registry. A GitHub App Installation token cannot be used as far as I know, it must be a token bound to a user account (OAuth Access Token).

For the OAuth part, I recently created a separate library will help you with that: [`@octokit/oauth-app`](https://github.com/octokit/oauth-app.js)

When creating a new GitHub App, a new "" option has been introduced which sounds exactly like what you need:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/39992/81351387-0eaeca00-9079-11ea-893e-102e896d8c56.png">

I have not tested it myself yet so I cannot tell how it works, and if it will work with [`@octokit/oauth-app`](https://github.com/octokit/oauth-app.js). I think it should, as long as you configure "User authorization callback URL" accordingly. 

Another new recent feature might be useful to you, too: https://developer.github.com/changes/2020-04-30-expiring-user-to-server-access-tokens-for-github-apps/. OAuth Access Tokens can now be required to be refreshed. It's a beta that you have to enable for your app though, [`@octokit/oauth-app`](https://github.com/octokit/oauth-app.js) does not implement the refresh feature at this point

Hope that helps?

**Comment by steve-norman-rft** [comment]
I'm not sure if packages are accessible using the user-to-server requests feature of a GitHub App.  

I have found there are a few things that you can't do in when using the user workflow, the list of available actions is available at https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/#user-to-server-requests.
