### ISSUE TITLE
getCommit API missing files and stats fields in response

### ISSUE THREAD

**Issue by shaunwarman** [octokit/octokit.js#1705]
**Checklist**

- [X] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [X] GitHub Enterprise Server: `2.18.16`
- [ ] GitHub Enterprise Cloud
- [X] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
$ npm ls | grep -v deduped | grep octokit
├─┬ @octokit/rest@17.8.0
│ ├─┬ @octokit/core@2.5.0
│ │ ├─┬ @octokit/auth-token@2.4.0
│ │ ├─┬ @octokit/graphql@4.3.1
│ │ ├─┬ @octokit/request@5.4.2
│ │ │ ├─┬ @octokit/endpoint@6.0.1
│ │ │ ├─┬ @octokit/request-error@2.0.0
│ │ ├─┬ @octokit/types@2.14.0
│ ├─┬ @octokit/plugin-paginate-rest@2.2.0
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@3.10.0
```

**What happened?**

Expected the `getCommit` api to return files in the response. Similar to the response shown in github api [here](https://developer.github.com/v3/repos/commits/#get-a-single-commit). For some reason, the files and stats properties are missing in octokit response.

```
const  response = await octokit.git.getCommit({
  owner: org,
  repo: repo,
  commit_sha: commit
});
console.log(response);
```

**What did you expect to happen?**

I expected to see the files listed in the response similar to the example response shown in the [github commit api](https://developer.github.com/v3/repos/commits/#get-a-single-commit).

```
"stats": {
    "additions": 104,
    "deletions": 4,
    "total": 108
  },
  "files": [
    {
      "filename": "file1.txt",
      "additions": 10,
      "deletions": 2,
      "changes": 12,
      "status": "modified",
      "raw_url": "https://github.com/octocat/Hello-World/raw/7ca483543807a51b6079e54ac4cc392bc29ae284/file1.txt",
      "blob_url": "https://github.com/octocat/Hello-World/blob/7ca483543807a51b6079e54ac4cc392bc29ae284/file1.txt",
      "patch": "@@ -29,7 +29,7 @@\n....."
    }
  ]
```

**Comment by shaunwarman** [comment]
Ah my apologies. It looks like `octokit.git.getCommit` vs. `octokit.repo.getCommit`. They both point to the same github API documentation.

**Comment by gr2m** [comment]
Could you please explain what you mean with "they both point to the same github API documentation"?

**Comment by shaunwarman** [comment]
My first thought was to just navigate to https://octokit.github.io/rest.js/v17/ and `ctrl + f` _commit_ or _getCommit_. Although https://developer.github.com/v3/repos/commits/#get-a-single-commit and https://developer.github.com/v3/git/commits/#get-a-commit are different it looks very similar. Just some noob confusion.
