### ISSUE TITLE
createOrUpdateRepoSecret params differ from docs

### ISSUE THREAD

**Issue by chrissloey** [octokit/octokit.js#1715]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js v12.8.0
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├─┬ @octokit/rest@17.9.1
│ ├─┬ @octokit/core@2.5.0
│ │ ├─┬ @octokit/auth-token@2.4.0
│ │ ├─┬ @octokit/graphql@4.4.0
│ │ ├─┬ @octokit/request@5.4.2
│ │ │ ├─┬ @octokit/endpoint@6.0.1
│ │ │ ├─┬ @octokit/request-error@2.0.0
│ │ ├─┬ @octokit/types@2.16.2
│ ├─┬ @octokit/plugin-paginate-rest@2.2.0
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@3.12.0
│   ├─┬ @octokit/types@4.0.0
│ ├─┬ @octokit/rest@17.9.0
│ │ └─┬ @octokit/plugin-rest-endpoint-methods@3.11.0
```

**What happened?**

`octokit.actions.createOrUpdateSecretForRepo` stopped working, I got an error `HttpError: Not Found` and some warnings about the function name changing to `createOrUpdateRepoSecret`. The error remained after updating to the new function. After investigating, the param `name` changed to `secret_name` and the 404 was because `secret_name` is at the end of the generated URL.

The [docs](https://octokit.github.io/rest.js/v17) don't reflect the updated param so opening this in case someone else runs into this problem.

**Minimal test case to reproduce the problem**

https://runkit.com/gr2m/octokit-rest-js-1715/1.0.0

**What did you expect to happen?**

Code not to break when going from 17.7 to 17.9.1

**What the problem might be**

`name` param was changed to `secret_name`

**Comment by gr2m** [comment]
> After investigating, the param name changed to secret_name and the 404 was because secret_name is at the end of the generated URL

Yes, the `:name` URL parameter was changed to `:secret_name`, but using `name` should continue to work, and a deprecation message should have been logged. I'll investigate what went wrong

**Comment by gr2m** [comment]
I was able to reproduce the problem, I've added the test case to your original issue.

Thanks for reporting the problem 👍

**Comment by gr2m** [comment]
This should be resolved shortly via https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/87.

What happened is that I commented out the code for handling of deprecated parameters, because there were no deprecated parameters in the current version. And of course I forgot to re-enable the handling of deprecated parameters once we deprecate a parameter name 🤦 sorry for that
