### ISSUE TITLE
getSelfHostedRunner status is always online never active

### ISSUE THREAD

**Issue by DavidGOrtega** [octokit/octokit.js#1738]
**Checklist**

- [X] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [X] Node.js

**Versions**

```
│ ├─┬ @octokit/graphql@4.5.0
│ │ ├─┬ @octokit/request@5.4.4
│ │ │ ├─┬ @octokit/endpoint@6.0.2
│ │ │ ├─┬ @octokit/request-error@2.0.1
│ │ ├─┬ @octokit/types@4.0.2
│ └─┬ @octokit/rest@16.43.1
│   ├─┬ @octokit/auth-token@2.4.1
│   ├─┬ @octokit/plugin-paginate-rest@1.1.2
│   │ └─┬ @octokit/types@2.16.2
│   ├── @octokit/plugin-request-log@1.0.0
│   ├─┬ @octokit/plugin-rest-endpoint-methods@2.4.0
│   │ ├─┬ @octokit/types@2.16.2
│   ├─┬ @octokit/request-error@1.2.1
│   │ ├─┬ @octokit/types@2.16.2
│   ├── octokit-pagination-methods@1.1.0
├── octokit@1.0.0-hello-world
```

**What happened?**

status is always online, it does not reflect if its idle or active.

**Minimal test case to reproduce the problem**

```js
let { data } = await octokit.actions.getSelfHostedRunner({
    owner,
    repo,
    runner_id
});
```

**What did you expect to happen?**

Its not returning the runner status, or at least not the one I would expect.

**Comment by gr2m** [comment]
Could you try to reproduce the problem with `curl` to see if it lies with Octokit, or the problem lies somewhere else?

Could you please try to upgrade to the latest `@octokit/rest` version is see if the problem persists?

**Comment by DavidGOrtega** [comment]
Im at the latest 2.2.0 @actions/github is there any other way to install it?

**Comment by gr2m** [comment]
I have no control over `@actions/github`. Could you please use `@octokit/action` instead?
https://github.com/octokit/action.js#readme

See also https://github.com/actions/toolkit/issues/334

**Comment by DavidGOrtega** [comment]
o_0 are both from github?

**Comment by gr2m** [comment]
Yes. I do maintain all the `@octokit/*` libraries. `@actions/github` is a thin layer on top of `@octokit/rest`, and it's not kept up-to-date, but the team is looking into it. For the time being, I recommend to use `@octokit/action`

**Comment by DavidGOrtega** [comment]
Sorry for the late reply, I will try,.

Looking at the [API docs](https://developer.github.com/v3/actions/self-hosted-runners/#get-a-self-hosted-runner-for-a-repository) looks like status can be online but does not state what other status can be.

**Comment by gr2m** [comment]
some of the responses also show `"offline"` as possible value, e.g. https://developer.github.com/v3/actions/self-hosted-runners/#response-2
