### ISSUE TITLE
Error thrown for a not-found user (404) should have more details

### ISSUE THREAD

**Issue by kevindigo** [octokit/octokit.js#1757]
**What’s missing?**
Currently, if you make a call to get the public events for a user that does not exist, a very generic Error is thrown. Here is the octokit log output for the call we're making:
`INFO 2020-06-09T21:54:02.320Z [dist/globals.js] GET /users/Xxxxxxxxx/events/public - 404 in 474ms`
But here is the message for the Error that is thrown:
`HttpError: Not Found`

The thrown error should give enough details for the consumer to be able to debug the problem, without having to resort to reading logs. A simple solution would be to return the URL that failed, so:
`HttpError: Not Found: /users/Xxxxxxxxx/events/public`

We figured we could catch the generic Error, figure out which username caused the problem, and construct a new, more detailed Error to throw. However, due to the structure of our code, this is somewhat difficult.

**Comment by gr2m** [comment]
We set the `error.request` property on errors, which should have all the necessary information about the request that caused the http error. Does that work for you?

We cannot create custom errors for all possible requests, it would greatly increase the bundle size of the library. But it could be implemented in a plugin for re-usability, see https://octokit.github.io/rest.js/v17/#plugins

**Comment by kevindigo** [comment]
Thanks for the reply! That sounds like exactly what we want. Can you point me to docs (or code) that describe the contents of the request member? In the case where I'm trying to use it, it seems that err.request is undefined.

**Comment by gr2m** [comment]
Sorry Kevin that I never got back to you!

The API looks like this:

```js
octokit.hook.error("request", async (error, options) => {
  // check options here. You can change the `error` object to add more helpful details before re-throwing it
});
```

The `options` object is the same as it's described here: 
https://github.com/octokit/request.js/tree/2c5ce4fb087601a7a186bfd8d37f406415fb4cf1#request

The full code would look something like this

```js
octokit.hook.error("request", async (error, options) => {
  if (options.url === "/users/{username}") {
    error.message = `User ${options.username} does not exist`
  }

  throw error
});
```

Note that this would only work if you use `octokit.users.getByUsername({ username })` or `octokit.request("GET /users/{username}", { username })`. If someone would e.g. do `octokit.request("GET /users/bli-bla-blop")` then `options.url` will be set to `"/users/bli-bla-blop"`, not `"/users/{username}"`

**Comment by kevindigo** [comment]
Thanks for the additional information. If I'm understanding correctly, we can't just look at the thrown error. We instead need to invoke octokit.hook.error in advance, in order to set things up? Is the hooking process documented anywhere?

**Comment by gr2m** [comment]
Hooks are documented here: https://octokit.github.io/rest.js/v18#hooks

I would create a plugin, see documentation at https://octokit.github.io/rest.js/v18#plugins
