### ISSUE TITLE
Documentation: Broken link to `client-options`

### ISSUE THREAD

**Issue by jyasskin** [octokit/octokit.js#1773]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**What happened?**

https://octokit.github.io/rest.js/v18#logging (https://github.com/octokit/rest.js/blob/master/docs/src/pages/api/11_logging.md) has

> They can be configured using the [log client option](https://octokit.github.io/rest.js/client-options), but that returns a 404, and there's no other mention of `client-options` in the source.

**Comment by gr2m** [comment]
Thanks  Jeffrey for open the issue. Would you like to send a pull request yourself? I'm happy to assist if you have any questions, or do it myself, if you prefer.

In this case, I would remove the link altogether
