### ISSUE TITLE
Octokit.AppsListReposResponse type is incorrect

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [octokit/octokit.js#1780]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [x] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

16.43.1

**What happened?**

Currently the type of `listRepos` is `Octokit.AppsListReposResponse`. `Octokit.AppsListReposResponse` is of the type

```
type AppsListReposResponse = {
  repositories: Array<AppsListReposResponseRepositoriesItem>;
  total_count: number;
};
```
which seems to be wrong because the endpoint when used together with `paginate` returns an array of repositories.

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

**What the problem might be**

https://github.com/octokit/rest.js/blob/16.x/index.d.ts#L21651

**Comment by SayakMukhopadhyay** [comment]
I was rereading the docs at https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-app-installation and I noticed that the example out has 2 root keys which lines up with the current implementation. This is very difference from say the example output for a list of all installations which is just an array. I am not sure if these different type of responses is causing issues.

**Comment by gr2m** [comment]
The type is correct. The paginate plugin normalizes endpoints that do not return an array at its root. Unfortunately GitHub's REST API endpoints are not very consistent when it comes to pagination

**Comment by SayakMukhopadhyay** [comment]
🙁 Is it possible to get the `AppsListReposResponseRepositoriesItem` type itself in my project? As far as I can see, since the types are not explicitly exported, I won't be able to use them in my code. But maybe I am missing something??

**Comment by gr2m** [comment]
The most reliable way to get the types for parameters and responses is by the `Endpoints` export from `@octokit/types`: https://github.com/octokit/types.ts/#get-parameter-and-response-data-types-for-a-rest-api-endpoint

In this case, this should work

```ts
import { Endpoints } from "@endpoint/types";
type AppsListReposResponseRepositoriesItem = Endpoints["GET /installation/repositories"]["response"]["data"]["repositories"][0]
```

I'm looking into bringing the named export types back, but it's rather complicated and I've been given other priorities. The biggest problem with the named exports is that the names keep changing, and I expect more changes over the next 3 months until GitHub will finish a thorough audit. And TypeScript has not a good deprecation story for these types.

Deriving the types you want from the REST API routes is much more resilient.

**Comment by SayakMukhopadhyay** [comment]
Thanks for the explanation! I am anyway keeping aliasing my own type definitions so I will use this method.
