### ISSUE TITLE
Instantiating Octokit on Windows 10 calls spawnSync

### ISSUE THREAD

**Issue by joaomoreno** [octokit/octokit.js#1781]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [x] Others: Electron

**Versions**

```
    "@octokit/rest": "^17.9.1",
```

**What happened?**

Octokit tries to figure out a good user agent to use, but when doing this on Windows 10, it happens to spawn sync at least one process:

https://github.com/sindresorhus/windows-release/blob/138a34491420ccab83cf67e31a3e11019c92ae37/index.js#L37

This is problematic since it blocks the entire process and can cause performance issues, such as https://github.com/microsoft/vscode/issues/98931

This occurs despite passing `userAgent` to the Octokit constructor:

https://github.com/octokit/core.js/blob/358f7528b89071697db8cce790fcae9e9714e971/src/index.ts#L89

**Minimal test case to reproduce the problem**

```
new Octokit()
```

**What did you expect to happen?**

No spawn sync.

---
It would at least be beneficial to have an option to bypass this behavior.

**Comment by gr2m** [comment]
It's something I need to fix in https://github.com/gr2m/universal-user-agent. 

Do you need the OS information? I'm strongly considering to remove it via https://github.com/gr2m/universal-user-agent/issues/52

**Comment by gr2m** [comment]
> This occurs despite passing userAgent to the Octokit constructor:

The userAgent is additive.

**Comment by joaomoreno** [comment]
We don't really need the OS information.

**Comment by joaomoreno** [comment]
@gr2m Any update on this, it's really causing a bit of harm.

We'd love at least an option to prevent the code from being run at all, given that a `userAgent` is passed along with the options.

**Comment by gr2m** [comment]
I'll try to have a look at it today

**Comment by gr2m** [comment]
still need to update to latest `universal-user-agent` in Octokit, @dependabot will take care of it tonight across the @octokit org

**Comment by joaomoreno** [comment]
@gr2m Here at VS Code we really appreciate the speediness! Thanks! 🙏 

Btw impressive actions pipeline, it seems everything is fully automated.

**Comment by gr2m** [comment]
I love my little bot babies 🤖💛 

The problem should be resolved via [`@octokit/core` v3.1.1](https://github.com/octokit/core.js/releases/tag/v3.1.1). Make sure to update your dependency tree
