### ISSUE TITLE
Error: Cannot find module '@octokit/rest' or its corresponding type declarations.

### ISSUE THREAD

**Issue by swyxio** [octokit/octokit.js#1790]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- Node.js 12.18

**Versions**

```
├─┬ @octokit/rest@18.0.0
│ ├─┬ @octokit/core@3.1.0
│ │ ├─┬ @octokit/auth-token@2.4.2
│ │ ├─┬ @octokit/graphql@4.5.1
│ │ ├─┬ @octokit/request@5.4.5
│ │ │ ├─┬ @octokit/endpoint@6.0.3
│ │ │ ├─┬ @octokit/request-error@2.0.2
│ │ ├─┬ @octokit/types@5.0.1
│ ├─┬ @octokit/plugin-paginate-rest@2.2.3
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.0.0
```

**What happened?**

the types are missing or not discoverable by typescript (v3.9.6)

![image](https://user-images.githubusercontent.com/6764957/87086636-70033d00-c264-11ea-9855-7150a2528ade.png)

**Minimal test case to reproduce the problem**

https://github.com/sw-yx/sw-yx/blob/f6a2a5f7b0f654384c402645217896cd8573247c/scrape.ts#L1

**What did you expect to happen?**

the types should just work

**What the problem might be**

i'm honestly not sure. the @octokit/rest package.json file points `types` accordingly to `"dist-types/index.d.ts"` and the file is there so i dont know why this doesnt work but it doesn't :(

**Comment by gr2m** [comment]
Hey Shawn 👋 

I haven't seen that problem being reported before, very odd! 

Could you share what you are trying to build?

For testing purposes, could you try to install [`@octokit/core`](https://github.com/octokit/core.js) instead of `@octokit/rest`? The difference is that `@octokit.rest` has all the named methods for the endpoints, while with core you need to use the lower level [`octokit.request` method](https://github.com/octokit/core.js#rest-api-example). 

But I just want to see if you see the TypeScript error with `@octokit/core`, too.

Meanwhile, I'll try to reproduce your error

**Comment by gr2m** [comment]
I was not able to reproduce the problem in latest VS Code

<img width="911" alt="image" src="https://user-images.githubusercontent.com/39992/87089250-ff6c0a00-c1ea-11ea-8f1c-da0f4c7df66f.png">

**Comment by swyxio** [comment]
testing with octokit/core 3.1.0

it doesnt error if i use `require`, but it still infers `any` meaning it cant find types

![image](https://user-images.githubusercontent.com/6764957/87184025-d39b7200-c319-11ea-8e4f-dcdc92fd84a7.png)

switching to import shows the error though:

![image](https://user-images.githubusercontent.com/6764957/87184056-e150f780-c319-11ea-8e71-f9ea28b17ac0.png)

i would class this as non urgent since i have simply abandoned typescript for now... but if others find this issue with v18 then they will find this issue and tag on.

**Comment by gr2m** [comment]
Do you see the error only in your editor, or also if you run tsc? I was not able to reproduce that error myself

**Comment by swyxio** [comment]
yes, i'm afraid so: 
![image](https://user-images.githubusercontent.com/6764957/87185710-d186e280-c31c-11ea-8026-01dd77d0f880.png)

editor is vscode btw. i've tried restarting the TS server and it still persists. could be that its entirely my fault and nothing on your end. if so i'm happy to close it... just very strange behavior.

**Comment by swyxio** [comment]
ok i started a new project and it is fine... so i am starting to suspect it's my tsconfig

![image](https://user-images.githubusercontent.com/6764957/87186106-79041500-c31d-11ea-8742-a5a40e3131d8.png)

**Comment by swyxio** [comment]
yup.. that was it. deleted my tsconfig and the problem was resolved :(

for info my tsconfig was the autogenerated one from `tsc --init`:

```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "es2017",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "esnext",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "tsBuildInfoFile": "./",               /* Specify file to store incremental compilation information */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictBindCallApply": true,           /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,          /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}

```

**Comment by gr2m** [comment]
Thanks Shawn!

**Comment by swyxio** [comment]
thanks for maintaining this nice library :)

**Comment by gr2m** [comment]
You have a different tsc config than me. Do you have a global typescirpt installed that is out-of-date maybe?

See the diff here: https://quickdiff.net/?unique_id=C06C32BA-7DD3-35E1-8112-33DB2DB37DFB

Do you get the same `tsconfig.json` when you run `./node_modules/.bin/tsc --init`?

**Comment by gr2m** [comment]
Changing `"module": "esnext"` to `"module": "commonjs"` fixes the problem for me. But no idea why 🤷

TypeScript is like Git, nobody _really_ understands it

**Comment by swyxio** [comment]
i got the same conclusion as you. i think this miiiight be a typescript bug. reporting to orta

**Comment by swyxio** [comment]
if i set `moduleResolution` to node this problem also goes away while preserving `"module": "esnext"`

**Comment by swyxio** [comment]
i think its a bug. according to this https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies `moduleResolution` should be `node` when `module` is `esnext`

**Comment by swyxio** [comment]
@gr2m fyi, i think its a TS bug :) https://github.com/microsoft/TypeScript-Handbook/pull/1333
