### ISSUE TITLE
octokit.repos.compareCommits always returns 404

### ISSUE THREAD

**Issue by alexr00** [octokit/octokit.js#1808]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

@octokit/rest@18.0.1

**What happened?**

Due to https://github.com/octokit/rest.js/issues/1781, I started upgrading the version of the octokit rest API that the VS Code [GitHub Pull Requests and Issues](https://github.com/microsoft/vscode-pull-request-github) uses. While doing the upgrade, I'm seeing `octokit.repos.compareCommits` always return a 404 error. You can see the usage [here](https://github.com/Microsoft/vscode-pull-request-github/blob/2942852b9895d9a0ecde45018cf5e9a2ac391c6b/src/github/pullRequestManager.ts#L1937-L1937), it hasn't changed during the upgrade.

**Minimal test case to reproduce the problem**

I think this should happen with any `compareCommits` where there are characters that are escaped. The branches I was comparing were `master` and `alexr00/issue#104`

**What did you expect to happen?**

Well, I expect the same behavior of `compareCommits` from eariler (16.21.0) versions.

**What the problem might be**

Debugging a little, I think there's something up with how octokit/rest.js is escaping the url now.
In version 16.21.0, the url for the GET appears to be:
`https://api.github.com/repos/alexr00/playground/compare/alexr00:master...alexr00:alexr00%2Fissue%23104`
In version 18.0.1, the url for the GET appears to be:
`https://api.github.com/repos/alexr00/playground/compare/alexr00%3Amaster...alexr00%3Aalexr00%252Fissue%2523104`

Its certainly still possible that I'm doing something wrong here, but the different urls are suspicious. This does prevent us from upgrading since compare is fundamental to this extension.

**Comment by gr2m** [comment]
Thank you for reporting the issue Alex, I'm looking into it

**Comment by gr2m** [comment]
It looks like the the URL from 18.0.1 is double-encoded. Is it possible that you encode the values for `base`/`head` before passing it to `octokit.repos.compareCommits()`? That is no longer necessary

I created a test case here: it shows that it works with v18 out of the box, while you need to encode the `head`/`base` values before passing them into v16

https://runkit.com/gr2m/octokit-rest-js-1808/1.0.0

I've added an item to the release notes of [v17.0.0](https://github.com/octokit/rest.js/releases/tag/v17.0.0) when the change was introduced

> URL parameters such as `options.base` and `options.head` for `octokit.repos.compareCommits` are now URL encoded automatically, you don't need to use `encodeURIComponent()` before passing the values to the endpoint methods.

**Comment by alexr00** [comment]
@gr2m thanks for investigating. ~~Does your example still work if you format your `base` and `head` options to compare across repos? From the documentation of ``compareCommits`:`~~

>  ~~"To compare branches across other repositories in the same network as `:repo`, use the format `<USERNAME>:branch`."~~

~~I might be double encoding the branch name (`alexr00/issue#104`), but I'm definitely not double encoding the `:` in `<USERNAME>:branch`. Perhaps as part of the new automatic URL encoding that is getting messed up?~~

You are correct, I removed all encoding and it works. Thank you!

**Comment by gr2m** [comment]
Glad to hear it’s working now!
