### ISSUE TITLE
How can I access main stream notifications?

### ISSUE THREAD

**Issue by IonicaBizau** [octokit/octokit.js#181]
How can I get the same output with this library?

``` sh
curl -v -u IonicaBizau:TOKEN https://github.com/IonicaBizau.private.json
```

**Comment by kaizensoze** [comment]
See https://mikedeboer.github.io/node-github/#api-activity-getNotifications

**Comment by IonicaBizau** [comment]
@kaizensoze Is that the same with the private stream (`/<username>.private.json`)?

**Comment by kaizensoze** [comment]
Actually it looks like the equivalent is the events stuff. If you hit https://github.com/kaizensoze.private.json in a browser you'll get:

> {
>     "message": "Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.",
>     "documentation_url": "https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received"
> }

https://developer.github.com/v3/activity/events/#list-events-that-a-user-has-received then shows

> List events that a user has received
> 
> These are events that you've received by watching repos and following users. If you are authenticated as the given user, you will see private events. Otherwise, you'll only see public events.
> 
> GET /users/:username/received_events

The library equivalent is https://mikedeboer.github.io/node-github/#api-activity-getEventsReceived

**Comment by IonicaBizau** [comment]
@kaizensoze Ah, that's really interesting. I guess this happened quite recently. Thanks for the info. ✨
