### ISSUE TITLE
Most of the the API documentation for octokit/rest.js v17 is missing

### ISSUE THREAD

**Issue by iliasbibas** [octokit/octokit.js#1819]
Hello, I am not sure if this is the correct place to open the issue.

**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**
- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**
Version 17

**What happened?**
Although in the documentation (https://octokit.github.io/rest.js) you can select v16 or v18 and the page loads normally, when you select v17 from the dropdown in the upper left corner, most of the documentation for octokit/rest.js v17 (https://octokit.github.io/rest.js/v17) is missing.

**Minimal test case to reproduce the problem**
N/A

**What did you expect to happen?**
N/A

**What the problem might be**
N/A

**Comment by gr2m** [comment]
Thanks Ilias for bringing that to our attention. It must be a problem with the docs setup, see the `docs/` folder. It's a Gatsby app with a plugin pulling in Markdown files from https://github.com/octokit/plugin-rest-endpoint-methods.js/

I'm pretty busy with other things right now. If anyone would like to investigate, I'd appreciate the help
