### ISSUE TITLE
Storing and requesting access tokens / login flow

### ISSUE THREAD

**Issue by reggi** [octokit/octokit.js#182]
When someone logs in with github the only data that returns is the "code" then you can get [the access token](https://github.com/mikedeboer/node-github/blob/master/test/oauth.js#L66) and then you get finally [the username](https://github.com/mikedeboer/node-github/blob/master/test/oauth.js#L52). This process has to happen everytime? Even if I store all this information, I have nothing to lookup the `access_token` again. Is this true?

**Comment by kaizensoze** [comment]
The access_token: username mapping is typically stored in a database on the back-end outside of node-github.
