### ISSUE TITLE
issues.createLabel does not authenticate request when using privateKey

### ISSUE THREAD

**Issue by AArnott** [octokit/octokit.js#1824]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├─┬ @octokit/auth-app@2.4.10
│ ├─┬ @octokit/request@5.4.7
│ │ ├─┬ @octokit/endpoint@6.0.5
│ ├─┬ @octokit/request-error@2.0.2
│ ├─┬ @octokit/types@5.2.0
├─┬ @octokit/rest@18.0.3
│ ├─┬ @octokit/core@3.1.1
│ │ ├─┬ @octokit/auth-token@2.4.2
│ │ ├─┬ @octokit/graphql@4.5.3
│ ├─┬ @octokit/plugin-paginate-rest@2.3.0
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.1.2
├─┬ @octokit/webhooks@7.7.0
```

**What happened?**

When I create an octokit object with auth supplied by a private key for a GitHub App, octokit apparently has no problems authenticating outbound requests such as `pulls.get` and `pulls.merge`. But when I call `issues.createLabel`, I was always getting 404's. In the thrown error object I could see that the original request did not have an `Authorization` HTTP header at all. 

I was finally able to resolve the issue by calling `createAppAuth` myself and using the resulting method to get the access token and passing *that* to `Octokit`'s constructor. Then `issues.createLabel` was authenticated just like the other calls to `pulls.get` and `pulls.merge`.

**Minimal test case to reproduce the problem**

```ts
import { Octokit } from "@octokit/rest"
import { createAppAuth } from "@octokit/auth-app"

export function getOctokit(installationId?: number): Octokit {
	const auth = {
		auth: {
			id: 1234, // GitHub App Id
			privateKey: "-----BEGIN RSA PRIVATE KEY----- ...",
			installationId,
		},
		authStrategy: createAppAuth,
	}

	return new Octokit(auth)
}

// elsewhere
const octokit = getOctokit(installation.id)

// Removing a label from a PR works fine.
const response = await this.octokit.issues.removeLabel({
	owner: this.pull_request.repository.owner.login,
	repo: this.pull_request.repository.name,
	issue_number: this.pullRequestNumber,
	name,
})

// But creating a label in the repo fails with a 404:
await octokit.issues.createLabel({
	owner: repo.full_name.split("/")[0],
	repo: repo.name,
	name: label[0],
	description: "Auto-completes a PR when reviews and checks pass",
	color: "0e8a16", // this is a green color
})
```

**What did you expect to happen?**

I expected this createLabel request to turn the GitHub App's privateKey into an access token and apply it to the request just like it does for other requests.

**What the problem might be**

Well, since I found it very strange that all other requests were authenticated except creating a label, I decided to get the token myself and then make an authenticated HTTP call. But along the way I tried just initializing Octokit with that same token first to see what would happen. What do you know... it works!
Specifically, I re-implemented my `getOctokit` function like this:

```ts
const auth = createAppAuth({
	id: Inputs.GitHubAppId,
	privateKey: Inputs.GitHubAppPrivateKey,
})

const authentication = await auth({ type: "installation", installationId })
const octokit = new Octokit({ auth: authentication.token })
return octokit
```

Then the rest of the code worked unchanged. So there's something about privateKey auth that Octokit wants to *skip* when creating labels, where it's perfectly happy to apply a string token if I give it one.

**Comment by gr2m** [comment]
Hi Andrew, I tried to reproduce the problem but had no luck, it works just as expected:
https://runkit.com/gr2m/octokit-rest-js-1824/1.0.0

Am I missing something?

**Comment by AArnott** [comment]
Rats. Well if you can wait another week I'll see what I can do about a smaller repro or at least pointing you to the commit where I worked around the problem to see if you can see anything missing in my description that would help explain the failure I was seeing.

**Comment by gr2m** [comment]
Hi Andrew, did you have a chance to look into creating a repository to reproduce the problem?

**Comment by AArnott** [comment]
I haven't. I'll close till I have time to follow-up. Thanks for your patience.
