### ISSUE TITLE
update refs is being escaped on the request.

### ISSUE THREAD

**Issue by aubelsb2** [octokit/octokit.js#1850]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [x] Node.js

**Versions**
```
>node --version
v13.11.0
% npm ls | grep -v deduped | grep octokit
npm ERR! peer dep missing: tslib@^1.10.0, required by @shiftcoders/dynamo-easy@5.6.0
npm ERR! peer dep missing: tslib@^1.10.0, required by @shiftcoders/dynamo-easy@5.6.0
npm ERR! extraneous: commander@5.1.0 /mnt/c/Users/arran_w/WebstormProjects/******/node_modules/commander
npm ERR! extraneous: nodemon@2.0.4 /mnt/c/Users/arran_w/WebstormProjects/*****/node_modules/nodemon
├─┬ @octokit/rest@18.0.4
│ ├─┬ @octokit/core@3.1.2
│ │ ├─┬ @octokit/auth-token@2.4.2
│ │ ├─┬ @octokit/graphql@4.5.4
│ │ ├─┬ @octokit/request@5.4.7
│ │ │ ├─┬ @octokit/endpoint@6.0.5
│ │ │ ├─┬ @octokit/request-error@2.0.2
│ │ ├─┬ @octokit/types@5.4.1
│ ├─┬ @octokit/plugin-paginate-rest@2.3.1
│ ├── @octokit/plugin-request-log@1.0.0
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.1.3

```

**What happened?**

When trying to update a ref I always get the following error:
```
RequestError [HttpError]: Reference does not exist
```

It seems that when injecting the :ref value into the URL it's being escaped: (From stack trace)
```
  request: {
    method: 'PATCH',
    url: 'https://api.github.com/repos/***/***/git/refs/refs%2Fheads%2Fmaster',
    headers: {
```
(`*` my addition)

**Minimal test case to reproduce the problem**

I am simply running:
```typescript
const githubOrg = "xyz"
const repoName = "xyz"
const branch = "master"
        console.log(`Updating branch ${githubOrg} ${repoName} ${branch}`)
        let branchUpdateResponse = await octokit.git.updateRef({
            owner: githubOrg || "",
            repo: repoName || "",
            sha: newCommit.data.sha,
            ref: `refs/heads/${branch}`
        })
```

**What did you expect to happen?**

I expected the REF to be accepted. Regardless of it's escaped status as this is the official (I believe) SDK.

**What the problem might be**

I couldn't exactly dive too deeply into the client repo as it's complex. I believe some end points with use ref are working fine.. I have had a look at:
https://github.com/bramstein/url-template 
and I don't believe it's at fault; although I would imagine as per:
https://tools.ietf.org/html/rfc6570 3.2.3. the variable in the URL would be +ref (however it looks like it's :ref even in places it works. For instance: (From dist-types/generated/parameters-and-response-types.d.ts)
```
        getCommit: {
            parameters: RequestParameters & Omit<Endpoints["GET /repos/:owner/:repo/commits/:ref"]["parameters"], "baseUrl" | "headers" | "mediaType">;
            response: Endpoints["GET /repos/:owner/:repo/commits/:ref"]["response"];
        };
```
(Verified it works in the code base:
```typescript
            console.log("Getting tag ref", tag)
            let tagRef = await octokit.git.getRef({
                owner: githubOrg,
                repo: repoName,
                ref: `refs/tags/${tag}`,
            })
```
)

Edit:
Actually in the RFC 3.2.6 has a `{/ref}` expansion but wouldn't fit with scheme. Eitherway probably not the solution to the problem here but a good reference.

**Comment by gr2m** [comment]
It's not a bug, but a feature. It was a breaking change in [version 17](https://github.com/octokit/rest.js/releases/tag/v17.0.0) of `@octokit/rest`

> URL parameters such as `options.base` and `options.head` for `octokit.repos.compareCommits` are now URL encoded automatically, you don't need to use `encodeURIComponent()` before passing the values to the endpoint methods.

The problem in your code is you shouldn't prefix the `ref` with `/refs`, see https://octokit.github.io/rest.js/v18#git-get-ref

I know the `ref` argument is not consistent across the methods, but we just wrap what GitHub's REST API is doing.

**Comment by aubelsb2** [comment]
Thanks.

**Comment by gr2m** [comment]
Anytime :)
