### ISSUE TITLE
Is it possible to call endpoint requiring JSON body?

### ISSUE THREAD

**Issue by rlaneve** [octokit/octokit.js#187]
There are (at least) a couple of endpoints which expect the body of an HTTP POST to be a JSON array, such as:
https://developer.github.com/v3/users/emails/#add-email-addresses
and
https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue

Is it possible to generate such a request with this library? The first has no other required parameters, but the second does (repo owner, repo name, and issue number). I've tried defining a new entry in the routes for the second example, but I can't seem to find a way to define the "body" of the request as a parameter. If I don't define a parameter, nothing gets sent in the body. If I try to define a parameter, a JSON object gets sent with the parameter name as a key, which Github does not accept.

Example definition:

```
        "add-issue-labels": {
          "url": "/repos/:user/:repo/issues/:number/labels",
          "method": "POST",
          "params": {
              "$user": null,
              "$repo": null,
              "$number": null,
              "$body": null
          }
        }
```

That results in a message body being sent like this:

```
REQUEST BODY: {"body":["_develop"]}
```

**Comment by MathiasFavro** [comment]
I just stumbled over this issue myself and found that there is a parameter type _data_ that works together with _requestFormat_.

Here is how I implemented the same function:

``` json
"add-labels": {
    "url": "/repos/:user/:repo/issues/:number/labels",
    "method": "POST",
    "requestFormat": "raw",
    "params": {
        "$user": null,
        "$repo": null,
        "$number": null,
        "$data": null
    }
},
```

Data needs to be in string format: 

``` JavaScript
API.issues.addLabels({
    user: user,
    repo: repo,
    number: number,
    data: JSON.stringify(labels),
});         
```

**Comment by rlaneve** [comment]
Thanks for the tip @Okar .

**Comment by kaizensoze** [comment]
Solution introduced was adding a flag (`sendValueAsBody`):

```
"add-labels": {
    "url": "/repos/:user/:repo/issues/:number/labels",
    "method": "POST",
    "params": {
        "$user": null,
        "$repo": null,
        "$number": null,
        "body": {
            "type": "Array",
            "sendValueAsBody": true,
            "required": true,
            "validation": "",
            "invalidmsg": "",
            "description": ""
        }
    },
    "description": "Add labels to an issue"
},
```

And then just calling it like so:

```
github.issues.addLabels({
    user: "kaizensoze",
    repo: "node-github",
    number: "101",
    body: ["invalid", "bug", "duplicate"]
}, function(err, res) {
    console.log(err, res);
});
```
