### ISSUE TITLE
workflow_file_name is not respected for createWorkflowDispatch or getWorkflow

### ISSUE THREAD

**Issue by yfried** [octokit/octokit.js#1885]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [x] Node.js

**Versions**

```
├─ @octokit/auth-token@2.4.2
│  └─ @octokit/types@^5.0.0
├─ @octokit/core@3.0.0
│  ├─ @octokit/auth-token@^2.4.0
│  ├─ @octokit/graphql@^4.3.1
│  ├─ @octokit/request@^5.4.0
│  ├─ @octokit/types@^5.0.0
├─ @octokit/endpoint@6.0.3
│  ├─ @octokit/types@^5.0.0
├─ @octokit/graphql@4.5.1
│  ├─ @octokit/request@^5.3.0
│  ├─ @octokit/types@^5.0.0
├─ @octokit/plugin-paginate-rest@2.2.3
│  └─ @octokit/types@^5.0.0
├─ @octokit/plugin-request-log@1.0.0
├─ @octokit/plugin-rest-endpoint-methods@4.2.0
│  ├─ @octokit/types@^5.5.0
│  ├─ @octokit/types@5.5.0
├─ @octokit/request-error@2.0.2
│  ├─ @octokit/types@^5.0.1
├─ @octokit/request@5.4.5
│  ├─ @octokit/endpoint@^6.0.1
│  ├─ @octokit/request-error@^2.0.0
│  ├─ @octokit/types@^5.0.0
├─ @octokit/rest@18.0.6
│  ├─ @octokit/core@^3.0.0
│  ├─ @octokit/plugin-paginate-rest@^2.2.0
│  ├─ @octokit/plugin-request-log@^1.0.0
│  └─ @octokit/plugin-rest-endpoint-methods@4.2.0
├─ @octokit/types@5.0.1

```
**What happened?**

```javascript

await octokit.actions.createWorkflowDispatch({
      owner: GITHUB_ORG,
      repo: repoName,
      ref: "master",
      workflow_file_name: "main.yml",
    })

```

**What did you expect to happen?**

expected to see the worklfow triggered

**What the problem might be**

`workflow_file_name` is not respected, and `workflow_id` accepts only `number`.

```
github.ts (117,56): Argument of type '{ owner: string; repo: string; workflow_file_name: string; }' is not assignable to parameter of type 'RequestParameters & Pick<ActionsGetWorkflowEndpoint, "owner" | "repo" | "workflow_id">'.
  Property 'workflow_id' is missing in type '{ owner: string; repo: string; workflow_file_name: string; }' but required in type 'Pick<ActionsGetWorkflowEndpoint, "owner" | "repo" | "workflow_id">'.
```

```
github.ts (123,67): Argument of type '{ owner: string; repo: string; ref: string; workflow_file_name: string; inputs: { projectName: string; platformTag: string; }; }' is not assignable to parameter of type 'RequestParameters & Pick<ActionsCreateWorkflowDispatchEndpoint, "owner" | "repo" | "workflow_id" | "ref" | "inputs">'.
  Property 'workflow_id' is missing in type '{ owner: string; repo: string; ref: string; workflow_file_name: string; inputs: { projectName: string; platformTag: string; }; }' but required in type 'Pick<ActionsCreateWorkflowDispatchEndpoint, "owner" | "repo" | "workflow_id" | "ref" | "inputs">'.
```

```
github.ts (127,7): Type 'string' is not assignable to type 'number'.
```

**Comment by gr2m** [comment]
The [Create a workflow dispatch event](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) lists `workflow_id` id as an integer parameter, it's also defined as such in the OpenAPI spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml (search for " workflow-id:")

I agree, given the description, `workflow_id` should be allowed to be a string. But there is no `workflow_file_name` parameter.

For the time being, you can workaround the issue by using the request method

```js
  await octokit.request("post /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches", {
      owner: GITHUB_ORG,
      repo: repoName,
      ref: "master",
      workflow_id: "main.yml",
    })
```

I will file an issue regarding the OpenAPI spec

**Comment by gr2m** [comment]
Yes, it will take a moment. We do not yet consume the schema from `github/rest-api-description`, but a previous version published to https://www.npmjs.com/package/@github/openapi. I'm working on it, but I run into a blocker (https://github.com/octokit/types.ts/issues/161), so it might take a while I'm afraid

**Comment by yfried** [comment]
Thank. I will wait for you to mark this issue as solved

**Comment by yfried** [comment]
Hi @gr2m is there an update on this issue?

**Comment by gr2m** [comment]
Does the problem persist? I think `workflow_id` can now be set to both a string and a number? If not, then we need to create an issue at https://github.com/github/rest-api-description/

**Comment by yfried** [comment]
It works. Thank you.

**Comment by yfried** [comment]
This issue can be closed
