### ISSUE TITLE
Not browserify compatible

### ISSUE THREAD

**Issue by rgiard** [octokit/octokit.js#191]
Not sure we should mark it has an issue, but it is not possible to browserify the module (http://browserify.org/).  Using variables in "require(...)" and reading the routes from a file is not browserify safe.  Just raising the point ...

**Comment by piranna** [comment]
Any update on this? I'm also interested on access GitHub API from browser...

**Comment by revolunet** [comment]
+1

**Comment by jamestalmage** [comment]
I have browser support working. See #261 

Until @mikedeboer merges, you can install my patch via:
`npm install --save jamestalmage/node-github#browserify-compatibility`

**Comment by jwickens** [comment]
+1 would be great if the patch was merged to master

**Comment by gr2m** [comment]
@jamestalmage note that `browserify-compatibility` branch no longer exist. Is it maybe `browserify-and-promises` now?

```
npm install --save jamestalmage/node-github#browserify-and-promises
```

I tried to browsery using your fork, but got `Error: Cannot find module './api/vundefined'`. Do you have a built somewhere you can share?

**Comment by gr2m** [comment]
update: browser compatibility is the next big milestone. I recommend to subscribe to this issue to stay up-to-date: #620

**Comment by gr2m** [comment]
The latest release of `@octokit/rest` is compatible with browserify. See more news regarding browser support in my latest update: https://github.com/octokit/rest.js/issues/620#issuecomment-362715478

I recommend to subscribe to issue #620 to stay up-to-date with all things JavaScript Octokit :)
