### ISSUE TITLE
github.issue.create is giving me a 404 (FIXED: Removing path prefix fixes it)

### ISSUE THREAD

**Issue by davidfurlong** [octokit/octokit.js#192]
{ message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
  code: 404 }

EDIT: Removing path prefix seemed to work. Annoying.

**Comment by robneville73** [comment]
Can you elaborate on "removing path prefix"? I didn't define one (even tried setting it null) and I'm still getting this issue.
