### ISSUE TITLE
isPlainObject.isPlainObject is not a function - error after compiling with ncc

### ISSUE THREAD

**Issue by cyamonide** [octokit/octokit.js#1929]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├─┬ @octokit/rest@18.0.9
│ ├─┬ @octokit/core@3.2.1
│ │ ├─┬ @octokit/auth-token@2.4.3
│ │ ├─┬ @octokit/graphql@4.5.7
│ │ ├─┬ @octokit/request@5.4.10
│ │ │ ├─┬ @octokit/endpoint@6.0.9
│ │ │ ├─┬ @octokit/request-error@2.0.3
│ │ ├─┬ @octokit/types@5.5.0
│ ├─┬ @octokit/plugin-paginate-rest@2.6.0
│ ├── @octokit/plugin-request-log@1.0.2
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.2.1
```

**What happened?**

On upgrading to `@octokit/rest@18.0.9` from `18.0.5`, our compiled (using `ncc`) [project](https://github.com/gagoar/use-herald-action) doesn't run, with the following error:
```
/home/runner/work/use-herald-action/use-herald-action/dist/index.js:8906
    if (isPlainObject.isPlainObject(options[key])) {
                      ^

TypeError: isPlainObject.isPlainObject is not a function
    at /home/runner/work/use-herald-action/use-herald-action/dist/index.js:8906:23
    at Array.forEach (<anonymous>)
```

Might be worth noting that we were also seeing this error a few days ago when trying to upgrade to `18.0.7` from `18.0.5`.

I believe this might be an issue when `@octokit/rest` interacts with webpack, since our project runs and passes tests locally, without compiling. An issue similar to this one was reported in #1354  and resolved in the `16.25.4` release.

**Minimal test case to reproduce the problem**

**EDIT:** Minimal repro created by @gagoar: https://github.com/octokit/rest.js/issues/1929#issuecomment-722011156

While I don't have a minimal test case, I hope the following is helpful in diagnosing the issue:

Renovate PR that produced the error:  https://github.com/gagoar/use-herald-action/pull/235
In particular, this GitHub action dry-runs the project after compiling with `ncc`: https://github.com/gagoar/use-herald-action/pull/235/checks?check_run_id=1343946483

`npm ls is-plain-object`
```
use-herald-action@2.3.0 /Users/siliu/GitHub/gagoar/use-herald-action
├─┬ @octokit/rest@18.0.9
│ └─┬ @octokit/core@3.2.1
│   └─┬ @octokit/request@5.4.10
│     ├─┬ @octokit/endpoint@6.0.9
│     │ └── is-plain-object@5.0.0        <------ 5.0.0
│     └── is-plain-object@5.0.0          <------ 5.0.0
└─┬ jest@26.6.2
  └─┬ @jest/core@26.6.2
    └─┬ jest-haste-map@26.6.2
      └─┬ sane@4.1.0
        └─┬ micromatch@3.1.10
          ├─┬ extend-shallow@3.0.2
          │ └─┬ is-extendable@1.0.1
          │   └── is-plain-object@2.0.4   <------ 2.04
          └─┬ snapdragon@0.8.2
            └─┬ base@0.11.2
              ├─┬ cache-base@1.0.1
              │ └─┬ set-value@2.0.1
              │   └── is-plain-object@2.0.4  deduped <------ 2.04
              └─┬ mixin-deep@1.3.2
                └─┬ is-extendable@1.0.1
                  └── is-plain-object@2.0.4  deduped <------ 2.04
```

cc @gagoar

**Comment by gagoar** [comment]
I'm preparing a minimal reproduction case to simplify debugability. 

The same issue was reported on https://github.com/octokit/graphql.js/issues/195#issuecomment-695368139

**Comment by gr2m** [comment]
thanks @gagoar. I'd be open to move on to another library, too. Both bundle size and performance are critical

**Comment by gagoar** [comment]
### Repo to reproduce issue
https://github.com/gagoar/is-plain-object-error-repro
### Checkrun Failing
https://github.com/gagoar/is-plain-object-error-repro/runs/1355424729

I've also created a workflow so if you want to test against this repo you can

### Github Documentation
Currently, the [documentation](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action) is suggesting ppl use ncc to build their actions, which will lead to this issue,  I can PR a change in the documentation to suggest esbuild given that I've already changed another node tools I own to esbuild to solve the problem. like [github-installaction-token](https://github.com/gagoar/github-app-installation-token). But let us know how can we help.

**Comment by gr2m** [comment]
Thanks!!



I'd love to see how you use `esbuild` as an `ncc` alternative. `ncc` compiles all dependencies into a single file which is what's needed for GitHub Actions. Does `esbuild` do the same thing?

**Comment by TrySound** [comment]
Hey, it's is-plain-object maintainer here. I see 404 here https://github.com/gagoar/is-plain-object-error-repro

**Comment by gagoar** [comment]
try again @TrySound

**Comment by gagoar** [comment]
gr2m take a look at  [use-herald-action](https://github.com/gagoar/use-herald-action/pull/244) is a good example of esbuild working for actions. 

I've also done the same for [github-app-installation-token-action](https://github.com/jnwng/github-app-installation-token-action/pull/5)

and yes esbuild does the same than ncc. but it doesn't use webpack and instead uses its own transpilter and bundler for it.

**Comment by TrySound** [comment]
Looks like [@zeit/ncc](https://www.npmjs.com/package/@zeit/ncc) is not maintained anymore. Try `@vercel/ncc`

**Comment by gagoar** [comment]
The issue happens with both. I'm gonna update the repro so you can see.

**Comment by gagoar** [comment]
https://github.com/gagoar/is-plain-object-error-repro/pull/2/checks?check_run_id=1355682716 cc @TrySound

**Comment by TrySound** [comment]
Looks like the issue is bundling `node_modules/is-plain-object` (default export) instead of `node_modules/@octokit/request/node_modules/is-plain-object` (named export). Something with ncc resolver. I think it's worth to open the issue in their repo.

**Comment by gagoar** [comment]
this is happening with `esbuld` as well, you can see it [here](https://github.com/gagoar/is-plain-object-error-repro/pull/3/checks?check_run_id=1361870496). I think there's something else going on with the package itself that is confusing 2 different building systems.

**Comment by gagoar** [comment]
@gr2m  I'm looking into the compiled files directly, and the issue is how @octokit/endpoint.js compiles the `dist-node` files on request dependency. 


Thanks to esbuild that shows what is the reference that was used we can see that the compiled code for `dist-node` has already the wrong reference. 
![image](https://user-images.githubusercontent.com/226559/98325625-17d71000-1fa4-11eb-90af-d3399e532616.png)

In the command line after installing the package, you can see the following:

````bash
➜  is-plain-object-error-repro git:(esbuild) cat  node_modules/@octokit/endpoint/dist-node/index.js | grep -n isPlainObject.isPlainObject
22:    if (isPlainObject.isPlainObject(options[key])) {
````
and that's the line that ncc and esbuild are using directly

**Comment by TrySound** [comment]
This is not the issue. See node_modules/@octokit/endpoint/node_modules/is-plain-object/dist/is-plain-object.js. It should work. But for some reason bundlers took only top level and old is-plain-object which is not octokit dependency.
```
exports.isPlainObject = isPlainObject;
```

**Comment by gagoar** [comment]
> This is not the issue. See node_modules/@octokit/endpoint/node_modules/is-plain-object/dist/is-plain-object.js. It should work. But for some reason, bundlers took only top-level and old is-plain-object which is not `@octokit` dependency.
> 
> ```
> exports.isPlainObject = isPlainObject;
> ```

I see. Not sure where to go from here tho. both bundlers (webpack and esbuild) behave the same way  so the error is consistent.  I wonder if there's anything we can do from is-plain-object to fix it. 

maybe pika which is the one producing the bundles for oktokit is faulty here?

**Comment by TrySound** [comment]
I would just post an issue in both bundlers. Maybe resolvers are not properly setup in both cases. There is nothing to do with is-plain-object except reverting all goodies and going back to 2 like exports. Though tomorrow another package may break the same way.

**Comment by TrySound** [comment]
Also post it in ncc first. They may configure webpack incorrectly.

**Comment by cyamonide** [comment]
> I would just post an issue in both bundlers. Maybe resolvers are not properly setup in both cases. There is nothing to do with is-plain-object except reverting all goodies and going back to 2 like exports. Though tomorrow another package may break the same way.

Hey @TrySound, thanks for working with @gagoar to look into the issue. It does look like a bundler problem as you suggested.

One theory is that webpack might be configured to resolve root modules only similar to here: https://stackoverflow.com/questions/48825061/webpack-sub-modules-not-resolved-correctly

I installed `is-plain-object@5.0.0` as a toplevel dependency in the reproduction repository here: https://github.com/gagoar/is-plain-object-error-repro/pull/4 which has seemed to resolve the issue. So, there's no problem with `is-plain-object` and the named export can (and should) stay.

I also tried removing `jest` as a dependency since it depends on `is-plain-object@2.0.4`. This also fixed our issues: https://github.com/gagoar/is-plain-object-error-repro/pull/5. Should be safe to conclude at this point that `ncc` and `esbuild` are both incorrectly resolving `is-plain-object@2.0.4` when octokit asks for `is-plain-object@5.0.0`.

I'll see to opening issues in `ncc` and `esbuild`, in that order.

**Comment by evanw** [comment]
Just checked out why esbuild does this. It's caused by [this line](https://github.com/gagoar/is-plain-object-error-repro/blob/f88051ffff01d0ab22977ef99e2d0d73bf78a344/tsconfig.json#L27) in `tsconfig.json`:

```json
"*": ["node_modules/*"]
```

This tells esbuild to check that folder first and that any match there takes priority over the normal module resolution process. Removing this line means esbuild falls back to node's module resolution algorithm which resolves `is-plain-object` correctly.

**Comment by cyamonide** [comment]
Thanks @evanw - removing that line worked for me!
Chalking this one up to user error then :')

**Comment by Legion2** [comment]
After the latest ncc update (0.27.0 to 0.28.2) I have the same issue and already tried to add `is-plain-object@5.0.0` as an explicit dependency but that did not resolve the issue. `"*": ["node_modules/*"]` does not appear in my `tsconfig.json` either, so I don't know how to resolve this. See https://github.com/Legion2/swagger-ui-action/pull/179 and https://github.com/Legion2/swagger-ui-action/pull/179/checks?check_run_id=2345910110

**Comment by gr2m** [comment]
@Legion2 could you create a repository or gist with a minimal reproducible test case, and then file a new issue with that please?

**Comment by Legion2** [comment]
@gr2m After an update from `@octokit/rest` from 18.5.2 to 18.5.3, `@vercel/ncc` 0.28.3 works

**Comment by gr2m** [comment]
that's great, thank you for letting us know!
