### ISSUE TITLE
PATCH /repos/:owner/:repo ignores the is_template parameter

### ISSUE THREAD

**Issue by fenske** [octokit/octokit.js#1931]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com

**Versions**

3.2.1

**What happened?**

Updating the `is_template` flag via `PATCH /repos/:owner/:repo` has no effect, even though the response status is 200.

**Minimal test case to reproduce the problem**
Run a snippet similar to below:
```
const makeTemplateRes = await octokit.request("PATCH /repos/:owner/:repo", {
      owner: owner,
      repo: repo,
      is_template: true
    });
```

**What did you expect to happen?**

The target repo to become a template.

**What the problem might be**

Don't know tbh.

**Comment by gr2m** [comment]
I think you need to enable the `baptiste` preview, see https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-a-repository

<img width="741" alt="image" src="https://user-images.githubusercontent.com/39992/98278535-994f8380-1f4d-11eb-98fc-99e617ec59ce.png">

Can you give that a try?

```js
const makeTemplateRes = await octokit.request("PATCH /repos/:owner/:repo", { {
      mediaType: { previews: ["baptiste"] },
      owner: owner,
      repo: repo,
      is_template: true
    });
```

If that resolves it, we should let the docs team know, they usually mention the preview in the parameter descriptions

**Comment by fenske** [comment]
Good catch, @gr2m ! 👏 

The clause you shared is indeed in the docs (although, at the very top).

I tried it and it worked. 🙏

I created https://github.com/github/docs/issues/1104 for the docs team to take a look.

Thanks for looking into this! ✌️
