### ISSUE TITLE
[TypeScript] Incompatible types between v18.0.10 and @octokit/types v5

### ISSUE THREAD

**Issue by iliasbibas** [octokit/octokit.js#1951]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [ ] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**
Before update:
```
├─┬ @octokit/rest@18.0.9
│ ├─┬ @octokit/core@3.2.2
│ │ ├─┬ @octokit/auth-token@2.4.4
│ │ │ └─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/graphql@4.5.8
│ │ │ ├─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/request@5.4.11
│ │ │ ├─┬ @octokit/endpoint@6.0.10
│ │ │ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├─┬ @octokit/request-error@2.0.4
│ │ │ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├── @octokit/openapi-types@1.2.2
│ ├─┬ @octokit/plugin-paginate-rest@2.6.1
│ │ └─┬ @octokit/types@6.0.1
│ ├── @octokit/plugin-request-log@1.0.2
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.2.1
│   ├─┬ @octokit/types@5.5.0
├─┬ @octokit/types@5.2.1
```
After update:
```
├─┬ @octokit/rest@18.0.10
│ ├─┬ @octokit/core@3.2.2
│ │ ├─┬ @octokit/auth-token@2.4.4
│ │ │ └─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/graphql@4.5.8
│ │ │ ├─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/request@5.4.11
│ │ │ ├─┬ @octokit/endpoint@6.0.10
│ │ │ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├─┬ @octokit/request-error@2.0.4
│ │ │ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├─┬ @octokit/types@6.0.1
│ │ ├─┬ @octokit/types@6.0.1
│ │ │ ├── @octokit/openapi-types@1.2.2
│ ├─┬ @octokit/plugin-paginate-rest@2.6.1
│ │ └─┬ @octokit/types@6.0.1
│ ├── @octokit/plugin-request-log@1.0.2
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.3.0
│   ├─┬ @octokit/types@6.0.1
├─┬ @octokit/types@5.2.1
```

**What happened?**

After trying to compile a project using the octokit packages as seen above, the compilation fails with multiple type errors like the ones stated below.

After this update we are seeing errors in compilation like the following:

```
error TS2531: Object is possibly 'null':

        return tinstallation.account.login === this.config.gitOwner;
```
```
error TS2322: Type 'OctokitResponse<{ type: string; size: number; name: string; path: string; content?: string | undefined; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { ...; }; }[] | { ...; } | { ...; } | { ...; }, 200>' is not assignable to type 'OctokitResponse<ReposGetContentResponseData>'.
  Types of property 'data' are incompatible.
    Type '{ type: string; size: number; name: string; path: string; content?: string | undefined; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { ...; }; }[] | { ...; } | { ...; } | { ...; }' is not assignable to type 'ReposGetContentResponseData'.
      Type '{ type: string; size: number; name: string; path: string; content?: string | undefined; sha: string; url: string; git_url: string | null; html_url: string | null; download_url: string | null; _links: { ...; }; }[]' is missing the following properties from type 'ReposGetContentResponseData': type, encoding, size, name, and 10 more.

        contents = await client.repos.getContent(
```

```
Type 'OctokitResponse<{ ref?: string | undefined; node_id?: string | undefined; url?: string | undefined; object?: { type?: string | undefined; sha?: string | undefined; url?: string | undefined; } | undefined; }, 201>' is not assignable to type 'OctokitResponse<GitGetRefResponseData>'.
  Types of property 'data' are incompatible.
    Type '{ ref?: string | undefined; node_id?: string | undefined; url?: string | undefined; object?: { type?: string | undefined; sha?: string | undefined; url?: string | undefined; } | undefined; }' is not assignable to type 'GitGetRefResponseData'.

        response = await client.git.createRef(
```

**Minimal test case to reproduce the problem**

\-

**What did you expect to happen?**

The compilation to finish without errors.

**What the problem might be**

In our project's package.json we have the entry `@octokit/rest": "~18.0.3"` which up until yesterday resolved to version `18.0.9`. This version was using `@octokit/plugin-rest-endpoint-methods": "4.2.1"` which in turn was using `"@octokit/types": "^5.5.0"`. The new release `@octokit/rest": "18.0.10"` is using `"@octokit/plugin-rest-endpoint-methods": "4.3.0"` which is using `"@octokit/types": "^6.0.0"`. As you can see the major version of `"@octokit/types"` was bumped from 5 -> 6 which seems to contain breaking changes.

**Comment by gr2m** [comment]
We migrated to GitHub's official OpenAPI specification via `@octokit/types` v6. The type definitions are significantly better and more efficient now, but unfortunately a few regressions have been introduced. 

It looks like you have dependencies on both, `@octokit/rest` and `@octokit/types`. 

```
├─┬ @octokit/rest@18.0.10
...
├─┬ @octokit/types@5.2.1
```

If you use types from `@octokit/types@5` and then set the variables from `@octokit/rest@18.0.10` which has the types from `@ocotkit/types@6` internally, you get the incompatibility compilation errors you are seeing.

Because they are compilation errors that you only see at build time, we don't consider them breaking changes. They will not affect any of your projects in production.

Updating `@ocotkit/types` to the latest version should resolve the problem.

**Comment by iliasbibas** [comment]
Thank you for getting back to me, I will try what you suggested.

**Comment by AndrewCsontos** [comment]
I ran into the same issue as above, though all of my @octokit/types references **are** to 6.x versions. 
Going from @octokit/rest@18.0.9 to @octokit/rest@18.0.10 broke a lot of TypeScript code.

For example, none of these types are available anymore. 

```ts
import type {
  SearchCodeResponseData,
  ReposGetResponseData,
  ReposGetBranchProtectionResponseData,
  ReposGetStatusChecksProtectionResponseData,
} from '@octokit/types';
```

Additionally, the Typescript types for octokit.repos.getContent seem to be broken. 
Previously it would return a Promise<OctokitResponse<ReposGetContentResponseData>> which had a data property with a content property.  

Now i get TypeScript errors trying to get to **content** - either through .data or directly. 

```
 'content' does not exist on type '{ type: string; size: number; name: string; path: string; content?: string; sha: string; url: string; git_url: string; html_url: string; download_url: string; _links: { git: string; html: string; self: string; }; }[] | { ...; } | { ...; } | { ...; }'.
      Property 'content' does not exist on type '{ type: string; size: number; name: string; path: string; content?: string; sha: string; url: string; git_url: string; html_url: string; download_url: string; _links: { git: string; html: string; self: string; }; }[]'.
```

This seems like a breaking change that should require a major version bump

As an aside, i vastly prefer the named types of @octokit/types@5 to the unnamed ones.

**Comment by wolfy1339** [comment]
We don't consider changing the TypeScript types to be a breaking change, since it doesn't affect the run-time of the module.

>Additionally, the Typescript types for octokit.repos.getContent seem to be broken.
>Previously it would return a Promise<OctokitResponse> which had a data property with a content property.

>Now i get TypeScript errors trying to get to content - either through .data or directly.

I can reproduce that same error, and can clearly see the `content` property in the types, not sure why it isn't working.

**Comment by wolfy1339** [comment]
The issue seems to come from the fact that there is multiple types appended together using the `|` (OR) operator.

It all boils down to the [`Operation['response']` type](https://github.com/octokit/types.ts/blob/v6.1.1/src/generated/Endpoints.ts#L53)

**Comment by gr2m** [comment]
let's continue discussion at #1971, as it's specific to Andrews question.

I think the original problem is resolved. Many errors you see are actually correct. The types are much better now, they catch more problems. There are however new errors that have been introduced, many of which we already track with the GitHub team working on the OpenAPI spec: https://github.com/github/rest-api-description/issues

I'd prefer we open separate issues for specific problems from here on now.
