### ISSUE TITLE
Create orphan branch using octokit api

### ISSUE THREAD

**Issue by techierishi** [octokit/octokit.js#1984]
Is there an API to create an orphan branch using Octokit.
Most probably and alternative of following git operation:
```bash
git checkout --orphan orp;
git commit -m 'orp branch initial commit';
git push -u origin orp;
```

**Comment by gr2m** [comment]
I'm not sure. There are several [REST APIs for `git` operations](https://docs.github.com/en/rest/reference/git), but I'm not sure if you can use any of them to create an orphan branch. This question is best asked in https://github.community/c/github-ecosystem/37, there are several GitHub support folks watching that forum. Would you mind asking there?

**Comment by techierishi** [comment]
Solution provided in following link worked!
https://github.community/t/create-orphan-branch-using-octokit-api-1984/157029/2?u=techierishi

**Comment by gr2m** [comment]
Great, thanks for sharing! We could create a reusable plugin for that 🤔 

Would you mind sharing why you need an orphan branch? I'm curious what you are building with it

**Comment by techierishi** [comment]
In one of our use cases we need to create a template repository which consists of 1-2 orphan branch.
