### ISSUE TITLE
actions.downloadArtifact follows the redirect instead of returning the URL

### ISSUE THREAD

**Issue by pluma** [octokit/octokit.js#1999]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├── @octokit/rest@18.0.15
```

**What happened?**

According to [the documentation](https://octokit.github.io/rest.js/v18#actions-download-artifact) `actions.downloadArtifact` should return a redirect URL for downloading the artifact. Instead it returns after following the redirect, which means `data` contains the entire artifact as a buffer.

**Minimal test case to reproduce the problem**

1. Have a workflow generate an artifact and set up a PAT for accessing it.
2. Create an auhorized octokit instance.
3. Run `await octokit.actions.downloadArtifact` against the artifact.
4. Wait several seconds for hundreds of megabytes of data being downloaded and loaded into V8 to create a buffer.
5. The function eventually returns with `data` set to the buffer.

**What did you expect to happen?**

According to the documentation, the API responds with a redirect and the response from octokit should be the URL (via the `location` header) which is good for one minute. This seems useful as the user might want to use something else to perform the download, e.g. to avoid loading hundreds of megabytes into memory.

**What the problem might be**

The underlying `@octokit/request´ library likely follows redirects by default. Either the documentation of the method needs to be changed to reflect this behavior or the request needs to be performed in a way that ensures the redirect is not followed in this case.

**Comment by pluma** [comment]
@gr2m Thanks for the detailed answer! That looks like it should be a good workaround. I ended up going a different route entirely, though, that no longer involves downloading artifacts. Feel free to close this issue.

**Comment by bobisjan** [comment]
I've encountered the same issue, and I was able to solve this with the `redirect` option, leaving following snippet for the future travellers.

```javascript
const { headers } = await octokit.actions.downloadArtifact({
  request: {
    redirect: 'manual',
  },
  owner,
  repo,
  artifact_id,
  archive_format,
});
```
