### ISSUE TITLE
18.2.0 regression - type mismatch between plugin-rest-endpoint-methods and plugin-paginate-rest

### ISSUE THREAD

**Issue by RLRabinowitz** [octokit/octokit.js#2019]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
│  ├─ @octokit/auth-app@2.11.0
│  ├─ @octokit/rest@18.2.0
│  ├─ @octokit/endpoint@5.5.1
│  │  ├─ @octokit/types@^2.0.0
│  ├─ @octokit/plugin-enterprise-rest@^6.0.1
│  ├─ @octokit/request-error@1.2.0
│  │  ├─ @octokit/types@^2.0.0
│  ├─ @octokit/request@5.3.1
│  │  ├─ @octokit/endpoint@^5.5.0
│  │  ├─ @octokit/request-error@^1.0.1
│  │  ├─ @octokit/types@^2.0.0
│  ├─ @octokit/rest@^16.28.4
│  ├─ @octokit/rest@16.35.0
│  │  ├─ @octokit/request-error@^1.0.2
│  │  ├─ @octokit/request@^5.2.0
│  │  ├─ octokit-pagination-methods@^1.1.0
│  ├─ @octokit/types@2.0.2
├─ @octokit/auth-app@2.11.0
│  ├─ @octokit/request-error@^2.0.0
│  ├─ @octokit/request@^5.4.11
│  ├─ @octokit/types@^6.0.3
├─ @octokit/auth-token@2.4.4
│  └─ @octokit/types@^6.0.0
├─ @octokit/core@3.2.4
│  ├─ @octokit/auth-token@^2.4.4
│  ├─ @octokit/graphql@^4.5.8
│  ├─ @octokit/request@^5.4.12
│  ├─ @octokit/types@^6.0.3
├─ @octokit/endpoint@6.0.5
│  ├─ @octokit/types@^5.0.0
│  ├─ @octokit/types@5.4.0
├─ @octokit/graphql@4.5.8
│  ├─ @octokit/request@^5.3.0
│  ├─ @octokit/request@5.4.7
│  │  ├─ @octokit/endpoint@^6.0.1
│  │  ├─ @octokit/request-error@^2.0.0
│  │  ├─ @octokit/types@^5.0.0
│  │  ├─ @octokit/types@5.4.0
│  ├─ @octokit/types@^6.0.0
├─ @octokit/openapi-types@2.0.0
├─ @octokit/plugin-enterprise-rest@6.0.1
├─ @octokit/plugin-paginate-rest@2.6.2
│  └─ @octokit/types@^6.0.1
├─ @octokit/plugin-request-log@1.0.2
├─ @octokit/plugin-rest-endpoint-methods@4.12.0
│  ├─ @octokit/openapi-types@5.1.0
│  ├─ @octokit/types@^6.10.0
│  ├─ @octokit/types@6.10.0
│  │  └─ @octokit/openapi-types@^5.1.0
├─ @octokit/request-error@2.0.2
│  ├─ @octokit/types@^5.0.1
│  ├─ @octokit/types@5.4.0
├─ @octokit/request@5.4.12
│  ├─ @octokit/endpoint@^6.0.1
│  ├─ @octokit/request-error@^2.0.0
│  ├─ @octokit/types@^6.0.3
├─ @octokit/rest@18.2.0
│  ├─ @octokit/core@^3.2.3
│  ├─ @octokit/plugin-paginate-rest@^2.6.2
│  ├─ @octokit/plugin-request-log@^1.0.2
│  └─ @octokit/plugin-rest-endpoint-methods@4.12.0
├─ @octokit/types@6.1.1
│  ├─ @octokit/openapi-types@^2.0.0
├─ octokit-pagination-methods@1.1.0
```

**What happened?**

In 18.1.1 the following code did not have any issues with the types. In 18.2.0, there are issues with the types (assume `client` is of type `Octokit`)
```
client.paginate.iterator(client.apps.listReposAccessibleToInstallation, {...})
```

In 18.2.0 we get the following TS error:
```
TS2769: No overload matches this call.   Overload 1 of 4, '(route: "GET /repos/{owner}/{repo}/pulls" | "GET /repos/{owner}/{repo}/issues/{issue_number}/comments" | "GET /app/installations" | "GET /applications/grants" | "GET /authorizations" | ... 179 more ... | "GET /users/{username}/subscriptions", parameters?: {} | ... 183 more ... | ({ ...; } & { ...; })): AsyncIterableIterator<...>', gave the following error.     Argument of type '{ (params?: RequestParameters & Pick<{ per_page?: number; page?: number; }, "per_page" | "page">): Promise<{ headers: { [x: string]: string | number; "cache-control": string; ... 15 more ...; "x-ratelimit-reset": string; }; status: 200; url: string; data: { ...; }; }>; defaults: <O extends RequestParameters = Reques...' is not assignable to parameter of type '"GET /repos/{owner}/{repo}/pulls" | "GET /repos/{owner}/{repo}/issues/{issue_number}/comments" | "GET /app/installations" | "GET /applications/grants" | "GET /authorizations" | ... 179 more ... | "GET /users/{username}/subscriptions"'.       Type '{ (params?: RequestParameters & Pick<{ per_page?: number; page?: number; }, "per_page" | "page">): Promise<{ headers: { [x: string]: string | number; "cache-control": string; ... 15 more ...; "x-ratelimit-reset": string; }; status: 200; url: string; data: { ...; }; }>; defaults: <O extends RequestParameters = Reques...' is not assignable to type '"GET /users/{username}/subscriptions"'.   Overload 2 of 4, '(route: string, parameters?: RequestParameters): AsyncIterableIterator<OctokitResponse<PaginationResults<unknown>, number>>', gave the following error.     Argument of type '{ (params?: RequestParameters & Pick<{ per_page?: number; page?: number; }, "per_page" | "page">): Promise<{ headers: { [x: string]: string | number; "cache-control": string; ... 15 more ...; "x-ratelimit-reset": string; }; status: 200; url: string; data: { ...; }; }>; defaults: <O extends RequestParameters = Reques...' is not assignable to parameter of type 'string'.   Overload 3 of 4, '(request: RequestInterface<object>, parameters?: string): AsyncIterableIterator<NormalizeResponse<OctokitResponse<any, number>>>', gave the following error.     Argument of type '{ (params?: RequestParameters & Pick<{ per_page?: number; page?: number; }, "per_page" | "page">): Promise<{ headers: { [x: string]: string | number; "cache-control": string; ... 15 more ...; "x-ratelimit-reset": string; }; status: 200; url: string; data: { ...; }; }>; defaults: <O extends RequestParameters = Reques...' is not assignable to parameter of type 'RequestInterface<object>'.       The types of 'endpoint.DEFAULTS' are incompatible between these types.         Type '{ url: string; } & RequestParameters & { baseUrl: string; method: RequestMethod; url?: string; headers: RequestHeaders & { accept: string; "user-agent": string; }; mediaType: { ...; }; }' is not assignable to type 'object & RequestParameters & { baseUrl: string; method: RequestMethod; url?: string; headers: RequestHeaders & { accept: string; "user-agent": string; }; mediaType: { ...; }; }'.           Type '{ url: string; } & RequestParameters & { baseUrl: string; method: RequestMethod; url?: string; headers: RequestHeaders & { accept: string; "user-agent": string; }; mediaType: { ...; }; }' is not assignable to type 'RequestParameters'.             The types of 'request.agent' are incompatible between these types.               Type '{}' is missing the following properties from type 'Agent': maxFreeSockets, maxSockets, sockets, requests, destroy
```

**Minimal test case to reproduce the problem**

**What did you expect to happen?**

Types should match, and the code should not fail `tsc`

**What the problem might be**

The reason for this error is that in `@octokit/types` version 6.8.5 the type of `RequestRequestOptions`'s `agent` changed in [this PR](https://github.com/octokit/types.ts/pull/264/files).

As you can see in my versions, `@octokit/rest` version 18.2.0 requires `@octokit/plugin-rest-endpoint-methods@4.12.0` and `@octokit/plugin-paginate-rest@2.6.2`. In those versions, `plugin-rest-endpoint-methods` requires `@octokit/types@^6.10.0`, but `plugin-paginate-rest` requires `@octokit/types@^6.0.1`.

This is what causes a mismatch in type between `plugin-rest-endpoint-methods`'s `apps.listReposAccessibleToInstallation`'s type, and  `plugin-paginate-rest`'s `RequestInterface`

**Comment by gr2m** [comment]
You have several versions of `@octokit/types` in your dependency tree. What are the direct `"@octokit/*"` dependencies in your `package.json`?

> In those versions, `plugin-rest-endpoint-methods` requires `@octokit/types@^6.10.0`, but `plugin-paginate-rest` requires `@octokit/types@^6.0.1`.

That's shouldn't be a problem. Try to `rm -rf package-lock.json node_modules && npm install`

**Comment by RLRabinowitz** [comment]
> You have several versions of @octokit/types in your dependency tree. What are the direct "@octokit/*" dependencies in your package.json?

The only direct `"@octokit/*"` dependencies we have are
```
"dependencies": {
    "@octokit/auth-app": "2.11.0",
    "@octokit/rest": "18.2.0"
  }
```

> That's shouldn't be a problem. Try to `rm -rf package-lock.json node_modules && npm install`

We're using `yarn`. Removing the `node_modules` and re-`yarn install`ing did not solve this issue. `yarn.lock` was not changed either.

From the contents of the `yarn.lock`:
```
"@octokit/plugin-paginate-rest@^2.6.2":
  version "2.6.2"
  resolved "https://registry.yarnpkg.com/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-2.6.2.tgz#45d13dbf5ff8aed54f1a3716b1d57fdc62720c5f"
  integrity sha512-3Dy7/YZAwdOaRpGQoNHPeT0VU1fYLpIUdPyvR37IyFLgd6XSij4j9V/xN/+eSjF2KKvmfIulEh9LF1tRPjIiDA==
  dependencies:
    "@octokit/types" "^6.0.1"

"@octokit/plugin-rest-endpoint-methods@4.12.0":
  version "4.12.0"
  resolved "https://registry.yarnpkg.com/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-4.12.0.tgz#1cec405cd4eaf0bdb58cb7d2a9b3d8473b3a70e8"
  integrity sha512-RgnQ1aoetdOJjZYC37LV5FNlL7GY/v1CdC5dur1Zp/UiADJlbRFbAz/xLx26ovXw67dK7EUtwCghS+6QyiI9RA==
  dependencies:
    "@octokit/types" "^6.10.0"
    deprecation "^2.3.1"

"@octokit/types@^2.0.0":
  version "2.0.2"
  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-2.0.2.tgz#0888497f5a664e28b0449731d5e88e19b2a74f90"
  integrity sha512-StASIL2lgT3TRjxv17z9pAqbnI7HGu9DrJlg3sEBFfCLaMEqp+O3IQPUF6EZtQ4xkAu2ml6kMBBCtGxjvmtmuQ==
  dependencies:
    "@types/node" ">= 8"

"@octokit/types@^5.0.0", "@octokit/types@^5.0.1":
  version "5.4.0"
  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-5.4.0.tgz#25f2f8e24fec09214553168c41c06383c9d0f529"
  integrity sha512-D/uotqF69M50OIlwMqgyIg9PuLT2daOiBAYF0P40I2ekFA2ESwwBY5dxZe/UhXdPvIbNKDzuZmQrO7rMpuFbcg==
  dependencies:
    "@types/node" ">= 8"

"@octokit/types@^6.0.0", "@octokit/types@^6.0.1", "@octokit/types@^6.0.3":
  version "6.1.1"
  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-6.1.1.tgz#bc88b3eb5f447b025a2a1a8177a72db216e8d4ca"
  integrity sha512-btm3D6S7VkRrgyYF31etUtVY/eQ1KzrNRqhFt25KSe2mKlXuLXJilglRC6eDA2P6ou94BUnk/Kz5MPEolXgoiw==
  dependencies:
    "@octokit/openapi-types" "^2.0.0"
    "@types/node" ">= 8"

"@octokit/types@^6.10.0":
  version "6.10.0"
  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-6.10.0.tgz#243faa864b0955f574012d52e179de38ac9ebafe"
  integrity sha512-aMDo10kglofejJ96edCBIgQLVuzMDyjxmhdgEcoUUD64PlHYSrNsAGqN0wZtoiX4/PCQ3JLA50IpkP1bcKD/cA==
  dependencies:
    "@octokit/openapi-types" "^5.1.0"
```

As you can see, both 6.10.0 and 6.1.1 are resolved for `@octokit/types`

**Comment by gr2m** [comment]
can you update `@octokit/auth-app` to the latest version (3.0.0). I don't expect it to resolve the issue, but the upgrade is easy enough, and we won't publish updates to 2.x versions: https://github.com/octokit/auth-app.js/releases/tag/v3.0.0

Here is what I get on a new directory

```
npm install @octokit/rest @octokit/auth-app
npm ls @octokit/types
```

returns

```
├─┬ @octokit/auth-app@2.1.1
│ └─┬ @octokit/request@5.4.14
│   ├─┬ @octokit/endpoint@6.0.11
│   │ └── @octokit/types@6.10.0  deduped
│   ├─┬ @octokit/request-error@2.0.5
│   │ └── @octokit/types@6.10.0  deduped
│   └── @octokit/types@6.10.0 
└─┬ @octokit/rest@18.2.0
  ├─┬ @octokit/core@3.2.5
  │ ├─┬ @octokit/auth-token@2.4.5
  │ │ └── @octokit/types@6.10.0  deduped
  │ ├─┬ @octokit/graphql@4.6.0
  │ │ └── @octokit/types@6.10.0  deduped
  │ └── @octokit/types@6.10.0  deduped
  ├─┬ @octokit/plugin-paginate-rest@2.10.0
  │ └── @octokit/types@6.10.0  deduped
  └─┬ @octokit/plugin-rest-endpoint-methods@4.12.0
    └── @octokit/types@6.10.0  deduped
```

You can see that there is a single `@octokit/types` version, while your output shows that you have several different versions, and I don't know why

**Comment by RLRabinowitz** [comment]
Hey sorry forgot to answer.

Apparently I forgot to delete the lock file, and deleting it fixes the dependencies to use the same `@octokit/types@6.10.0`. However, I do not wish to delete my lock file, as it would affect dependencies unrelated to `octokit`.

My current versions satisfy the dependencies defined by `@octokit/rest`, even thought `@octokit/types` is resolved in multiple different versions. Shouldn't the dependencies be defined in such a way that any resolved `@octokit/types`, even if there are multiple `@octokit/types` versions, should work fine? 
If `@octokit/types` contains breaking changes in a non major version (6.8.5), then in any version of  `@octokit/rest`, every dependency should either limit `@octokit/types` to be < 6.8.5, or limit it to be >= 6.8.5
Alternatively, if `@octokit/types` must only be resolved once with one specific version, then it should be a `peerDependency` instead

**Comment by gr2m** [comment]
> My current versions satisfy the dependencies defined by `@octokit/rest`, even thought `@octokit/types` is resolved in multiple different versions. Shouldn't the dependencies be defined in such a way that any resolved `@octokit/types`, even if there are multiple `@octokit/types` versions, should work fine?

Yes it should and that's how it usually works. I did a fresh install as I mentioned, and it worked as it was supposed to. I don't know how your app got into the state it is.

> If `@octokit/types` contains breaking changes in a non major version (6.8.5), then in any version of `@octokit/rest`, every dependency should either limit `@octokit/types` to be < 6.8.5, or limit it to be >= 6.8.5

It's complicated. We don't consider type changes to be breaking changes, as they don't impact your production environment, only your build environment.

> Alternatively, if `@octokit/types` must only be resolved once with one specific version, then it should be a `peerDependency` instead

peerDependencies are a great way to go to dependency hell ;) We try to avoid them if possible.

I understand your points, but I'd rather not have a principal discussion about how semver and npm works. What your problem comes down to is that you you have multiple versions of `@octokit/types` and you really shouldn't. It should not be caused by your `@octokit/*` dependencies

**Comment by RLRabinowitz** [comment]
Thank you for the in-depth response!

I ended up simply removing the specific version that was giving me trouble from the lock file. Now I have a single version for `@octokit/types` from `@octokit/rest`, so there's no type mismatch now
