### ISSUE TITLE
Release Asset upload support

### ISSUE THREAD

**Issue by callicles** [octokit/octokit.js#203]
Hi !

Are you planning on supporting the release asset upload part of the api ?

Thanks

**Comment by mantoni** [comment]
Just had a look at this module to find that the one feature I want is the only one that is not supported _haha_. Seems not so trivial from glancing over the GitHub API docs.

**Comment by mantoni** [comment]
Oh, just found out [this has been implemented](https://github.com/mikedeboer/node-github/pull/100) quite a while back. This issue should be closed and the docs updated.

**Comment by mikedeboer** [comment]
You're right. I also should just release a new version.

**Comment by am11** [comment]
Hello, 

Uploading the release asset is different than Creating a file in repo.

> _Uploading release asset to existing release on GitHub via v3 API: 
> https://developer.github.com/v3/repos/releases/#upload-a-release-asset_

vs.

> _Creating a file in GitHub repo: 
> https://developer.github.com/v3/repos/contents/#create-a-file_

Please reopen this issue.

**Comment by kaizensoze** [comment]
https://mikedeboer.github.io/node-github/#api-repos-uploadAsset
