### ISSUE TITLE
Support for cancelling api calls

### ISSUE THREAD

**Issue by pkrukp** [octokit/octokit.js#2036]
**What’s missing?**

I'd like to be able to cancel api call in progress.

**Why?**

API calls like `octokit.actions.downloadArtifact` could take a long time - for example because network is slow or because artifact is big. I would like to be able to cancel download (because I don't want to wait anymore, or because I noticed I'm downloading wrong artifact).

**Alternatives you tried**

I think there is no way to cancel a Promise :(

**Comment by pkrukp** [comment]
Would be great if api calls accepted `AbortController`: https://www.npmjs.com/package/abort-controller
Here's how it is used for example with `node-fetch`: https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal

**Comment by gr2m** [comment]
> Would be great if api calls accepted `AbortController`: https://www.npmjs.com/package/abort-controller
> Here's how it is used for example with `node-fetch`: https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal

It accepts exactly that. See `request.signal` option documentation at https://github.com/octokit/request.js/#readme

Does that work for you?

**Comment by pkrukp** [comment]
@gr2m thanks, it works for me. I apologize, I have missed that part of documentation.

It works, although Octokit throws generic HttpError exception, I don't see any visible indication (except for message) that it was caused by the abort. Would be great if Octokit threw some other exception (AbortException or similar).

**Comment by pkrukp** [comment]
Thanks, opened issue on the octokit/request.js, so I'm closing this one.
