### ISSUE TITLE
Unable to define Octokit

### ISSUE THREAD

**Issue by IzMichael** [octokit/octokit.js#2051]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Cloud
- [ ] Node.js
- [ ] GitHub Enterprise Server
- [x] Browsers: Microsoft Edge 89
- [ ] Others

**Versions**

Browser, latest from skypack. HTML.

**What happened?**

I'm unable to define the `Octokit` variable. I have ```<script type="module">
        import { Octokit } from "https://cdn.skypack.dev/@octokit/core";
    </script>``` in my header, and am using the `const octokit = new Octokit({ auth:`TOKEN HERE`});` in my footer. When I run my code, I get an error: `ReferenceError: Octokit is not defined`

**What did you expect to happen?**

I expected to be able to use the `new Octokit()` function from the brief instructions on the main repo

**Comment by wolfy1339** [comment]
Have you tried other browsers? Is it only this module that doesn't work?

**Comment by IzMichael** [comment]
This doesn't work in Firefox either, it gives me this error in the console `Loading failed for the module with source “https://cdn.skypack.dev/-/before-after-hook@v2.2.0-9V2cZe3lCgNnlBXFxPuf/dist=es2020,mode=imports/optimized/before-after-hook.js”.`

**Comment by gr2m** [comment]
We had problems with skypack before. It might have been a change on our or their side, it will take a moment to investigate. 

It would be very helpful if you could try importing previous versions and see if they all fail, and if not, at what version it started to fail. E.g. to pin the version to 3.2.5, do this:

```html
<script type="module"> import { Octokit } from "https://cdn.skypack.dev/@octokit/core@3.2.5"; </script>
```

**Comment by IzMichael** [comment]
Hiya, they all fail, unfortunately

**Comment by gr2m** [comment]
okay thanks for testing, I'll check in with the Skypack folks

**Comment by gr2m** [comment]
I just tried to reproduce the problem with Firefox on Mac, and it worked without a problem.

Here is the html file I served locally at localhost:8000 and the code worked as expected

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script type="module">
      import { Octokit } from "https://cdn.skypack.dev/@octokit/core";

      const octokit = new Octokit();
      octokit.request("/").then(({ data }) => console.log(data));
    </script>
  </body>
</html>
```

**Comment by IzMichael** [comment]
Huh, odd. I've managed to resolve my issue by using `fetch()` instead of octokit. I feel like the documentation could be clearer about this, but this may just be me.

**Comment by gr2m** [comment]
> I feel like the documentation could be clearer about this

How? About what exactly?

**Comment by IzMichael** [comment]
Idk, probably just me being dumb, thanks for the help

**Comment by namelessperson0** [comment]
The below works
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script type="module">
      import { Octokit } from "https://cdn.skypack.dev/@octokit/core";

      const octokit = new Octokit();
      octokit.request("/").then(({ data }) => console.log(data));
    </script>
  </body>
</html>
```

But the below does not work
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script type="module">
      import { Octokit } from "https://cdn.skypack.dev/@octokit/core";
    </script>
    
<script>
      const octokit = new Octokit();
      octokit.request("/").then(({ data }) => console.log(data));
</script>
  </body>
</html>
```

**Comment by wolfy1339** [comment]
Skypack is unmaintained and is no longer compatible with Octokit. Use esm.sh instead as written in the README
