### ISSUE TITLE
Pulls API's list method with filter returns incorrect PR

### ISSUE THREAD

**Issue by divyenduz** [octokit/octokit.js#2056]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js
- [ ] Browsers: NA
- [ ] Others: NA

**Versions**

```
$ [octo-pulls]$ npm ls | grep -v deduped | grep octokit
│ ├─┬ @octokit/core@3.3.1
│ │ ├─┬ @octokit/auth-token@2.4.5
│ │ ├─┬ @octokit/graphql@4.6.1
│ │ ├─┬ @octokit/request@5.4.14
│ │ │ ├─┬ @octokit/endpoint@6.0.11
│ │ ├─┬ @octokit/request-error@2.0.5
│ │ ├─┬ @octokit/types@6.13.0
│ │ │ └── @octokit/openapi-types@6.0.0
│ ├─┬ @octokit/plugin-paginate-rest@2.13.3
│ └─┬ @octokit/plugin-rest-endpoint-methods@4.15.0

```

**What happened?**

`pulls.list` when called with `head` filter on a branch returns incorrect PR if there is another branch on the same commit hash. 

**Minimal test case to reproduce the problem**

Minimal reproduction repo https://github.com/divyenduz/octo-pulls

**What did you expect to happen?**

`pulls.list` should have returned an empty array if there is no PR from `branch1` to `main`. 

**What the problem might be**

I can understand if this is the intended behavior. It should be mentioned in the docs (here https://octokit.github.io/rest.js/v18#pulls) though.

**Comment by gr2m** [comment]
You use `@actions/github` in your minimal test case, the repository for that project is https://github.com/actions/toolkit.

I don't know if they use `@octokit/rest` or not. 

Can you reproduce the problem with `curl` or a similar tool to send requests? It's very unlikely a problem with @octokit. 

The docs are generated from GitHub's OpenAPI spec at https://github.com/github/rest-api-description/. If the description for the `puls/list` operation could be improved, could you file an issue there? 

You can also file an issue with the docs team, the endpoint is described here: https://docs.github.com/en/rest/reference/pulls#list-pull-requests, the repository for the GitHub docs is https://github.com/github/docs

**Comment by divyenduz** [comment]
Thanks for the quick response, you are right. 

1. Updated repro to use `@octokit/rest`
2. But I am able to reproduce this with curl
```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/divyenduz/octo-pulls/pulls?head=heads%2Fbranch1" | jq ".[0].title"
```

Will raise it with the docs team. Thank you.

**Comment by divyenduz** [comment]
Ha, quick update for anyone who reads this. It was incorrect usage, the format of `head` parameter is incorrect. 

```
$ [octo-pulls]$ curl \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/divyenduz/octo-pulls/pulls?head=INCORRECT_FORMAT_FOR_HEAD_PARAM" | jq ".[] | .title"

"chore: file"
"chore: fake"
```

When used correctly, it does filter correctly

```
$ [octo-pulls]$ curl \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/divyenduz/octo-pulls/pulls?head=divyenduz:branch | jq ".[] | .title"
```

Create this discussion in docs repo https://github.com/github/docs/discussions/4843
