### ISSUE TITLE
Bug: Erroneous open issue count

### ISSUE THREAD

**Issue by lionel-nj** [octokit/octokit.js#2073]
**Checklist**

- [x] I checked [all open bugs](https://github.com/octokit/rest.js/issues?q=is%3Aissue+label%3Abug) and none of them matched my problem.

**Environment**

- [x] https://api.github.com
- [ ] GitHub Enterprise Server: 
- [ ] GitHub Enterprise Cloud
- [x] Node.js (version `14.16.0`)
- [ ] Browsers: 
- [ ] Others: 

**Versions**

```
├─┬ @octokit/rest@18.5.2
│ ├─┬ @octokit/core@3.3.0
│ │ ├─┬ @octokit/auth-token@2.4.5
│ │ ├─┬ @octokit/graphql@4.6.1
│ │ ├─┬ @octokit/request@5.4.14
│ │ │ ├─┬ @octokit/endpoint@6.0.11
│ │ ├─┬ @octokit/request-error@2.0.5
│ │ ├─┬ @octokit/types@6.12.2
│ │ │ └── @octokit/openapi-types@5.3.2
│ ├─┬ @octokit/plugin-paginate-rest@2.13.0
│ ├── @octokit/plugin-request-log@1.0.3
│ └─┬ @octokit/plugin-rest-endpoint-methods@5.0.0
│   ├─┬ @octokit/types@6.13.0
│   │ └── @octokit/openapi-types@6.0.0

```
**What happened?**

The request to get all open issues includes PRs which is a bug IMHO.

**Minimal test case to reproduce the problem**

https://runkit.com/lionel-nj/bug-issue-count-request

**What did you expect to happen?**

Script output should be **49** instead of 54 as suggested by the number of issues listed [here ](https://github.com/MobilityData/gtfs-validator/issues)

<img width="1116" alt="Capture d’écran, le 2021-04-15 à 17 10 42" src="https://user-images.githubusercontent.com/35747326/114938816-91a1de00-9e0d-11eb-96c2-7f77172c73a7.png">

**What the problem might be**

PRs [848](https://github.com/MobilityData/gtfs-validator/issues/858)-[850](https://github.com/MobilityData/gtfs-validator/issues/850)-[851](https://github.com/MobilityData/gtfs-validator/issues/851)-[854](https://github.com/MobilityData/gtfs-validator/issues/854)-[855](https://github.com/MobilityData/gtfs-validator/issues/855) are listed as issues when executing the request.

**Comment by wolfy1339** [comment]
This isn't a bug with `@octokit/rest` itself, it is merely a wrapper around the GitHub REST API

As noted on [Github's docs for the enpoint](https://docs.github.com/en/rest/reference/issues#list-repository-issues):
> GitHub's REST API v3 considers every pull request an issue, but not every issue is a pull request. For this reason, "Issues" endpoints may return both issues and pull requests in the response. You can identify pull requests by the pull_request key. Be aware that the id of a pull request returned from "Issues" endpoints will be an issue id. To find out the pull request id, use the "List pull requests" endpoint.

**Comment by lionel-nj** [comment]
Thanks @wolfy1339 for this quick answer! Filtering the response data based on `pull_request` key as suggested allowed me to get what I needed.
