### ISSUE TITLE
Can`t get data.meta.link when fetch issues by labels

### ISSUE THREAD

**Issue by tavriaforever** [octokit/octokit.js#209]
Hello! I have a trouble.
When I get repo issues list -> in response I have data.meta.link, that contain link to last page https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/issues.js#L110
I use this link to understand what page is last & it's work well

But, when I am trying to get repos issues list by any labels https://developer.github.com/v3/issues/#list-issues-for-a-repository - in response I haven`t data.meta.link and I cannot know what page is last by filter tags, why? And how can I fix it?

**Comment by kaizensoze** [comment]
Doesn't that just mean the results take up a single page?

```
"use strict";

var Client = require("./../lib/index");

var github = new Client({
    debug: false
});

github.issues.getForRepo({
    user: "mikedeboer",
    repo: "node-github",
    labels: "feedback welcome"  // TODO: test with this commented/uncommented
}, function(err, res) {
    var hasNext = github.hasNextPage(res);
    console.log(hasNext);
    // console.log(err, res);
});

```

**Comment by kaizensoze** [comment]
On a somewhat related note, I believe there's a bug in which providing multiple labels doesn't work, but that's a separate existing issue.

**Comment by kaizensoze** [comment]
Nevermind, the labels param does an intersection so if you provide labels A, B, it only gets issues that have both A and B as opposed to A or B.

Closing this. Feel free to open a new ticket if the problem persists.
