### ISSUE TITLE
favicons.githubusercontent.com response missing Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by Slion** [octokit/octokit.js#2100]
**What happened?**

Fetching favicons from https://favicons.githubusercontent.com/ fails because of missing Access-Control-Allow-Origin header.

**What did you expect to happen?**

Downloading favicons using XMLHttpRequest should work.

**What the problem might be**

Response should have Access-Control-Allow-Origin wildcard I guess.

**Comment by wolfy1339** [comment]
You will have to contact GitHub's support as we aren't GitHub staff.
