### ISSUE TITLE
github.orgs.getMembers 2fa_disabled

### ISSUE THREAD

**Issue by janearc** [octokit/octokit.js#211]
I can't seem to get the `filter: '2fa_disabled'` flag to work for `github.orgs.getMembers()`. I've written a small [test case](https://github.com/avriette/misc/blob/master/list-mfa-users.js). Obviously, you'd need to switch the organisation and you'd need to be an owner of that organisation.

Is this known to be working?

**Comment by janearc** [comment]
Is there anyone we can notify to have this merged?

**Comment by mikedeboer** [comment]
#212 is now merged, so this will be in the next release.
