### ISSUE TITLE
Direct Download

### ISSUE THREAD

**Issue by brunoaugusto** [octokit/octokit.js#2111]
### Please avoid duplicates

- [X] I checked [all open feature requests](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.

### What’s missing?

Direct link to download Octokit

### Why?

For a number of reasons, using CDNs or compiling from sources aren't viable approaches to me and, therefore, I would like a direct link to download the minified JS file to embed into my tiny site. Plain and simple!

### Alternatives you tried

Node, though I try my best to not get involved with it for anything more than a CLI (e.g. Babel)

### Would you be interested in contributing the feature?

- [ ] yes

**Comment by gr2m** [comment]
You'd usually install `octokit` as dependency using `npm` and `yarn` and then have a build step locally, we do not plan to offer a pre-bundled version ourselves

**Comment by brunoaugusto** [comment]
Heh, creating from scratch it is then :(
