### ISSUE TITLE
Cannot import `createNodeMiddleware` from "octokit"

### ISSUE THREAD

**Issue by koahmad** [octokit/octokit.js#2119]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

https://www.typescriptlang.org/play?ssl=19&ssc=1&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgQTGANHAxlApgQxlwDkIATXAWWDLIBtcB3fPOAXzgDMoIQ4AiCFhgQA1sBj8A3ACgZWCADsAzvHxo4AXjiKmKNAAoEMuHHVgAkmQBccAIwO76E3DBRgAN0K4A0rgCetvxunt78zqaMuABGABYQYsq2SMq4OLgwQanpkuzObACUsjLmAHRRcQmiyqVKBvzAKjD4dHSEwEql6d5k4XBGcEIi4jCYYPj+dBD4ZOwFWgB8iC54MACuUIqDwmISpXiqpcDKymu4Nd1EAMK8ILiKMEYuphCMulC245PTZPu4kMoJNB-LU3rgoKUpgBzRoRUxwPCQT4TKYzP4AoFQEGKfB3OGmaLkQICAASuFaEEwAHVoHQyABCcIuQqyFlyBRNOAgGj0JgsXBabB4bykCjUWgMZh4AzmIpyIA

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

```
├── @octokit/app@11.4.2
├── @octokit/webhooks-definitions@0.0.0-development (git+ssh://git@github.com/octokit/webhooks.git#6556ef3f0d784f2bda76d90ce23e6c1950d881d1)
├── @octokit/webhooks@9.8.4
├── octokit@1.0.6
```

### What happened?

I'm attempting to follow this example in the readme: https://github.com/octokit/octokit.js#webhooks

The error is that I'm unable to import `createNodeMiddleware` from "octokit"

```
github-webhook.ts:1:15 - error TS2305: Module '"octokit"' has no exported member 'createNodeMiddleware'.

1 import { App, createNodeMiddleware } from "octokit";
```

Not sure what I'm doing wrong here? Any guidance would be appreciated. 

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by gr2m** [comment]
Oops, sorry for that! I'll look into it shortly, should be an easy fix

**Comment by koahmad** [comment]
Thank you for the quick fix!!
