### ISSUE TITLE
Method for getting All Milestones

### ISSUE THREAD

**Issue by nimit2801** [octokit/octokit.js#2133]
### Please avoid duplicates

- [X] I checked [all open feature requests](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.

### What’s missing?

We need a method to get all milestones, there's already a method to get individual milestones but I was not able to find any method for getting all milestones.

### Why?

Was not able to find a method for getting all milestones. I was trying to make a progress bar of sorts to get progress on milestones.

### Alternatives you tried

Have to hard code the `milestone_number` in `octokit.rest.issues.getMilestone`

eg:

```js
octokit.rest.issues.getMilestone({
  owner: "some owner",
  repo: "some repo",
  milestone_number: 2
})
```

### Would you be interested in contributing the feature?

- [X] yes

**Comment by wolfy1339** [comment]
`octokit.rest` is merely a wrapper around the GitHub REST API. If GitHub doesn't have an api for getting all milestones, then there won't be one here.

You should contact support to suggest the feature.

**Comment by nimit2801** [comment]
Github has the endpoint for getting all the milestones

https://docs.github.com/en/rest/reference/issues#milestones
GET
`/repos/{owner}/{repo}/milestones`

**Comment by wolfy1339** [comment]
My bad.

What versions are you using? Run `npm ls octokit`

**Comment by nimit2801** [comment]
`└── octokit@1.1.0`
would love to make a PR! ✅

**Comment by wolfy1339** [comment]
It's not as simple as making a PR. The endpoint methods are autogenerated from GitHub's published [OpenAPI spec](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.json)

You'd have to check in `@octokit/rest` and all of it's upstreams.

***

Just found the relevant method.

```js
octokit.rest.listMilestones({
    owner: "foo",
    repo: "bar"
});
```

**Comment by nimit2801** [comment]
`(node:29180) UnhandledPromiseRejectionWarning: TypeError: octokit.rest.listMilestones is not a function`

basically method not found 😅 

is this on some latest commit?

**Comment by wolfy1339** [comment]
https://octokit.github.io/rest.js/v18#issues-list-milestones
My bad. it's `octokit.rest.issues.listMilestones()`
