### ISSUE TITLE
List all public repositories missing

### ISSUE THREAD

**Issue by htammen** [octokit/octokit.js#217]
Hi,
I'm missing the [list all public repositories](https://developer.github.com/v3/repos/#list-all-public-repositories) in your API. Did I overlook it or is it really missing?

Regards Helmut

**Comment by hellerve** [comment]
Seconded. Can't find it either.

**Comment by kaizensoze** [comment]
Added: https://mikedeboer.github.io/node-github/#api-repos-getPublic
