### ISSUE TITLE
Error when doing anonymous call with conditional request using etag

### ISSUE THREAD

**Issue by g-hoang** [octokit/octokit.js#2170]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

https://runkit.com/g-hoang/octokit-rest-js-2169

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

+-- @octokit/auth-app@3.6.0
| +-- @octokit/auth-oauth-app@4.3.0
| | +-- @octokit/auth-oauth-device@3.1.2        
| +-- @octokit/auth-oauth-user@1.3.0
| | +-- @octokit/oauth-methods@1.2.4
| | | +-- @octokit/oauth-authorization-url@4.3.3
| +-- @octokit/request@5.6.1
| | +-- @octokit/endpoint@6.0.12
| +-- @octokit/request-error@2.1.0
| +-- @octokit/types@6.27.1
| | `-- @octokit/openapi-types@10.1.4
+-- @octokit/plugin-retry@3.0.9
+-- @octokit/plugin-throttling@3.5.2
+-- @octokit/rest@18.10.0
| +-- @octokit/core@3.5.1
| | +-- @octokit/auth-token@2.4.5
| | +-- @octokit/graphql@4.8.0
| +-- @octokit/plugin-paginate-rest@2.16.1
| +-- @octokit/plugin-request-log@1.0.4
| `-- @octokit/plugin-rest-endpoint-methods@5.10.2

### What happened?

Hi,

I'm trying to cache one of my requests using conditional request with etag. All the calls are anonymous. Here is my code in the test case:

```
const { Octokit } = require('@octokit/rest')
const cache = require('memory-cache')

const octokit = new Octokit({});

const res1 = await octokit.request("GET /gists/{gist_id}", { 
  gist_id: '60e9b5d7ce65ca474c29'
});

cache.put('testCacheKey', res1, 1000 * 60 * 60) // 1 hour

const cachedData = cache.get('testCacheKey')

if (cachedData) {
    try {
        res2 = await octokit.request("GET /gists/{gist_id}", { 
          gist_id: '60e9b5d7ce65ca474c29',
          headers: {
            'If-None-Match': JSON.stringify(cachedData.headers.etag.split('"')[1])
          }
        });
        return res
    }
    catch (error) {
        if (error.status === 304) {
            console.log('Conditional request using etag')
            return cachedData
        } else {
            console.error(error)
        }
    }
}
```

Output:

`RequestError: invalid json response body at https://api.github.com/gists/abczyz123 reason: Unexpected end of JSON input`

The first call (res1) seems to work fine, but in the second call, I added headers `If-None-Match` returned the above output. Most likely I'm doing something wrong here but I cannot find out where is the error.

Thank you in advance and best regards

### Would you be interested in contributing a fix?

- [X] yes

**Comment by Chocrates** [comment]
Hey @g-hoang looks like if you replace your header with this it works

```
headers: {
    "If-None-Match": cachedData.headers.etag.split('"')[1],
}
```
Looks like it just doesn't like the stringify

**Comment by g-hoang** [comment]
Hi @Chocrates 
Thank you for your response. I will try to test follow your recommendation soon.
Just one thing, actually I implemented the same way with the personal access token (not anonymous) and it's working fine. So I'm not sure if the stringify caused the problem

**Comment by Chocrates** [comment]
oh weird @g-hoang, well let me know if it still doesn't work.

**Comment by gr2m** [comment]
The `etag` value can be different depending on how the request is authenticated. I'm not sure if that's the case for all API endpoints, but it is the case for `GET /gists/{gist_id}`. 

I'm going to close this issue as it's very old and I'm pretty sure that is what caused the problem. Feel free to keep commenting if you have any further questions
