### ISSUE TITLE
Add support for new branch protection rules

### ISSUE THREAD

**Issue by jeffreylanters** [octokit/octokit.js#2184]
### Please avoid duplicates

- [X] I checked [all open feature requests](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.

### What’s missing?

When updating branch protection rules, the "Allow specified actors to bypass pull request requirements" option under the "Require a pull request before merging" section is not available. I've looked into the API documentation and GET responses, but it is not present there either. It might not be available at all on API level, but I thought it might be an idea to open this issue as anyway.

### Why?

The missing field is preventing developers for setting alle branch protection rules.

### Alternatives you tried

Using the Request method in order to make the request without the usage of the built-in methods. But the key is unknown at all.

### Would you be interested in contributing the feature?

- [X] yes

**Comment by wolfy1339** [comment]
Thanks for this report :+1:

There's nothing we can do on our side. The types, and functions are auto-generated from GitHub's OpenAPI spec.

The alternative way you have tried is the way to go. There won't be any types, but it will work, you just have to refer to the github api docs.

Unfortunately, the JS octokit packages don't have an active maintainer anymore, so we cannot update the types for the REST endpoints.

You can check out [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174) for further updates
