### ISSUE TITLE
Deno import issue auth-oauth-app

### ISSUE THREAD

**Issue by mfbx9da4** [octokit/octokit.js#2185]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

-

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [X] Deno

### Version

latest version (in deno so npm doesn't apply)

### What happened?

```js
import { Octokit } from 'https://cdn.skypack.dev/octokit?dts'
export { createOAuthAppAuth } from 'https://cdn.skypack.dev/@octokit/auth-oauth-app'
const octokit = new Octokit({
  authStrategy: createOAuthAppAuth,
  auth: {
    clientId: 'foo',
    clientSecret: 'bar',
  },
})
```

throws the following error 
```
TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:aws-lambda?from=@octokit/oauth-app"' has no exported member 'APIGatewayProxyEventV2'. Did you mean to use 'import APIGatewayProxyEventV2 from "https://cdn.skypack.dev/error/unknown:aws-lambda?from=@octokit/oauth-app"' instead?
import { APIGatewayProxyEventV2, APIGatewayProxyStructuredResultV2 } from "/error/unknown:aws-lambda?from=@octokit/oauth-app";
         ~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.6.0-ZkvSUss803B9yJ25ReA6/dist=es2019,mode=types/dist-types/middleware/aws-lambda/api-gateway-v2.d.ts:4:10
```

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by wolfy1339** [comment]
It is known that there are problems with Deno compatibility, as you can see in the [other issues](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Adeno) and the discussion at #1708.

Unfortunately the JS octokit libraries no longer have an active maintainer.

You can read about it in [this discussion](https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174), subscribe to it for further updates.

**Comment by KikeE36** [comment]
> ### Por favor, evite los duplicados.
> * [x] Revisé [todos los errores abiertos](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) y ninguno coincidía con mi problema.
> 
> ### Caso de prueba reproducible
> 
> ### Seleccione los entornos que sean relevantes para su informe de error
> * [x] Mecanografiado
> * [x] Empresa
> * [x] navegadores
> * [x] Nodo
> * [x] Deno
> 
> ### Versión
> última versión (en deno, por lo que no se aplica npm)
> 
> ### ¿Qué sucedió?
> ```js
> importar  {  Octokit  }  desde  'https://cdn.skypack.dev/octokit?dts' 
> exportar  {  createOAuthAppAuth  }  desde  'https://cdn.skypack.dev/@octokit/auth-oauth-app' 
> const  octokit  =  nuevo  Octokit ( { estrategia de 
>   autenticación : createOAuthAppAuth , autenticación : { clientId : 'foo' , clientSecret : 'bar' , } , } )
>   
>     
>     
>   
> ```
> 
> arroja el siguiente error
> 
> ```
> TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:aws-lambda?from=@octokit/oauth-app"' has no exported member 'APIGatewayProxyEventV2'. Did you mean to use 'import APIGatewayProxyEventV2 from "https://cdn.skypack.dev/error/unknown:aws-lambda?from=@octokit/oauth-app"' instead?
> import { APIGatewayProxyEventV2, APIGatewayProxyStructuredResultV2 } from "/error/unknown:aws-lambda?from=@octokit/oauth-app";
>          ~~~~~~~~~~~~~~~~~~~~~~
>     at https://cdn.skypack.dev/-/@octokit/oauth-app@v3.6.0-ZkvSUss803B9yJ25ReA6/dist=es2019,mode=types/dist-types/middleware/aws-lambda/api-gateway-v2.d.ts:4:10
> ```
> 
> ### ¿Estaría interesado en contribuir con una solución?
> * [x] sí

**Comment by KikeE36** [comment]
@KikeE36
