### ISSUE TITLE
repoIssues functionality doesn't return results when request parameter added for multiple labels

### ISSUE THREAD

**Issue by NikhileshKshirsagar** [octokit/octokit.js#219]
I am using following JSON as input to the repoIssues function, the doc. specifies labels attribute functionality as  'String list of comma separated Label names' but if multiple labels are provided no issues are returned.

```
{
    user: "strongloop",
    repo: "generator-loopback",
    labels: "#label1,#label2,#label3"
}
```

To cross check I had used following JSON with only one label, in this case the API returns couple of issues

```
{
    user: "strongloop",
    repo: "generator-loopback",
    labels: "#label1"
}
```

I am not if there is some other way to provided labels but I sure didn't find anything in the documentation.

**Comment by kaizensoze** [comment]
It's not what I was expecting, but the labels param is an intersection as opposed to a union so it'll only return issues that have all three labels: label1, label2, label3.

Closing this. Feel free to create a new ticket if you're still having an issue.
