### ISSUE TITLE
Creating Review Comment on PR is not working

### ISSUE THREAD

**Issue by mvecha** [octokit/octokit.js#2191]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

pull_request_review_thread.end_commit_oid

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

From GitHub Actions. Not sure about the version it is including on runtime.

### What happened?

Expected to create a comment on the PR file given in the request. 

### Would you be interested in contributing a fix?

- [X] yes

**Comment by mvecha** [comment]
I am trying to create comments as review on PR using below snippet

const octokit = github.getOctokit(token);
const request = {
owner: github.context.repo.owner,
repo: github.context.repo.repo,
pull_number : github.context.payload.pull_request.number,
body :"Comeback to me!!!!",
commit_id : github.context.sha,
path : ,
position : 3,
};
octokit.rest.pulls.createReviewComment(request).then((response) => {
resolve(response);
})

I keep getting error pull_request_review_thread.end_commit_oid . Can someone guide me out with this issue.

**Comment by ostiwe** [comment]
Is there any progress with this problem?

**Comment by timrogers** [comment]
@ostiwe Would you be able to confirm what error message you're getting? 

To look into this, I'll need to find your request in the logs. 

If you're able to get the request ID from the response headers to help with debugging, that would be fantastic. 

If you're not able to do that, could you email me the owner, repo and PR number and that'll do the trick too? My email is my GitHub username @github.com.

**Comment by ostiwe** [comment]
@timrogers, 

If I understood correctly, then here: 91F1:D11F:29B00F:2A6BC8:63304991

**Comment by timrogers** [comment]
Hi @ostiwe! Thanks. I can see that you're getting a `422` error. I'd like to try to rule out Octokit being the issue here. Would you be able to try making a request to the API with curl (or another HTTP client), and seeing if you can reproduce the issue?

**Comment by ostiwe** [comment]
Hi @timrogers , I tried to send the exact same request via Postman, as a result I received the same response, here is the request ID: EF58:798B:311BFBD:31DA980:63381A03

**Comment by timrogers** [comment]
Thanks! Would you be able to share the JSON request body? That'll give me everything I need to report this to the relevant team.

**Comment by ostiwe** [comment]
Yep, 
```
{
    "body": "\n            Rule: @typescript-eslint/no-explicit-any\n            Message: Unexpected any. Specify a different type.\n            Lines: 6:51 - 6:54\n    ",
    "commit_id": "5f76c60270592494f2034f937ae7c0c0a62e5492",
    "path": "/app/src/store/publication/index.ts",
    "line": 6,
    "side": "RIGHT"
}
```

**Comment by timrogers** [comment]
Thanks! I think your best bet would be to [contact GitHub support](https://support.github.com/?tags=dotcom-footer) with this one. I'd share the request ID, request body and response body. Sorry that we can't help you more here!

**Comment by ostiwe** [comment]
Okay, thanks
