### ISSUE TITLE
Pagination is not documented

### ISSUE THREAD

**Issue by mfornasa** [octokit/octokit.js#220]
README.md should report some code sample about pagination mechanisms.

**Comment by LeonardoGentile** [comment]
+1

**Comment by mikedeboer** [comment]
Pull requests welcome!

**Comment by tmarshall** [comment]
Is there a way to paginate, or is that missing?

**Comment by tmarshall** [comment]
Ah I [see it](https://github.com/mikedeboer/node-github/blob/master/index.js#L539) now
