### ISSUE TITLE
Releases API Not Returning Expected Results When Authenticated

### ISSUE THREAD

**Issue by johnlindquist** [octokit/octokit.js#2203]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

https://runkit.com/johnlindquist/6218ede3781696000867e25e

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

Latest

### What happened?

I'm investigating this issue: https://github.com/johnlindquist/kit/issues/741#issuecomment-1050850122

It seems like something changed in the releases API or Octokit that returns different results when authenticated. 
The issue is also reflected in the release page UI:

![image](https://user-images.githubusercontent.com/36073/155737423-a0f1da03-1fab-43ef-97f0-3bc2b27e7b87.png)

When signed-out:

```json
[
    "1.6.9",
    "1.6.8",
    "1.6.7",
    "1.6.6-alpha.4",
    "1.6.6-alpha.3",
    "1.6.6-alpha.2",
    "1.6.6-alpha.1",
    "1.6.5",
    "1.6.4",
    "1.6.3",
    "1.6.2",
    "1.6.1",
    "1.6.0",
    "1.6.0-alpha.6",
    "1.6.0-alpha.5",
    "1.6.0-alpha.4",
    "1.5.1",
    "1.4.4",
    "1.4.3",
    "1.4.1",
    "1.4.0-beta.1",
    "1.3.2-beta.2",
    "1.3.1",
    "1.3.0-beta.133",
    "1.3.0",
    "1.3.0-beta.132",
    "1.3.0-alpha.264",
    "1.3.0-alpha.260",
    "1.3.0-alpha.259",
    "1.3.0-alpha.258"
]
```

When signed-in:

```json
[
    "1.6.6-alpha.5",
    "1.6.6",
    "1.6.0-alpha.3",
    "1.6.0-alpha.2",
    "1.6.0-alpha.1",
    "1.5.0",
    "1.4.2",
    "1.4.0",
    "1.3.2-beta.1",
    "1.3.0-alpha.267",
    "1.3.0-alpha.266",
    "1.3.0-alpha.265",
    "1.3.0-alpha.263",
    "1.3.0-alpha.262",
    "1.3.0-alpha.261",
    "1.3.0-alpha.254",
    "1.3.0-alpha.253",
    "1.3.0-alpha.251",
    "1.3.0-alpha.242",
    "1.3.0-alpha.241",
    "1.3.0-alpha.240",
    "1.3.0-alpha.239",
    "1.3.0-alpha.238",
    "1.3.0-alpha.237",
    "1.3.0-alpha.236",
    "0.0.0-development",
    "1.3.0-alpha.234",
    "1.3.0-alpha.233",
    "1.3.0-alpha.232",
    "1.3.0-alpha.231"
]
```

### Would you be interested in contributing a fix?

- [X] yes

**Comment by wolfy1339** [comment]
The issue seems to be that you are using draft releases, instead use the pre-release option.

Draft releases show up higher than regular releases as to remind you to publish them from my understanding, and only show up for maintainers of the repo.

This isn't anything actionable on octokit's side.

**Comment by johnlindquist** [comment]
@wolfy1339 That makes sense, thanks.

This code had worked fine for almost a year, then broke in the past couple days. So the "drafts are higher" change must have happened recently.

**Comment by timrogers** [comment]
@johnlindquist Thanks for taking the time to report this issue! It looks like there was a subtle change to the API here in terms of how it sorts results, which it probably doesn't make sense to address in Octokit, so I'm going to close this. If you disagree with me, do feel free to reopen it!
