### ISSUE TITLE
Missing get/add team membership

### ISSUE THREAD

**Issue by rissem** [octokit/octokit.js#221]
[add-team-member](https://developer.github.com/v3/orgs/teams/#add-team-member) has been deprecated in favor of [add-team-membership](https://developer.github.com/v3/orgs/teams/#add-team-membership). Likewise for remove-team-member.

I'm happy to take a stab at this if you're open to a pull request.

**Comment by mikedeboer** [comment]
@rissem we certainly are!

**Comment by OllieJennings** [comment]
Is this issue being actively worked on? 

if not am willing to get a pull request in this weekend

**Comment by area** [comment]
For anyone else looking for these endpoints, #224 appears to incorporate these changes.

**Comment by kaizensoze** [comment]
Added
