### ISSUE TITLE
listWorkflowRuns does not list latest runs

### ISSUE THREAD

**Issue by pkit** [octokit/octokit.js#2214]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

Are you kidding?

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

$ yarn why octokit
yarn why v1.22.18
[1/4] Why do we have the module "octokit"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "octokit@1.7.1"
info Has been hoisted to "octokit"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "108KB"
info Disk size with unique dependencies: "2.9MB"
info Disk size with transitive dependencies: "11.15MB"
info Number of shared dependencies: 8
Done in 0.09s.

### What happened?

Running a test function like the one below does not list the latest workflow runs in the repo.
```js
async function main (owner, repo, branch, workflow) {
    const github = new octokit.Octokit({ auth: process.env.GITHUB_TOKEN })
    const params = {
        owner,
        repo,
        workflow_id: workflow,
        status: "success",
        branch,
    }
    github.rest.actions
        .listWorkflowRuns(params)
        .then((res) => {
            console.log(res.data)
        })
        .catch((e) => {
            console.log(e.message);
        });
}
```
Was working perfectly for a long time, but not right now.
Started happening after the worklow yaml file was changed.
It always lists only the workflows before the change.
Using `gh run list --workflow workflow.yaml` lists all the runs, but `octokit.js` doesn't.
I.e. `gh` lists 25 runs and the code above: 22 runs.
What's going on?

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by pdemro** [comment]
@pkit The query returns more responses if you remove some of the filter parameters (status, branch, etc).  Obviously this isn't a solution but may be a band aide for some

**Comment by pdemro** [comment]
Not sure if someone on the Octokit team is messing with me, but around the exact time I posted my previous comment, this SDK method started working again 🤷‍♂️.  I wonder if @pkit can confirm?  Maybe this is an intermittent issue?

**Comment by pkit** [comment]
@pdemro Yup, I've opened a support ticket in github and it got fixed today.
