### ISSUE TITLE
removeAssignees fails when not providing optional assignees parameter

### ISSUE THREAD

**Issue by pozil** [octokit/octokit.js#2221]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

See code in description

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [X] Node
- [ ] Deno

### Version

Just imported latest octokit version with npm:
```
└─┬ octokit@1.7.1
  ├─┬ @octokit/app@12.0.5
  │ ├─┬ @octokit/auth-app@3.6.1
  │ ├─┬ @octokit/auth-unauthenticated@2.1.0
  │ └─┬ @octokit/webhooks@9.24.0
  │   ├── @octokit/webhooks-methods@2.0.0
  │   ├── @octokit/webhooks-types@5.6.0
  ├─┬ @octokit/core@3.6.0
  │ ├─┬ @octokit/auth-token@2.5.0
  │ ├─┬ @octokit/graphql@4.8.0
  │ ├─┬ @octokit/request@5.6.3
  │ │ ├─┬ @octokit/endpoint@6.0.12
  │ ├─┬ @octokit/request-error@2.1.0
  ├─┬ @octokit/oauth-app@3.6.2
  │ ├─┬ @octokit/auth-oauth-app@4.3.1
  │ │ ├─┬ @octokit/auth-oauth-device@3.1.2
  │ ├─┬ @octokit/auth-oauth-user@1.3.0
  │ ├── @octokit/oauth-authorization-url@4.3.3
  │ ├─┬ @octokit/oauth-methods@1.2.6
  ├─┬ @octokit/plugin-paginate-rest@2.17.0
  ├─┬ @octokit/plugin-rest-endpoint-methods@5.13.0
  ├─┬ @octokit/plugin-retry@3.0.9
  ├─┬ @octokit/plugin-throttling@3.6.2
  └─┬ @octokit/types@6.34.0
    └── @octokit/openapi-types@11.2.0
```

## Issue
When calling `octokit.rest.issues.removeAssignees()` without supplying the `assignees` parameter, the request fails with:
```
HttpError: Body should be a JSON object
```

The problem is that `assignees` is [not marked as required in the docs](https://docs.github.com/en/rest/issues/assignees#remove-assignees-from-an-issue).

Note that the doc is correct because the REST query can run without the `assignees` parameter. However, the request body must be an empty JSON object `{}` otherwise, you'll get the same error.

![Screen Shot 2022-05-30 at 21 27 24](https://user-images.githubusercontent.com/5071767/171050674-899b223e-1b8c-4037-b9f4-806a72b78e6e.png)

## Repro code
```js
const { Octokit } = require("octokit");

// Create a personal access token at https://github.com/settings/tokens/new?scopes=repo
const octokit = new Octokit({ auth: 'MY_TOKEN' });

const run = async () => {
  const response = await octokit.rest.issues.removeAssignees({
    owner: 'pozil',
    repo: 'temp',
    issue_number: 1
  });
  console.log(JSON.stringify(response, null, 4));
}

run();
```

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by timrogers** [comment]
@pozil Thanks for submitting this issue! What do you expect the API to do when you don't specify any assignees?

**Comment by timrogers** [comment]
It looks to me, from trying it, that the API does nothing if you don't supply the `assignees` parameter. It looks like really there is a bug in the API here - it should enforce that the assignees are provided.

**Comment by pozil** [comment]
Yes, I think that the Node client should align with the behavior of the REST API and the docs.

Suggested fix:
- Mark `assignees` as required in the [REST API docs](https://docs.github.com/en/rest/issues/assignees#remove-assignees-from-an-issue)
- Throw an error in the REST API when `assignees` is missing
- Have a meaningful error message in the Node client such as "Missing required assignees parameter" instead of "HttpError: Body should be a JSON object"

**Comment by timrogers** [comment]
👍🏻 Glad we're in agreement. I have created an issue with the Issues team at GitHub (😂 ) to ask them to take a look at this.

**Comment by pozil** [comment]
Awesome, thanks.

**Comment by timrogers** [comment]
@gr2m What do you think of adding an override in `octokit/openapi` to mark `assignees` as required? If you don't have it, the endpoint is no-op, which seems like a GitHub API bug 😓

**Comment by timrogers** [comment]
Technically, that would be a breaking change to the Octokit.js types, but it is only tidying up a case that is broken right now and which our types shouldn't permit. 

It looks like the Issues team will fix it in the API itself, but that will take a while.

**Comment by gr2m** [comment]
> Technically, that would be a breaking change to the Octokit.js types, but it is only tidying up a case that is broken right now and which our types shouldn't permit.

I wouldn't consider it a breaking change if we fix an incorrect behavior.

> @gr2m What do you think of adding an override in `octokit/openapi` to mark `assignees` as required

Sure, we can add the override here: https://github.com/octokit/openapi/tree/main/scripts/overrides. But we should remove it once GitHub fixes it on their side, because an override is an all-or-nothing for an operation, so we will miss all future updates to that operation as long as our override exists

**Comment by timrogers** [comment]
> > Technically, that would be a breaking change to the Octokit.js types, but it is only tidying up a case that is broken right now and which our types shouldn't permit.
> 
> 
> 
> I wouldn't consider it a breaking change if we fix an incorrect behavior.
> 
> 
> 
> > @gr2m What do you think of adding an override in `octokit/openapi` to mark `assignees` as required
> 
> 
> 
> Sure, we can add the override here: https://github.com/octokit/openapi/tree/main/scripts/overrides. But we should remove it once GitHub fixes it on their side, because an override is an all-or-nothing for an operation, so we will miss all future updates to that operation as long as our override exists

Sounds good to me. I'll add that override tomorrow and will tag you. 

I'm following the internal GitHub issue on the Issues side so I'll be aware when they fix it. It may need to be treated as a breaking change though, since this is a long-standing behaviour, so it could take a while.

**Comment by timrogers** [comment]
This is now fixed at the SDK level - Typescript will complain if you don't set the `assignees`.

<img width="1421" alt="Screenshot 2022-07-15 at 12 51 00" src="https://user-images.githubusercontent.com/116134/179217698-8e6f8f07-ad29-4d6f-931d-1031cb0ce237.png">
