### ISSUE TITLE
issue with Path property on repo.updateFile

### ISSUE THREAD

**Issue by SleepyBandit** [octokit/octokit.js#227]
Maybe it is just me, but I'm having trouble getting repo.updateFile to work properly.
When I copy the path of my test file via the button on github, I see the following path 

```
'{RepoName}/test.html'
```

When I use this as the path required for repo.updateFile it creates a directory within the repo with the repo's name, and then creates a new test.html file inside of it.  The return response provides this new files SHA and everything.

Obviously this isn't what I wanted it to do. I wanted it to update the test.html file in the root of the repo, not create a folder and a new file with the same name in it.  What makes it worst, is if I use the returned SHA to try and update the newly created file I get the same error I show below.

When I test the code with the appropriate SHA of the test.html file that is housed in the root of my repo, and I fix the path property to match [how it is documented](https://developer.github.com/v3/repos/contents/#update-a-file), i.e) path: 'test.html', it does not work.  I receive the following error;

```
{ [Error: {"message":"test.html does not match {COMMIT SHA NUMBER}","documentation_url":"https://developer.github.com/v3/repos/contents/"}]
  message: '{"message":"test.html does not match {COMMIT SHA NUMBER}","documentation_url":"https://developer.github.com/v3/repos/contents/"}',
  code: 409 }
```

I think this may relate [to issue 160](https://github.com/mikedeboer/node-github/issues/160)

any thoughts or ideas?

for reference purposes, here is my code;

```
var GitHubApi = require("github");

var github = new GitHubApi({
    version: "3.0.0"
});

github.authenticate({
    type: "basic",
    username: 'USERNAME',
    password: 'PASSWORD'
});

var msg = {
    user: 'USERNAME',
    repo: 'REPO-NAME',
    path: 'test.html',
    message: 'test update via api',
    content: new Buffer("Hello World").toString('base64'),
    sha: 'mySHANumberGoesHere',
    branch:'BRANCH-NAME'
};

github.repos.updateFile(msg, function(err, response){
    if (err) {
        console.log(err);
    } else {
        console.log(response);
        console.log('New SHA: '+response.commit.sha)
    }
});
```

**Comment by SleepyBandit** [comment]
Ok I am pretty sure this was just me.  The SHA I was using from the browser was incorrect. Not sure why, but when I query for the SHA via the API I get a different string back.  This other SHA appears to work.  Just figured I'd clear this up here. Even for testing, use the API for fetching your SHA value.

**Comment by ghost** [comment]
@SleepyBandit How did you query the SHA that did work?

**Comment by SleepyBandit** [comment]
Pretty straight forward. Just create a repo, and call to the file you're looking to work with. the current SHA is a property of the returned data (which I've given the name of info in this example).  Log the entirety of the info object if you want to see what else it provides.

```
var octo = new Octokat({
    username: 'username',
    password: 'password'
});

var repo = octo.repos('username', 'repoName');
repo.contents('fileName.txt').fetch(function(err, info) {
    if (err) {
        console.log(err);
    } else {
        console.log('fileName.txt SHA number is: ' + info.sha);
    }
});
```
