### ISSUE TITLE
can not access content property

### ISSUE THREAD

**Issue by taronlee** [octokit/octokit.js#2273]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

```js
const { data } = await octokit.request('GET /repos/{owner}/{repo}/contents/{path}',  {
       owner: 'taronlee',
       repo: 'testoctokit',
       path: 'test.json'
     }
);
console.log(data.content);
```
### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

$ npm ls | grep -v deduped | grep octokit
├── @octokit/types@6.41.0
├── octokit@2.0.5

### What happened?

must set the type `any`.
otherwise, I can not access content property.
It's weired in Typescript.

![bug1](https://user-images.githubusercontent.com/18044244/184085468-410be967-2ab6-4f28-9f25-4e9a4aff2b71.png)

``` json
console.log(data)
{
    "name": "test.json",
    "path": "test.json",
    "sha": "8acbaa2ad0edc0b8d7909fe7d9a210ddfa5c1e9e",
    "size": 203,
    "url": "https://api.github.com/repos/taronlee/testoctokit/contents/test.json?ref=develop",
    "html_url": "https://github.com/taronlee/testoctokit/blob/develop/test.json",
    "git_url": "https://api.github.com/repos/taronlee/testoctokit/git/blobs/8acbaa2ad0edc0b8d7909fe7d9a210ddfa5c1e9e",
    "download_url": "https://raw.githubusercontent.com/taronlee/testoctokit/develop/test.json",
    "type": "file",
    "content": "ewogICJhcHBzIjogWwogICAgewogICAgICAiaWQiOiAib2N0b2tpdCIsCiAg\nICAgICJuYW1lIjogIm9jdG9raXQiLAogICAgICAiZGVzY3JpcHRpb24iOiAi\nb2N0b2tpdCIKICAgIH0sCiAgICB7CiAgICAgICJpZCI6ICJ0YXJvbiIsCiAg\nICAgICJuYW1lIjogInRhcm9uIiwKICAgICAgImRlc2NyaXB0aW9uIjogInRh\ncm9uIiAgICAgIAogICAgfQogIF0KfQo=\n",
    "encoding": "base64",
    "_links": {
        "self": "https://api.github.com/repos/taronlee/testoctokit/contents/test.json?ref=develop",
        "git": "https://api.github.com/repos/taronlee/testoctokit/git/blobs/8acbaa2ad0edc0b8d7909fe7d9a210ddfa5c1e9e",
        "html": "https://github.com/taronlee/testoctokit/blob/develop/test.json"
    }
}
```

### Would you be interested in contributing a fix?

- [x] yes

**Comment by wolfy1339** [comment]
This is a known issue, it's currently blocked upstream.
https://github.com/octokit/rest.js/issues/32

**Comment by taronlee** [comment]
Thank you for the answer.
I'll check it out.

**Comment by wolfy1339** [comment]
I'm going to close this in favor of the other issue mentioned.
