### ISSUE TITLE
`pull request` api doesn't work when .yml file in .github/workflow is added

### ISSUE THREAD

**Issue by taronlee** [octokit/octokit.js#2290]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

await this.octokit.request('PUT /repos/{owner}/{repo}/contents/{path}', {   ...uploadYML,   owner: app.org,   repo: app.repo,   path: '.github/workflows/lumos-publish.yml' }); await this.octokit.request('POST /repos/{owner}/{repo}/pulls', {   owner: app.org,   repo: app.repo,   title: title,   body: title,   head: 'develop',   base: 'lumos-publish' });

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

2.0.5

### What happened?

# step
1. upload .yml file for adding github actions to `A branch`
```javascript
await this.octokit.request('PUT /repos/{owner}/{repo}/contents/{path}', {
  ...uploadYML,
  owner: app.org,
  repo: app.repo,
  path: '.github/workflows/lumos-publish.yml'
});
```
2. .yml file is added successfully on `A branch`
![image](https://user-images.githubusercontent.com/18044244/187816696-f29b7a1f-15b3-4ae8-bca2-f6781a5ae1a1.png)
3. But, `pull request` api doesn't work.
```javascript
await this.octokit.request('POST /repos/{owner}/{repo}/pulls', {
  owner: app.org,
  repo: app.repo,
  title: title,
  body: title,
  head: 'develop',
  base: 'lumos-publish'
});
```
![image](https://user-images.githubusercontent.com/18044244/187817389-0751a5d4-9fb5-4c7c-ba7b-24656b821679.png)

when I commit something into `.github` folder,
`octokit` cannot determine whether a new file has been added.
(I can make pr on web pages, **but I want to add github actions and make pr automatically**.)

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by timrogers** [comment]
@taronlee Hi there! Sorry to hear you're having issues working with Octokit. Can you help me a bit more to understand what you're trying to do? 

Are you trying to create your `.github/workflows/lumos-publish.yml` file on one branch, and then create a pull request to merge it into another branch? What branch do you want to create the file on, and what branch do you want to merge into?

I'd recommend using the https://github.com/gr2m/octokit-plugin-create-pull-request Octokit plugin for this. It's from one of our JavaScript contributors, and it makes this much easier.

**Comment by taronlee** [comment]
It works, Thank you for your help.
