### ISSUE TITLE
Inconsistent API for createRef and deleteRef

### ISSUE THREAD

**Issue by Stono** [octokit/octokit.js#2307]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

See comment

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

❯ npm ls | grep -v deduped | grep octokit
├── @octokit/rest@19.0.4

### What happened?

I got caught out by this today, to create a branch - you can do:

```
      await this.octoKit.rest.git.createRef({
        owner: 'whatever',
        owner: 'whatever',
        ref: 'refs/heads/whatever',
        sha: 'whatever
      })
```

But in order to delete the branch:

```
      await this.octoKit.rest.git.deleteRef({
        owner: 'whatever',
        owner: 'whatever',
        ref: 'heads/whatever'
      })
```

Note in the create, the ref needs to be prefixed with `refs`, whereas in the `deleteRef`, it needs to be omitted.

### Would you be interested in contributing a fix?

- [ ] yes

**Comment by timrogers** [comment]
Hi @Stono! 👋🏻 I can definitely see that this is a bit confusing and inconsistent. 

We wouldn't want to fix this in Octokit though - for consistency, we try to make sure that this SDK mirrors the GitHub API's design. Making these kinds of cosmetic adjustments in the SDK itself would probably make things more confusing, as they wouldn't match up with the GitHub API docs!

I'd recommend submitting your feedback [here](https://github.com/community/community/discussions/categories/api-and-webhooks) for the product team that owns that API.

**Comment by Stono** [comment]
Totally valid @timrogers - thanks for the pointer, will feed it back there!

**Comment by Stono** [comment]
@timrogers - realistically api changes, even if agreed, would take a long time to surface.  To save people getting caught out by it, i think it'd be ok for `deleteRef` to throw an error if someone passes `refs/` at the start though?

That way we're not silently drifting from the API, but we are preventing people running into a known weird UX issue.

Just trying to save the next sucker a couple of hours :D

**Comment by timrogers** [comment]
I’m definitely on board with helping people not to make mistakes and making it clearer when their parameter is wrong. But I’m mindful of adding more complexity here or ending up with a solution that only works in Octokit.js.

What do you think of proposing a change to the GitHub API to return a clearer error in this case?

From: Karl Stoney ***@***.***>
Date: Friday, 16 September 2022 at 18:32
To: octokit/octokit.js ***@***.***>
Cc: Tim Rogers ***@***.***>, Mention ***@***.***>
Subject: Re: [octokit/octokit.js] Inconsistent API for createRef and deleteRef (Issue #2307)

@timrogers<https://github.com/timrogers> - to save people getting caught out by it, i think it'd be ok for deleteRef to throw an error if someone passes refs/ at the start though?

Just trying to save the next sucker a couple of hours :D
