### ISSUE TITLE
Allow updating social preview image of the repository

### ISSUE THREAD

**Issue by ShivamJoker** [octokit/octokit.js#2329]
### Please avoid duplicates

- [X] I checked [all open feature requests](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Afeature) and none of them matched my problem.

### What’s missing?

I looked up everywhere but couldn't find an API which we can use to update the social preview of the repository.

Right now it's only possible with GUI:
![image](https://user-images.githubusercontent.com/23727670/197276514-449d8926-11a9-4ad6-b641-bef3768865ef.png)

### Why?

I want to show latest info about the repository and my projects on the social preview.

### Alternatives you tried

No alternatives

### Would you be interested in contributing the feature?

- [X] yes

**Comment by gr2m** [comment]
I'm afraid but there is no such API right now, there is nothing we can do with the SDKs. 

The right place to ask is https://github.com/community/community/discussions/categories/api-and-webhooks
