### ISSUE TITLE
GET /orgs/${string}/repos returns OctokitResponse<any, number>

### ISSUE THREAD

**Issue by Inrixia** [octokit/octokit.js#2337]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAelWgFMyAoVxgOwGd5qNs8ALxxOTAO4oaggBQBKdnTpwAJgEMYauMG5w1nAJ4cIPeEnWa4+EWvFqccfrRgA6KEwCOAVya8ZZAHEAUQAVODpoAHNuOiYADzVwABsmOndIbjI5IA

### Please select the environment(s) that are relevant to your bug report

- [X] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [ ] Deno

### Version

^4.1.0

### What happened?

The types exist in the `Endpoints`, `paths` and `openapi-types` but for some reason `any` is being returned.

### Would you be interested in contributing a fix?

- [X] yes

**Comment by gr2m** [comment]
You have to use the path that includes the path parameters with the URL template notation

```js
const { data } = await octokit.request("GET /orgs/{org}/repos", { org: "example" })
```

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAelWgFMyAoVxgOwGd5qNs8ALxxOTAO4oaggBQBKdl16I4AEwCGMdXHwj149Tjj9aMAHRQmARwCuTXjLIBxAKIAVOHWgBzbnQQ+uHSWkNxkADQqPgBc5EwAHurgADYsOnJAA)

**Comment by alper** [comment]
Are return types untyped in this library?

**Comment by gr2m** [comment]
Responses of all known endpoints are fully typed
