### ISSUE TITLE
`deno run` dependencies with `Requires authentication`

### ISSUE THREAD

**Issue by mr-kelly** [octokit/octokit.js#2341]
### Please avoid duplicates

- [X] I checked [all open bugs](https://github.com/octokit/octokit.js/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.

### Reproducible test case

import { Octokit } from "https://cdn.skypack.dev/octokit?dts";

### Please select the environment(s) that are relevant to your bug report

- [ ] TypeScript
- [ ] Enterprise
- [ ] Browsers
- [ ] Node
- [X] Deno

### Version

import { Octokit } from "https://cdn.skypack.dev/octokit?dts";

### What happened?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/520852/199966684-52d1711f-3edd-404b-a708-0f9f814ac36c.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/520852/199967852-3c0dcac9-66d0-4faa-a6fa-69c70530efac.png">

As the picture show.

This is a new problem today..

I run same script success 12 hours ago.

```
error: Uncaught (in promise) HttpError: Requires authentication
      const error = new RequestError(toErrorMessage(data), status, {
                    ^
    at https://cdn.skypack.dev/-/@octokit/request@v6.2.1-nNBYVdjyDnH6n0gpygNS/dist=es2019,mode=imports/optimized/@octokit/request.js:81:21
    at async Job.doExecute (https://cdn.skypack.dev/-/bottleneck@v2.19.5-WnyfIkTTdKNNPUEySJVJ/dist=es2019,mode=imports/unoptimized/light.js:354:20)
```

### Would you be interested in contributing a fix?

- [x] yes

**Comment by mr-kelly** [comment]
still error until now

**Comment by gr2m** [comment]
Can you please test if you see the error with when using `@octokit-next/core`?

You can use https://esm.sh/ which I think is what the Deno folks recommend:
https://esm.sh/@octokit-next/core@2.6.0

`@octokit-next/*` is not production ready, but it's a native ESM and built with Deno compatibility in mind.

**Comment by mr-kelly** [comment]
> Can you please test if you see the error with when using `@octokit-next/core`?
> 
> You can use https://esm.sh/ which I think is what the Deno folks recommend: https://esm.sh/@octokit-next/core@2.6.0
> 
> `@octokit-next/*` is not production ready, but it's a native ESM and built with Deno compatibility in mind.


what you mean, should i import from esm.sh? @gr2m 

```
import { Octokit } from "https://esm.sh/octokit?dts";
```

I encounter same problem yet.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/520852/200571355-e75cba54-6ff0-4787-9817-8c40db590ecd.png">

**Comment by mr-kelly** [comment]
> Can you please test if you see the error with when using `@octokit-next/core`?
> 
> You can use https://esm.sh/ which I think is what the Deno folks recommend: https://esm.sh/@octokit-next/core@2.6.0
> 
> `@octokit-next/*` is not production ready, but it's a native ESM and built with Deno compatibility in mind.

I found that this problem will appear under my macOS (M1) native `deno`.

Success with `docker run -it --init denoland/deno:1.23.1 deno run`

**Comment by gr2m** [comment]
I was not able to reproduce the problem with my M1 machine, using Deno 1.26.1 and Deno 1.27.1 (latest version)

```js
// test.js
import { Octokit } from "https://cdn.skypack.dev/octokit?dts";
```

and then run with

```
deno run test.js
```

**Comment by gr2m** [comment]
@mr-kelly did you find out what the problem was?

**Comment by mr-kelly** [comment]
> @mr-kelly did you find out what the problem was?

sorry...no... i switch to NodeJS and give up the Deno version  @gr2m
