### ISSUE TITLE
[FEAT]: stats/metrics counters like count user private/public commits, count user private/public repos, count private/public starred

### ISSUE THREAD

**Issue by faustoct1** [octokit/octokit.js#2347]
### Describe the need

Possibility of endpoints to get stats / metrics in read-only mode counters like: count user private/public commits, count user private/public repos, count private/public starred can give insights and open a huge opportunity for developers build things to improve developers career.

### SDK Version

4.1.0

### API Version

no

### Relevant log output

```shell
A read only endpoint app to get more user stats of public/private repos, commits, gists, starred.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Unfortunately, this isn't the right place to request new endpoints.

Octokit is only a client for the API, meaning we only implement the GitHub API.

The proper place to request such feature would be at: https://github.com/orgs/community/discussions/categories/api-and-webhooks

**Comment by faustoct1** [comment]
@jokernomade cc
