### ISSUE TITLE
Add support of web application flow

### ISSUE THREAD

**Issue by aivus** [octokit/octokit.js#236]
https://developer.github.com/v3/oauth/#web-application-flow

Current implementation doesn't support retrieving `access_token` for web application flow, when `code` should be exchanged on `access_token`.

Related: #182 #16

**Comment by jamestalmage** [comment]
The `code` is used server side to complete an oath flow. Implementing an `oath` flow seems outside the scope of this project.

[github-oath](https://www.npmjs.com/package/github-oauth) looks like a good solution. I haven't tried it myself, but after a quick review the API seems sane enough.

**Comment by kaizensoze** [comment]
Yeah web application flow is out of scope and on a per webapp basis. In addition to [github-oauth](https://github.com/maxogden/github-oauth), there's also [passport-github2](https://www.npmjs.com/package/passport-github2).
