### ISSUE TITLE
repos.compareCommits incorrectly errors when used with Accept: 'application/vnd.github.diff'

### ISSUE THREAD

**Issue by amillward** [octokit/octokit.js#237]
When trying to retrieve the diff between two commits (using header Accept: 'application/vnd.github.diff'), the response errors as it is not JSON but is trying to be parsed as if it is.

It should handle non-JSON responses gracefully.

**Comment by shuhrat** [comment]
Same as https://github.com/mikedeboer/node-github/issues/235
