### ISSUE TITLE
[BUG]: failure to retrieve project by ID: 403 on REST API, null using GraphQL

### ISSUE THREAD

**Issue by TluwaniMS** [octokit/octokit.js#2382]
### What happened?

Pardon me team I'm trying to use octokit to get a project by id.

  const project = await octokit.rest.projects.get({ project_id: projectId });
  
  I get 403 telling me I should have admin rights, although the project is public and I've granted the app admin rights on the project.
  
  I tried using the graphql option:
  but it's returning null for the project.

### Versions

Octokit.js V^2.0.10 Node v16.14.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
can you post the full error you are seeing? Where does the `octokit` instance come from?
