### ISSUE TITLE
[FEAT]:  CloudQuery Source Plugin

### ISSUE THREAD

**Issue by yevgenypats** [octokit/octokit.js#2389]
### Describe the need

Extracting data from GitHub API to build an "operational datalake".

Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are asked for a [GitHub source plugin](https://www.cloudquery.io/docs/plugins/sources/github/overview), and we already shipped a first version.

As we have limited capacity to maintain all plugins, we are usually looking for the official vendor to help maintain it (similar to terraform provider).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync/ELT GitHub APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Hi! That's cool to see. Unfortunately we do not have the capacity to do so at this time.
