### ISSUE TITLE
[BUG]: Bad credentials when passing auth to octokit but not on the request itself

### ISSUE THREAD

**Issue by statusunknown418** [octokit/octokit.js#2390]
### What happened?

```typescript
// When doing it this way it throws a 401 Bad credentials
const octokit = new Octokit({ auth: ghu_token })

octokit.request('GEt /users/{username}/repos')
```
I inspected the network and the authorization header is `token 12332123`.

After that I tried passing the header to the request itself like this and worked, is it a bug?

``` typescript
 const getRepos = async () => {
    if (!userName || !githubToken) return;

    const { data } = await octokit.request("GET /users/{username}/repos", {
      username: userName,
      headers: {
        "If-None-Match": "",
        authorization: `${githubToken}`,
      },
    });
  };
```

And how can I make this work when instantiating `new Octokit({ auth: token })`

### Versions

Octokit 2.0.14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
> After that I tried passing the header to the request itself like this and worked, is it a bug?

No, github expects the token to be prefixed with `token ` in the `authorization` header.

**Comment by statusunknown418** [comment]
I encountered another issue, when trying to get `user/installations` it always throws `401 Bad Credentials`, however I'm using Next-auth github integration and successfully getting a `ghu` token. Any idea why this may be happening?

**Comment by statusunknown418** [comment]
Update: Found a fix, seems like it's necessary to enable `require oAuth while installing` feature on the Github App settings.
