### ISSUE TITLE
[FEAT]: API support for new Project

### ISSUE THREAD

**Issue by vadorvatsal** [octokit/octokit.js#2397]
### Describe the need

When I am running
- `gh api -H "Accept: application/vnd.github+json" /orgs/ORGNAME/projects` 
- `gh api -H "Accept: application/vnd.github+json" /repos/OWNER/REPO/projects`
- `gh api -H "Accept: application/vnd.github+json" /users/USERNAME/projects`
- `gh api -H "Accept: application/vnd.github+json" /orgs/ORG/teams/TEAM_SLUG/projects`

for my paid organization, it returns empty list `[]`

As I see in [documentation](https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28#list-organization-projects) that current API only supports **Project (classic)** .

Can we have feature which supports **new Project** and have all current functionality of boards, columns, cards and other API for it?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timrogers** [comment]
﻿At the moment, the new GitHub Projects is only supported in the GraphQL API, so you’d need to use GraphQL queries instead. There is a separate Octokit package which helps with GraphQL requests. Hope that helps!

From: Vatsal ***@***.***>
Date: Friday, 10 February 2023 at 08:51
To: octokit/octokit.js ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [octokit/octokit.js] [FEAT]: API support for new Project (Issue #2397)
Describe the need

When I am running gh api -H "Accept: application/vnd.github+json" /orgs/<org-name>/teams/<team-slug>/projects command for my paid organization, it returns empty list []

As I see in documentation<https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28#list-organization-projects> that current API only supports Project (classic) .

Can we have feature which supports new Project and have all current functionality of boards, columns, cards and other API for it?

SDK Version

No response

API Version

No response

Relevant log output

No response

Code of Conduct

  *   I agree to follow this project's Code of Conduct

**Comment by vadorvatsal** [comment]
@timrogers Is it https://github.com/octokit/graphql.js that you're referring to?

**Comment by wolfy1339** [comment]
> Can we have feature which supports new Project and have all current functionality of boards, columns, cards and other API for it?

We don't have control over GitHub's API, we only provide an API client.

If you would like to suggest new features, at the following page: https://github.com/orgs/community/discussions/categories/api-and-webhooks

> timrogers Is it https://github.com/octokit/graphql.js that you're referring to?

That would be it. Also note, it is included in the `octokit` and `@octokit/core` packages

**Comment by gr2m** [comment]
You might find https://github.com/gr2m/github-project/ useful, it's built on top of octokit, to make it easier to interact with a new Project (v2)
