### ISSUE TITLE
[BUG]: React Native Support

### ISSUE THREAD

**Issue by Ic3b3rg** [octokit/octokit.js#2406]
### What happened?

Following the official github guide I continually encounter the problem that octokit keeps giving me errors to call the github api doing the same code on react web on stackblitz works. Is there no support on react native ? 

code:

```
import { Octokit } from "octokit";

const octokit = new Octokit({ 
  auth: 'YOUR-TOKEN',
});

await octokit.request("GET /repos/{owner}/{repo}/issues", {
  owner: "github",
  repo: "docs",
  per_page: 2
});
```

### Versions

latest version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
What kind of errors are you getting?

React native should work fine

**Comment by Ic3b3rg** [comment]
It was my mistake  sorry a lot
