### ISSUE TITLE
How to retrieve user info and public repos of a user?

### ISSUE THREAD

**Issue by ashking** [octokit/octokit.js#243]
Hi, I did not understand this package documentation. and I'm unable to find the right object to use to get a specific user's info and to get the list of public repositories. 

https://developer.github.com/v3/repos/#list-user-repositories

Any help is much appreciated.

**Comment by hbi99** [comment]
@ashking
Agree...the documentation is a little cryptic and the lack of example code makes it a little bit confusing. I'm trying to understand as well...though, I have managed to  do what you're looking for:

``` js

var GitHubApi = require("github");

var github = new GitHubApi({
    // required
    version: "3.0.0",
    // optional
    debug: true,
    protocol: "https",
    host: "api.github.com", // should be api.github.com for GitHub
    pathPrefix: "", // for some GHEs; none for GitHub
    timeout: 5000,
    headers: {
        "user-agent": "Some cool app" // GitHub is happy with a unique user agent
    }
});

github.authenticate({
    type: "basic",
    username: "username",
    password: "password"
});

/* gets all repos as an array
 */
github.repos.getAll({}, function(err, list) {
    console.log( list );
});
```

**Comment by kaizensoze** [comment]
get user's info: https://mikedeboer.github.io/node-github/#api-users-getForUser
get public repos: https://mikedeboer.github.io/node-github/#api-repos-getPublic

**Comment by zahidalidev** [comment]
Agree... use this end point and you will get all public repos details for specific user

https://api.github.com/users/username/repos

and for all public details use like this
https://api.github.com/users/username/repos/events/public

**Comment by jagadeeshdevula** [comment]
Hi,
I want to see on my Linux machine who all are using my public repository in Github.
Except for the Github-Dorks tool.
Is it possible?
If, Yes please tell me those tool names.

Thanks.
