### ISSUE TITLE
Ignore webhook labeled event if issue was just created

### ISSUE THREAD

**Issue by faisalsayed10** [octokit/octokit.js#2444]
### What happened?

Is there a way to ignore the `issues.labeled` webhook, if I labeled the issue during creation?

The problem is:
I have two webhook listeners set up - `issues.opened` and `issues.labeled`. Now, when I create an issue on Github, I add some labels during creation and then hit create. 

However, this results in both the webhooks being called and leads to duplicate errors on our backend, i.e `issues.opened` and `issues.labeled`. Is there a way I can ignore the labeled event if it happened during issue creation?

### Versions

```
"@octokit/webhooks": "^10.9.1"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
You can handle the `issue.opened` event and keep a record of the issue then check in the `issue.labelled` event if you have seen it for the opened event.

Otherwise, there isn't a way. It's how github sends the webhooks

**Comment by faisalsayed10** [comment]
Ah i see. Cool I'll close this issue.
