### ISSUE TITLE
[BUG]: incorrect type of `data` parameter for `pulls.update` that should be object but TS compiler expects `never`

### ISSUE THREAD

**Issue by atsu85** [octokit/octokit.js#2445]
### What happened?

# TypeScript compiler error
TypeScript compiler error is produced when trying to close Pull Request with:
```TypeScript
  await octokit.pulls.update({
    owner: organization,
    repo,
    pull_number: prNumber,
    data: {
//  ^^^^ error TS2322: Type '{ state: string; }' is not assignable to type 'never'.
      state: 'closed',
    },
  })
```
TypeScript emits error for `data` parameter:
`TS2322: Type '{ state: string; }' is not assignable to type 'never'`

# Workaround
This seems to be an issue with TypeScript types, because when `data` is manually cast to `never` TS compiles and when running the code, it closes the PR as expected:
```TypeScript
...
    data: {
      state: 'closed',
    } as any as never, // <-- WORKAROUND
...
```

# Expected behaviour
I would expect that original code works without the workaround that casts `data` to `never`

### Versions

@octokit/rest v19.0.7
Node v18.12.1
**UPDATE: @octokit/types: 17.0.0 - root cause of this bug, [fixed in 17.1.1](https://github.com/octokit/openapi-types.ts/releases/tag/v17.1.1)**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Can you share what version of `@octokit/types` is installed?

**Comment by wolfy1339** [comment]
This seems like an issue with your code, and not cause by the types. Though there might be an unrelated issue withthe types.

The correct way to do that is to do it like so:

```ts
  await octokit.pulls.update({
    owner: organization,
    repo,
    pull_number: prNumber,
    state: 'closed',
  })
```

**Comment by atsu85** [comment]
@wolfy1339 , thanks for quick response, but
`1)`
> This seems like an issue with your code, and not cause by the types.

No, the issue was with types! Problem was related to transitive dependency `@octokit/types` version 17.0.0 - after `npm uninstall @octokit/rest && npm install @octokit/rest` `@octokit/types` was upgraded to 17.1.1, that fixed the bug as mentioned in the [changelog](https://github.com/octokit/openapi-types.ts/releases/tag/v17.1.1):
> update the types for the patch to fix occurences of never (https://github.com/octokit/openapi-types.ts/issues/309) ([032e20f](https://github.com/octokit/openapi-types.ts/commit/032e20f29f3de6408dfe3de41154e29df58f0a81))

`2)`
> The correct way to do that is to do it like so:

Both versions work with `@octokit/types@17.1.1` (i also tried them both before reporting this issue), but neither of them compiles with `@octokit/types@17.0.0` where your approach is generating different TS compiler error:
> TS2345: Argument of type '{ owner: string; repo: string; pull_number: number; state: string; }' is not assignable to parameter of type 'RequestParameters & Omit<{ owner: string; repo: string; pull_number: number; } & { data: never; }, "headers" | "baseUrl" | "mediaType">'.
  Property 'data' is missing in type '{ owner: string; repo: string; pull_number: number; state: string; }' but required in type 'Omit<{ owner: string; repo: string; pull_number: number; } & { data: never; }, "headers" | "baseUrl" | "mediaType">'.
