### ISSUE TITLE
[BUG]: Unable to import from Skypack CDN

### ISSUE THREAD

**Issue by ipselon** [octokit/octokit.js#2450]
### What happened?

Error loading https://cdn.skypack.dev/@octokit/core from CDN.

[Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").

Details are here: https://github.com/skypackjs/skypack-cdn/issues/354

### Versions

https://cdn.skypack.dev/@octokit/core

### Relevant log output

```shell
/*

[Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/lru-cache/dist/mjs/index.js
Unexpected token (406:4) in lru-cache/dist/mjs/index.js
Install failed.
Install failed.
How to fix:
If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
Use https://skypack.dev/ to find a web-friendly alternative to find another package.
*/
console.warn("[Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").\n[1/5] Verifying package is valid…\n[2/5] Installing dependencies from npm…\n[3/5] Building package using esinstall…\nRunning esinstall...\nFailed to load node_modules/lru-cache/dist/mjs/index.js\n Unexpected token (406:4) in lru-cache/dist/mjs/index.js\nInstall failed.\nInstall failed.");
throw new Error("[Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").");
export default null;
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Darcrandex** [comment]
same problem, help please 🤣

**Comment by gr2m** [comment]
This is the line it chokes on for you:
https://unpkg.com/browse/lru-cache@9.1.1/dist/mjs/index.js#L406

The `#` is a private class field, it's supported since Node 12?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by gr2m** [comment]
Try to use https://esm.sh instead

It fails on skypack

https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV

but it works on esm.sh

https://esm.sh/v122/lru-cache@9.1.1/es2022/lru-cache.mjs

**Comment by tnguyen14** [comment]
@gr2m when I tried to replace `https://cdn.skypack.dev/octokit@2` with `https://esm.sh/octokit@2`, the request for https://esm.sh/v122/@octokit/auth-app@4.0.10/es2022/auth-app.mjs returned a 500 error code.

**Comment by gr2m** [comment]
Hmm the latest version is 4.0.13, and that works: https://esm.sh/v122/@octokit/auth-app@4.0.13/es2022/auth-app.mjs

I assume there is some caching going on 🤔 We don't pin the versions. I don't know if there is a way to invalidate cache on esm.sh, that would be really good to know, we might integrate cache busting into our release process. Could you try to find out?

**Comment by Netail** [comment]
I am facing the same issue with >=2.0.15

`import { App, Octokit } from 'https://cdn.skypack.dev/octokit?dts';`

```js
Error: [Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
    at https://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app:20:7
```
    
`https://cdn.skypack.dev/octokit@2.0.14?dts` seems to be the last workable version.

**Comment by wolfy1339** [comment]
Please try using the version on `esm.sh` instead. There seems to be a problem with Skypack

Switch your imports to https://esm.sh/octokit

**Comment by JayKim88** [comment]
> 

@Netail,

Hello, Netali!   Thanks a lot for your comment, now i fixed the error :) 
Sorry but, could u let me know how you found the last version of octokit available ?? 
(Is there a page or something the version mentioned?)
Because it might happen again, thus i want to find solution as you did. 

Thank you once again!

**Comment by Netail** [comment]
> > 
> 
> @Netail,
> 
> Hello, Netali! Thanks a lot for your comment, now i fixed the error :) Sorry but, could u let me know how you found the last version of octokit available ?? (Is there a page or something the version mentioned?) Because it might happen again, thus i want to find solution as you did.
> 
> Thank you once again!

I saw the issue occuring yesterday, but knew it worked since the last deployment over a week ago.
So on https://github.com/octokit/octokit.js/releases I picked an older release and checked if it worked, which it did for 2.0.14.

**Comment by JayKim88** [comment]
> 

@Netail 
Thank you for your valuable comment! 
I'll keep tracking on this error:)

**Comment by wolfy1339** [comment]
I have submitted octokit/app.js#422 to bump the dependency on `@octokit/auth-app` to alleviate some of the caching issues with esm.sh

**Comment by gr2m** [comment]
https://github.com/octokit/app.js/pull/422 is merged and released as `@octokit/app@13.1.5`

**Comment by wolfy1339** [comment]
@ipselon @Netail Can you try again, with this new release
```js
import { Octokit } from "https://esm.sh/octokit@2.0.19";
```

**Comment by amenowanna** [comment]
> @ipselon @Netail Can you try again, with this new release
> 
> ```js
> import { Octokit } from "https://esm.sh/octokit@2.0.19";
> ```

This import is resolving our issues in Deno. Thank you!

**Comment by wolfy1339** [comment]
> This is the line it chokes on for you: https://unpkg.com/browse/lru-cache@9.1.1/dist/mjs/index.js#L406
> 
> The `#` is a private class field, it's supported since Node 12? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

Private class fields is an ES2022 feature, while the Skypack CDN uses ES2019 which makes it choke on that line.

https://dev.to/smitterhane/private-class-fields-in-javascript-es2022-3b8

The feature may have been supported in NodeJS v12 back when it was still a proposal and not ratified into the ECMAScript spec

**Comment by denizdogan** [comment]
Anyone else hitting this error now?

```ts
import { App } from "https://esm.sh/octokit";
```

```
error: Uncaught SyntaxError: The requested module '/v125/@octokit/oauth-app@4.2.2/denonext/oauth-app.mjs' does not provide an export named 'createNodeMiddleware'
    at <anonymous> (https://esm.sh/v125/@octokit/app@13.1.5/denonext/app.mjs:2:842)
```

**Comment by wolfy1339** [comment]
How are you getting that error? `createNodeMiddleware` is exported from `@octokit/oauth-app`

**Comment by denizdogan** [comment]
@wolfy1339 I am literally just trying to import `App` from `octokit`, example:

```
❯ echo 'import { App } from "https://esm.sh/octokit"; console.log(App);' > foobar.ts

❯ cat foobar.ts
import { App } from "https://esm.sh/octokit"; console.log(App);

❯ deno

❯ deno run --unstable -A --no-lock --reload foobar.ts
error: Uncaught SyntaxError: The requested module '/v125/@octokit/oauth-app@4.2.2/denonext/oauth-app.mjs' does not provide an export named 'createNodeMiddleware'
    at <anonymous> (https://esm.sh/v125/@octokit/app@13.1.5/denonext/app.mjs:2:842)
```

**Comment by denizdogan** [comment]
This error happens with v3.0.0-beta.3 as well.

Environment:

```
❯ deno --version
deno 1.34.2 (release, aarch64-apple-darwin)
v8 11.5.150.2
typescript 5.0.4
```

I also tried clearing out `DENO_DIR` from caches, but it ultimately didn't help.

**Comment by denizdogan** [comment]
Overriding the dependency to use 4.2.1 or 5.0.0-beta.3 fixes the issue. 4.2.2 seems to have [modified the build process](https://github.com/octokit/oauth-app.js/pull/416) so I'm guessing that has something to do with it?

Please advise me on how to proceed – should I create an issue in that repo?

**Comment by wolfy1339** [comment]
Yes, please open an issue on that repository.

I'll have to look into that. The export is definitely there in the source code

**Comment by hilbix** [comment]
I can confirm hat v2.0.19 still **fails** for browsers.

FWIW:  The workaround at my side *is* to use

    <script type="module">import { Octokit, App } from 'https://cdn.skypack.dev/octokit@v2.0.14'; window.octokit={Octokit,App}</script>

instead of

    <script type="module">import { Octokit, App } from 'https://cdn.skypack.dev/octokit'; window.octokit={Octokit,App}</script>  

which was not obvious to me, *and this probably is not the correct way to solve the issue*.

PS: I opened #2471, sorry, because I used `"browser"` in my search, so this bug did not show up.  Lesson learned:  I should have a look more closely into more current issues on a list.

**Comment by wolfy1339** [comment]
I think that we should stop recommending the Skypack CDN in light of the issues people are having with it.

Looking at their GitHub repos, they don't seem to have been updated.
The issues on the Skypack CDN don't seem to be getting answered either.

Deno currently recommends esm.sh, and removed any mention of Skypack from their docs, from version 1.31.2 onwards.

---

@hilbix Try using `esm.sh` instead
```ts
import { Octokit, App } from "https://esm.sh/octokit@2.0.19";
```

**Comment by gr2m** [comment]
> I think that we should stop recommending the Skypack CDN in light of the issues people are having with it.

Yes. The skypack folks moved on with their focus to Astro, we should replace it everywhere with esm.sh

**Comment by amenowanna** [comment]
We are having to drop to version `2.0.14` to address the latest set of issues.

**Comment by wolfy1339** [comment]
Please stop using the Skypack CDN. Use ESM.sh instead

```ts
import { Octokit } from "https://esm.sh/octokit@2";
```

Skypack is no longer maintained.

We will be updating our docs to make the switch.

Please don't comment with "me too" messages, use the reactions instead.
Unless you have something to add that is constructive to this issue.

Thanks

**Comment by amenowanna** [comment]
@wolfy1339 we have been using esm and `2.0.19` is not working. Based on your latest recommendation I wanted to note that we had to drop to version '2.0.14`. I don't feel like this is a me too comment as the conclusion on this thread didn't seem correct.

**Comment by wolfy1339** [comment]
You should have specified it was with ESM.sh then.

Either way, it is a different bug.

I think there's already another issue opened in another repo about this.

Can you share the error you get?

**Comment by amenowanna** [comment]
@wolfy1339 I apologize for causing frustration by not providing more details. As part of this issue with  Deno we switched to esm with version `2.0.19` which resolved our issues with the CDN. However, that same version rstarted to show the error below and we were not able to find a solution. Several of the linked issues point back to this issue so I wanted to let the community know that a workaround for not only the CDN but also the latest issue with oauth which I see the linked issue for was to downgrade to version `2.0.14`. In the future I will try and be more robust in my comments. We love this project and really appreciate the work you put into it as it supports our OSS project as well.

```
The requested module '/v125/@octokit/oauth-app@4.2.2/deno/oauth-app.mjs' does not provide an export named 'createNodeMiddleware'
```

**Comment by wolfy1339** [comment]
Ah yes, that issue is known. It is being tracked in https://github.com/octokit/oauth-app.js/issues/424

**Comment by wolfy1339** [comment]
We have updated the docs to stop recommending Skypack.

If anyone has any further issues, please open up a new one

**Comment by hilbix** [comment]
FTR: I can confirm that, at my side, the browser issues are gone with the `esm.sh` URl from documentation.  Thank you very much!
