### ISSUE TITLE
this.constants munges what's defined in this.config during initializations

### ISSUE THREAD

**Issue by landongn** [octokit/octokit.js#246]
setting up a test to see if GHE is supported and it seems like it is.

however, when attempting to query a known user from GHE using the setup perscribed in the readme, i'm redirect to use the public github.com apis rather than the prefixed GHE host. 

It looks like the constants are always used within the config from the `routes.defines` area rather than the config.

**Comment by kaizensoze** [comment]
A lot has changed since this ticket was created. Are you still seeing this?

**Comment by kaizensoze** [comment]
There was an issue where any provided host in the config was being clobbered by the default non-enterprise one. It's been fixed.
