### ISSUE TITLE
Get Latest Release API not implemented

### ISSUE THREAD

**Issue by Voxelot** [octokit/octokit.js#247]
The readme says the release API is 100% implemented but I can't find any references to this API in the docs or the code:
https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by GochoMugo** [comment]
:+1: please! please! please! :pray:

**Comment by shana** [comment]
:+1: on this

**Comment by dfarr** [comment]
:+1:

**Comment by owenthereal** [comment]
:+1:

**Comment by princejwesley** [comment]
:+1:

**Comment by unfulvio** [comment]
:+1:

**Comment by kaizensoze** [comment]
I have getLatestRelease included in a fork: https://github.com/kaizensoze/github4

**Comment by kaizensoze** [comment]
Merged into upstream

https://mikedeboer.github.io/node-github/#api-repos-getLatestRelease
