### ISSUE TITLE
[BUG]: Introduction of breaking changes in a patch release

### ISSUE THREAD

**Issue by wolfy1339** [octokit/octokit.js#2477]
### What happened?

Automated renovate PRs were merged that contained breaking changes, since those versions dropped support for Node v14, v16

Now users won't be able to install these packages anymore

### Versions

Octokit.js 2.0.21

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gavacq** [comment]
This is affecting our project as well and preventing new builds.

**Comment by wolfy1339** [comment]
PRs hat need to be reverted #2474 and #2475

**Comment by estraph** [comment]
Confirming that this broke the release of one of our projects, because node 14 isn't supported anymore

```
 error @octokit/request-error@4.0.2: The engine "node" is incompatible with this module. Expected version ">= 18". Got "14.18.3"
```

**Comment by estraph** [comment]
Thanks for sorting this out @wolfy1339 @kfcampbell  - error no longer happening for me.
