### ISSUE TITLE
[BUG]: Unable to import from Skypack CDN

### ISSUE THREAD

**Issue by brunojuliao** [octokit/octokit.js#2494]
### What happened?

I use the octokit to authenticate my users and then retrieve files from a repo. It was working up to Saturday. Now I am getting the error below:

[Package Error] "@octokit/core@v5.0.0" could not be built. (Imported by "@octokit/rest").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/@octokit/core/dist-web/index.js
  Unexpected token (13:9) in @octokit/core/dist-web/index.js
Install failed.
Install failed.

### Versions

Octokit.js v.19

import { Octokit } from "https://cdn.skypack.dev/@octokit/rest";

### Relevant log output

```shell
[Package Error] "@octokit/core@v5.0.0" could not be built. (Imported by "@octokit/rest").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/@octokit/core/dist-web/index.js
  Unexpected token (13:9) in @octokit/core/dist-web/index.js
Install failed.
Install failed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
We don't recommend users use Skypack as it's not maintained anymore, and we use features that are too new for it to handle.

Instead we recommend people use ESM.sh
