### ISSUE TITLE
[DOCS]: global fetch warning is confusing

### ISSUE THREAD

**Issue by skeddles** [octokit/octokit.js#2495]
### Describe the need

Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.

```
const { Octokit } = require("octokit");
const nodefetch = import("node-fetch");
const octokit = new Octokit({ auth: KEY, request: {fetch: nodefetch.fetch} });
```

```
const { Octokit } = require("octokit");
global.fetch = import("node-fetch").fetch;
const octokit = new Octokit({ auth: KEY, request: {fetch: fetch} });
```

```
const { Octokit } = require("octokit");
const {fetch}= import("node-fetch");
const octokit = new Octokit({ auth: KEY, request: {fetch: fetch} });
```

I've tried every combination I can think of, and can't get it to work. Please provide a working example of how I am supposed to make this work. 

### Relevant log output

```shell
Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
    at fetchWrapper (/home/skeddles/azlador.com/node_modules/@octokit/request/dist-node/index.js:57:11)
    at request2 (/home/skeddles/azlador.com/node_modules/@octokit/request/dist-node/index.js:172:14)
    at hook (/home/skeddles/azlador.com/node_modules/@octokit/auth-token/dist-node/index.js:58:10)
    at async requestWithGraphqlErrorHandling (/home/skeddles/azlador.com/node_modules/octokit/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
    at async Job.doExecute (/home/skeddles/azlador.com/node_modules/bottleneck/light.js:405:18)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Abrarhaj** [comment]
Ok

**Comment by wolfy1339** [comment]
Please answer the following questions in order for us to help you:
* What platform? Deno? Web? NodeJS?
* What version of that platform?
* What version of Octokit are you using?
* What version of `node-fetch`?

**Comment by skeddles** [comment]
node
v16.17
^3.0.0 (latest)
^3.3.1 (latest)

**Comment by wolfy1339** [comment]
That is the issue, we don't support Node JS 16 in version 3.x of Octokit

**Comment by wolfy1339** [comment]
I agree that the message might be confusing, reopening to track a possible wording of the message

**Comment by gr2m** [comment]
you cannot combine `require` and `import` statements. If you use CommonJS (`require`), then install `node-fetch@2` and try this

```js
const { Octokit } = require("octokit");
const fetch = require("node-fetch");
const octokit = new Octokit({ auth: KEY, request: {fetch} });
```

But as @wolfy1339 mentioned, while this might work, we dropped official support for Node 16. Node 16 will no longer be maintained at all in two months: https://nodejs.dev/en/about/releases/.

**Comment by wolfy1339** [comment]
Closing in favor of #2457
