### ISSUE TITLE
Throw a helpful error when `fetch` is not set

### ISSUE THREAD

**Issue by oscard0m** [octokit/octokit.js#2497]
- [x] octokit/octokit.js#2499
- [x] #2500
- [x] octokit/request.js#616

---

Maybe we could add a section to the README and link to it from the error, so we can provide a more thorough explanation and most importantly we can update whenever needed.

I'd say the availability of `fetch` is independent of the Node version. `fetch` is still experimental and it can be disabled with `--no-experiemental-fetch`. Also `Node` is not the only place where Octokit is run, I'm not sure if e.g. Electron or React Native have a global `fetch` method. 

I'd do something like this:

> `fetch` is not set. Please pass a `fetch` implementation as `new Octokit({ request: { fetch }})`. Learn more at https://github.com/octokit/octokit.js/#fetch-missing

_Originally posted by @gr2m in https://github.com/octokit/octokit.js/issues/2486#issuecomment-1633271530_

**Comment by gr2m** [comment]
should we rename this issue to 

> Throw a helpful error when `fetch` is not set

I don't think the error is really about Node 14/16 compatibility
