### ISSUE TITLE
Why so much duplicated code ?

### ISSUE THREAD

**Issue by zallek** [octokit/octokit.js#251]
First of all, thank you for your lib it works
But why is there so much duplicated code ?
The same 20 lines of code are repeated again and again. .
Which is a bit sad, as people can be afraid and it weights the lib.

**Comment by zallek** [comment]
I mean can we do something about it ?

**Comment by mikedeboer** [comment]
This is because all the code is generated with generate.js.
In the next push I'll update that script to add comments in the files that are auto-generated.
