### ISSUE TITLE
[DOCS]: Code examples, statement ending with a colon

### ISSUE THREAD

**Issue by michaelsatish** [octokit/octokit.js#2515]
### Describe the need

The README document has the below code statement ending with a colon. It should be a semicolon. There are three occurrence in the whole document.

```js
import { createServer } from "node:http":
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Thank you for spotting those errors. Would you like to submit a fix for them?

**Comment by michaelsatish** [comment]
@wolfy1339 You're welcome. I will submit a PR.
