### ISSUE TITLE
Documentation is unclear on Typescript usage of this package

### ISSUE THREAD

**Issue by alper** [octokit/octokit.js#2525]
### Describe the need

I can't find any documentation here about what the Typescript return types are of Octokit.

Say here:
```typescript
export async function createBranch(
  repo: string,
  {
    token,
    ref,
    sha,
  }: {
    token: string;
    ref: string;
    sha: string;
  }
): Promise<any> {
  const octokit = buildOctokit(token);

  const res = await octokit.rest.git.createRef({
    owner: OWNER,
    repo,
    ref,
    sha,
  });

  return res.data;
}
```

It's unclear to me how to type the return type.

Is it true that the project does not supply any and we need to use something like this? 
https://www.npmjs.com/package/@octokit/plugin-rest-endpoint-methods

It seems weird that this is a typescript package without type support.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sangdth** [comment]
I face similar issue. When I check, it shows that the `request` accepts a `RequestParameters`, but I can not import it from `octokit` because it does not export that.

I tried to Google as well as searching across Github's Octokit's issues, but still can not find a good answer. Why it's so hard for a TypeScript project?

**Comment by alper** [comment]
I have to test it but for the createBranch function I now have this which seems to work as far as ts is concerned:

```typescript
import { RestEndpointMethodTypes } from "@octokit/plugin-rest-endpoint-methods";

Promise<RestEndpointMethodTypes["git"]["createRef"]["response"]>
```

**Comment by wolfy1339** [comment]
If you don't want to dig into the internals of Octokit, or just want a simple solution, you can simply use the [`ReturnType`](https://www.typescriptlang.org/docs/handbook/utility-types.html#returntypetype) utility built into typescript.

```ts
type OctokitReturn = ReturnType<Octokit["rest"]["git"]["createRef"]>
```

**Comment by gr2m** [comment]
use `@octokit/types`: https://github.com/octokit/types.ts#examples

```ts
import { Endpoints } from "@octokit/types";

type listUserReposParameters =
  Endpoints["GET /repos/{owner}/{repo}"]["parameters"];
type listUserReposResponse = Endpoints["GET /repos/{owner}/{repo}"]["response"];

async function listRepos(
  options: listUserReposParameters,
): listUserReposResponse["data"] {
  // ...
}
```
