### ISSUE TITLE
authorization problem

### ISSUE THREAD

**Issue by marcinwal** [octokit/octokit.js#253]
I am trying to get access to github using my client id, secret and app; 
It does not work on my server side but it works if use same credentials for jquery $.get method.
My code to authorize is:

creating a github client:

var github = new GitHubApi({
  version: "3.0.0",
  debug: true,
  protocol: "https",
  host: "api.github.com",
  timeout: 5000,
});

and then : 

github.authorization.create({
  "scopes" : ["user"],
  "note" : "admin server rights",
  "app": {
    "name" : "gitHubNetwork",
    "client_id" : process.env['GITHUB_CLIENT_ID'],
    "client_secret" : process.env['GITHUB_CLIENT_SECRET']
  }
});
I am getting the reply:

running server on port:3000
STATUS: 401
HEADERS: {"server":"GitHub.com","date":"Mon, 18 May 2015 10:47:22 GMT","content-type":"application/json; charset=utf-8","content-length":"138","connection":"close","status":"401 Unauthorized","x-ratelimit-limit":"60","x-ratelimit-remaining":"57","x-ratelimit-reset":"1431949287","x-github-media-type":"github.v3; format=json","x-xss-protection":"1; mode=block","x-frame-options":"deny","content-security-policy":"default-src 'none'","access-control-allow-credentials":"true","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","x-github-request-id":"4D64523D:71E0:36478:5559C33A","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff"}
[error] { [Error: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3/oauth_authorizations/#oauth-authorizations-api"}]

What am I doing wrong if you could help ?

Marcin

**Comment by mAAdhaTTah** [comment]
You can't just create a new authorization; the client has to be authenticated first.

**Comment by kaizensoze** [comment]
You have to authenticate first: https://github.com/mikedeboer/node-github#authentication
