### ISSUE TITLE
[MAINT]: Pin peter-evans/create-or-update-comment action for all

### ISSUE THREAD

**Issue by nickfloyd** [octokit/octokit.js#2534]
### Describe the need

So we've implemented an [immediate response action](https://github.com/octokit/octokit.js/blob/main/.github/workflows/immediate-response.yml) across all SDK repos and did not pin the version of `peter-evans/create-or-update-comment action`.  This causes an enormous amount of chatter in dependabot PRs when commits are made. 

We should do 2 things here:
1. Use our automatic [publish-project-workflow](https://github.com/octokit/.github/blob/main/.github/workflows/publish-project-workflow.yml) to publish the [immediate response action](https://github.com/octokit/octokit.js/blob/main/.github/workflows/immediate-response.yml)  workflow across all octokit owned repos.
2. Build the template pinning the action to v3.0.2 so: `uses: peter-evans/create-or-update-comment@v3.0.2`

### SDK Version

All SDK repos

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
An alternative might be to use a reusable workflow: https://github.blog/2022-02-10-using-reusable-workflows-github-actions/

I never tried it, but I think it would let us have a single place where we wrap an action like peter-evans/create-or-update-comment that we need to update on new releases. And all the @octokit repositories would reference our shared workflow and never need to be updated ever.

**Comment by nickfloyd** [comment]
@gr2m that's a good thought - I think I tried that originally but I got roadblocked by bot permissions - I'll need to have another look - given that we are not just octokit but also maintaining the integrations org as well it made things a bit bumpy there.

**Comment by gr2m** [comment]
> I got roadblocked by bot permissions

Hm let me know if you run into permission problems again, we might need to use a bot token instead of the provided GITHUB_TOKEN in order to access cross repository workflows?
