### ISSUE TITLE
[BUG]: Typings not resolving correctly for rest/checks/get & rest/checks/update

### ISSUE THREAD

**Issue by Codex-** [octokit/octokit.js#2564]
### What happened?

I noticed this when trying to use `octokit.rest.checks.update`:

```ts
const octokit = github.getOctokit(config.token);

// Should error with the required props not being provided
octokit.rest.checks.update({});
```

I inspected the params further, comparing with `create`, using `status` as an example:
```ts
// "queued" | "in_progress" | "completed" | undefined
type CheckCreateStatus = NonNullable<Parameters<Octokit["rest"]["checks"]["create"]>[0]>["status"];

// unknown
type CheckUpdateStatus = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["status"];
```

Appears to be related to the type generation for `/repos/{owner}/{repo}/check-runs/{check_run_id}`

The documentation indicates that `status` should be available, but trying to get any types for this endpoint results in unknown:
```ts
// unknown
type owner = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["owner"];
// unknown
type repo = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["repo"];
// unknown
type name = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["name"];
// unknown
type details_url = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["details_url"];
// unknown
type external_id = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["external_id"];
// unknown
type started_at = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["started_at"];
// unknown
type status = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["status"];
// unknown
type conclusion = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["conclusion"];
// unknown
type completed_at = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["completed_at"];
// unknown
type output = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["output"];
// unknown
type actions = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["actions"];
```

### Versions

Node 20.8.1

```yml
  /@actions/core@1.10.1:
    resolution: {integrity: sha512-3lBR9EDAY+iYIpTnTIXmWcNbX3T2kCkAEQGIQx4NVQ0575nk2k3GRZDTPQG+vVtS2izSLmINlxXf0uLtnrTP+g==}
    dependencies:
      '@actions/http-client': 2.2.0
      uuid: 8.3.2
    dev: false

  /@actions/github@6.0.0:
    resolution: {integrity: sha512-alScpSVnYmjNEXboZjarjukQEzgCRmjMv6Xj47fsdnqGS73bjJNDpiiXmp8jr0UZLdUB6d9jW63IcmddUP+l0g==}
    dependencies:
      '@actions/http-client': 2.2.0
      '@octokit/core': 5.0.1
      '@octokit/plugin-paginate-rest': 9.1.0(@octokit/core@5.0.1)
      '@octokit/plugin-rest-endpoint-methods': 10.1.0(@octokit/core@5.0.1)
    dev: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I just double checked the generated endpoints and types, and the URL parameters are set as required, the body parameters are all defined as you would expect.

Are you able to use Octokit directly instead of using `@actions/github` in order to isolate the issue?

**Comment by Codex-** [comment]
The same results for me when using the latest `octokit` directly.

```ts
import type { Octokit } from "octokit";

// unknown
type owner = NonNullable<Parameters<Octokit["rest"]["checks"]["update"]>[0]>["owner"];

// Same results for the other expected types too
```

`update`:
![image](https://github.com/octokit/octokit.js/assets/8297838/7f94d1c9-9c94-4440-92dd-2e2c4a551fe5)

`create`:
![image](https://github.com/octokit/octokit.js/assets/8297838/090f7293-f469-4f77-a6d0-79f0c333585f)

**Comment by wolfy1339** [comment]
Thanks for confirming that. I can't seem to reproduce this myself.

In the Typescript transpilation of the OpenAPI spec everything seems fine.

Are you able to diagnose this?

**Comment by wolfy1339** [comment]
The base types from `@octokit/types` are correct, it's when we create method types over in `@octokit/plugin-rest-endpoint-methods` where things start going foul.

You can see in my TypeScript playground the issue [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUQHYBNLFTAznAXzgDMoIQ4AiAAQgGMYIBrYGAehgE8wBTXSgNwAoUJFiI4AeQbNWhEmQo16jFuyh8YgoULZs4ABTK8ocLmGwBzfKXJwABrRlqO3PvaHmecMAEMoviD4ALwoGFg4uADalAYAggAqAMIAEnBsGpC4bAgQAO6oPFAEOZkQJXQAFjx0TAC0UACuqNkIVTVMAPpNqJ3A6ASUALoxfgEgPDBF-EM6XnD5haahY4HRlItFw8LzZXAr-msxZds6enAJ1WZucHk8wFDohbj42A5OqqwZmh7zSdW1ACqYHQvimBkOQX2cAAchBUDDGgAbJG+ABGSJ4AB4IeNJtMsdJPjBjpphjF2rUZjFGiCwTxhgA+KIABiGjM8N3+HWBoKmAGUYGDGiE4NygXTwZD1psoMMgA).

The types for this endpoint in `@octokit/plugin-rest-endpoint-methods`:

https://github.com/octokit/plugin-rest-endpoint-methods.js/blob/51ea414f2401f1725e353f7a33288a4fb1faf873/src/generated/parameters-and-response-types.ts#L1694-L1698

I have narrowed it down to the `Omit<[...], "baseUrl" | "headers" | "mediaType">`
It seems that TypeScript narrows it down to `{ [key: string]: unknown }`

@gr2m Do you recall why the `Omit` is there? The earliest that I can find it's usage is from https://github.com/octokit/plugin-rest-endpoint-methods.js/commit/7ed9fc41b3c714e851610111ae785841df0f77fd

**Comment by gr2m** [comment]
> Do you recall why the `Omit` is there

I don't, sorry 😞 `"baseUrl" | "headers" | "mediaType"` are all generic request options, not specific to any rest API endpoint, I assume they are added back at a later point, so  that the `parameters` types are only containing types for the respective endpoint, without the generic ones

**Comment by wolfy1339** [comment]
At that point there where the `Omit` is currently, there doesn't seem to be any request related parameters. It's only the endpoint parameters themselves.

**Comment by gr2m** [comment]
feel free to experiment and remove it, I was learning TypeScript as I was building this, it's likely that I messed things up. The types I built for https://github.com/octokit/octokit-next.js are more elegant 🤷 I really wish we could complete that work

**Comment by wolfy1339** [comment]
I removed the `Omit` from the types, and ran the tests for `@octokit/rest` along with the tests for `octokit` with the updated types and every test passes, including the typescript test.

I believe that that would alleviate this issue. I will prepare a PR to fix that

**Comment by wolfy1339** [comment]
It seems we have run into this issue before: https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/441
