### ISSUE TITLE
Handle moved repo(301 redirect)

### ISSUE THREAD

**Issue by PeterDaveHello** [octokit/octokit.js#257]
Seems currently can not handle moved repo, hope it can be supported, thanks!

**Comment by dominicbarnes** [comment]
+1

**Comment by jamestalmage** [comment]
According to [the spec](https://developer.github.com/v3/#http-redirects), all redirects should be followed.

> API v3 uses HTTP redirection where appropriate. Clients should assume that any request may result in a redirection. Receiving an HTTP redirection is not an error and clients should follow that redirect. 
> ...
> Other redirection status codes may be used in accordance with the HTTP 1.1 spec.

[follow-redirects](https://www.npmjs.com/package/follow-redirects) may provide a simple solution. Unfortunately, it currently [has a dependency on underscore](https://github.com/olalonde/follow-redirects/issues/15) which adds a whole bunch of bulk we don't want if we are [running in a browser](https://github.com/mikedeboer/node-github/pull/261). I have [raised an issue](https://github.com/olalonde/follow-redirects/issues/15) to get `underscore` removed, and will likely create a PR to address that.

**Comment by zenorocha** [comment]
GitHub officially turned that on and my app broke: https://developer.github.com/changes/2015-07-21-automatic-redirects-for-renamed-repositories 

Would be awesome if this was built-in on node-github @mikedeboer.

**Comment by podviaznikov** [comment]
+1 would love to see fix for this in the node-github

**Comment by jamestalmage** [comment]
I would recommend `follow-redirects`. Should be a drop in replacement for `http`. The underscore dependency is gone, but that does not really impact the browser anyways. Browsers automatically follow redirects, so we recommend having browserify just replace `follow-redirects` with vanilla `http` during bundling.

There is still [one issue](https://github.com/olalonde/follow-redirects/issues/12). It may affect non-`GET` requests that are redirected with `307`. I just picked that back up this afternoon and should be close to a resolution within a day or two.

**Comment by jamestalmage** [comment]
@podviaznikov @zenorocha 
Can you try #284 and see if it fixes your issue?

It is probably only a partial fix. I will be improving `follow-redirects` in the coming days, which should hopefully fix everything.
