### ISSUE TITLE
[BUG]: `log` option doesn't work, but the types suggest that it should

### ISSUE THREAD

**Issue by timrogers** [octokit/octokit.js#2571]
### What happened?

The ["Debug" section in the `@octokit/rest.js` docs](https://octokit.github.io/rest.js/v20#debug) states that you can pass the `log: console` option when instantiating the client and all requests will then be logged.

This works when you use `rest.js` directly, but it seems to be broken in the `octokit` package, even though the types included in `octokit` suggest that it should work:

![Image](https://github.com/octokit/octokit.js/assets/116134/4169155b-812f-4177-99ed-1c5e47f8f917)

Any idea what's going on here?

I've pushed a minimal reproduction to my own GitHub repo, [`timrogers/octokit-js-logging-minimal-reproduction`](https://github.com/timrogers/octokit-js-logging-minimal-reproduction):

- [`using-rest-js-directly.js`](https://github.com/timrogers/octokit-js-logging-minimal-reproduction/blob/main/using-rest-js-directly.js) shows the behaviour working as expected with `@octokit/rest`.
- [`using-octokit.js`](https://github.com/timrogers/octokit-js-logging-minimal-reproduction/blob/main/using-octokit.js) shows that it doesn't work when you use the `octokit` package.

### Versions

Octokit.js 3.1.1
Node v18.17.0

### Relevant log output

N/A

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
It's not a bug. `@octokit/rest` loads a plugin for legacy compatibility: https://github.com/octokit/rest.js/blob/414943c79b7b5b94d31914c340957282c50b0312/src/index.ts#L2 that the `octokit` package does not. You can add the `@octokit/plugin-request-log` plugin if you like that, or implement your own request logging pretty easily using `octokit.hook.wrap("request", ...)`: https://github.com/octokit/core.js/#hooks

**Comment by timrogers** [comment]
@gr2m Ah, super interesting! In that case, isn't it a bit strange to declare the `log` option in the types? I'll add that plugin now!

**Comment by gr2m** [comment]
> isn't it a bit strange to declare the `log` option in the types

you can pass a custom logger to the `Octokit` constructor. By default it's just `console`, but I usually set it to a pino logger instance in most of my projects to get proper line-delimited JSON log output
