### ISSUE TITLE
[BUG]: teams.getByName does not work

### ISSUE THREAD

**Issue by johnament** [octokit/octokit.js#2585]
### What happened?

There exists an API call Get A Team by Name: https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#get-a-team-by-name
Following code examples (https://octokit.github.io/rest.js/v20#teams scroll to getByName), I should be able to call it like:

```
octokit.rest.teams.getByName({
  org: <org name>,
  team_slug: <team name>});
```

However that does not return any teams.

When I call it the way described in the API, or via curl it works fine with the same params

```
client.request('GET /orgs/{org}/teams/{team_slug}', {
    org: 'Contrast-Security-Inc',
    team_slug: 'team-cratus',
    headers: {
      'X-GitHub-Api-Version': '2022-11-28'
    }
  }).then((response) => {
    console.log(response);
  }).catch((error) => {
    console.log(error);
  });
```

### Versions

Node v20.9.0
Octokit: latest available

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I can't reproduce the issue
```js
const { Octokit } = require("octokit")
const octokit = new Octokit({
    auth: "<token>"
});
async function main() {
    const data = await octokit.rest.teams.getByName({
        org: "octokit",
        team_slug: "maintainers",
    });
    console.log(data);
}
main();
```

**Comment by johnament** [comment]
Should octokit/maintainers work for me (as someone not a member of your org)?

**Comment by wolfy1339** [comment]
No, it only works for members of the org. You can change the values of `org` and `team_slug` as needed.

**Comment by johnament** [comment]
So I retested with yours and confirmed that i pulled in 3.1.2 of octokit, and that worked.  I noticed that where I was running the original test was on 2.1.0 of octokit (not latest as I had assumed).  I can upgrade that and see if that resolves this issue.

**Comment by wolfy1339** [comment]
Glad to hear that it is now working 👍
