### ISSUE TITLE
Suggested docs change - issues.create

### ISSUE THREAD

**Issue by karanhiremath** [octokit/octokit.js#259]
Suggesting a change to docs for issues.create (and wherever else it may be applicable) that 'user' field is not the username of the current github user but the username of the repo owner

See http://mikedeboer.github.io/node-github/#issues.prototype.create

**Comment by kaizensoze** [comment]
In general, `:owner` in the github api is `:user` in the library. I'm going to close this, but I'm open to making it more consistent if this closed ticket or a related newly created one gets a bunch of reactions pushing for the change.
