### ISSUE TITLE
[BUG]: Octokit Intellisense with Deno in VS Code

### ISSUE THREAD

**Issue by mcgear** [octokit/octokit.js#2595]
### What happened?

We have setup a simple Deno Fresh project to recreate the issue inside this repo:
https://github.com/fathym-deno/octokit-types-test

Specifically in this API route:
https://github.com/fathym-deno/octokit-types-test/blob/integration/routes/api/octokit.ts

We are currently not getting any intellisense on the import of `octokit`. Everything comes back as an any type, so we have to dig through lots of docs to figure out the calls we are looking to make. 

This start with the simple `Octokit.plugin` call, but is an issue for everything else in the `.rest` and `.graphql` sections of Octokit too.  

Looking for help on how to get this intellisense on the octokit import and creation of a new octokit class (`new Octokit({...})`).

Thanks for the help.

### Versions

Octokit: https://esm.sh/octokit@3.1.2?dts
Deno: 1.38.2
Deno Fresh: 1.6.1 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Does VSCode support getting types over http?

Anyways, the paginate graphql plugin is already included in the Octokit package

**Comment by mcgear** [comment]
Thanks for the heads up on the paginate. I updated the example to better show other use cases. My hope is to have intellisense on the Octokit type so that the api can be explored, rather than always googling for the correct calls.  I added a call to instantiate Octokit (which doesn't have intellisense) and a call to get authenticated user from the rest api (which has no intellisense). 

Hoping to get some direction on how to get intellisense working in the Deno, typescript project.

Thanks for the help.

**Comment by mcgear** [comment]
I forgot to mention that this code is all on the `integration` branch. I added some clarifying comments and my assumptions on how `@octokit/types` should be used. So as a part two on this question/bug, do i have the right idea on how the sdk should work?

**Comment by wolfy1339** [comment]
In most cases, you won't need to require `@octokit/types` yourself.

Everything is supposed to be strongly typed.

Using the package from NPM everything seems to work as expected for the typehints in vscode.

Can you try importing directly in your source file and not use import aliases?

If that doesn't work, can you try using [`npm:` specifier imports](https://docs.deno.com/runtime/manual/node/npm_specifiers)?

**Comment by mcgear** [comment]
Thank you for the help. I noticed some "wonkyness" while switching between the types and got me thinking...  I was able to get it working with the import alias after using `deno cache --reload main.ts`.  After running that, everything worked. The only issue now is how slow it can be to pull up the intellisense, but that isn't a showstopper.

Thank you for the help.
