### ISSUE TITLE
[FEAT]: Do we have the CJS version? If not, are we considering supporting CJS?

### ISSUE THREAD

**Issue by shen774411223d** [octokit/octokit.js#2668]
### Describe the need

My project is based on CJS and I want to import octokit.js, but it is not compatible with ESM.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This package is still CJS, it hasn't moved to ESM yet. It will be the last major version to support CJS

**Comment by shen774411223d** [comment]
sorry, but i install lastest version. in octokit/core package.json, the type is module.
why i install package not cjs?
thank you answer!

#### octokit/core package.json
```json
{
  "type": "module"
}
```

**Comment by wolfy1339** [comment]
That is a different package, and a different repository.

You need to use the last CJS version, which is https://github.com/octokit/core.js/releases/tag/v5.2.0

**Comment by shen774411223d** [comment]
Thank you very much for your answer. This is exactly the package I want.
