### ISSUE TITLE
[BUG]: Octokit 4 can't be `import`ed or `require`d

### ISSUE THREAD

**Issue by s100** [octokit/octokit.js#2676]
### What happened?

This should work:

`a.mjs`:

```js
import * as octokit from 'octokit'
```

However this fails with a module loading error (see later).

Note that `octokit@4.0.1` ships with `"type": "module"` in its `package.json`, indicating a pure ESM package, but `"main"` points to `dist-node/index.js`, which is clearly a CJS module making use of `module.exports` and `require`. Something's gone wrong here.

### Versions

Octokit 4.0.1, Node.js 18.17.1

### Relevant log output

```shell
C:\...>node a.mjs
file:///C:/.../node_modules/octokit/dist-node/index.js:29
module.exports = __toCommonJS(dist_src_exports);
^

ReferenceError: module is not defined in ES module scope
    at file:///C:/.../node_modules/octokit/dist-node/index.js:29:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by s100** [comment]
I'm finding that CJS can't use Octokit 4 either:

`a.js`:

```js
require('octokit')
```

```
C:\...>node a.js
C:\...\a.js:1
require('octokit')
^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\...\node_modules\octokit\dist-node\index.js from C:\...\a.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\...\node_modules\octokit\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (C:\...\a.js:1:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1
```

**Comment by wolfy1339** [comment]
Sorry that is my fault.

I forgot to change the build script

**Comment by wolfy1339** [comment]
You should be able to point to the files directly in order to import them

```js
import Octokit from "octokit/dist-src/index.js";
```

**Comment by gr2m** [comment]
I confirmed that this works now:

```js
// test.mjs
import { Octokit } from "octokit";
console.log(Octokit.VERSION);
// 6.1.2
```

**Comment by rolwin100** [comment]
I'm still facing the issue with nestjs. I solved it by downgrading it to version 3. This solved my issue

**Comment by wolfy1339** [comment]
NestJS can't do ESM only packages.

There is a new NodeJS feature that can allow you to use `require()` in order to import ESM packages.
However support is limited to 23 currently, and is going to be backported to 22 soon.

You can also use `await import()`.

If you are stuck on a version of Node that is older, and require CJS stick to v3 of Octokit.
We will support bug fixes for it for the time being

Please open a new issue with proper information if ever you encounter an issue like this again
