### ISSUE TITLE
[BUG]: Octokit v4 types

### ISSUE THREAD

**Issue by klippx** [octokit/octokit.js#2677]
### What happened?

TS does not seem to like the `import("@octokit/core/types").Constructor` or any such `import`, it resolves to `any` as you can see in the screenshot when I hover it:

<img width="874" alt="Screenshot 2024-05-08 at 15 18 42" src="https://github.com/octokit/octokit.js/assets/2785359/9285b708-35c1-47df-b15d-fc5dd940b955">

This causes my ts-eslint to panic `Unsafe assignment of an `any` value.eslint[@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)`, but since it is opt-in most people might not even notice they start getting `any` all over the place.

My `.eslintrc.js`

```js
module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended-type-checked',
    'plugin:@typescript-eslint/stylistic-type-checked',
    'plugin:import/errors',
    'plugin:import/typescript',
    'prettier',
  ],
  plugins: ['@typescript-eslint'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: true,
    tsconfigRootDir: __dirname,
  },
  root: true,
  settings: {
    'import/parsers': {
      '@typescript-eslint/parser': ['.d.ts', '.ts', '.tsx'],
    },
    'import/resolver': {
      typescript: {
        // always try to resolve types under `<root>@types` directory even it doesn't contain any source code, like `@types/unist`
        alwaysTryTypes: true,
        // Choose from one of the "project" configs below or omit to use <root>/tsconfig.json by default
        project: '<root>/tsconfig.json',
      },
    },
  },
}
```

Related to #2676 

### Versions

Octokit.js 4.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
What is your tsconfig?

**Comment by gr2m** [comment]
can you test again with the latest version? We had a build config bug that was resolved in [v4.0.2](https://github.com/octokit/octokit.js/releases/tag/v4.0.2)

**Comment by northword** [comment]
seems stil：

![image](https://github.com/octokit/octokit.js/assets/44738481/aa52697e-29cd-4959-a36f-c4823f0b07d9)

![image](https://github.com/octokit/octokit.js/assets/44738481/b1a390a0-5da8-4d05-864a-c0032cbe5535)

my tsconfig:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "strict": true,
    "resolveJsonModule": true,
    "declaration": true,
    "outDir": "dist",
    "skipLibCheck": true,
    "rootDir": "src"
  },
  "include": ["src", "types", "bin"]
}

```

Currently using 4.0.2, works fine on 3.1.2.

**Comment by wolfy1339** [comment]
Please read up https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports
and https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

This is an error with your `tsconfig.json`, you have to use either `node16` or `nodenext` modules and moduleresolution

**Comment by northword** [comment]
Oh very sorry for taking up your time because of my problem, I made changes based on your suggestions and have fixed the problem, thanks!

**Comment by wolfy1339** [comment]
The original author hasn't responded, and given that #2676 was resolved and that this seems like a case of misconfigured TypeScript, I will close this

**Comment by klippx** [comment]
Yes, my project was not correctly in ESM, not in terms of typescript. After applying NodeNext and absolute imports `octokit` works fine.
