### ISSUE TITLE
get-branch route improperly defined

### ISSUE THREAD

**Issue by Voxelot** [octokit/octokit.js#268]
The node-github get-branch API expects a parameter called 'user', however the reference documentation from github shows that this field should be 'owner'. This is misleading as the GitHub documentation for this API is referenced from the node-github docs.

**Comment by kaizensoze** [comment]
It's not that difficult to discern that user == owner between this library and the github rest api, unless I'm misunderstanding the issue.

https://mikedeboer.github.io/node-github/#api-repos-getBranch
https://developer.github.com/v3/repos/#get-branch
