### ISSUE TITLE
[BUG]: [Nestjs] [ERR_REQUIRE_ESM]: require() of ES Module not supported

### ISSUE THREAD

**Issue by rs-duongnt1** [octokit/octokit.js#2680]
### What happened?

```typescript
import { Octokit, App } from 'octokit';
const app = new App({
      appId: 'APP_ID',
      privateKey: this.getPrivateKey(),
});
```

Throw error `Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.` in nestjs framework.

I have change it below, but it not working in nestjs.
> As we use [conditional exports](https://nodejs.org/api/packages.html#conditional-exports), you will need to adapt your tsconfig.json by setting "moduleResolution": "node16", "module": "node16".

### Versions

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This seems like an issue with NestJS. They don't have support for ESM

A quick search yields https://github.com/nestjs/nest/issues/7021
https://stackoverflow.com/questions/74830166/unable-to-import-esm-module-in-nestjs

**Comment by suka233** [comment]
same error

**Comment by itspers** [comment]
This modern web is something crazy.
Its not "issue with NestJS. They don't have support for ESM"  - its issue with this library. Other libs work - this one dont. Github monopolized it, there are no alternatives and it just cant work not in hello-world nodejs app with express and react.

**Comment by wolfy1339** [comment]
It is not an issue with this library. We don't do CJS builds anymore.

NestJS doesn't support ESM as I've linked to above.

The error given means that you are trying to import an ESM library using CJS `require()`.

It is not an issue on our side. Other libraries might still have support for CJS, we decided to switch to ESM only.

Please read the changelog and previous issues before posting on an old resolved issue.

Simply use an older version of Octokit that still has CJS support.
