### ISSUE TITLE
How do I disable node-github from emitting log messages to the console?

### ISSUE THREAD

**Issue by bookercodes** [octokit/octokit.js#269]
Hi, 

Quick question: How do I disable _node-github_ from emitting log messages to the console? 

Many thanks.

**Comment by jeancedron** [comment]
Isn't enough using **debug: false** here?:

``` javascript
var github = new GitHubApi({
    debug: false
});
```

**Comment by bookercodes** [comment]
I did try that but it didn't work on account of [me using an outdated version of this library](https://github.com/mikedeboer/node-github/issues/270).

I meant to close this issue. Sorry. And thanks!
