### ISSUE TITLE
Possibly make it clearer that the module called github is dead/depracated...?

### ISSUE THREAD

**Issue by bookercodes** [octokit/octokit.js#270]
I _know_ this is my fault but _damn_... I just spent a couple of hours debugging a problem that was caused by my installing the [`node-github`](https://www.npmjs.com/package/node-github) module  instead of  [`github`](https://www.npmjs.com/package/github).

I appreciate the correct package is clearly documented in the `readme.md` but seeing as how @mikedeboer also owns the module called `node-github`, might it be a good idea to remove it or at least, depreciate it. Maybe you could throw an error on `requrie`.

**Comment by just-be-dev** [comment]
Do you have that backwards?

Isn't `github` the latest and `node-github` the deprecated one?

**Comment by bookercodes** [comment]
Yeah, I do. Or rather, I did -- I updated my post.

**Comment by zenorocha** [comment]
I experienced the same thing couple days ago. +1 for that

**Comment by kaizensoze** [comment]
This repo is back from the dead, but yeah node-github still needs to be removed from npm to avoid any confusion, which is another issue (#141).

![youngfrankenstein3](https://cloud.githubusercontent.com/assets/218869/15659215/5ab4f566-2695-11e6-9631-a24926658dbe.jpg)
