### ISSUE TITLE
[FEAT]: Provide an API endpoint to resolve conflicts in PR

### ISSUE THREAD

**Issue by KarimGhallab** [octokit/octokit.js#2726]
### Describe the need

I'am writing a bot that manages binary files. These binary files often caused conflicts when a PR is opened.
As i know the structure of theses conflicted files, i can easily fix these conflicts programmatically
However, i don't know if there is any endpoint that allow me to mark these conflicted files as resolved when creating a new commit for the PR.

This need is related to #2085

Thanks in advance

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Unfortunately we don't have control over what API endpoints are available. If you'd like to provide a suggestion to the API, you can raise a discussion [here](https://github.com/orgs/community/discussions/categories/api-and-webhooks).
