### ISSUE TITLE
[FEAT]: Get a PR or issue related to the issue

### ISSUE THREAD

**Issue by RSS1102** [octokit/octokit.js#2733]
### Describe the need

When we raise an issue or PR, we can link other issues and PRs (whether in this repo or in someone else's repo). It will be displayed under the current issue or PR, and of course it will be displayed in another place.

So there is an API that can get this information, and we can do something with it.

For example:
We can close the following related issues.
We can notify related issues.
Of course, this is not what this API is intended to achieve.

![image](https://github.com/user-attachments/assets/cef61d6d-8c93-4687-bded-cf8561e3afae)
![image](https://github.com/user-attachments/assets/95e285bd-ab6a-4257-87ef-8d32e0382a79)

### SDK Version

v4.x.x

### API Version

none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Unfortunately we can't add new API features relating to the GitHub API.

We only implement methods to use the API.

Feel free to forward your request here: https://github.com/orgs/community/discussions/categories/api-and-webhooks
