### ISSUE TITLE
[BUG]: Octokit breaks Deno tests

### ISSUE THREAD

**Issue by thisguycodes** [octokit/octokit.js#2759]
### What happened?

When I run `deno test` with tests that use Octokit, I get a "Module not found" error. Running non-tests works fine.

Here's a gist that will reproduce this: https://gist.github.com/ThisGuyCodes/3d98652574ad726754fa7b5069367553

But really, this is the code (`main_test.ts`):
```typescript
import { App } from "octokit";

Deno.test({
  name: "App",
  fn() {
    new App({
      appId: "1234567890",
      privateKey: "1234567890",
    });
  },
});
```

and here's the `deno.json`:
```json
{
  "imports": {
    "octokit": "https://esm.sh/octokit@4.0.2?dts"
  }
}
```

### Versions

Octokit.js v4.0.2
Deno v2.0.6

### Relevant log output

```shell
$ deno test
error: Module not found "https://esm.sh/v135/@octokit/app@15.0.1/dist-types/web.d.ts".
    at https://esm.sh/v135/octokit@4.0.2/dist-types/app.d.ts:1:35
$
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
That file simply does not exist at all. It's an error in the `package.json`

This will be fixed when https://github.com/octokit/app.js/pull/583 is merged.

**Comment by thisguycodes** [comment]
thank you @wolfy1339! I was going crazy trying to figure this out 😓

**Comment by thisguycodes** [comment]
ok, this feels superfluous, but the [process](https://github.com/octokit/.github/blob/main/community/prioritization_response.md#overview) linked by the bot says "Critical" includes:
> Broken or non functioning SDK that has been published - Any stop work scenarios for users (where rollback is not possible)

If it's purported that esm.sh / Deno is "supported" (which, I mean it's in the readme for how to use it), I feel this counts as "non functional". There's an argument it's more like "broken features" from the "High" priority, but only if you argue "being able to use the SDK at all is a feature".
