### ISSUE TITLE
No Add Label to issue endpoint

### ISSUE THREAD

**Issue by aicioara** [octokit/octokit.js#279]
Either that or it is super hard to find. I can create labels, delete labels, view all labels for an issue, but there are no endpoints for adding / deleting labels to / from issues

**Comment by jlank** [comment]
+1

https://developer.github.com/v3/issues/labels/ is not included in the API

**Comment by msound** [comment]
+1

**Comment by msound** [comment]
@aicioara A workaround, if you are willing to pass all labels, is to do [issues#edit](https://developer.github.com/v3/issues/#edit-an-issue).

**Comment by aicioara** [comment]
@msound So as a workaround, basically read all labels, apply my diff and pass the new state back? That sounds reasonable. I'll check if it woks. Thank you!

**Comment by kaizensoze** [comment]
I have this implemented in my fork:

https://github.com/kaizensoze/node-github
https://kaizensoze.github.io/node-github/#api-issues-addLabels

**Comment by kaizensoze** [comment]
Merged into upstream: https://mikedeboer.github.io/node-github/#api-issues-addLabels
