### ISSUE TITLE
Documentation site bug

### ISSUE THREAD

**Issue by stephantabor** [octokit/octokit.js#281]
On the documentation site, the search bar on the top left corner has the same `id` as the `search` mixin header causing an issue with appearance and preventing the user from being able to jump to the search section.

changing the `id` of the search bar would correct this

<img width="772" alt="screenshot 2015-09-13 10 02 17" src="https://cloud.githubusercontent.com/assets/8570366/9837025/c40649de-59fe-11e5-989b-732688e1db6e.png">

**Comment by kaizensoze** [comment]
Updated docs.
