### ISSUE TITLE
createKey read_only

### ISSUE THREAD

**Issue by hypesystem** [octokit/octokit.js#286]
createKey should accept the read_only field: https://developer.github.com/v3/repos/keys/

I couldn't figure out where to change it in the code, otherwise I would have made a PR :-(

**Comment by kaizensoze** [comment]
Fixed: https://mikedeboer.github.io/node-github/#api-repos-createKey

**Comment by hypesystem** [comment]
Nice! Haha I had completely forgotten about this issue :+1:
