### ISSUE TITLE
Management console API

### ISSUE THREAD

**Issue by quocvu** [octokit/octokit.js#287]
It seems this library doesn't cover the Management Console API

https://developer.github.com/enterprise/2.2/v3/enterprise/management_console/

Since it doesn't start with /api/v3, could you suggest a way to extend it to cover it?  I can add support for this.

Cheers
Quoc

**Comment by kaizensoze** [comment]
You should just have to modify the host and port in config. I've created an issue to remind me to add the endpoints: https://github.com/mikedeboer/node-github/issues/376
