### ISSUE TITLE
Easy way to fetch pull request patch

### ISSUE THREAD

**Issue by jviotti** [octokit/octokit.js#294]
Given a pull request user/repo/id, fetch the contents of `patch_url`.

**Comment by kaizensoze** [comment]
I don't really like adding convenience methods. It should be simple enough to grab the pull request and download the patch:

```
github.pullRequests.get({
  user: "<user>",
  repo: "<repo",
  number: "<number>"
}, function(err, res) {
  var patchURL = res["patch_url"];
  // TODO: download patch
});
```

**Comment by liorsion** [comment]
It's not that easy because of authentication. The way it's done in Octokit is different than "plain" http

**Comment by gr2m** [comment]
The way you would implement this with today's octokit is to set `mediaType: { format: "patch" }`

```js
const { data: diff } = await octokit.rest.pulls.get({
  owner: "octokit",
  repo: "octokit.js",
  pull_number: 123,
  mediaType: {
    format: "patch",
  },
});
```
