### ISSUE TITLE
getContent breaks if optional path is not included

### ISSUE THREAD

**Issue by Snugug** [octokit/octokit.js#296]
Stepping through [repos.getContent](https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/repos.js#L1521), `path` should be optional. However, if not path is included, `:path` gets appended at the end of the URL being called, breaking the call and preventing its usage (a 404 is returned).

If I set the `path` parameter to an empty string (`''`), it works as expected.

**Comment by kaizensoze** [comment]
Easiest solution is to just make it required. I know it's not the most proper thing since now it technically differs from the github api, but it shouldn't be a dealbreaker. People who figured it out up to now ended up having to provide it [as an empty string] anyway.
