### ISSUE TITLE
Missing "Add or update organization membership" 

### ISSUE THREAD

**Issue by cparisctb** [octokit/octokit.js#300]
Per the GitHub API Documentation, there is a function to add or update (same call) membership to an organization.

https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership

Currently the GET and DELETE functions are implemented, but, not the PUT method for this route.

I looked in the routes.json and to verify that the route was not implemented.

**Comment by kaizensoze** [comment]
I forked this repo and included the PR for addOrganizationMembership here: [kaizensoze/github4](https://github.com/kaizensoze/github4)

**Comment by kaizensoze** [comment]
Merged fork into upstream
