### ISSUE TITLE
Repo dead ??? So many PRs and issues ...

### ISSUE THREAD

**Issue by stefanwalther** [octokit/octokit.js#302]
Such a nice library, but it seems that the repo is dead??
Is there a will to continue improving on a fork or do you guys move over to another repo like octonode (https://github.com/pksunkara/octonode)?

Regards
Stefan

**Comment by kaizensoze** [comment]
If the author is open to adding people to help go through the issues/PRs, I'm very interested. Otherwise, I'm just going to fork it and apply all the PRs myself.

**Comment by kaizensoze** [comment]
I created a fork and published it as github4: https://github.com/kaizensoze/github4

I'll start going through the issues and pr's recording progress in the transition here: 
https://github.com/kaizensoze/github4/wiki/Transition-from-upstream

**Comment by stefanwalther** [comment]
:+1: 
@mikedeboer ... Open to adding people?

**Comment by zedtux** [comment]
+1

**Comment by kaizensoze** [comment]
Fork is good to go with most of the key PR's merged: https://github.com/kaizensoze/node-github

``` bash
npm install github4
```

Feel free to submit issues/PRs there.

**Comment by mikedeboer** [comment]
Sorry for the _very_ late reply 😞 

As you all have seen here, I'm no longer maintaining this project.

I more than open to add contributors to 1) this repo and 2) the npm list.

@kaizensoze I believe your fork is most up to date?

**Comment by kaizensoze** [comment]
@mikedeboer Would you be open to marking `mikedeboer/node-github` as deprecated and allowing `kaizensoze/node-github` to use `github` on npm?

**Comment by sivakumar-kailasam** [comment]
@mikedeboer I didn't realize that this repo was outdated until I ran into a bug that was fixed in @kaizensoze's repo. Would merging @kaizensoze's code into this repo, making him a contributor & giving him npm access make sense? Because this repo lists comes up on top in searches in npm & google and it might take other newbies a while to figure what I struggled with.

**Comment by mikedeboer** [comment]
@kaizensoze I don't see the benefit of moving to another location vs. making you a contributor/ maintainer of this repo and giving you push rights for NPM too... same net effect, whilst maintaining the google and npm listings.

**Comment by kaizensoze** [comment]
@mikedeboer Right, it was more the adding a "DEPRECATED" or "No longer maintained" note in the repo info or README to prevent any potential confusion. As far as merging the fork, I'm all for becoming a contributor/maintainer if you're open to that.

**Comment by mikedeboer** [comment]
@kaizensoze sounds good. I added you as a contributor now.

**Comment by mikedeboer** [comment]
@kaizensoze which, for me, means a complete vouch to take things over here and make it your own.

**Comment by kaizensoze** [comment]
Sweet, thanks!

**Comment by kaizensoze** [comment]
When I get a chance, I'll merge the fork and go through the issues/PR's.

**Comment by kaizensoze** [comment]
@mikedeboer Would I be able to get npm publish privs?

**Comment by mikedeboer** [comment]
@kaizensoze of course! Expect it tomorrow.

**Comment by mikedeboer** [comment]
BTW, feel free to contact me on Skype - I have the same username everywhere.

**Comment by mikedeboer** [comment]
@kaizensoze done!

**Comment by kaizensoze** [comment]
Thanks!

**Comment by 2heal** [comment]
please remove me from your threads I have been getting up to thirty and forty a day, can't keep up.  thank you though for your good work.

**Comment by kaizensoze** [comment]
If you're watching the repo you can just unwatch it.
