### ISSUE TITLE
Requests not using port specified in argument to constructor

### ISSUE THREAD

**Issue by KanoYugoro** [octokit/octokit.js#305]
I'm doing some high integration tests in another project that uses this as a dependency, so I've set the configurations to use an irregular port, but the request is still going on on port 80 instead.

In my project, I am creating the api like so:

``` javascript
const options = {
  version: '3.0.0',
  protocol: 'http',
  host: 'localhost',
  port: 3002,
  pathPrefix: ''
};
const api = new GitHubAPI(options);
```

However, when I make the request, I get the following error message:
`Error: connect ECONNREFUSED 127.0.0.1:80`

This package appears to be using port 80 to make the request, even though I specified 3002 in the constructor argument.  I did console log `api.config` after the api gets created, and the port is 3002 inside of the config property.

**Comment by kaizensoze** [comment]
This repo is no longer being maintained, but I'll take a look in my fork: https://github.com/kaizensoze/node-github

**Comment by kaizensoze** [comment]
This should be fixed now and you'll get `Error: connect ECONNREFUSED 127.0.0.1:3002`
