### ISSUE TITLE
module not found:chai,describe

### ISSUE THREAD

**Issue by lv7777** [octokit/octokit.js#306]
I get an error when installing.

> npm ERR! addLocal Could not install C:\Users\tes
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g"
> npm ERR! node v5.4.0
> npm ERR! npm  v3.3.12
> npm ERR! code EISDIR
> npm ERR! errno -4068
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\tes\npm-debug.log

and get moduleerror "chai" when running `node test.auth.js`

then

> ReferenceError: describe is not defined

is this mocha?

**Comment by kaizensoze** [comment]
Yeah describe is part of mocha. Do you get an error if you do the following?

```
mkdir test && cd test
npm init (hit enter a bunch of times)
npm i -S github
```

**Comment by kaizensoze** [comment]
Closing for now. Feel free to open a new ticket if you're still seeing ModuleError.

**Comment by lv7777** [comment]
sorry for late reply.
I solved this problem.

thanks @kaizensoze
