### ISSUE TITLE
repos.watch() doesn't "watch"

### ISSUE THREAD

**Issue by mapsam** [octokit/octokit.js#308]
Hi there! Thanks for this excellent tool.

I'm working with the `github.repos.watch()` function and not seeing the repos actually being "watched". Here's what I have running:

``` javascript
github.repos.unStar({
    user: "mapsam",
    repo: "mapsam.github.io", // example
    headers: {
        "X-GitHub-OTP": "<mfa_code>"
    }
}, function(err, res) {
    if (err) throw err;
    console.log(res);
});
```

Here's the response, including `debug: true`

```
REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/user/watched/mapsam/mapsam.github.io',
  method: 'put',
  headers: 
   { host: 'api.github.com',
     'content-length': 2,
     'content-type': 'application/json; charset=utf-8',
     authorization: 'Basic bWFwc2FtOm15UHIzY2lvdXM=',
     'x-github-otp': '<mfa_code>',
     'user-agent': 'NodeJS HTTP Client',
     accept: 'application/vnd.github.v3+json' } }
REQUEST BODY: {}

STATUS: 204
HEADERS: {"server":"GitHub.com","date":"Thu, 14 Jan 2016 01:46:37 GMT","status":"204 No Content","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4975","x-ratelimit-reset":"1452738501","x-github-media-type":"github.v3; format=json","access-control-allow-credentials":"true","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","vary":"Accept-Encoding","x-served-by":"bd82876e9bf04990f289ba22f246ee9b","x-github-request-id":"46D60507:B793:8BF8EFA:5696FDFD"}
{ meta: 
   { 'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4975',
     'x-ratelimit-reset': '1452738501',
     status: '204 No Content' } }
```

Not exactly sure if that's expected, but a couple things seem weird here. I'm expecting the `.watch()` function to work similarly to `.star()` (having similar issues with `unWatch()` vs `unStar()`) but maybe I misunderstand the expected output. Some things I've observed (may or may not be helpful):
- the header `path` set to the github API is `/user/watched/mapsam/mapsam.github.io` but according to the [Github API](https://developer.github.com/v3/activity/watching/#set-a-repository-subscription) docs it should be someting like `/repos/:owner/:repo/subscription`
- the response is a `204`, but the Github API says successful responses are [`Status: 200 OK`](https://developer.github.com/v3/activity/watching/#response-2)

Any help would be great!

**Comment by kaizensoze** [comment]
The watch repo endpoint is now considered legacy, but 204 is the expected response code.
https://developer.github.com/v3/activity/watching/#watch-a-repository-legacy

The replacement is https://developer.github.com/v3/activity/watching/#set-a-repository-subscription.
