### ISSUE TITLE
affiliation parameter for repos.getAll

### ISSUE THREAD

**Issue by tigranbs** [octokit/octokit.js#313]
Hi
I'm trying to get all repos from user with types <code>owner, collaborator</code> as it is described in documentation <a href="https://developer.github.com/v3/repos/#list-your-repositories">https://developer.github.com/v3/repos/#list-your-repositories</a> with parameter <code>affiliation</code>.

<p>
The problem is that in <a href="http://mikedeboer.github.io/node-github/#repos.prototype.getAll">http://mikedeboer.github.io/node-github/#repos.prototype.getAll</a> documentation parameter  <code>affiliation</code> not listed and it's not working even when passing it to <code>msg</code> object.
</p>

How to make a call for getting user repos where user is **owner** or **member/contributor** ?
Thanks

**Comment by kaizensoze** [comment]
This repo hasn't been updated in a while. You should be able to use the `affiliation` param with the following fork: https://github.com/kaizensoze/node-github.

docs: https://kaizensoze.github.io/node-github/#api-repos-getAll

**Comment by kaizensoze** [comment]
merged into upstream: https://mikedeboer.github.io/node-github/#api-repos-getAll
