### ISSUE TITLE
Not able to use repos.getReadme()

### ISSUE THREAD

**Issue by leefsmp** [octokit/octokit.js#314]
Hey Mike, 
Thanks for this great package. I am not able to get the read me for a specific repo, I am supposed to pass repo.id and user.id?

`gitClient.repos.getReadme({
        user: user,
        repo: repo
      }, (err, res)=> {

```
   // ...
  });`
```

I'm getting a 404, I tried passing the id's or repo.name, user.login, no success.

Also it's not clear why it requires the user as parameter?

Thanks,
Philippe.

**Comment by kaizensoze** [comment]
This repo is no longer maintained.

You should be able to get the readme with the following fork: https://github.com/kaizensoze/node-github. You shouldn't need the id's, just the names so: `user: "kaizensoze", repo: "node-github"`.

docs: https://kaizensoze.github.io/node-github/#api-repos-getReadme

**Comment by leefsmp** [comment]
Thanks a bunch!
