### ISSUE TITLE
Documentation for releases#uploadAsset is incorrect

### ISSUE THREAD

**Issue by kyleolsondesign** [octokit/octokit.js#319]
https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/releases.js#L388

release#uploadAsset is missing docs for the `filePath` property in `msg` object, used in the test file:
https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/releasesTest.js#L205

**Comment by kyleolsondesign** [comment]
It's also missing docs for the `filePath` option used in the test file:
https://github.com/mikedeboer/node-github/blob/master/api/v3.0.0/releasesTest.js#L205

**Comment by kyleolsondesign** [comment]
Related: https://github.com/mikedeboer/node-github/issues/203

**Comment by kaizensoze** [comment]
Let me know if this works: https://mikedeboer.github.io/node-github/#api-repos-uploadAsset
