### ISSUE TITLE
How does createfile work?

### ISSUE THREAD

**Issue by vydingding** [octokit/octokit.js#322]
I'm trying to create a file and it prompts me a status error 404, message: not found, null vydingding

var GitHubApi = require("github");
var Assert = require("assert");

var github = new GitHubApi({
    // required
    version: "3.0.0",
    // optional
    debug: true,
    protocol: "https",
    host: "api.github.com", 
    pathPrefix: "", 
    timeout: 5000,
    headers: {
        "user-agent": "My-Cool-GitHub-App" 
    }
});
github.repos.createFile({

```
user: "vydingding",
repo: "166KATA",
path: "/master/",
message: "my commit message",
content: "hello.csv"
```

}, function(err, res) {

});

**Comment by kaizensoze** [comment]
Answered in https://github.com/kaizensoze/node-github/issues/96
