### ISSUE TITLE
Webpack incompatibility

### ISSUE THREAD

**Issue by Kmaschta** [octokit/octokit.js#328]
Hello there,

It's impossible for me to include `node-github` in a webpack build.

I have this warning (with many others) when I build:

```
WARNING in ./~/github/index.js
Critical dependencies:
779:22-39 the request of a dependency is an expression
 @ ./~/github/index.js 779:22-39
```

And when I run the project, I have:

```
Error: Cannot find module './v3.0.0'.
    at /var/task/index.js:4003:42
    at webpackContextResolve (/var/task/index.js:4003:90)
    at webpackContext (/var/task/index.js:4000:30)
    at new module.exports (/var/task/index.js:263:39)
    at handler (/var/task/index.js:63:19)
```

I saw the closed issue #291, I have the same problem, which is not solved.

**Comment by cmbirk** [comment]
I'm getting the same issue with browserify.

**Comment by kaizensoze** [comment]
New version published to npm. Let me know if you're still having the issue.

**Comment by tocttou** [comment]
I tried with the latest version on npm and still facing this issue.

**Comment by kaizensoze** [comment]
Ok I'll take a look.

**Comment by kristajg** [comment]
Also having same issue.  Mainly having to do with json-loader, and I tried installing & configuring that... then subsequently webpack doesn't like:

`WARNING in ./~/github/lib/generate.js
Module parse failed: /node_modules/github/lib/generate.js Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.`

**Comment by SxMShaDoW** [comment]
Would love webpack issues to be fixed.

**Comment by mohsen1** [comment]
Using isomorphic-fetch instead of http should make this work in browsers with very little change
