### ISSUE TITLE
repos.getAll doesn't contain the meta attribute or the headers info

### ISSUE THREAD

**Issue by deepakprabhakara** [octokit/octokit.js#329]
getAll returns an array and hence doesn't contain the meta attribute or the headers info which prevents users from paginating. How do we get to the 'link' header for pagination?

**Comment by renatoargh** [comment]
Having the same problem here

**Comment by kaizensoze** [comment]
I'm seeing meta attributes when running repos.getAll:
You're not seeing anything for `res.meta` when running this?

``` javascript
"use strict";

var Client = require("./../lib/index");
var testAuth = require("./../testAuth.json");

var github = new Client({
    debug: false
});

github.authenticate({
    type: "oauth",
    token: testAuth["token"]
});

github.repos.getAll({}, function(err, res) {
    console.log(err, res.meta);
});
```

Are you referring to the getAllPages generic util method?

**Comment by kaizensoze** [comment]
Actually the whole point of getAllPages is to include data for all pages without having to paginate. As it says in the docs: 

> Follow all next links and returned the combined data of all pages
