### ISSUE TITLE
Add TypeScript definition file

### ISSUE THREAD

**Issue by ludohenin** [octokit/octokit.js#337]
Do you have any plans to provide a TypeScript definition file for your library? which is, btw, awesome.

**Comment by ludohenin** [comment]
I'll actually try to generate it from the routes.json file.

**Comment by kaizensoze** [comment]
Ehh PR welcome :)

**Comment by kaizensoze** [comment]
Including this possibly helpful link for future reference: https://www.stevefenton.co.uk/2013/01/complex-typescript-definitions-made-easy/

**Comment by jessehouwing** [comment]
Would love this as well :).

**Comment by DanielRosenwasser** [comment]
Fix is up on #479.

**Comment by jessehouwing** [comment]
Current typescript lib is causing compile errors with Typescript 2.1.4. Fix is relatively easy as far as I can tell:
```
node_modules/github/lib/index.d.ts(1328,18): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
node_modules/github/lib/index.d.ts(1413,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
node_modules/github/lib/index.d.ts(1420,19): error TS2314: Generic type 'Array<T>' requires 1 type argument(s).
```

Replacing `Array` with `Array<string>` or `string[]` at these locations fixes the compile issues.

**Comment by jessehouwing** [comment]
Pull request submitted.
