### ISSUE TITLE
repos#getForOrg not generated

### ISSUE THREAD

**Issue by ludohenin** [octokit/octokit.js#338]
The above mentioned method (`repos#getForOrg`) isn't genrated, though it's in the doc and the `routes.json` (https://github.com/mikedeboer/node-github/blob/master/lib/routes.json#L3140)

**Comment by kaizensoze** [comment]
Yeah there's a current mismatch between repo/docs and npm. Waiting on npm publish access. Sorry about that,

**Comment by kaizensoze** [comment]
Should be up to date now.

**Comment by ludohenin** [comment]
Awesome, has it been published to npm ?

**Comment by kaizensoze** [comment]
Yep, 1.1.0 on npm.

**Comment by ludohenin** [comment]
Excellent, why aren't keeping your github release align with npm ?
That's quite confusing to see `0.2.4` in package.json and `1.1.0` in npm.

**Comment by kaizensoze** [comment]
I was maintaining a fork for some time and only recently merged it into upstream. Forgot to update tags/releases. Will do so.
