### ISSUE TITLE
Any plans to publish tags and npm?

### ISSUE THREAD

**Issue by cristiandouce** [octokit/octokit.js#339]
Hi!

Sorry to bother... I just saw that there has been plenty of development on this project in the last months but there has been no proper release as github tags nor npm versions in the registry, so there is no easy way to reference to those releases via package.json.

Thanks.

**Comment by kaizensoze** [comment]
Should be good to go as 1.1.0 on npm.

**Comment by kaizensoze** [comment]
I still need to update the tags/releases.

**Comment by kaizensoze** [comment]
Tag/relase added: https://github.com/mikedeboer/node-github/releases/tag/v1.1.0

**Comment by cristiandouce** [comment]
Thanks a lot!
