### ISSUE TITLE
repos#getContent doesn't expect the correct params ans returns an array of repos

### ISSUE THREAD

**Issue by ludohenin** [octokit/octokit.js#340]
It's me again, I'm having an issue with `repos#getContent`. It expects param `org` (`user`, `repo`, `path`, `ref` reading the doc) and return a array of repos, basically all of them (first page).

**Comment by kaizensoze** [comment]
Where are you seeing the `org` param?

https://mikedeboer.github.io/node-github/#api-repos-getContent
https://developer.github.com/v3/repos/contents/#get-contents

This should work:

``` javascript
var GitHubApi = require("github");

var github = new GitHubApi({
  debug: true
});

github.authenticate({
    type: "oauth",
    token: <token>
});

github.repos.getContent({
  user: "mikedeboer",
  repo: "node-github",
  path: "README.md"
}, function(err, res) {
  console.log(err, res.content);
});
```

**Comment by ludohenin** [comment]
Oooops, my bad ... this is working very fine. I'm wrapping up the method calls into promises and I was just invoking the wrong one :/ sorry about that.
