### ISSUE TITLE
github.getAllPages throws RangeError when rate limit exceeded

### ISSUE THREAD

**Issue by renatoargh** [octokit/octokit.js#350]
I am getting a `RangeError` (and thus stopping the whole app) when anonymously performing more than 60 requests per hour!

As soon as the time limitation passes everything is back to work again!

This is the stack trace: 

``` text
_http_server.js:192
    throw new RangeError(`Invalid status code: ${statusCode}`);
    ^

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (/Users/renatoargh/Github/ghsummary/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:433:10)
```

**Comment by kaizensoze** [comment]
I'm not seeing that when, for example, running `node examples/getIssuesForRepo` with the auth-related lines commented out and exceeding the hourly limit. What endpoint are you using?

**Comment by renatoargh** [comment]
Hi @kaizensoze thanks for your reply, the code I am running is this; `github.getAllPages(github.repos.getForUser, params, cb);`. I forgot mentioning that I am using `github.getAllPages` and params is; `{ user: 'renatoargh', per_page: 100 }`.

**Comment by kaizensoze** [comment]
Ahh ok so it's an issue with github.getAllPages. I'll look into it.

**Comment by renatoargh** [comment]
Hey, @kaizensoze any position about this issue?

**Comment by kaizensoze** [comment]
Haven't gotten a chance to look into this yet. I'm pretty sure it's related to https://github.com/mikedeboer/node-github/issues/329 since rate limit info is in meta, which is missing. Probably a matter of including meta and headers in the getAllPages util function.

**Comment by renatoargh** [comment]
Thanks @kaizensoze will try to have a look at this as soon as I can!

**Comment by kaizensoze** [comment]
I'm going to get rid of the getAllPages method. It was only added recently, meant as a convenience utility method, but it doesn't really fit, and has already proven confusing/buggy by users.

**Comment by renatoargh** [comment]
@kaizensoze ok, thanks for your time anyway, congrats for the great job!
