### ISSUE TITLE
Support Squash in the Merge API

### ISSUE THREAD

**Issue by supertylerc** [octokit/octokit.js#352]
See [this blog post](https://developer.github.com/changes/2016-04-01-squash-api-preview/).  I use a bot that could automatically merge pull requests for me, but I prefer the newer option to squash commits before merging and leave a reference to the pull request number in the commit message.

**Comment by kaizensoze** [comment]
Yep, it'll require preview period accept headers. Something I'm working on. https://github.com/mikedeboer/node-github/pull/353
