### ISSUE TITLE
add enterprise management console endpoints

### ISSUE THREAD

**Issue by kaizensoze** [octokit/octokit.js#376]
https://developer.github.com/v3/enterprise/management_console/

**Comment by gr2m** [comment]
FYI the current plan is to remove enterprise routes in a future release and instead create separate packages for the respective enterprise versions. These will include all supported endpoints. The process will be automated using https://github.com/octokit/routes

**Comment by gr2m** [comment]
closing in favor of https://github.com/octokit/rest.js/issues/1098
