### ISSUE TITLE
support - get list of repos by/of/from organization

### ISSUE THREAD

**Issue by the1mills** [octokit/octokit.js#378]
Hi! Thanks for this project - is there a way to get a list of all the repos under an organization (public repos + private repos)? thanks

**Comment by kaizensoze** [comment]
This should do the trick: http://mikedeboer.github.io/node-github/#api-repos-getForOrg

**Comment by the1mills** [comment]
thanks that seemed to work! cheers

**Comment by vincerubinetti** [comment]
Stumbled here from Google.

The [current docs](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories) give `await octokit.request('GET /orgs/{org}/repos')` as the example for getting an orgs repos, but it looks like you can use `await octokit.rest.repos.listForOrg` instead (a little more readable and ergonomic).
