### ISSUE TITLE
createDeployment task parameter should be optional

### ISSUE THREAD

**Issue by roonyh** [octokit/octokit.js#383]
In [createDeployment](http://mikedeboer.github.io/node-github/#api-repos-createDeployment) `task` parameter is required though a default value is specified.

But its optional in the [github api](https://developer.github.com/v3/repos/deployments/#create-a-deployment). 

It could be optional with "deploy" as the default value.

**Comment by kaizensoze** [comment]
Thanks for pointing this out. Should be fixed in the next release.
