### ISSUE TITLE
add protected branch api endpoints

### ISSUE THREAD

**Issue by kaizensoze** [octokit/octokit.js#391]
https://developer.github.com/v3/repos/branches/

**Comment by codydaig** [comment]
@kaizensoze I'm happy to take this task on if noone else it.

**Comment by kaizensoze** [comment]
@codydaig Sure, go for it.

**Comment by codydaig** [comment]
I have some work done on this, but I had some work things come up. I'd love to finish but it won't be until later next week. If you want to get it in sooner, that's fine! If you want to wait, I will finish it.

**Comment by kaizensoze** [comment]
Later next week is fine. No rush.

**Comment by kaizensoze** [comment]
I'm gonna go ahead and work on this.
