### ISSUE TITLE
Comma-separated list for affiliation parameter

### ISSUE THREAD

**Issue by JNKielmann** [octokit/octokit.js#394]
Hi,
I want to get all repos from a user with the types `owner,organization_member`
The docs say the affiliation parameter of repos.getAll can be a comma-separated list of values (https://mikedeboer.github.io/node-github/#api-repos-getAll).
However when I send a request like that I get the following error:
`Invalid value for parameter 'affiliation': owner,organization_member`

The validation regex in routes.json looks like this:
`"validation": "^(owner|collaborator|organization_member)$",`
This only allows single values and no lists. Maybe the validation can be removed for this parameter, because it is hard to validate with just a regex.

**Comment by kaizensoze** [comment]
fixed by 653866c24b6249ffd595013f5e0e047394b7dffe
