### ISSUE TITLE
Add Promise option if no callback is provided

### ISSUE THREAD

**Issue by NorikDavtian** [octokit/octokit.js#396]
What do you guys think about being able to use this module with a Promise API to prevent the [callback hell](http://callbackhell.com/)? 
 All it requires is a slight modification to the `index.js` file.

``` javascript
if (callback) {
    api[section][funcName].call(api, msg, block, callback);
} else {
    return new Promise(function (resolve, reject) {
        api[section][funcName].call(api, msg, block, function (err, res) {
            if (err) {
                reject(err);
            } else {
                resolve(res);
            }
        });
    });
}
```

**Comment by kaizensoze** [comment]
This is already implemented. You just need to provide the desired Promise library in the constructor. See the `Promise` param in the example: https://github.com/mikedeboer/node-github#example.

**Comment by NorikDavtian** [comment]
Yeh just pulled the latest version 👍 Thanks
