### ISSUE TITLE
ETIMEDOUT when making  alot of calls at once

### ISSUE THREAD

**Issue by kamil-maslowski** [octokit/octokit.js#397]
So what I'm doing is making around ~1800 request for user data at once, each one inside a promise, but everytime I get the same error (it's not happening when there is a lot less requests)

> Error: connect ETIMEDOUT 192.30.253.117:443
>     at config.sendError (c:\PATH\node_modules\github\lib\index.js:780:19)
>     at c:\PATH\node_modules\github\lib\index.js:789:29
>     at callCallback (c:\PATH\node_modules\github\lib\index.js:665:17)
>     at ClientRequest.<anonymous> (c:\PATH\node_modules\github\lib\index.js:737:17)
>     at emitOne (events.js:77:13)
>     at ClientRequest.emit (events.js:169:7)
>     at TLSSocket.socketErrorListener (_http_client.js:267:9)
>     at emitOne (events.js:77:13)
>     at TLSSocket.emit (events.js:169:7)
>     at emitErrorNT (net.js:1269:8)

Is that a bug in a library or am I doing something wrong?

**Comment by kaizensoze** [comment]
Can I get a code sample to reproduce it?

**Comment by kamil-maslowski** [comment]
Sorry, problem solved...

Turned out that GH has some abuse rate limits, when doing so many calls in a loop it was rejecting them.
Although weird is that on my local machine I was getting ETIMEDOUT, but on remote machine it was correctly logging message from GH that I have exceeded abuse rate limits...

I was just calling
`github
            .users
            .getForUser({
              user: username,
            }, theUserIsHere);`
in a loop 1811 times.

Now I'm using rate-limit package to rate the calls to 1 per 5ms.

**Comment by kaizensoze** [comment]
Yeah the Github API allows 5000 authenticated requests/hr.

https://developer.github.com/v3/#rate-limiting

**Comment by kamil-maslowski** [comment]
That was not the problem, I'm aware of 5k call limit.
This is the one that I encountered: https://developer.github.com/v3/#abuse-rate-limits

**Comment by kaizensoze** [comment]
Ah ok.
