### ISSUE TITLE
add support for promise Q

### ISSUE THREAD

**Issue by calvinhmw** [octokit/octokit.js#400]
I was trying to use the Q library https://github.com/kriskowal/q to create promise in node-github's calls.   I ran the code (given in the example) below:

```
"use strict";

var Client = require("./../lib/index");
var Promise = require("q");  

var github = new Client({
    debug: false,
    Promise: Promise
});

github.orgs.getAll({
    page: 5,
    per_page: 100
}).then(function(res) {
    console.log(res);

    github.users.getById({ id: "429706" }).then(function(res) {
        console.log(res);
    });
});

```

But got the output:

```
[Function]
[Function]

```

Is Q library not supported in node-github or am I using it the wrong way ?

**Comment by kaizensoze** [comment]
I'll take a look.

**Comment by jamsinclair** [comment]
From a quick play around I've found the default Q library export does not return a valid JS Promise Object API. 

To get things working you'll need to ensure you use the `Promise` object from within the Q package.

The following works for me:

``` javascript
var GitHubApi = require('github');
var Q = require('q');  

var github = new GitHubApi({
    Promise: Q.Promise
});

github.users.getById({ id: '5057219' }).then(function(res) {
    console.log(res);
});
```

Or es6:

``` javascript
const GitHubApi = require('github');
const { Promise } = require('q');  

const github = new GitHubApi({
    Promise: Promise
});

github.users.getById({ id: '5057219' }).then(res => {
    console.log(res);
});
```

**Comment by kaizensoze** [comment]
Ah perfect. I've added an [example](https://github.com/mikedeboer/node-github/blob/master/examples/testPromiseQ.js). Going to close this.

**Comment by advance512** [comment]
Can we add some sort of comment about this in the documentation, or the main Readme?

This issue caused me quite a bit of pain :)

**Comment by kaizensoze** [comment]
Sure I'll add a section on Promises to the readme.

**Comment by advance512** [comment]
Thank you!
