### ISSUE TITLE
Content validation for reactions.createForIssue has invalid regex

### ISSUE THREAD

**Issue by lbustelo** [octokit/octokit.js#410]
`"^(+1|-1|laugh|confused|heart|hooray)$"`

Need to escape the `+`. 
`"^(\\+1|-1|laugh|confused|heart|hooray)$"`

Other might be affected too.

Example
https://github.com/mikedeboer/node-github/blob/d6aee8b1e8bfa56d536d9ebb094f9afc4ac59b20/lib/routes.json#L3619

**Comment by lbustelo** [comment]
This prevent usage of those apis.

**Comment by kaizensoze** [comment]
Thanks. Fix pushed in 2.5.2 (https://www.npmjs.com/package/github). (forgot to reference issue in commit)
