### ISSUE TITLE
add support for renaming labels

### ISSUE THREAD

**Issue by Xiphe** [octokit/octokit.js#415]
**Given** I have a label "foo"

**When** I want to rename it to "bar"

**Then** I use [`github.issues.updateLabel`](http://mikedeboer.github.io/node-github/#api-issues-updateLabel)

**But** The API only accepts one `name` parameter and I'm unable to define the `oldname`

---
### Background

GitHubs [API to update a label](https://developer.github.com/v3/issues/labels/#update-a-label) supports a `PATCH` request to `https://api.github.com/repos/Jimdo/github-sync-labels-milestones/labels/foo` with `{ name: "bar", color: "ff00ff" }` parameters.

**Comment by Xiphe** [comment]
I'd propose to add a `github.issues.renameLabel` method with this route

``` json
{
  "rename-label": {
    "url": "/repos/:user/:repo/labels/:oldname",
    "method": "PATCH",
    "params": {
      "$user": null,
      "$repo": null,
      "$oldname": null,
      "$name": null,
      "$color": null
    },
    "description": "Rename a label"
  }
}
```

I'd be happy to propose a PR

**Comment by kaizensoze** [comment]
Yes, the updateLabel endpoint is missing a `name` param. Nice catch. I'll fix it shortly. It'll be a major release since it's a breaking change.

**Comment by Xiphe** [comment]
yeah, that was fast! thank you!
