### ISSUE TITLE
[Question] Get user by email

### ISSUE THREAD

**Issue by Naramsim** [octokit/octokit.js#420]
Is it possible with this API to get a user by email field?

I saw that you support `/user/:id`

**Comment by gaborcsardi** [comment]
There is no direct API for this AFAIK, but you can use the search API for public email addresses, e.g. like here: https://github.com/sindresorhus/github-username/blob/master/index.js

**Comment by kaizensoze** [comment]
Yeah the email address would need to be public. Otherwise you need to know the user's id/username.

**Comment by kaizensoze** [comment]
Going to close this since getUserByEmail isn't possible in the github api.
