### ISSUE TITLE
Add Collaborator - Permissions

### ISSUE THREAD

**Issue by callmekatootie** [octokit/octokit.js#421]
Reference: http://mikedeboer.github.io/node-github/#api-repos-addCollaborator

`permission`: `pull` - team members can pull, but not push or administer this repositories (**Default**)

It says that by default, the collaborators have only pull access.

I assume that means that if the permission is not provided, the only Read permissions are assigned.

However, it appears that if I don't specify the permission while adding a collaborator, they are given Write permissions (push). The documentation and the actual function do not match

**Comment by kaizensoze** [comment]
I'm testing it now, but just to double check, is the repo you're trying it with an organization-owned repo?

https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator

**Comment by callmekatootie** [comment]
Yes, if I explicitly pass `pull` as a value, it does set the Read permission.

I was expecting that by not passing anything, it sets it automatically because the documentation says `pull` is default.

I now notice that the official Github documentation says `push` is default while the documentation for this module says `pull` is the default. I am guessing your documentation needs an update, and not the code...

**Comment by kaizensoze** [comment]
Yeah I'll go ahead and update the docs. Thanks for the heads up.
