### ISSUE TITLE
Add support for installations repositories

### ISSUE THREAD

**Issue by olivierlesnicki** [octokit/octokit.js#447]
Installations can access the list of repositories they have access to by calling:
`/installation/repositories`

**Comment by kaizensoze** [comment]
added: 1b355653b8d97f8793c4e6763b1ccb59475ec280, included in latest 5.3.3

**Comment by olivierlesnicki** [comment]
That was a fast turnaround! Good job!

**Comment by olivierlesnicki** [comment]
@kaizensoze actually might be more involved...
There are a large number of new end-points being introduced with installations:
https://developer.github.com/early-access/integrations/permissions/#metadata-permissions

Installation have to use /repositories/:repository-id/... instead of /repos/:owner/:repo/

**Comment by kaizensoze** [comment]
I also missed that there are two other endpoints: https://developer.github.com/v3/integrations/installations/

**Comment by kaizensoze** [comment]
Two other endpoints have been included. Creating a separate ticket for the integration permissions.
