### ISSUE TITLE
API Docs down?

### ISSUE THREAD

**Issue by JonatanS** [octokit/octokit.js#457]
Hi, it appears that the documentation for this project is down. I get the following errors when trying to load this URL:  http://mikedeboer.github.com/node-github/
![image](https://cloud.githubusercontent.com/assets/3217286/20086821/4a614efa-a541-11e6-8ce1-eb8abb9e86b7.png)

**Comment by kaizensoze** [comment]
I'm trying to figure out if something is up with github pages at the moment. If you checkout the gh-pages branch and open index.html in browser it works fine. An alternative is staying in master, running `apidoc -i doc/ -o apidoc/` and opening the index.html in the apidoc folder.

**Comment by kaizensoze** [comment]
Got this response:

> Thanks for reaching out to us! GitHub Pages has upgraded to Jekyll 3.3.0. The reason you can't access the vendor folder anymore is because it is now ignored by default. If you need that folder included in your site, simply add it to your configuration's include directive.
> 
> For more on this upgrade you can view our blog post here:
> 
> https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3
> 
> And for more on the newest version of Jekyll you can take a look here: http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/
> 
> If you're not using Jekyll, you can add a .nojekyll file to the root of your repository to disable Jekyll from building your site. Once you do that, your site should build with your vendor folder.

I'll look into this shortly.

**Comment by kaizensoze** [comment]
Fixed.

**Comment by JonatanS** [comment]
Awesome. Thank you for fixing it this quickly!
