### ISSUE TITLE
gitdata get-references issue

### ISSUE THREAD

**Issue by yotamshacham** [octokit/octokit.js#460]
The code in question is something like:
`github.gitdata.getReferences({owner:"embroker", repo:"embroker"}, callback);`

I think there is some issue with my understanding of the github API or possible a documentation issue there.  The docs specify:
`GET` /repos/:owner/:repo/git/refs`

> This will return an array of all the references on the system, including things like notes and stashes if they exist on the server.

[](https://developer.github.com/v3/git/refs/#get-all-references)

However for me it doesnt return all the refs, only a relatively small amount.  Using postman to diagnose, I discovered if I add "/" or "/heads" to the url, then I do get all the refs, for some reason.

I created a fork with an additional function getReferencesWithSelector as a workaround:
`github.gitdata.getReferencesWithSelector({owner:"embroker", repo:"embroker", selector: "heads"}, callback);`
But maybe you have some insight regarding this problem / a better solution..

Thanks!

**Comment by kaizensoze** [comment]
Honestly I'm not sure why http://api.github.com/repos/mikedeboer/node-github/git/refs/ returns way more references than http://api.github.com/repos/mikedeboer/node-github/git/refs. It seems like adding the slash disables pagination and returns all results. if you bump per_page to something like 100 and iterate over the pages you should get all references with the getReferences endpoint as is.

**Comment by yotamshacham** [comment]
Yes, I think you're right regarding the pagination, strange that "/" gives a non-default page size.

In any case the github api does support sub-namespace, from the docs:

> You can also request a sub-namespace. For example, to get all the tag references, you can call:
> GET /repos/:owner/:repo/git/refs/tags

I think it would be convenient and efficient to have this functionality compared to looping on all refs always from the root.  If you like I can open a pull request with my fork (I'll just rename "selector" to "tags").

**Comment by kaizensoze** [comment]
If you want to add an endpoint that's `getReferencesWithPath` that adds a `path` param, that works.

**Comment by kaizensoze** [comment]
Actually rather than add another endpoint, I think I'm going to just add the trailing slash to the getReferences url. I might additionally allow the empty string for the ref param in general.

**Comment by yotamshacham** [comment]
Sure, that sounds good but upon trying to make the change, there is complication:
- path param is also used by create-commit
- path param would need same "special" treatment as ref param (to keep forward slashes)

In other words the change would affect create-commit, which I'm not sure is desired.
Please advise.

Also, I'm trying to run the tests, and getting most failing.  I created the testAuth.json.  See attached
[node github log.txt](https://github.com/mikedeboer/node-github/files/582583/node.github.log.txt)

Thanks!

**Comment by yotamshacham** [comment]
I didn't see your earlier response for some reason.
The update you did of adding slash does give me the full list, but just wondering why not give the full sub-namespace flexibility?  Looks like empty argument is supported in your code, would just need to add such an arg after the slash for this command.
Thanks

**Comment by kaizensoze** [comment]
The sub-namespace flexibility is built into the existing getReference endpoint. You can pass a subnamespace as the ref param for that endpoint. It's misleading I guess since getReference will return multiple references, but that's as according to the official github docs.

**Comment by yotamshacham** [comment]
Ah I see now, thanks.

**Comment by kaizensoze** [comment]
Also, tests are a lost cause at the moment as I don't think they've ever worked.
