### ISSUE TITLE
Content is trimmed when creating blobs

### ISSUE THREAD

**Issue by lennym** [octokit/octokit.js#461]
When I call `github.gitdata.createBlob` any trailing whitespace is removed from the file content here - https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L173

This means that all files end up showing up like this when they are committed:

<img width="259" alt="screen shot 2016-11-09 at 17 16 34" src="https://cloud.githubusercontent.com/assets/117398/20147618/bc95bd16-a6a0-11e6-8d28-98526c9e3dd0.png">

I would expect file content passed into `createBlob` to preserved *exactly* as-is and not modified.

**Comment by kaizensoze** [comment]
Fix included in latest 6.0.4.

**Comment by lennym** [comment]
Amazing. Thanks so much for the super-fast turnaround. I really appreciate it.
