### ISSUE TITLE
Add support for delete-reference

### ISSUE THREAD

**Issue by dmelton-gpsw** [octokit/octokit.js#463]
I'd like to use this library to delete a branch after merging the PR, i.e. with this command:

https://developer.github.com/v3/git/refs/#delete-a-reference

```
DELETE /repos/:owner/:repo/git/refs/:ref

DELETE /repos/octocat/Hello-World/git/refs/heads/feature-a
```

**Comment by kaizensoze** [comment]
Should be included already: https://mikedeboer.github.io/node-github/#api-gitdata-deleteReference

**Comment by dgmltn** [comment]
Well, nevermind, I just noticed my version was outdated. Thanks! 👍

**Comment by kaizensoze** [comment]
Sure thing.
