### ISSUE TITLE
Route GET /repos/:owner/:repo does not work?

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#465]
```
var auth = {
            token: process.env.GITHUB_ACCESS_TOKEN,
            type: 'oauth',
        }
    }

var github = new Github();
github.authenticate(auth);

github.repos.get({ owner: 'joliejuke', repo: 'myRepo' }, function(err, res) {

            if (err) {
                return reject(err)
            }
            return resolve(res)
        });
```

Got response 404 from Github api v3.

Maybe there is a change on github API but I didn't notice that.
Do you have same problem? Or did I miss something in my code?

**Comment by jeffwilcox** [comment]
"Works on my machine" with the latest `npm` right now.

It's always a little tough since a 404 in GitHub can also mean "there's a private thing, but you can't see it"

**Comment by kaizensoze** [comment]
`joliejuke/myRepo` seems to be private. Make sure `process.env.GITHUB_ACCESS_TOKEN` has access to private repos.

**Comment by ghost** [comment]
Thanks guys for your answers :)

I just found why it was 404...
I have created a repo with my account "joliejuke", but this repo live in an Organisation, so I could not reach it using the route `/repos/joliejuke/:repo`

Nice module btw, it helps a lot :)

**Comment by kaizensoze** [comment]
Ah ok. Glad you got it resolved!
