### ISSUE TITLE
Add support for .netrc

### ISSUE THREAD

**Issue by ruimarinho** [octokit/octokit.js#466]
`.netrc` is a commonly used login helper, specially for github.com. Would you be open to support it?

**Comment by kaizensoze** [comment]
I'd be open to reading from a `~/.netrc` for authentication.

**Comment by jeffwilcox** [comment]
There's also the `node-netrc` library that might be able to help without having to bake it right into the library. On GitHub here: https://github.com/duojs/node-netrc

**Comment by gr2m** [comment]
@ruimarinho @kaizensoze @jeffwilcox we are removing `.netrc` support in preparation to make the library compatible for browser usage.

The workaround is to use the [netrc](https://www.npmjs.com/package/netrc) package directly and then pass username/password to `github.authenticate({type: 'basic', username, password})`. 

Does that break any of your usage right now?

The pull request is at https://github.com/octokit/node-github/pull/640 👀

**Comment by jeffwilcox** [comment]
@gr2m thanks for reaching out. We don't use `.netrc`, supportive of the change, love the focus on reducing those dependencies.

**Comment by ruimarinho** [comment]
@gr2m I greatly appreciate your ping - [not quite the same](https://xkcd.com/1873/) but not very far either :)

I have checked some changelog generators that I know were using this lib and, so far, I couldn't find any explicit reference to `.netrc`. If I remember correctly, the original idea of this PR was to avoid setting up additional environment variables with access tokens as `.netrc` served that purpose well. Any project using this lib would just work out of the box.

Fast forward to today and `.netrc` probably continues to see marginal use so I am sympathetic with your move to promote a leaner code base.
