### ISSUE TITLE
Example for pushing a commit?

### ISSUE THREAD

**Issue by skistaddy** [octokit/octokit.js#475]
I searched for an example of making a commit to a repository, and couldn't find one. What file in `examples` will show me how to make a commit?

**Comment by kaizensoze** [comment]
There isn't an example but it should be gitdata.createCommit: 
https://mikedeboer.github.io/node-github/#api-gitdata-createCommit

github api link: https://developer.github.com/v3/git/commits/#create-a-commit

**Comment by kaizensoze** [comment]
Going to go ahead and close this for now.

**Comment by skistaddy** [comment]
Ok, thank you!
