### ISSUE TITLE
Mustache is not installed.

### ISSUE THREAD

**Issue by skistaddy** [octokit/octokit.js#476]
I received an error in `lib/generateFlowTypes.js`, and the error was because you're `require()`ing the `mustache` module, when it isn't installed in your dependencies.

**Comment by kaizensoze** [comment]
It's a dev dependency. That should just be required when running `node lib/generate.js`, but that's not required for simply using the module. How are you using the module? Are you getting that error when trying to run one of the examples?

**Comment by skistaddy** [comment]
I got the error when running `node lib/generate.js`, sorry.

**Comment by kaizensoze** [comment]
Yeah you only need to run that if you're making changes to the library, in which case the repo will be checked out and you'll have mustache as a dev dependency.

**Comment by skistaddy** [comment]
Ah, I see.
