### ISSUE TITLE
Is there an endpoint for GET repository?

### ISSUE THREAD

**Issue by jkup** [octokit/octokit.js#478]
Please provide a minimal code sample to reproduce the issue if possible.

Hello! I'm just using your library for the first time and I'm wondering if there is equivalent to the GitHub GET /repos/:owner/:repo (https://developer.github.com/v3/repos/#get).

Specifically, I want to get stargazers_count and it only seems available on that general GET call.

Thanks!

**Comment by kaizensoze** [comment]
Sure, there's https://mikedeboer.github.io/node-github/#api-repos-get.
There's also https://mikedeboer.github.io/node-github/#api-activity-getStargazersForRepo for just stargazers content.

**Comment by jkup** [comment]
Wow, it's right there! I swear I searched the docs for just a repos-get request! Thank you!
