### ISSUE TITLE
Forking name collision

### ISSUE THREAD

**Issue by laggingreflex** [octokit/octokit.js#483]
If you try to fork a repo which has the same name as one that previously exists, for example

https://github.com/webpack/webpack
https://github.com/start-runner/webpack

it gives an error. But it does gets forked as `webpack-1` 

Any way to get that name instead of an error?

**Comment by kaizensoze** [comment]
Can you provide some example code for what you're trying to fork?

**Comment by laggingreflex** [comment]
I was mistaken, it does give you the name of the forked repo as `webpack-1`. Sorry about that.

**Comment by kaizensoze** [comment]
No worries. Glad it's resolved!
