### ISSUE TITLE
Issue within React Create App

### ISSUE THREAD

**Issue by Darren-Ivey** [octokit/octokit.js#485]
I have added this package to a React Create App, but get the following error (as well as a several warning):

"Uncaught TypeError: Invalid Version: semver.js:293 "

I updated both my npm and node, but the issue persisted. Is this a common issue and is there a solution?

Thanks in advance.

**Comment by kaizensoze** [comment]
Are you using gulp? Searching on the error in google shows several of the first results being related to gulp: 

https://www.google.com/search?q=Uncaught+TypeError%3A+Invalid+Version%3A+semver.js%3A293&oq=Uncaught+TypeError%3A+Invalid+Version%3A+semver.js%3A293&aqs=chrome..69i57.132j0j7&sourceid=chrome&ie=UTF-8

**Comment by Darren-Ivey** [comment]
Thanks for a fast response. Unfortunately I am not using Gulp.

**Comment by kaizensoze** [comment]
Do you have a sample project I can take a look at to reproduce the issue?

**Comment by Darren-Ivey** [comment]
I have put a bare bones crate react app with the github demo in the App.js here: https://github.com/Darren-Ivey/React-GitHubApi-Test

**Comment by kaizensoze** [comment]
My best guess is an incompatibility with webpack. Unfortunately there isn't currently a fix.

**Comment by Darren-Ivey** [comment]
Ok, fair enough. Thank you for looking into the issue, it's much appreciated.

**Comment by gr2m** [comment]
@Darren-Ivey I made a few changes recently that should help with browserify compatibility. Could you give it another try by chance?

Also the next milestone is browser compatibility, if you are interested in progress I recommend to subscribe to this issue: #620

**Comment by gr2m** [comment]
It should work with latest `@octokit/rest`, please let me know if it doesn’t.

I working towards further browser improvements, like test setups and reduced bundle size. See https://github.com/octokit/rest.js/issues/620#issuecomment-362715478

**Comment by rsullivan00** [comment]
@gr2m Looks like the Octokit npm package isn't compiled to ES5, which `create-react-app` expects for dependencies.

```
yarn run v1.5.1
$ yarn run build
$ NODE_PATH=./src react-app-rewired build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/@octokit/rest/lib/plugins/pagination/get-page-links.js:10:26

Read more here: http://bit.ly/2tRViJ9

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c NODE_PATH=./src react-app-rewired build
```

**Comment by gr2m** [comment]
Could you please create a follow up issue on that? I try to avoid a build step right now, but plan to use the ES Modules syntax in future for better tree shaking / smaller bundle size, so that should fix it for good. But before that it would be great if you could have a look what syntax is breaking right now, if it's not too much we can just make the change directly

**Comment by rsullivan00** [comment]
Looks like that line uses an arrow function--I doubt it's worthwhile to manually convert ES6 syntax to ES5. I can work around this by forking and building to ES5 in the short term.

```js
link.replace(/<([^>]*)>;\s*rel="([\w]*)"/g, (m, uri, type) => {
```

I'll create a separate issue to track the issue.
