### ISSUE TITLE
Not able to use github.pullRequests.getReviewsComments

### ISSUE THREAD

**Issue by luisfernandos** [octokit/octokit.js#488]
I have noted that I need to pass a different header information in order to this api work.
I tried it with curl and this command works:

curl  -v -H "Accept: application/vnd.github.black-cat-preview+json" https://api.github.com/repos/spring-projects/spring-boot/pulls/7600/reviews/15601905/comments

I got this answer:
*   Trying 192.30.253.116...
* Connected to api.github.com (192.30.253.116) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.github.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /repos/spring-projects/spring-boot/pulls/7600/reviews/15601905/comments HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.43.0
> Accept: application/vnd.github.black-cat-preview+json
> 
< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Wed, 11 Jan 2017 15:34:32 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 2291
< Status: 200 OK
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 48
< X-RateLimit-Reset: 1484149074
< Cache-Control: public, max-age=60, s-maxage=60
< Vary: Accept
< ETag: "ae43d650d3c6e5301fba36fcf8d630ad"
< X-GitHub-Media-Type: github.black-cat-preview; format=json
< Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-Frame-Options: deny
< X-XSS-Protection: 1; mode=block
< Vary: Accept-Encoding
< X-Served-By: 075bb2f6b7031ca3c0e69edb17939fae
< X-GitHub-Request-Id: BD1D3EEF:6B4D:5CFB31B:58765088
< 
[
  {
    "id": 95054811,
    "url": "https://api.github.com/repos//spring-projects/spring-boot/pulls/comments/95054811",
    "pull_request_review_id": 15601905,
    "diff_hunk": "@@ -0,0 +1,2 @@\n+# Use random port for embedded Mongod.\n+spring.data.mongodb.port = 0",
    "path": "spring-boot-test-autoconfigure/src/test/resources/application.properties",
    "position": 2,
    "original_position": 2,
    "commit_id": "f82c23ce30e3a5354f4521df65205fa900bac7b0",
    "original_commit_id": "e7c73faf6decc7894f701333e8ca270cf14a8ca3",
    "user": {
      "login": "snicoll",
      "id": 490484,
      "avatar_url": "https://avatars3.githubusercontent.com/u/490484?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/snicoll",
      "html_url": "https://github.com/snicoll",
      "followers_url": "https://api.github.com/users/snicoll/followers",
      "following_url": "https://api.github.com/users/snicoll/following{/other_user}",
      "gists_url": "https://api.github.com/users/snicoll/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/snicoll/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/snicoll/subscriptions",
      "organizations_url": "https://api.github.com/users/snicoll/orgs",
      "repos_url": "https://api.github.com/users/snicoll/repos",
      "events_url": "https://api.github.com/users/snicoll/events{/privacy}",
      "received_events_url": "https://api.github.com/users/snicoll/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "I wish there was another way. I'll give it more thoughts.",
    "created_at": "2017-01-07T08:11:38Z",
    "updated_at": "2017-01-07T08:11:38Z",
    "html_url": "https://github.com/spring-projects/spring-boot/pull/7600#discussion_r95054811",
    "pull_request_url": "https://api.github.com/repos/spring-projects/spring-boot/pulls/7600",
    "_links": {
      "self": {
        "href": "https://api.github.com/repos//spring-projects/spring-boot/pulls/comments/95054811"
      },
      "html": {
        "href": "https://github.com/spring-projects/spring-boot/pull/7600#discussion_r95054811"
      },
      "pull_request": {
        "href": "https://api.github.com/repos/spring-projects/spring-boot/pulls/7600"
      }
    }
  }
]
* Connection #0 to host api.github.com left intact

However I need to use the api, so I have changed my code to ad header information like this:
<pre>
function fetchReviewComments(organization, prId, reviewId) {
            return github.pullRequests.getReviewsComments({
                    owner: organization,
                    number: prId,
                    id: reviewId,
                    // we are using the Accept because the review api is still under testing
                    headers: {
                        "Accept": "application/vnd.github.black-cat-preview+json"
                    }
                })
                .then(function (comments) {
                    console.log("fetchReviewComments Hey I got " + comments.length + " comments for:" + reviewId)
                })
                .catch(function (err) {
                    console.log("fetchReviewComments Error" + err);
                });
        }
</pre>

After dispatching this command I receive this error:

<pre>
STATUS: 404
HEADERS: {"server":"GitHub.com","date":"Wed, 11 Jan 2017 15:44:54 GMT","content-type":"application/json; charset=utf-8","content-length":"77","connection":"close","status":"404 Not Found","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4869","x-ratelimit-reset":"1484150605","x-oauth-scopes":"","x-accepted-oauth-scopes":"repo","x-github-media-type":"github.black-cat-preview; format=json","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-github-request-id":"BD1D3EEF:6B4E:977CAD4:587652F6"}
[error] { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
[error]   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}',
[error]   code: 404,
[error]   status: 'Not Found',
[error]   headers: 
[error]    { server: 'GitHub.com',
[error]      date: 'Wed, 11 Jan 2017 15:44:54 GMT',
[error]      'content-type': 'application/json; charset=utf-8',
[error]      'content-length': '77',
[error]      connection: 'close',
[error]      status: '404 Not Found',
[error]      'x-ratelimit-limit': '5000',
[error]      'x-ratelimit-remaining': '4869',
[error]      'x-ratelimit-reset': '1484150605',
[error]      'x-oauth-scopes': '',
[error]      'x-accepted-oauth-scopes': 'repo',
[error]      'x-github-media-type': 'github.black-cat-preview; format=json',
[error]      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
[error]      'access-control-allow-origin': '*',
[error]      'content-security-policy': 'default-src \'none\'',
[error]      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
[error]      'x-content-type-options': 'nosniff',
[error]      'x-frame-options': 'deny',
[error]      'x-xss-protection': '1; mode=block',
[error]      'x-github-request-id': 'BD1D3EEF:6B4E:977CAD4:587652F6' } } { owner: 'spring-projects',
[error]   number: 7600,
[error]   id: 15601905,
[error]   headers: { Accept: 'application/vnd.github.black-cat-preview+json' } } null

</pre>

  Am I doing something wrong? I tried putting the header option when instantiating the GitHubApi, but the error is the same, anyway here is where I have put the code:

<pre>
var github = new GitHubApi({
    debug: true,
    Promise: Promise,
    timeout: 5000
});
</pre>

Could somebody help me? Thanks a lot.

**Comment by kaizensoze** [comment]
Something's definitely changed since the first announcement of the preview api(s). I'll take a look.

**Comment by kaizensoze** [comment]
Yeah so when they initially announced the preview apis that use the black-cat Accept header, they originally forgot the `:repo` param in the `getReview` and `getReviewsComments` endpoints.

**Comment by luisfernandos** [comment]
humm, so I just need to send the :repo param? I will give it a try

**Comment by luisfernandos** [comment]
I tried like this:
<pre>
github.pullRequests.getReviewsComments({
                    owner: organization,
                    repo: repository,
                    number: prId,
                    id: reviewId,
                    // we are using the Accept because the review api is still under testing
                    headers: {
                        "Accept": "application/vnd.github.black-cat-preview+json"
                    }
                })
</pre>

but I got the same error :(

**Comment by kaizensoze** [comment]
No no, I need to release an update with breaking changes.

**Comment by kaizensoze** [comment]
Just pushed an 8.0.0 release.

**Comment by luisfernandos** [comment]
thank you a lot, now getReviewComments is working.

**Comment by kaizensoze** [comment]
Great, glad that did the trick!
