### ISSUE TITLE
400 Bad Request "Problems parsing JSON"

### ISSUE THREAD

**Issue by brunolemos** [octokit/octokit.js#489]
This happens on some PUT requests, like these:
```js
github.activity.markNotificationsAsRead()
github.activity.markNotificationsAsReadForRepo({ owner: 'facebook', repo: 'react', last_read_at: "2017-01-12T00:00:13Z" })
```

GitHub is expecting a valid json in the body, but it's receiving empty content.
Related to #431.

**Comment by kaizensoze** [comment]
The responses for those two endpoints look ok to me. What version of the api are you using?

**Comment by kaizensoze** [comment]
If you were to throw this in under the examples folder:

```
"use strict";

var Client = require("./../lib/index");
var testAuth = require("./../testAuth.json");

var github = new Client({
    debug: true
});

github.authenticate({
    type: "oauth",
    token: testAuth["token"]
});

// github.activity.markNotificationsAsRead({
// }, function(err, res) {
//     console.log(err, res);
// });

github.activity.markNotificationsAsReadForRepo({
    owner: "facebook",
    repo: "react",
    last_read_at: "2017-01-12T00:00:13Z"
}, function(err, res) {
    console.log(err, res);
});
```

Both of them just return Status: 205 Reset Content with data: ''.

**Comment by brunolemos** [comment]
@kaizensoze sorry, you are right.
It was a problem with my fork to be able to use on react native. I removed the nodejs dependency, used `fetch` for the requests, but forgot to add the `body` option so only get requests were working.

```js
if (hasBody) options.body = query;
```
