### ISSUE TITLE
Wrong type for comment body in Typescript defs

### ISSUE THREAD

**Issue by jimmidyson** [octokit/octokit.js#492]
Function definition for [`createComment`](https://github.com/mikedeboer/node-github/blob/263e57f411f00fe90978da16761efbd67b8dd3ba/lib/index.d.ts#L2660):

```
createComment(params: Github.IssuesCreateCommentParams, callback?: Github.Callback): Promise<any>;
```

With [`Github.IssuesCreateCommentParams`]() defined as:

```
export type IssuesCreateCommentParams =
    & Owner
    & Repo
    & Number
    & {
      body: string[];
    };
```

but body should be a string, not an array according to [Github API docs](https://developer.github.com/v3/issues/comments/#create-a-comment).

Not sure how to update this?

**Comment by kaizensoze** [comment]
I think all `body: string[]` and body?: string[]` need to be changed to just string, but I don't use typescript so I'm not 100% sure. Anyone want to verify?

**Comment by jimmidyson** [comment]
That sounds good to me, I'll have a full look through later to double check.

BTW it looks the same in flow types and needs to be updated there too.

**Comment by jimmidyson** [comment]
Looked through & I can't see any body references that should be arrays rather than just strings.

Submitted #493 that should fix this.
