### ISSUE TITLE
not able to use github.issues.addAssigneesToIssue

### ISSUE THREAD

**Issue by hsorellana** [octokit/octokit.js#496]
Hey! I'm not sure if i'm missing something, but i can't assign myself an issue in one of my own repos.

The main difference i see is that, on github's API version 3, to assign someone to an issue, the request does a 
`PATCH /repos/:owner/:repo/issues/:number` 
but reading in the documentation, the request goes to 
`POST /repos/:owner/:repo/issues/:number/assignees`.

Any feedback i can use?? 
Thanks!

**Comment by kaizensoze** [comment]
The api endpoint matches what's in the github api doc: https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue. Do you have a simple example with output I can take a look at?

**Comment by kaizensoze** [comment]
Are you trying to call the edit issue endpoint? That would be issues.edit.
The assignee field is deprecated but it should still work.

https://developer.github.com/v3/issues/#edit-an-issue

**Comment by hsorellana** [comment]
im using the add-ssignees-to-an-issue, and in the meta keys shows the 201 status code but when i see the issue on github, it doesn't show any assignees. and when i try to use the edit an issue, it throws an promise exception

**Comment by kaizensoze** [comment]
You're seeing it do `PATCH /repos/:owner/:repo/issues/:number` when you call the api endpoint? Are you using the latest version? Also, what's the exact exception you're getting?

Just to verify: https://mikedeboer.github.io/node-github/#api-issues-addAssigneesToIssue

**Comment by hsorellana** [comment]
i managed to figure out the exception, and it was my mistake. Between using issue.edit and issue.addAssigneesToIssue i was using other thing so it'd never work jeje

thanks for so quick response, Joe!

**Comment by kaizensoze** [comment]
Ah good, glad it's resolved!
