### ISSUE TITLE
Http 401 on company's private git repo 

### ISSUE THREAD

**Issue by dorjon** [octokit/octokit.js#498]
I've been consuming your API to retrieve content of a file however getContent() fails with HTTP 401. used your sample code only and just changed host value to my company's git repo host.
any pointers?

**Comment by kaizensoze** [comment]
Does the access token you're using have access to that private repo? Can you include code of the endpoint and params you're using?

**Comment by kaizensoze** [comment]
If you're using a custom `host` you also might need to specify a `pathPrefix`.

**Comment by kaizensoze** [comment]
Closing soon if no reply.
