### ISSUE TITLE
github.pullRequests.getComments({...}) doesn't work

### ISSUE THREAD

**Issue by therobinkim** [octokit/octokit.js#510]
## NOT WORKING
http://mikedeboer.github.io/node-github/#api-pullRequests-getComment
> /repos/:owner/:repo/pulls/comments/:id

```
github.pullRequests.getComments({
  owner: 'therobinkim',
  repo: 'jokes',
  number: '1'
})
.then((data) => {
  console.log(data);
});
```

results in `data: []`

## WORKING
https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue
> /repos/:owner/:repo/issues/:number/comments

```
github.issues.getComments({
  owner: 'therobinkim',
  repo: 'jokes',
  number: '1'
})
.then((data) => {
  console.log(data);
});
```

results in

```
data: [ { url: 'https://api.github.com/repos/therobinkim/jokes/issues/comments/204621579',
  html_url: 'https://github.com/therobinkim/jokes/pull/1#issuecomment-204621579',
  issue_url: 'https://api.github.com/repos/therobinkim/jokes/issues/1',
  id: 204621579,
  user: [Object],
  created_at: '2016-04-02T01:10:19Z',
  updated_at: '2016-04-02T01:10:19Z',
  body: 'Thanks JackieeeeeEEEee\n' } ],
```

---

I propose `github.pullRequests.getComment({ ... })` be removed OR that it taps into the Issues API instead.

First paragraph of https://developer.github.com/v3/pulls/ says:
> The Pull Request API allows you to list, view, edit, create, and even merge pull requests. Comments on pull requests can be managed via the [Issue Comments API](https://developer.github.com/v3/issues/comments/).

**Comment by kaizensoze** [comment]
I think the [possibly] necessary change is to clarify that they are review comments:

https://developer.github.com/v3/pulls/comments/#list-comments-on-a-pull-request

Then again, the description for the endpoint in the github api docs is literally "List commit comments for a repository."

There are many flavors of comments: commit comments, [pull request] review comments, gist comments, and issue comments.

**Comment by kaizensoze** [comment]
Wait, do you mean `pullRequests.getComments` or `pullRequests.getComment`?

The endpoint url mapping in this ticket is incorrect. It should be:

```
pullRequests.getComments (/repos/:owner/:repo/pulls/:number/comments)
pullRequests.getComment (/repos/:owner/:repo/pulls/comments/:id)
```
