### ISSUE TITLE
users.get() fails when executed

### ISSUE THREAD

**Issue by PabloZaiden** [octokit/octokit.js#513]
The following code is supposed to return the current user object:

```javascript
github.users.get()
            .then((userData) => {
                // do something
            })
            .catch((err) => {
                // process the error
            });
```

But it always invokes the catch with the following error:
`'TypeError: Cannot read property 'body' of undefined' at node_modules/github/lib/index.js:621:50`

Currently using version `9.0.0`, but the same happened with the previous version

**Comment by kaizensoze** [comment]
Have you tried running this example? https://github.com/mikedeboer/node-github/blob/master/examples/getUser.js

I think you need to include an empty params dict.

**Comment by PabloZaiden** [comment]
If that's the case, the typings info (i'm consuming it from typescript) is wrong. 

The method signature for that operation is:

```typescript
get(callback?: Github.Callback): Promise<any>;
```

**Comment by kaizensoze** [comment]
To be honest, I don't really know typescript too well. Most of it has been contributions so a pull request for a fix is definitely welcome.

**Comment by PabloZaiden** [comment]
Great! Will do that in a few minutes
