### ISSUE TITLE
How to Fetch data from webAPi using nodeJS libraries?

### ISSUE THREAD

**Issue by LijinDurairaj** [octokit/octokit.js#515]
i have explained my issue in [stackoverflow](http://stackoverflow.com/questions/42581564/how-to-fetch-data-from-webapi-using-nodejs-libraries). please leave a comment which will help me to resolve the issue.... thanks

**Comment by kaizensoze** [comment]
There are a bunch of examples here, which should get you going: https://github.com/mikedeboer/node-github/tree/master/examples
