### ISSUE TITLE
XMLHttpRequest support

### ISSUE THREAD

**Issue by Mr-Wallet** [octokit/octokit.js#518]
Is there any interest in adding support to connect via XHR? The main advantage is that it automatically uses system settings for proxies, Instead of having to set everything manually. 

Back when this repo wasn't being maintained (a year ago), My team [branched off](https://www.npmjs.com/package/github-xhr) to merge pending PRs and to add XHR support. Now that this repo is alive again we would be eager to abandon our fork if XHR support made it into this project.

**Comment by kaizensoze** [comment]
Sure, a pull request is welcome.

**Comment by ramonsnir** [comment]
@Mr-Wallet has this been done yet?

**Comment by Mr-Wallet** [comment]
This problem isn't isolated to `node-githib` - API packages in general don't have XHR support. As a result we've forked a number of packages just to shoehorn it in. To minimize how many independent forks we maintain we've been looking at the possibility of dropping our XHR dependency instead of making a PR for this issue, but exploring that option has been on hold for now in favor of other priorities for our project. (Basically, we'd have to start handling proxy options manually, but we've had to mostly do that anyway for unrelated reasons so we might be most of the way there.)

We didn't think anyone wanted XHR support except for us, but If you also have a need for it then I could try to find time to investigate exactly what a PR would entail, since we're about a year behind on our fork. Let me know.

**Comment by kaizensoze** [comment]
Given the lack of +1's on this I think we'll just leave it out for now.

**Comment by Mr-Wallet** [comment]
We're really interested in doing this now because we need to modernize our API client - are you still open to one, despite the lack of enthusiasm? We'd rather not have to maintain our own fork if we can help it.

**Comment by gr2m** [comment]
We are using `fetch` now internally. But we plan to provide a hook API with the next release in which you can replace the request logic with your own, stay tuned :)
