### ISSUE TITLE
Self-signed certificate error

### ISSUE THREAD

**Issue by shanalikhan** [octokit/octokit.js#522]
I am using your library in my Visual Studio Code extension.

Its working for most of the users though but some users are reporting errors like as
> Error: self signed certificate in certificate chain - \node_modules\github\lib\index.js:849:29

Im attaching their log.

[image 1](https://cloud.githubusercontent.com/assets/770373/23912371/c2cb0ff2-08b5-11e7-8b9d-68f83b11a1a8.png)

[image 2](https://cloud.githubusercontent.com/assets/770373/23912382/cb0e7906-08b5-11e7-9302-dcc8edb40442.png)

Why does this this exception comes from github API ? do you know any idea or any direction to which you can point me :)

**Comment by jeffwilcox** [comment]
Sounds like a proxy at play, or maybe they are using Charles or Fiddler or another interceptor locally. You would need to turn off certificate validation for HTTP requests.

**Comment by shanalikhan** [comment]
> You would need to turn off certificate validation for HTTP requests.

so is there any flag in your library i have to check in order to disable the certificate validation for HTTP request ?

**Comment by shanalikhan** [comment]
If i use protocol as http instead of https, will that work ?
```
var github = new GitHubApi({
    // optional
    debug: true,
    protocol: "http",
    host: "github.my-GHE-enabled-company.com", // should be api.github.com for GitHub
    pathPrefix: "/api/v3", // for some GHEs; none for GitHub
    headers: {
        "user-agent": "My-Cool-GitHub-App" // GitHub is happy with a unique user agent
    },
    Promise: require('bluebird'),
    followRedirects: false, // default: true; there's currently an issue with non-get redirects, so allow ability to disable follow-redirects
    timeout: 5000
});
```

**Comment by johncade** [comment]
Why was this closed? I am interested in being able to use this module, but I cannot make https calls to our Enterprise GitHub instance. Instead we use SSH.

**Comment by gr2m** [comment]
@johncade can you please create a new issue based on the latest version of `@octokit/rest`?

**Comment by corydorning** [comment]
I'm getting the above issue using the latest version of @octokit/rest

**Comment by gr2m** [comment]
please make follow up issues with a code example that reproduce the error, ideally with a test 🙏
