### ISSUE TITLE
Please change github description

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#523]
Please change the link to https://mikedeboer.github.io/node-github/ ,gh-pages does not support http links

**Comment by kaizensoze** [comment]
I don't have the ability to change the description since I'm not the owner of the repo (although a maintainer), but where are you seeing an issue resolving the url as simply http? @mikedeboer Would you be able to do this?

**Comment by kaizensoze** [comment]
Correct me if I'm wrong, but it should just redirect to the https url.
