### ISSUE TITLE
repos.getReadme() failed with "problem with request: unable to verify the first certificate"

### ISSUE THREAD

**Issue by logmonster** [octokit/octokit.js#525]
not sure if it is related to 2-phase authentication setup for my github account; in actual any operation to access github would fail with "problem with request: unable to verify the first certificate"

example code: (copy from https://github.com/mikedeboer/node-github/blob/master/examples/getContent.js)

```js
github.repos.getContent({
    owner: "mikedeboer",
    repo: "node-github",
    path: ""
}, function(err, res) {
    console.log(err, res);
});
```

**Comment by jeffwilcox** [comment]
That sounds like a proxy/other issue. Try using the `request` npm to hit something at GitHub or api.github.com via `https` and see if that is the same error.

**Comment by moem9625** [comment]
rejectUnauthorized: false

**Comment by kaizensoze** [comment]
Try playing around with some more of the config variables: https://github.com/mikedeboer/node-github#example

**Comment by gr2m** [comment]
I was not able to reproduce the issue with the latest version. Please let me know if you still can
