### ISSUE TITLE
How to use the promises

### ISSUE THREAD

**Issue by rohmanhm** [octokit/octokit.js#527]
Hi, I'm new using `node-github`.
Currently are you support return promises or just support the callback?

If you support return promises, how I can implement that? I find in your docs but I cannot see where is it.

**Comment by williamkapke** [comment]
Hey @rohmanhm, it does both. If a callback is not used, it returns a Promise. I used Promises for the Node.js OrgBot. You can check out one of the scrips for examples.... like this:
https://github.com/williamkapke/orgbot/blob/master/scripts/manage-members.js#L107

**Comment by rohmanhm** [comment]
Thanks @williamkapke , you help a lot
