### ISSUE TITLE
[help/question] Assigning a project to an issue (create or update)

### ISSUE THREAD

**Issue by 26medias** [octokit/octokit.js#528]
Hi,

I can create/update an issue using this package.

However, I can't find how to assign a project to an issue, like here:
![](https://i.imgur.com/dprnB5H.png)

I looked in your doc & github's doc, no solution found so far.

Any idea? I don't mind implementing myself if it's possible but not supported yet.

Thanks.

**Comment by jeffwilcox** [comment]
Interesting, I don't know the answer to this, either... maybe it's not documented yet by GitHub.

**Comment by ghost** [comment]
@26medias all the columns in a project seem to have identifiers that are unique across Github; if you use [createProjectCard](http://mikedeboer.github.io/node-github/#api-projects-createProjectCard) with the appropriate `content_type` and `content_id` that should assign your issue to the project.  However, I'm failing doing just that as described in #531.  

I also see no way to get your issue into the "awaiting triage" mode...

**Comment by gr2m** [comment]
Hey there, if you are still interested in this, the https://platform.github.community/ forum would be a good place to ask about it :)
