### ISSUE TITLE
miss leading  addLabels and addAssigneesToIssue examples

### ISSUE THREAD

**Issue by Gormartsen** [octokit/octokit.js#529]
Hi 

I noticed miss leading code examples and missing documentation when I was using:
- github.issues.addLabels
- github.issues.addAssigneesToIssue

Here details are:

https://github.com/mikedeboer/node-github/blob/014075062ff7b8b3ecac8e4b93a07e7bafa15444/test/issuesTest.js#L50

```js
        client.issues.addLabels(
            {
                owner: "String",
                repo: "String",
                number: "Number",
                labels: "Array"
            },
```

Correct one:

```js
        client.issues.addLabels(
            {
                owner: "String",
                repo: "String",
                number: "Number",
                body: "Array"
            },
```

While `github.issues.addLabels` requires body to set labels, `github.issues.addAssigneesToIssue` requires assignees. 

It is not intuitive. I was using `labels` for client.issues.addLabels and got error. (I started with labels due to test example popup to me faster that example code)

I replaced `labels` with `body` - all good.

Then I had to use  `addAssigneesToIssue`  and due to expectations (and copy paste ) I got error with `body` that I had to replace with `assignees`.

I understand that changing API is something that hard to do.

Fixing mentioned code in test file should help.
Also test and example code for addAssigneesToIssue should help new comers as well.

I hope to be helpful

**Comment by kaizensoze** [comment]
Resolved by ae1c18439739d025607e41ef4b8fe38a6c55fcb8 and e4d3090be90687e255ac032e0482dfc3c3f41e5b.
