### ISSUE TITLE
[document] Missing description about createReview's parameter "comments"

### ISSUE THREAD

**Issue by hokein** [octokit/octokit.js#530]
The `comments` is lacking of descriptions in [`createReview`](http://mikedeboer.github.io/node-github/#api-pullRequests-createReview) API.

It'd be nicer and clearer to add the document about the `comments`. GitHub gives a document about it officially: https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review.

**Comment by kaizensoze** [comment]
Should be fixed now.
