### ISSUE TITLE
createProjectCard: should content_id be number, not string?

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#531]
Your doc: http://mikedeboer.github.io/node-github/#api-projects-createProjectCard
Github doc:  https://developer.github.com/v3/projects/cards/#create-a-project-card

When I attempt to create a project card with v9.2, I get an error like this:
````
 "Could not resolve to a node with the global id of 'MDExOlB1bGxSZXF1ZXN0Nw=='"
````
I am definitely passing in an issue id, in a fragment like this:
````
              let cardInfo = { 
                column_id: BACKLOG_COLUMN,
                content_id: request.payload.issue.id,
                content_type: 'issue'
              }
````
Wondering if the "string" type I see here in [`index.d.ts`](https://github.com/mikedeboer/node-github/blob/master/lib/index.d.ts#L1209) is the issue?

**Comment by Artemmkin** [comment]
hey, I'm having the same problem.
The `content id` should definitely be an integer according to the [docs](https://developer.github.com/v3/projects/cards/#create-a-project-card)

**Comment by gscott** [comment]
@kaizensoze you moved on?  not whining, just wondering if you're actively maintaining.  Totally get it if you're not.

**Comment by alex-page** [comment]
@zeke @gr2m are issues like this not meant to be in this project? Should these problems be addressed in the community, happy to open a discussion there if it is the case. Maybe there should be some documentation when creating a new issue on in the README.md

I am having the same problem and it seems like a bug that would be relevant to this project 😕

**Comment by gr2m** [comment]
The issue was closed because it was fixed in 07fa82f back in April 2017, see the timeline event above

![image](https://user-images.githubusercontent.com/39992/56097008-c1771d80-5ea3-11e9-917e-15fae278c14c.png)

Bug reports such as this are always welcome. 

The `content_id` parameter has type `number`, make sure you use the latest version of @octokit/rest. If you still think there is an issue, please open a new issue

**Comment by alex-page** [comment]
My bad @gr2m! I read the issue backwards and didn't notice the commit.

From my understanding the ID is meant to be a string. The ID you get from the columns and issues is a string like @gscott mentions above `"MDExOlB1bGxSZXF1ZXN0Nw=="`. Using these id's in a mutation function with graphql works but using the create card function here does not 😢 
```
`mutation {
  addProjectCard( input: { contentId: "${ pullrequest.node_id }", projectColumnId: "${ column.id }" }) {
    clientMutationId
  }
}`
```

I feel like the documentation is maybe wrong for the GitHub api. I have tried using `database_id` and that also does not work.

I am happy to create a new issue if this sounds correct, but I might be wrong.

**Comment by gr2m** [comment]
The methods and types for `@octokit/rest` are automatically generated based on what is documented on https://developer.github.com/v3. In this case, the documentation for [Create a project card](https://developer.github.com/v3/projects/cards/#create-a-project-card) says that `content_id` is a number, you set it to the (database) id of the issue or pull request that you want the project card to be associated with. You also have to set `content_type` accordingly.

Note that this is all related to the REST API only, not the GraphQL API. In GraphqlQL, the `contentId` parameter for the `addProjectCard` mutation is indeed a string. It’s the node ID which is a base64 encoded string of content type + database id. For example

```js
query { 
  resource(url:"https://github.com/octokit/rest.js/issues/531") {
    ... on Issue {
      id
	}
  }
}
```

returns `MDU6SXNzdWUyMjI5Njk2MTM=` as id, which is the encoded string of `05:Issue222969613`. Not exactly sure what the `05:` prefix is, but both information are included in the string, hence there is no second `contentType` parameter in GraphQL

**Comment by alex-page** [comment]
@gr2m thank you so much 👍 

I had no idea about any of that and it all now makes sense.
