### ISSUE TITLE
Why can't  I "submit a pull request to one repo that requests a merge to a base of another repo"?

### ISSUE THREAD

**Issue by meygerjos** [octokit/octokit.js#532]
This is explicitly disallowed in [the documentation](https://mikedeboer.github.io/node-github/#api-pullRequests).  Why? ([Here is why I want to do this.](https://github.com/eduardoboucas/staticman/issues/98))

**Comment by STRML** [comment]
This would be a useful feature, but it seems the GitHub API itself disallows this, or at least it says it does:

https://developer.github.com/v3/pulls/#create-a-pull-request

EDIT: I actually think we're misinterpreting this. You definitely can request a pull from another repo, you can't just span two separate repos:

```json
{
  "title": "Amazing new feature",
  "body": "Please pull this in!",
  "head": "octocat:new-feature",
  "base": "master"
}
```

is legal, as per the docs, but the `base` must correlate with the `:repo` in `/repos/:owner/:repo/pulls`.

**Comment by meygerjos** [comment]
Oh, I am misinterpreting this.  Thanks!
