### ISSUE TITLE
Wrong declaration files

### ISSUE THREAD

**Issue by mrmlnc** [octokit/octokit.js#534]
In your code i see:

```js
var port = this.config.port || (protocol == "https" ? 443 : 80);
```

https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L638

But I don't see the `port` option in the `d.ts` or `flow` files. This is a mistake or feature?

**Comment by kaizensoze** [comment]
resolved by 971b68ace5e8ca45cf5197661c7e700213638d9c
