### ISSUE TITLE
Proxy param not supported in options interface

### ISSUE THREAD

**Issue by a1626** [octokit/octokit.js#539]
In [index.js](https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L660) proxy is first looked in `config` object

     if (this.config.proxy !== undefined)

but `options` [interface](https://github.com/mikedeboer/node-github/blob/master/lib/index.d.ts#L19-L28) does not support `proxy` param, which makes `process.env` as the only option to set proxy in `client`.

**Comment by kaizensoze** [comment]
This should be taken care of by 971b68ace5e8ca45cf5197661c7e700213638d9c.
