### ISSUE TITLE
Cookies must be enabled to use GitHub

### ISSUE THREAD

**Issue by serginator** [octokit/octokit.js#544]
Hi,
I've been using `node-github` for some years now, and it worked nice in a github enterprise in my company. Now we have moved to github, so I removed the `pathPrefix: '/api/v3',` and added `protocol: 'https'` to the initialization:
```javascript
var github = new Github({
  debug: false,
  protocol: 'https',
  rejectUnauthorized: false,
  host: 'github.com',
  headers: {
    'user-agent': 'crowdin-project'
  }
}),
```
Then authenticate:
```javascript
github.authenticate({
  token: githubOptions.token,
  type: 'token'
}, function(e) {
  grunt.log.writeln('auth error: ' + e); // this does not throws an error so I think it authenticates
});
```
The problem is that when I'm trying to open a pull request with
```javascript
github.pullRequests.create({
  user: 'user',
  repo: 'repository',
  title: 'title here',
  body: 'message here',
  base: 'master',
  head: 'newBranch'
}, function(err) {
  if (err) {
    grunt.log.writeln('pr error: ' + err);
  }
});
```
I receive the following error: `pr error: Cookies must be enabled to use GitHub`.

Do I need to add something to enable cookies? Because looking at the API I don't see anything. Maybe something changed in github's api?

Thanks

**Comment by serginator** [comment]
I've found that I had to use `host: 'api.github.com',`. Sorry

**Comment by rammamia** [comment]
when i upload files, it will go to error page, then say "Cookies must be enabled to use GitHub."
Why?
