### ISSUE TITLE
How to run the tests

### ISSUE THREAD

**Issue by zeke** [octokit/octokit.js#549]
I'm trying to run the test suite locally, but I'm missing the `testAuth.json` file.

What should this file look like?

Once I get it working, I'd be happy to update `CONTRIBUTING.md` with setup details for those who come after.

```
❯ npm i && npm t

> github@9.2.0 test /Users/z/git/forks/node-github
> mocha

(node:63796) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
module.js:472
    throw err;
    ^

Error: Cannot find module './../testAuth.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/z/git/forks/node-github/test/activityTest.js:14:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/z/git/forks/node-github/node_modules/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/z/git/forks/node-github/node_modules/mocha/lib/mocha.js:149:14)
    at Mocha.run (/Users/z/git/forks/node-github/node_modules/mocha/lib/mocha.js:306:31)
    at Object.<anonymous> (/Users/z/git/forks/node-github/node_modules/mocha/bin/_mocha:348:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! Test failed.  See above for more details.
```

**Comment by ghost** [comment]
He tells you in the README. https://github.com/mikedeboer/node-github/blob/master/README.md#create-test-auth-file

**Comment by zeke** [comment]
Thanks, @gscott. I've changed the title of this issue to reflect the larger goal: getting the tests passing in a development environment.

So far..

- [x] Create a GitHub personal access token
- [x] Create `testAuth.json`
- [ ] ???

@kaizensoze when I run `npm test` I'm seeing the following message from nearly every test:

```
  28) [activity] should successfully execute PUT /repos/:owner/:repo/subscription (setRepoSubscription):
     Uncaught AssertionError: { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
  message: '{"message":"Not Found","doc == null
      at /Users/z/git/octokit/node-github/test/activityTest.js:456:24
```

Is there something else I need to set up first? Is it necessary to [create an application authorization](https://github.com/mikedeboer/node-github#creating-a-token-for-your-application) rather than a personal access token?

**Comment by zeke** [comment]
It looks like the tests are specifying the type of each parameter (like `String` for `owner`):

```js
client.repos.addCollaborator(
    {
        owner: "String",
        repo: "String",
        username: "String",
        permission: "String"
    },
    function(err, res) {
        Assert.equal(err, null);
        // other assertions go here
        next();
    }
);
```

When I add `{debug: true}` to the client, I can see that it's actually injecting those (invalid) values into the request URL:

```
❯ mocha test/reposTest.js
(node:17439) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.

  [error] { [Error: Invalid value for parameter 'permission': String]
[error]   defaultMessage: 'Bad Request',
[error]   message: 'Invalid value for parameter \'permission\': String',
[error]   code: '400',
[error]   status: 'Bad Request',
[error]   headers: undefined } { url: '/repos/:owner/:repo/collaborators/:username',
[error]   method: 'PUT',
[error]   params: 
[error]    { permission: 
[error]       { type: 'String',
[error]         required: false,
[error]         validation: '^(pull|push|admin)$',
[error]         invalidmsg: '',
[error]         description: '`pull` - can pull, but not push to or administer this repository, `push` - can pull and push, but not administer this repository, `admin` - can pull, push and administer this repository.',
```

**Comment by zeke** [comment]
cc @mikedeboer any tips on getting these tests running?

**Comment by piascikj** [comment]
I'm having the same issue.  Validation is failing.

**Comment by piascikj** [comment]
@kaizensoze Any ideas?  I must be doing something wrong, but I can 't see what it is.  I've created testAuth.json with a valid token and I'm running `node lib/generate.js` before running `npm test`.

**Comment by bkeepers** [comment]
I spent some time digging into this today. From what I can tell, the hand-coded tests were all replaced with generated stubs in https://github.com/kaizensoze/node-github/pull/20. I don't see anything since then that suggests the generated tests were ever passing. 

cc @gr2m

**Comment by kaizensoze** [comment]
Yeah, those generated stubs need to be re-customized on a per-endpoint basis using nock unless there's something better.

**Comment by gr2m** [comment]
@zeke and I started adding a first test via https://github.com/octokit/node-github/pull/5. I’m not sure what the current state of merging the fork with the main project is
