### ISSUE TITLE
Unable to pass Client ID/Secret for increased Unauthenticated Rate Limit

### ISSUE THREAD

**Issue by jamesrenaud** [octokit/octokit.js#551]
As per https://developer.github.com/v3/#rate-limiting I should be able to pass a client secret and client ID as part of my request to increase my rate limit for unauthenticated calls (in my case I'm doing a repos.getStatsContributors() call).

Is it possible to include this in the call and I'm missing it?

**Comment by jeffwilcox** [comment]
Take a look at the `authenticate` method here: https://github.com/mikedeboer/node-github#authentication

**Comment by jamesrenaud** [comment]
Yep, misunderstood the appropriate use of the authenticate stuff, thanks for the pointer.
