### ISSUE TITLE
Updating issue state - unable to open closed issues

### ISSUE THREAD

**Issue by brianamarie** [octokit/octokit.js#552]
We're trying to use a bot to reopen issues if they've been closed by someone other than the person that opened it. We're running into problems using `state: 'open'` in a way that isn't adding up.

For example, this code works:
```js
module.exports = robot => {
    robot.on('issues', async (event, context) => {
        const issue = event.payload.issue;
        const action = event.payload.action;

        if (action === 'reopened') {
            return context.github.issues.edit(context.issue({state: 'closed'}));
        }
    });
};
```

BUT this code does _not_ work:
```js
module.exports = robot => {
    robot.on('issues', async (event, context) => {
        const issue = event.payload.issue;
        const action = event.payload.action;

        if (action === 'closed') {
            return context.github.issues.edit(context.issue({state: 'open'}));
        }
    });
};
```

Are we doing something wrong?

cc @crichID @jasonetco @hectorsector

**Comment by kaizensoze** [comment]
@brianamarie Any luck with the latest version?

**Comment by brianamarie** [comment]
@kaizensoze Thanks for the ping - @hectorsector Would you be interested in trying this out again tomorrow with me?

**Comment by kaizensoze** [comment]
It looks like a permissions issue. I added a working [example](https://github.com/mikedeboer/node-github/blob/master/examples/reopenClosedIssue.js) that reopens a closed issue. Have you double checked the permissions of the bot? Reopening an issue vs closing requires different permissions: https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by brianamarie** [comment]
@kaizensoze Thank you so much. Admittedly I didn't get around to testing like I hoped I would. I am comfortable closing this issue, and if we run into problems I will circle back. Thank you again! 🎉  😊

**Comment by hectorsector** [comment]
👋 just wanted to confirm that this is indeed working now
