### ISSUE TITLE
removeOutsideCollaborator Wrong URL

### ISSUE THREAD

**Issue by LukeJosten** [octokit/octokit.js#558]
http://mikedeboer.github.io/node-github/#api-orgs-removeOutsideCollaborator
The current path on node-github's side is this: /orgs/:org/outside_collaborator/:username
https://developer.github.com/v3/orgs/outside_collaborators/
But the official path on GitHub's documentation is this: /orgs/:org/outside_collaborators/:username

collaborators instead of collaborator
I'm getting the message 'Not Found' when calling removeOutsideCollaborator as a result.

Thanks!

**Comment by NickLiffen** [comment]
I am seeing the same error message 👍  💯

**Comment by kaizensoze** [comment]
Resolved by 7cbd06aeaffdd7eb464e4fb87a0a7dadbb7da69f.
