### ISSUE TITLE
Create an IFTTT applet for GitHub API changelog

### ISSUE THREAD

**Issue by patcon** [octokit/octokit.js#559]
Related: https://github.com/mikedeboer/node-github/pull/556

@bkeepers and @hiimbex found a subtle change to the API that wasn't reflected in `node-github`. Given how tough it is to stay on top of all changes, I thought I'd suggest that core devs create an IFTTT applet to "Review changelog update to GitHub API" which can link to the new changelog item :)

(This assumes that all changes will be in the changelog, which is hopefully the case!)

Anyhow, I'll leave it to you to set up if you think it work it!

https://ifttt.com/applets/379423p-if-rss-then-github-issue
https://developer.github.com/changes.atom

**Comment by kaizensoze** [comment]
Yeah right now I'm subscribed to the github changes blog rss feed. Not sure how I feel about issues being automatically created.

**Comment by patcon** [comment]
Totally. I get if you have it covered and would rather not, but the thought is that it might help reduce invisibilized labour and effort. This feels important for collaborative open source efforts :)

And please feel free to close if it's not actionable!

**Comment by kaizensoze** [comment]
No it's definitely a good idea to help let all contributors know what's changed recently without assuming they're all personally monitoring the latest github api changes over at https://developer.github.com/changes/. Some of the changes don't necessarily require any dev changes and are simply notices so I'd rather not have it automatically create issues that don't need to be there, but that's just me. If anyone feels better safe than sorry, feel free to link the changes blog rss to the repo issues.

**Comment by gr2m** [comment]
I’ve created a separate project which compares responses from the GitHub API using pre-defined scenarios on a daily basis using Travis Cron Jobs:
https://github.com/gr2m/octokit-fixtures

The idea is to use these fixtures for tests of node-github, which we started doing in the @octokit fork: https://github.com/octokit/node-github/pull/8

I'll create scenarios for all the [node-github/examples](https://github.com/mikedeboer/node-github/tree/master/examples) so we should have a pretty good coverage. Any help much appreciated 👍
