### ISSUE TITLE
npm not able to install ossuibuilder

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.js#565]
[INFO] --- exec-maven-plugin:1.4.0:exec (exec-npm-install) @ utilities ---
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ossui-builder
npm ERR! 404
npm ERR! 404  'ossui-builder' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'utilities'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (exec-npm-install) on project utilities: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

Please suggest as how can I solve this?
Using 32 bit-- 6.11.2

**Comment by kaizensoze** [comment]
This is unrelated to the node-github package.
