### ISSUE TITLE
How do I set the content-type when uploading an asset using uploadAsset?

### ISSUE THREAD

**Issue by retorquere** [octokit/octokit.js#566]
When uploading an asset, I'm supposed to set the content-type (as per https://developer.github.com/v3/repos/releases/#upload-a-release-asset), but I don't see how to set it at http://mikedeboer.github.io/node-github/#api-repos-uploadAsset

**Comment by kaizensoze** [comment]
You can specify it in a headers object for the request like so:

```
github.repos.uploadAsset({
    owner: "...",
    repo: "...",
    id: "...",
    headers: {
        "content-type": "..."
    },
}, function(err, res) {
    console.log(res);
});
```
