### ISSUE TITLE
How do I upload an asset when I have the body in string form?

### ISSUE THREAD

**Issue by retorquere** [octokit/octokit.js#567]
I tried 

```
yield github.repos.uploadAsset({
    id: release.data.id,
    name: json,
    body: JSON.stringify(form),
    headers: { 'content-type': 'application/json' },
    owner: 'retorquere', repo: 'zotero-better-bibtex'
  })
```
but I'm getting

```
Empty value for parameter 'filePath': undefined
```

**Comment by hiimbex** [comment]
According to the [GitHub API Docs](https://developer.github.com/v3/repos/releases/#upload-a-release-asset):
> The asset data is expected in its raw binary form, rather than JSON.

So I don't think it's possible to upload it as JSON :/ but it's probably not to hard to throw your data into something that will work with `filePath`

**Comment by retorquere** [comment]
In this case JSON *is* the raw binary form; I'm uploading a JSON document. I understand I can put it in a temp file and have it picked up using `filePath`, it just seems a bit of a waste to send something to disk only so it can be read from there right after. But I've gone with a minimal wrapper around http-promise and everything's good. The Github API is pretty simple.

**Comment by kaizensoze** [comment]
The data needs to be in a file with a filePath to provide: See this [example](https://github.com/mikedeboer/node-github/blob/master/examples/enterpriseUploadAsset.js).

**Comment by retorquere** [comment]
I do understand the current API requires this; I should have phrased my request as "can this be added"? In my current workflow:

1. I figure out the body
2. write it to a temp file
3. give node-github the path to the temp file
4. node-github reads the file contents (right?)
5. ....
6. profit

Steps 2-4 are superfluous when I could just give node-github the file contents which I have in-mem anyhow.

**Comment by gr2m** [comment]
@retorquere with the new API, you can set the `file` option to a string, see all options at https://octokit.github.io/node-github/#api-repos-uploadAsset

Does that work for you?

**Comment by retorquere** [comment]
Awesome.
