### ISSUE TITLE
Issue Locking passes in content-length: 2, expected 0

### ISSUE THREAD

**Issue by hiimbex** [octokit/octokit.js#570]
My code: `github.issues.lock(repo, owner, number);`

Output with verbose logging:
```js
DEBUG:  (number=26, owner=hiimbex, repo=testing-things)
REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/repos/hiimbex/testing-things/issues/26/lock',
  method: 'put',
  headers: 
   { host: 'api.github.com',
     'content-length': 2,
     'content-type': 'application/json; charset=utf-8',
     Authorization: 'token $TOKEN',
     'user-agent': 'NodeJS HTTP Client',
     accept: 'application/vnd.github.v3+json' },
  ca: undefined }
REQUEST BODY: {}
```

The [GitHub API Issue Locking Docs](https://developer.github.com/v3/issues/#lock-an-issue) specify `content-length` must be set to 0. I tried adding that as a header within my query to no avail, so I think somewhere it's getting replaced by this client, but I can't seem to figure out where. If anyone can point me in the right direction about where that might be happening, I'd be happy to crank out a fix.

**Comment by kaizensoze** [comment]
Do you have some example code I can play around with to see where the content-length header might be getting modified in index.js?

**Comment by hiimbex** [comment]
Yes, I'm starting to think this issue might be more related to apps than anything else. I am getting my instance of github through [github-app](https://github.com/probot/github-app), which allows me to authenticate as an integration. I'm using [probot](https://github.com/probot/probot) as a platform for github apps.

The code is:
```js
module.exports = robot => {
  robot.on('issue_comment.created', async context => {
  //context.github is the client authenticated through github-app
    context.github.issues.lock({
      repo: 'testing-things',
      owner: 'hiimbex',
      number: 26
    });
  });
}
```
I wrote a short script and was able to test that with my personal access token, I could successfully lock an issue. It's possible something in the stack is going wrong on the github-app or probot side of things as well. 

cc/ @bkeepers

**Comment by bkeepers** [comment]
> ```
> REQUEST BODY: {}
> ```

It looks like the request body is getting set to an empty JSON object (`{}`), which is why the content length is 2.

**Comment by hiimbex** [comment]
> It looks like the request body is getting set to an empty JSON object ({}), which is why the content length is 2.

Yep, I just can't seem to figure out where that is happening, or how to prevent it.

**Comment by gr2m** [comment]
I have a test case that reproduces the problem now:
https://travis-ci.org/octokit/node-github/jobs/277000057#L520

One problem is that `node-github` always considers `put` requests to include a body, via 

https://github.com/mikedeboer/node-github/blob/f06dd9fc310c0f8e6893793ed8ce6335f7cde2a6/lib/index.js#L641

The default to `{}` happens in this line

https://github.com/mikedeboer/node-github/blob/f06dd9fc310c0f8e6893793ed8ce6335f7cde2a6/lib/index.js#L565

I’m looking into it

**Comment by gr2m** [comment]
Can you please test if [my PR](https://github.com/octokit/node-github/pull/11) fixes it? You can install that version with

```
npm install --save octokit/node-github
```

Here is the patch commit https://github.com/octokit/node-github/pull/11/commits/589b39e0403b027b521ac5f2c3e3b94d20e3093f

**Comment by hiimbex** [comment]
Hmm this was the response I got which still has `content-length` set to 2:
```
09:52:19.995Z DEBUG Probot: test { number: 39, owner: 'hiimbex', repo: 'testing-things' }
REQUEST:  { host: 'api.github.com',
  port: 443,
  path: '/repos/hiimbex/testing-things/issues/39/lock',
  method: 'put',
  headers: 
   { host: 'api.github.com',
     'content-length': 2,
     'content-type': 'application/json; charset=utf-8',
     Authorization: 'token xxx',
     'user-agent': 'NodeJS HTTP Client',
     accept: 'application/vnd.github.v3+json' },
  ca: undefined,
  family: undefined }
REQUEST BODY: {}

STATUS: 204
HEADERS: {"server":"GitHub.com","date":"Wed, 20 Sep 2017 09:52:20 GMT","content-type":"application/octet-stream","connection":"close","status":"204 No Content","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4998","x-ratelimit-reset":"1505904695","x-github-media-type":"github.v3; format=json","access-control-expose-headers":"ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-runtime-rack":"0.087491","x-github-request-id":"F638:850B:E8C6A98:1D5782A9:59C23A54"}
```

the dependency is declared as: `"github": "github:octokit/node-github#collaborators-test"`

**Comment by gr2m** [comment]
@hiimbex can you please test it with my gist:

https://gist.github.com/gr2m/48ad793b3fb7dbb59bcd696bbf75baee

**Comment by hiimbex** [comment]
the gist works fine, so the problem is likely something with probot or our github-app creation, or potentially github app permissions, as there are still issues when using it through a github app.
