### ISSUE TITLE
Best way to transition from JSON.parse(fs.readFileSync(routesPath, "utf8")); to require

### ISSUE THREAD

**Issue by kaizensoze** [octokit/octokit.js#575]
Due to caching and whatnot, it's not as simple as replacing with require. What's the best option for switching to require to make it more friendly with webpack?

Related: https://github.com/mikedeboer/node-github/issues/573

**Comment by cfeckardt** [comment]
I think the best way would be to not mutate the routes with a delete in the first place (see #573), instead make a copy but omit and delete on that new object.

**Comment by gr2m** [comment]
I’ll have a look into this :)

**Comment by gr2m** [comment]
this is done now, I’ve split up routes and definitions into two JSON files. Please let me know if you have any further questions
