### ISSUE TITLE
[QUESTION] Get total number of commits for a repo (on a branch)

### ISSUE THREAD

**Issue by WandersonAlves** [octokit/octokit.js#578]
Hi guys!
I wanna get the total number of commits for a repo (like when i click on a repo and see `956 commits` per exemple). 
There's some trick to do that? I was playing with `/repos/:owner/:repo/commits` but, no success 

😭

**Comment by WandersonAlves** [comment]
Thanks for u response @kaizensoze, but, paginate all commits just to pick a length value? 😢

**Comment by kaizensoze** [comment]
Yep :(

**Comment by jeffwilcox** [comment]
Hopefully you could just pull into a container or into a temp folder and use a proper Git API or shell out to Git to learn more about the repo from a clone instead of a ton of API calls...

**Comment by kaizensoze** [comment]
Those are some other options. Going to close this though since the github api doesn't provide any easier method.
