### ISSUE TITLE
Preview the new Nested Teams APIs

### ISSUE THREAD

**Issue by kaizensoze** [octokit/octokit.js#579]
https://developer.github.com/changes/2017-08-30-preview-nested-teams/

**Comment by jeffwilcox** [comment]
Will be interested to hear whether the "will include inherited team members" means longer term this is a breaking change, or if the existing API will remain...

Ideally I hope we have a way to ask for either the entire inheritance list of members or repos _OR_ to pass an option for just the "direct" entities in the team...
