### ISSUE TITLE
github.repos.get({owner: 'octokit', repo: 'node-github'}) is sending wrong accept header

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#587]
The request currently sends `Accept: application/vnd.github.drax-preview+json`

```js
const GitHub = require('github')
const nock = require('nock')
nock('https://api.github.com', {
  reqheaders: {
    'accept': 'Accept: application/vnd.github.v3+json'
  }
})
  .get('/repos/octokit/node-github')
  .reply(200, {
    full_name: 'octokit/node-github'
  })

const github = new GitHub()

github.repos.get({owner: 'octokit', repo: 'node-github'}).catch(console.log)
// Nock: No match for request
// {
//   "method": "get",
//   "url": "https://api.github.com/repos/octokit/node-github",
//   "headers": {
//     "host": "api.github.com",
//     "content-length": "0",
//     "user-agent": "NodeJS HTTP Client",
//     "accept": "application/vnd.github.drax-preview+json"
//   }
// }
```

Try it on https://runkit.com/gr2m/59b7290cfadd4e00123218df

The reason is this line:

https://github.com/mikedeboer/node-github/blob/f06dd9fc310c0f8e6893793ed8ce6335f7cde2a6/lib/routes.json#L511

Can you tell why the `"/repos/:owner/:repo"` route is in both the `application/vnd.github.drax-preview+json` and also the `application/vnd.github.scarlet-witch-preview+json` group? Looks like a bug to me?

**Comment by gr2m** [comment]
for reference, here are all accept headers by route as they are implemented today
https://gist.github.com/gr2m/46b593a662638aafeba373132b8fa48c

**Comment by kaizensoze** [comment]
There's an overlap for that endpoint for getting additiional preview-only content in the response when providing either the scarlet witch or drax accept header. Unfortunately it doesn't look like you can include both and it just picks the first accept header. So the endpoint can optionally include info for License preview or Codes of Conduct.

https://developer.github.com/v3/licenses/#get-a-repositorys-license
https://developer.github.com/v3/codes_of_conduct/#get-a-repositorys-code-of-conduct

**Comment by gr2m** [comment]
Okay, so that is a problem with the current implementation, right? Not easy to fix? I’d suggest we leave the issue open until we revise the current generation of APIs

**Comment by ghost** [comment]
```
Can you tell why the "/repos/:owner/:repo" route is in both the application/vnd.github.drax-preview+json and also the application/vnd.github.scarlet-witch-preview+json group? Looks like a bug to me?
```
Youʻre actually right, ivʻe been having this problem to but it is weird that "/repos/:owner/:repo" is both in the application tho.

**Comment by gr2m** [comment]
the preview headers can be combined :) 

You can enforce sending `application/vnd.github.v3+json` by explicitly setting

```js
  headers: {
    accept: 'application/vnd.github.v3+json'
  }
```

We will make the usage of the preview headers explicit in a future version
