### ISSUE TITLE
Error: ENOENT: no such file or directory, open \'//routes.json\''

### ISSUE THREAD

**Issue by azhivaeva-flo** [octokit/octokit.js#588]
When I try to create GitHubApi, I catch this error
`[ 'Error: ENOENT: no such file or directory, open \'//routes.json\'',
  'at Error (native)',
  'at Object.fs.openSync (fs.js:641:18)',
  'at Object.fs.readFileSync (fs.js:509:33)',
  'at new module.exports (/home/azhivaeva-bmt/projects/media-shop-service (copy)/.webpack/api/github/handler.js:1254:33)',
  'at new GitHub (/home/azhivaeva-bmt/projects/media-shop-service (copy)/.webpack/api/github/handler.js:1127:23)',
  'at createIssue (/home/azhivaeva-bmt/projects/media-shop-service (copy)/.webpack/api/github/handler.js:1109:18)',
  'at handler (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/serverless-offline/src/index.js:732:25)',
  'at Object.internals.handler (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/handler.js:96:36)',
  'at request._protect.run (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/handler.js:30:23)',
  'at internals.Protect.run (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/protect.js:64:5)',
  'at exports.execute (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/handler.js:24:22)',
  'at each (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/request.js:384:16)',
  'at iterate (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/items/lib/index.js:36:13)',
  'at done (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/items/lib/index.js:28:25)',
  'at internals.Auth.payload (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/auth.js:223:16)',
  'at each (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/request.js:384:16)',
  'at iterate (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/items/lib/index.js:36:13)',
  'at done (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/items/lib/index.js:28:25)',
  'at onParsed (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/route.js:402:20)',
  'at Subtext.parse (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hapi/lib/route.js:423:20)',
  'at next (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/subtext/lib/index.js:45:26)',
  'at Wreck.read (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/subtext/lib/index.js:242:16)',
  'at finish (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/subtext/node_modules/wreck/lib/index.js:373:20)',
  'at wrapped (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/hoek/lib/index.js:875:20)',
  'at onReaderFinish (/home/azhivaeva-bmt/projects/media-shop-service (copy)/node_modules/subtext/node_modules/wreck/lib/index.js:447:16)',
  'at g (events.js:292:16)',
  'at emitNone (events.js:91:20)',
  'at emit (events.js:185:7)',
  'at finishMaybe (_stream_writable.js:512:14)',
  'at endWritable (_stream_writable.js:522:3)',
  'at Writable.end (_stream_writable.js:487:5)',
  'at IncomingMessage.onend (_stream_readable.js:511:10)',
  'at IncomingMessage.g (events.js:292:16)',
  'at emitNone (events.js:91:20)',
  'at IncomingMessage.emit (events.js:185:7)',
  'at endReadableNT (_stream_readable.js:974:12)',
  'at _combinedTickCallback (internal/process/next_tick.js:80:11)' ]`

In this sting: 
`this.routes = JSON.parse(fs.readFileSync(__dirname + "/routes.json", "utf8"));`

My code:
```js
const GitHubApi = require('github');
export class GitHub {
  private github;
  constructor() {
    this.github = new GitHubApi({
      debug: false,
      Promise: require('bluebird'),
      timeout: 5000,
      host: 'api.github.com',
      protocol: 'https',
      headers: {
        'Accept': 'application/vnd.github.v3+json'
      },
      requestMedia: 'application/vnd.github.v3+json',
      followRedirects: false
    });
```

**Comment by kaizensoze** [comment]
Are you using npm or running locally from source?

Try creating a small project from scratch to test:

```
npm init
npm install -S github
create index.js
node index.js
```

**Comment by jojobyte** [comment]
I'm getting this same problem for an Electron App, but only in the Karma unit test. Its installed via the package.json: `"github": "^9.3.1",`, commenting out the `import GitHubApi from 'github';` and its related code gets rid of the error.

```bash
Electron 1.8.0 (Node 8.2.1) ERROR
  Uncaught Error: ENOENT: no such file or directory, open 'C:\routes.json'
  at fs.js:652

Electron 1.8.0 (Node 8.2.1): Executed 0 of 0 ERROR (0.698 secs / 0 secs)
```

Appears to be working fine when actually running the app.

**Comment by gr2m** [comment]
Can you please try if that patch fixes it for you: https://github.com/mikedeboer/node-github/commit/9c2ee388039f6518edf3f833acbf7d910acf3fcc, it’s in the [remove-fs-readfile](https://github.com/mikedeboer/node-github/tree/remove-fs-readfile) branch

you can set the version for `"github"` in package.json to `"mikedeboer/node-github#remove-fs-readfile"` and run `npm install` to try it out

**Comment by JeroenSormani** [comment]
I'm currently getting the same using Electron. I believe its related to WebPack, when I add a sample code to the index.html directly it works, when its in one of the scripts that gets build it no longer works `__dirname` is just `/`.

Didn't find the solution yet, but I'm just figuring out WebPack so looking further into that.

Dunno if @azhivaeva-bmt  also uses Electron and if its the same. Def. does sound like it with @jojobyte 

@gr2m doing `require('./routes.json')` doesn't resolve it for me, at least not yet, probably due to underlying issues Re the above. (`Uncaught Error: Cannot find module "."`)

**Comment by JeroenSormani** [comment]
Ok so here's what I've found out that works for me / what I found that _didn't_ work for me, but might for someone else who comes here.

This did not do the trick for me, but for many others it did help.
https://github.com/webpack/webpack/issues/1599#issuecomment-186841345

Adding this to my `webpack.config.js` file 
```
const { dependencies } = require('./package.json')
[...]
module.exports = {
...
externals: [
    ...Object.keys(dependencies || {}).filter(d => !['vue'].includes(d))
  ],
...
}
```

Figured this out by grabbing the [Electron-Vue ](https://github.com/SimulatedGREG/electron-vue) sample app and started tearing it apart to remove all that was not needed to see when it would break (as it did work out of the box there)

@gr2m I don't believe there's anything wrong this repo as the initial/current code looked fine (although using a `Path.join()` [here](https://github.com/mikedeboer/node-github/commit/9c2ee388039f6518edf3f833acbf7d910acf3fcc#diff-6d186b954a58d5bb740f73d84fe39073L85) would add for consistency.

**Comment by atrauzzi** [comment]
Has any solution been determined when using this library from within an electron app?

**Comment by gr2m** [comment]
@atrauzzi @JeroenSormani et all, I think this should be resolved now, I’ve removed the us of `fs` in the library. Could you please give it another try?

If it persist, it would help a ton if someone could create a repository for a minimal electron app that uses this library. I can use that as a test case to see how to work around it. Thanks for all your help!
