### ISSUE TITLE
Is GitHub API v4 (GraphQL) supported? Plans?

### ISSUE THREAD

**Issue by alundiak** [octokit/octokit.js#592]
- https://developer.github.com/v4/
- https://developer.github.com/v4/explorer/

I've spotted on this module recently, and before I worked with https://github.com/github-tools/github and also I work on v4 API fo my sandbox project. So would be nice to know if current `node-github` warapper supports v4 POST requests.

**Comment by gr2m** [comment]
there is no support for GraphQL at this point. Let’s so what news [GitHub Universe](https://githubuniverse.com/) and take the discussion from there :) 

There are no specific plans yet, but there is commitment for higher level libraries for all official GitHub APIs moving forward

**Comment by gr2m** [comment]
@alundiak I’ve learned all aspects of GraphQL in the past weeks. We don’t have any decision on how to move forward with GraphQL yet in scope of this library, but I will start looking into creating better tooling for developers that work against GitHub’s GraphQL API.

For a starter, I created https://github.com/gr2m/github-graphql-schema which has a validate method that you can use to validate all your queries as part of your tests. Creating eslint plugins and Editor addons for Atom, VS Code etc could be next. I’m also looking into how we can make it easier to create mocks for your tests.

Let me know if you have any further questions. This is an ongoing discussion within Octokit in general, we value your input on it :)

**Comment by tiev** [comment]
FYI.
Updating pull request review body is not possible in API v3, but supported in v4.
https://stackoverflow.com/questions/48421313/how-to-update-the-comment-text-of-a-github-pull-request-review-using-the-api
I'm struggling with this use case.

**Comment by gr2m** [comment]
@tiev you can send GraphQL requests with [`octokit.request`](https://github.com/octokit/rest.js/tree/master/lib/request). Note that is not considered a public API yet so it might change between major releases, so better to pin the `@octokit/rest` version in your package.json if you do until v16.

```js
const {data} = await octokit.request({
  method: 'POST',
  url: '/graphql',
  query: `mutation UpdateReview {
    updatePullRequestReview(input: {pullRequestReviewId: "${pullRequestReviewId}", body: "some test"}) {
      pullRequestReview {
        updatedAt
      }
    }
  }`
})
```

does that work for you?

**Comment by tiev** [comment]
Thank you 👍

**Comment by gr2m** [comment]
There you go: https://github.com/octokit/graphql.js please let me know how you like it :)
