### ISSUE TITLE
Check authenticated state

### ISSUE THREAD

**Issue by jacquesdev** [octokit/octokit.js#597]
This is more of a question than an issue. I am busy writing some tests for a project that uses this project, and just trying to understand how I can confirm when a github instance has been authenticated.

For example if I use the authenticate method, ie github.authenticate(), does it add any property to the object so that it's obvious that it has now been authenticated?

**Comment by kaizensoze** [comment]
The only thing that authenticate() does is `this.auth = options`. See [here](https://github.com/mikedeboer/node-github/blob/master/lib/index.js#L352-L373). The auth token will then later be used as the Authorization header value. It's only until you make a request that you'll see if you're authorized for that given request.
