### ISSUE TITLE
How do i authenticate with custom oauth scopes

### ISSUE THREAD

**Issue by lukeeey** [octokit/octokit.js#598]
I would previously used this
```js
window.location.href = "https://github.com/login/oauth/authorize?scope=user:email,repo&client_id=<?= Main::$CLIENT_ID ?>";
```

But how would i do it in this library?

**Comment by gr2m** [comment]
does this work for you?

https://github.com/mikedeboer/node-github#creating-a-token-for-your-application

**Comment by lukeeey** [comment]
Would that allow for a system where each user signs in with github then my site creates a profile for them? I only have experience with the `/login/oauth/authorize` endpoint because it doesnt require any credentials sent from my app and it returns a token for me to use.

I used the above method but it says i'm not authorized in console.

**Comment by gr2m** [comment]
if you look for something that is running in the browser only, then node-github is not for you at this point, it only runs in the server I’m afraid

**Comment by lukeeey** [comment]
What? When a user clicks a button i want them to authenticate my app and return an auth token so my app can can create repos on their behalf. I'm asking because `node-github` doesn't contain the endpoint that i'm used to using for this task.

**Comment by gr2m** [comment]
What endpoint is missing? `POST /authorizations` (https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) is implemented as shonw at https://github.com/mikedeboer/node-github#creating-a-token-for-your-application

**Comment by lukeeey** [comment]
`GET https://github.com/login/oauth/authorize`

**Comment by gr2m** [comment]
this is not part of the REST API (v3) that node-github implements. It is a URL that you redirect your app users to, they open this URL in their browser and will see a UI with information about your app and what scopes it requires. 

There is a Non-Webaplication Flow https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/#non-web-application-flow it’s basically what I linked above
