### ISSUE TITLE
Close Issue

### ISSUE THREAD

**Issue by bazjapan** [octokit/octokit.js#60]
Hello, thanks for all the effort put into this library, very helpful indeed.
Could you tell me whether it is possible to close an issue?  I've tried via issue edit, but with no success.

thanks

**Comment by crash83k** [comment]
I have trouble with this too. I've traced it down to 'github/index.js', line 778. It seems that the "PATCH" method isn't supported. So it dies on the vine without any error returned. (Pretty bad of Node, if you ask me.)

**Comment by kaizensoze** [comment]
`github.issues.edit({ ... });` Pass in state: closed

https://mikedeboer.github.io/node-github/#api-issues-edit
