### ISSUE TITLE
Opinions on how a PR diff could be accessed

### ISSUE THREAD

**Issue by orta** [octokit/octokit.js#602]
Hey there, I would like to get a PR's diff though the API. 

This is done via a request to `pulls/[id]/[number]` with an `Accept: vnd.github.v3.diff` header. See the [media type bit here](https://developer.github.com/v3/pulls/#get-a-single-pull-request).

Right now a route can't override headers (nor can I do it on a per-request basis) - any advice on how I can add this?

**Comment by gr2m** [comment]
I don’t have a helpful answer right now I’m afraid, but I run into this myself and plan to make the usage of preview headers more explicit in a future version. Maybe there is a workaround though, please let us know if you find one, you are not the first to ask about it :)

**Comment by bkeepers** [comment]
It's not very well documented, but there is an [example in the readme](https://github.com/octokit/node-github#example) that shows how to do this. In this case, it would be:

```
github.pullRequests.get({
  owner: "octokit",
  repo: "node-github",
  number: 600,
  headers: {accept: "application/vnd.github.v3.diff"}
});
```

**Comment by orta** [comment]
<3 amazing, thanks

**Comment by GMouron** [comment]
Thanks for this, exactly what I was looking for !

**Comment by GMouron** [comment]
Note: the correct header is `application/vnd.github.v3.diff` 😉

**Comment by gr2m** [comment]
Thanks @GMouron, I’ve updated Brandon’s code snippet accordingly
