### ISSUE TITLE
💯 Test coverage

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#621]
Initial Setup is done via https://github.com/octokit/node-github/pull/612.

Current status:
[![Coverage Status](https://coveralls.io/repos/github/octokit/node-github/badge.svg?branch=milestone-v13)](https://coveralls.io/github/octokit/node-github?branch=milestone-v13)

**Comment by Ethan-Arrowood** [comment]
I'd be interested in helping with test coverage if you'd like

**Comment by gr2m** [comment]
sure thing @Ethan-Arrowood! I've started a pull request to run the examples as part of the test suite, see my work-in-progress at https://github.com/octokit/node-github/pull/627. I got until `examples/enterpriseUploadAsset.js`, the other files still need to adapted like the ones I already did, would you like to have a look at that? Happy to pass that over to you and help you out if you run into any blockers? I'll make you a contributor so you can work on the PR directly, just assign yourself to the PR :)

**Comment by Ethan-Arrowood** [comment]
Let me familiarize myself with the whats already existing and see what I can do over the next few days. I'll keep you update 👍

**Comment by gr2m** [comment]
This is done in #629 and will be released in [v13](https://github.com/octokit/node-github/pull/629)
