### ISSUE TITLE
remove built-in netrc support

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#633]
As part of our efforts to make `node-github` work in the browser, we will remove the built-in support for authentication using `netrc` which is currently depending on the [netrc](https://www.npmjs.com/package/netrc) package. 

The workaround is simple enough, just use the netrc file directly and pass username/password to the `.authenticate()` method.

**Comment by gr2m** [comment]
this issue is available if you'd like to contribute, just comment below to claim it. When you send a pull request, please send it against the `milestone-v13` branch instead of master, as it is a breaking change and we want to combine breaking changes to avoid too many breaking version releases

**Comment by copperwall** [comment]
I'll give this a try.

**Comment by gr2m** [comment]
This is done via https://github.com/octokit/node-github/pull/640 and will be released in [v13](https://github.com/octokit/node-github/pull/629)
