### ISSUE TITLE
Multiple commits on same file

### ISSUE THREAD

**Issue by hms15** [octokit/octokit.js#643]
Please provide a minimal code sample to reproduce the issue if possible.
Hi,

I am trying to achieve committing to a file multiple times. Is there a way which I can achieve this as it is done with "git commit -m"? I am using the update file API, however, that requires the SHA. Is there a way to avoid having to input the SHA?

Thanks

**Comment by gr2m** [comment]
> Is there a way to avoid having to input the SHA

I’m afraid not. You can get the first sha in two ways, dependening on wether the file you want to create already exists or not.

### 1. If file does not yet exist

Create a file as shown in https://octokit.github.io/node-github/#api-repos-createFile. 

```js
github.repos.createFile({
  owner: 'octokit',
  repo: 'node-github',
  path: 'A_NEW_FILE.md',
  message: 'creating A_NEW_FILE.md',
  content: Buffer.from('Content here').toString('base64')
})

.then(result => {
  const sha = result.data.commit.sha

  return github.repos.updateFile({
    owner: 'octokit',
    repo: 'node-github',
    path: 'A_NEW_FILE.md',
    message: 'updating A_NEW_FILE.md',
    content: Buffer.from('New content').toString('base64')
    sha: sha
  })
})

.then(result => {
  const sha = result.data.commit.sha

  return github.repos.updateFile({
    // ... etc
  })
})
```

### 2. If file already exist

```js
github.repos.createFile({
  owner: 'octokit',
  repo: 'node-github',
  path: 'README.md'
})

.then(result => {
  const sha = result.data.commit.sha

  return github.repos.updateFile({
    owner: 'octokit',
    repo: 'node-github',
    path: 'README.md',
    message: 'updating README.md',
    content: Buffer.from('New content').toString('base64')
    sha: sha
  })
})

.then(result => {
  const sha = result.data.commit.sha

  return github.repos.updateFile({
    // ... etc
  })
})
```

**Comment by gr2m** [comment]
For the future it would be better if you would ask "How do I ... ?" questions on the new [GitHub Community Forum](https://github.community/t5/How-to-use-Git-and-GitHub/bd-p/Board_1)
or https://stackoverflow.com. That way more people can benefit from your question and the answers that you will receive – and more people will be able to help you out.

GitHub issues are a better fit for bug reports or feature requests.
