### ISSUE TITLE
Node 4+ support and `mime` dependency

### ISSUE THREAD

**Issue by twokul** [octokit/octokit.js#645]
Ran into a peculiar issue whilst updating `ember-cli` to the latest version of the library. 

```
yarn install v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error mime@2.0.3: The engine "node" is incompatible with this module. Expected version ">=6.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It seems like `mime` supports `node@6+` and `node-github` supports `node@4+` hence the error above. It might make sense to align node version support but I don't know what that entails for `node-github` (don't know if you are planning on supporting LTS or not).

thanks! 👋

**Comment by gr2m** [comment]
Thanks for the heads up @twokul! I think `mime` is currently only used for the file upload which we might simply soon.

Note that `node-github` is currently not running in the browser.

**Comment by gr2m** [comment]
Thank you stale bot :)

In fact, we already dropped the mime dependency. @twokul can you give it another try? I can reopen this issue or open a new one if there is still any problem
