### ISSUE TITLE
Add `archived` field to repos.edit()

### ISSUE THREAD

**Issue by JasonEtco** [octokit/octokit.js#647]
Heya folks 👋

Following the [release of Archived Repositories](https://github.com/blog/2460-archiving-repositories), I'd like to suggest adding the appropriate field to the `github.repos.edit()` method. From what I understand based on the [API docs](https://developer.github.com/v3/repos/#edit), this is just a new field that should be passed; I'm not sure if you'll need to do anything from the library side, it might just be adding the field to the documentation.

New field being:

```
archived: boolean
```

**Comment by gr2m** [comment]
Thanks @JasonEtco!

I’d like to create a test first before adding the feature. Let me know if you want to help out, we’ll have to create new fixtures, see https://github.com/octokit/fixtures/blob/master/HOW_IT_WORKS.md#updating-fixtures

**Comment by gr2m** [comment]
that is fixed now via #822 🎉 note that it’s published as pre-release: https://github.com/octokit/rest.js/releases/tag/v15.3.0
