### ISSUE TITLE
Handling Enterprise specific routes for GitHub Apps

### ISSUE THREAD

**Issue by tcbyrd** [octokit/octokit.js#650]
Due to a need to avoid route conflicts with customers that have Organizations in GHE called `/apps`, once Apps ships in Enterprise, the route will be:

`http(s)://[hostname]/github-apps/[app]/`

instead of

`https://github.com/apps/[app]`

I think this means we'll need to add Enterprise specific logic for these routes:

https://github.com/octokit/node-github/blob/072a53f6d8f5e8fe642284c13af93177def6abbe/lib/routes.json#L1079
https://github.com/octokit/node-github/blob/072a53f6d8f5e8fe642284c13af93177def6abbe/lib/routes.json#L1163
https://github.com/octokit/node-github/blob/072a53f6d8f5e8fe642284c13af93177def6abbe/lib/routes.json#L1172

I wasn't sure what the optimal way would be to implement, so I wanted to open this issue first so we can discuss. I'm happy to help test once we have release candidates of GHE with Apps enabled.

**Comment by gr2m** [comment]
perfect, thanks for the heads-up @tcbyrd 👍 

I think we shouldn’t be affected by the App installation routes that you open in the browser, `node-github` is only using the API endpoints for which I don’t think the conflict will apply? E.g. the full route for [`GET /app/installations`](https://developer.github.com/v3/apps/#find-installations) is `https://<host name>/api/v3/app/installations`. The route to an organization called `app` would be `https://<host name>/api/v3/orgs/app`.

Or am I missing something?

**Comment by tcbyrd** [comment]
@gr2m Nope my brain was totally not thinking straight here. You're right. API routes are not changing!
