### ISSUE TITLE
Add callback parameter in API docs

### ISSUE THREAD

**Issue by paolodm** [octokit/octokit.js#681]
![image](https://user-images.githubusercontent.com/21039701/34457857-5f80fdb4-ed8c-11e7-95f3-eca81a53d828.png)

This is what the `repos.getAll()` documentation currently is. It doesn't specify that the last parameter is actually a callback. It would be super helpful if it was specified - I spent 30 minutes assuming it was returning a promise and wondering why it was always returning undefined.

**Comment by gr2m** [comment]
@paolodm It does return a Promise – unless you pass in a function as last argument.

I have new docs ready as part of #680, the add examples using callbacks, would that have helped in your case?

![image](https://user-images.githubusercontent.com/39992/34457907-8f07ea6a-ed74-11e7-8847-8ea602359911.png)

**Comment by paolodm** [comment]
Really? I am getting `undefined` for the following:

```js
const GitHubApi = require('node-github');
const github = new GitHubApi({
    host: 'api.github.com',
    version: '3.0.0'
});

github.authenticate({
    type: 'token',
    username: 'paolodm',
    token: 'your-token-here'
});

let r = github.repos.getAll({
    affiliation: 'owner,organization_member'
});

console.log(typeof r);
```

**Comment by paolodm** [comment]
I think I know what is happening. This repo's name is node-github, but it _actually_ maps to npmjs's [github](https://www.npmjs.com/package/node-github). 

Meanwhile, I'm using npmjs's [node-github](https://www.npmjs.com/package/node-github) that corresponds to the now defunct https://github.com/c9/node-github3.

**Comment by gr2m** [comment]
you are not the first to run into this, it happened to me in the past as well :( GitHub adopted this pacakge recently and will rename it to `@octokit/rest` soon, so this won’t happen in future. I’m sorry for the headaches this caused you.

**Comment by ghost** [comment]
We can close this and the other issue. Thanks for the help.

**Comment by gr2m** [comment]
@paolodm just fyi, we took over [node-github](https://www.npmjs.com/package/node-github), this won’t happen again
