### ISSUE TITLE
repos.getBranches API specifies owner as parameter, but is actually user

### ISSUE THREAD

**Issue by paolodm** [octokit/octokit.js#682]
The repos.getBranches API doc specifies that we should pass owner as the param. See this:

https://octokit.github.io/node-github/#api-repos-getBranches

But when I pass owner, I get the following error:

```
 Empty value for parameter 'user': undefined
```

So I replaced owner with user, and everything was working as expected.

**Comment by ghost** [comment]
Closing. Same reason as #681. I had installed the `node-github` package, not the official `github` package.

**Comment by gr2m** [comment]
thanks
