### ISSUE TITLE
Recursive octokit.getNextPage(response) omits headers.

### ISSUE THREAD

**Issue by synicalsyntax** [octokit/octokit.js#706]
Hello `octokit/rest.js` maintainers!

It seems like recursive pagination with the `octokit.getNextPage(response)` method results in noninitial requests omitting some headers (the one that causes the error I'm getting is the missing User-Agent, although it looks like Authorization is also ommitted).

---

Please provide a minimal code sample to reproduce the issue if possible.

Using the [Pagination sample](https://github.com/octokit/rest.js#pagination) from the README:

```js
async function paginate (method) {
  let response = await method({per_page: 100});
  let {data} = response;
  while (client.hasNextPage(response)) {
    response = await client.getNextPage(response);
    data = data.concat(response.data);
  }
  return data;
}

paginate(client.users.getAll).then(data => {
  console.log(data.length);
});
```

throws the error (Octokit debug logs included):

```
octokit:rest REQUEST: Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'api.github.com',
  port: null,
  hostname: 'api.github.com',
  hash: null,
  search: '?per_page=100',
  query: 'per_page=100',
  pathname: '/users',
  path: '/users?per_page=100',
  href: 'https://api.github.com/users?per_page=100',
  method: 'get',
  body: undefined,
  headers: 
   { accept: 'application/vnd.github.v3+json',
     'user-agent': 'octokit/rest.js v14.0.3',
     authorization: '[REDACTED]' },
  ca: undefined,
  family: undefined,
  proxy: undefined,
  rejectUnauthorized: true,
  timeout: 0 } +0ms

  octokit:rest STATUS: 200 +665ms

  octokit:rest HEADERS: {"date":"Fri, 19 Jan 2018 03:03:56 GMT","content-type":"application/json; charset=utf-8","content-length":"86247","connection":"close","server":"GitHub.com","status":"200 OK","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4980","x-ratelimit-reset":"1516333134","cache-control":"private, max-age=60, s-maxage=60","vary":"Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding","etag":"\"85b1f3e97952bba8b1614e3c777a43b8\"","x-github-media-type":"github.v3; format=json","link":"<https://api.github.com/users?per_page=100&since=135>; rel=\"next\", <https://api.github.com/users{?since}>; rel=\"first\"","access-control-expose-headers":"ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval","access-control-allow-origin":"*","content-security-policy":"default-src 'none'","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-content-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","x-runtime-rack":"0.329031","x-github-request-id":"E0B0:1EFFA:241E194:2A5FCF4:5A61601C"} +0ms

  octokit:rest REQUEST: Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'api.github.com',
  port: null,
  hostname: 'api.github.com',
  hash: null,
  search: '?per_page=100&since=135',
  query: 'per_page=100&since=135',
  pathname: '/users',
  path: '/users?per_page=100&since=135',
  href: 'https://api.github.com/users?per_page=100&since=135',
  headers: { accept: 'application/vnd.github.v3+json' } } +84ms

  octokit:rest STATUS: 403 +161ms

  octokit:rest HEADERS: {"cache-control":"no-cache","connection":"close","content-type":"text/html"} +0ms

UNHANDLED PROMISE REJECTION: Promise {
  <rejected> { [Error: Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.
]
  message: 'Request forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\n',
  code: 403,
  status: undefined,
  headers: 
   { 'cache-control': 'no-cache',
     connection: 'close',
     'content-type': 'text/html' } } }
```

**Comment by gr2m** [comment]
Thank you for the great bug report, I was just able to reproduce it. Would you like to send a pull request for it? I’d be happy to help to find your way around if you have any questions

**Comment by synicalsyntax** [comment]
Mind telling me how I'm supposed to access the original request's headers then to pass it on to the next request then?

**Comment by gr2m** [comment]
the problem is probably in [lib/plugins/pagination/get-page.js](https://github.com/octokit/rest.js/blob/9003db1701979493dd2130a01a93c1d928b3d023/lib/plugins/pagination/get-page.js), I must have changed something compared to how it was implemented before: https://github.com/octokit/rest.js/blob/v13.1.1/lib/index.js#L407-L449

A good thing to start would be to create a failing test, or adapt the current pagination test at https://github.com/octokit/rest.js/blob/master/test/integration/smoke-test.js#L61 to reproduce the problem. Then figure out how to fix it.

Does that help?

**Comment by synicalsyntax** [comment]
The issue is your new [httpRequest](https://github.com/octokit/rest.js/blob/9003db1701979493dd2130a01a93c1d928b3d023/lib/request/request.js#L15) function that replaces [httpSend](https://github.com/octokit/rest.js/blob/ac39fb54c236df3c321dbe3843ae7ecb762b204f/lib/index.js#L598-L703) never bothers to set `User-Agent` and `Authentication` headers if they're undefined in the `requestOptions` parameters. The `User-Agent` seems pretty simple to set (maybe in [applyAcceptHeader](https://github.com/octokit/rest.js/blob/9003db1701979493dd2130a01a93c1d928b3d023/lib/plugins/pagination/get-page.js#L38)?), but the `Authentication` header don't seem to be set outside of `before-request` hooks. 

Given the experimental status of the [Hooks](https://github.com/octokit/rest.js/blob/master/HOW_IT_WORKS.md#hooks---) plugin, I'm pretty hesitant to dive into modifying this portion of the project, and I hope you'll be able to stabilize and create better documentation for it in the future. I'll be downgrading to v13 while this issue is WIP, but I hope to see this issue resolved soon! :)
