### ISSUE TITLE
typings: getForRepo returns Promise<Github.AnyResponse> instead of a promise for an iterable

### ISSUE THREAD

**Issue by retorquere** [octokit/octokit.js#711]
I used to be able to do

```
for (const issue of await octokit.issues.getForRepo({ owner, repo, state: 'open', labels: 'translation' })) {
...
}
```

but now I get

```
error TS2488: Type must have a '[Symbol.iterator]()' method that returns an iterator.
```

**Comment by gr2m** [comment]
is that a typescript related question? I’m no expert, I’m trying to keep the type definitions around as they have been there before, but I need help if folks run into bugs.

The template file is here: https://github.com/octokit/rest.js/blob/master/scripts/templates/index.d.ts.tpl

You can build it with `npm run build:ts`

**Comment by gr2m** [comment]
The typings are generated before the release to npm, so they are not in the source code. Here is the template used to generate the definition file from v13.1.1: https://github.com/octokit/rest.js/blob/v13.1.1/scripts/templates/index.d.ts.tpl

Here is the definition file as it exist on npm for v13.1.1
https://unpkg.com/github@13.1.0/lib/index.d.ts

does that help?

**Comment by retorquere** [comment]
It does; the 13.1 typings say getForRepo returns a `Promise<any>`, the 14.0 typings say it returns a `Promise<Github.AnyResponse>`. The `any` is a typescript wildcard type. If `getForRepo` still returns an array(ish), so `AnyResponse` would need to say it can also be an iteratable. I've opened a pull request at https://github.com/octokit/rest.js/pull/713.

**Comment by Xapphire13** [comment]
@retorquere 

I'm wondering how your pull request fixed the issue? Syntactically `Github.AnyResponse` is iterable now, but at runtime, the object returned isn't iterable:

```typescript
const response = await octokit.issues.getForRepo({owner, repo});
[...response]
// => TypeError: response is not iterable
```

And looking at the [source](https://github.com/octokit/rest.js/blob/2c35158f89f7b912fb7fb719a699b55573ebbfb5/lib/request/request.js#L82-L85), the object returned isn't iterable, its just a vanilla object.

**Comment by retorquere** [comment]
At runtime it may or may not be iterable; a the AnyResponse interface doesn't really change the objects rest.js returns, it just makes it so the typescript compiler doesn't complain at compile time if you treat it as such.

So if getforrepo doesn't return an iterable, the change in the typings does not fix that. But without the change, you couldn't iterate over the result of getforrepo even if it was iterable, because it would cause the typescript compiler to stop. AnyResponse doesn't really describe the responses from rest.js, it just describes the maximum shape they could have ("anything not named here is forbidden"). I just added one more feature that is not forbidden in AnyResponse objects.

**Comment by Xapphire13** [comment]
This seems like an abuse of the type system. All objects should conform to their declared types, and if not, then the typings should be changed to the minimum guaranteed subset.

Also by reading the code I linked above, the response will _never_ be iterable in any code path. Seems like we should cut a bug to either change the typings file or to make the response iterable.

**Comment by retorquere** [comment]
This arrangement is not my choice. getForRepo returns an AnyResponse, as do all rest.js methods (hence the name I suppose), I just made it so that AnyResponse would also cover iterables.

I'm not sure what happened in the interim because adding the iterable declaration to AnyResponse made it that my (typescript) release scripts which depend on it being iterable run again. I'm perfectly fine with any solution that gets getForRepo to work for typescript.

**Comment by Xapphire13** [comment]
Makes sense. Out of curiosity, what version of `octokit/rest.js` are you using?

**Comment by retorquere** [comment]
14.0.9, like so:

```
for (const issue of await octokit.issues.getForRepo({ owner, repo, state: 'open', labels: 'translation' })) {
  ...
}
```

**Comment by gr2m** [comment]
@Xapphire13 @retorquere I'm no expert in Typescript, I really want to get more into it to avoid trouble like this in the future, really sorry for that.

If one of you could send a PR for now that makes things right and the other give it a review, I'd appreciate it :)

**Comment by Xapphire13** [comment]
@retorquere

The example code you pasted doesn't work (this is nothing to do with TypeScript).

See this example in runkit: https://runkit.com/embed/dm8czahc179e

**Comment by retorquere** [comment]
@gr2m you are absolutely right; I should be iterating the `.data` property (which is declared `any`, so the compiler won't do any syntax checking on it), so the iterator doesn't serve any purpose there and should be removed. This works: https://runkit.com/retorquere/5a82b2308fd97000126c068b
