### ISSUE TITLE
 github.pullRequests.createComment has wrong validation

### ISSUE THREAD

**Issue by 0xjocke** [octokit/octokit.js#712]
According do docs [github.pullRequests.createComment](https://octokit.github.io/rest.js/#api-PullRequests-createComment) should take the following args:
owner: string 
repo: string
number: number 
body: string

But when using the module, it also requires you to pass in `commit_id`, `path` and `position`.
`Unhandled rejection Empty value for parameter 'commit_id': undefined`

If you pass in all the required params GitHub gives back an error:

```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "message": "commit_id is not part of the pull request",
      "resource": "PullRequestReviewComment",
      "field": "commit_id",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/pulls/comments/#create-a-comment"
}
```

Which makes it impossible to add a comment to PR right now. :(

**Comment by gr2m** [comment]
If you only want to create a comment on a pull request, use `github.issues.createComment`.

The `github.pullRequests.createComment` API should probably better be called `github.pullRequests.createReviewComment`. The API endpoint requires both `path` and `commit_id`. `position` is optional: https://developer.github.com/v3/pulls/comments/#create-a-comment

The error message you receive does not look like an problem with `@octokit/rest` but with the `commit_id` you are sending. It must be a valid commit sha for a commit that belongs to a pull request.

I hope that helps?

**Comment by 0xjocke** [comment]
Cool! 
That makes a lot of sense. Thanks for answering this quickly.
