### ISSUE TITLE
typings: ReposUploadAssetParams.file has changed from "Object" to "object"

### ISSUE THREAD

**Issue by retorquere** [octokit/octokit.js#714]
In 13.1, the `file` parameter could be either a `string` or an `object`, these were both captured by `Object`. Does 14.0 still accept strings for the file body? In that case it would either have to be typed as `Object`, or as `string | object`.

**Comment by retorquere** [comment]
I don't know how the template at https://github.com/octokit/rest.js/blob/master/scripts/templates/index.d.ts.tpl works, sorry, so I can't open a pull request for this.

**Comment by gr2m** [comment]
I guess it’s this line here:
https://github.com/octokit/rest.js/blob/34109d614958f8e423beb94c6959920e79c14862/scripts/templates/index.d.ts.tpl#L104

you could update this line to uppercase the first letter of type:
https://github.com/octokit/rest.js/blob/34109d614958f8e423beb94c6959920e79c14862/scripts/generate-types.js#L31

That would also change `string` to `String` etc, would that work for Typescript? It would also affect the flow types that I know even less about :D

I’m thinking about making a dedicated repository for the type definitions for `@octokit/rest` as they are generated anyway. Do you know if that is something commonly done?

**Comment by retorquere** [comment]
I thought I had found the right spot in the `lib/routes.json` -- was that wrong?

`String` (string object) is not the same as `string` (native string) for TS unfortunately.

I have absolutely no idea how separate typings are usually distributed. I'm new to typescript and blundering my way through.

**Comment by retorquere** [comment]
(I had opened PR #715 to change `lib/routes.json`)

**Comment by gr2m** [comment]
the type in there is not only used to generate the Flow/Typescript types, but also for the documentation as well as the validation when running methods like `octokit.repo.uploadAsset()`, see

https://github.com/octokit/rest.js/blob/34109d614958f8e423beb94c6959920e79c14862/lib/plugins/endpoint-methods/validate.js#L11

So we have to be careful with this one, I need to give it some thought

**Comment by retorquere** [comment]
So how about adding a 2nd parameter, something like "body", that's exclusively a string? Or splitting the expected type at that line you highlighted to get an array of allowed types? 

Alternately, I could pass a "new String" if it'd help (I assume because you're testing with "typeof", and typeof will return "object" for that.

**Comment by retorquere** [comment]
Using `new String` doesn't solve the problem; rest.js apparently tries to JSON-ify if it encounters an object, and in the case of `new String`, that ends up as a JSON-quoted string literal rather than the body I wanted to pass as the string itself.

**Comment by retorquere** [comment]
I've worked around it for now using stringToArrayBuffer, but as it is, you can't pass a string body using typescript.

**Comment by gr2m** [comment]
Thank you! I’ll have a look into it tomorrow (Monday)

**Comment by gr2m** [comment]
I’m still on it, give me another day :)

**Comment by gr2m** [comment]
The reason this takes me so long is that I tried to make things work with the flow definitions, too. But turns out that the current "object" flow type is not working in flow either, but neither will "string | object" work. I’m new to both Flow & Typescript so this all takes me quite some time to investigate. But I don’t want to make you wait longer, and given that the current version is already broken with flow types I don’t see a reason to just go ahead and merge your PR, then figure out the flow types later.

Thanks for you patiences!
