### ISSUE TITLE
since parameter incorrectly formatted

### ISSUE THREAD

**Issue by JuanCaicedo** [octokit/octokit.js#716]
I've been having a bug with requesting notifications while setting a `since` parameter. The following would not return a notification which came in at `2018-01-22T15:27:32Z`
```js
 octokit.activity.getNotifications({since: '2018-01-21T23:27:32Z' })
```
Upon researching, I found that this was the request getting sent to github 
> https://api.github.com/notifications?since=Mon%20Jan%2022%202018%2007%3A27%3A31%20GMT%2B0800%20(WITA)
>
> This corresponds to 2018-01-22

I don't think this is the correct format, [their api](https://developer.github.com/v3/activity/notifications/#list-your-notifications) expects an ISO string in the format `YYYY-MM-DDTHH:MM:SSZ`.

AFAICT, the error comes from [here](https://github.com/octokit/rest.js/blob/master/lib/plugins/endpoint-methods/validate.js#L59) and [here](https://github.com/octokit/rest.js/blob/master/lib/endpoint/add-query-parameters.js#L19).

The root of the problem is that the value this expression changes based on your system clock.
```js
encodeURIComponent(new Date('2018-01-21T23:27:31.000Z'))
```

I don't think the validate.js should cast dates strings to date objects. I think what it should do instead is try making a date object, and if that fails throw a `new errors.BadRequest` like other validations steps. If it succeeds, it should leave the datestring alone so it is passed to github. 

All this sound okay? I can make a PR for it

**Comment by gr2m** [comment]
Thanks for reporting the bug @JuanCaicedo! I just tested it with `v13.1.1` and the error existed in there, too. 

I guess we can remove these lines altogether:

https://github.com/octokit/rest.js/blob/34109d614958f8e423beb94c6959920e79c14862/lib/plugins/endpoint-methods/validate.js#L58-L60

you can also remove the lines below as they don’t do anything :)

https://github.com/octokit/rest.js/blob/34109d614958f8e423beb94c6959920e79c14862/lib/plugins/endpoint-methods/validate.js#L62-L64

If you could add a test, that’d be much appreciated. Please let me know if I can help with anything
