### ISSUE TITLE
Publish this as github on npm?

### ISSUE THREAD

**Issue by finnp** [octokit/octokit.js#724]
Hey,

Is there a reason why this is only published as `@octokit/rest` on npm? `github` seams like a better name for people to find this library on npm.

Also with the new name, people using the existing `github` library will not  see the updates to this library (well apart from a deprecation notice).

You could even publish this as `github` as well as `@octokit/rest` on npm.

**Comment by gr2m** [comment]
GitHub is building out `Octokit` to be its own brand, as the toolkit you use if you want to integrate with GitHub in anyway, hence the rename.

Having two packages with the same name doing the same thing will be rather harmful than helpful in the long run, so I don’t think it’s a good idea?

Eventually we will release a new `github` version which just throws an error telling the user that the package has been renamed to `@octokit/rest`.

But I realised that we don’t set any keywords in the package name, I’ll add github there to improve the likability that people find it by chance when searching for the package on npm

**Comment by ivankristic** [comment]
Can you please add something in description so we dont have to lose 10mins to find out which package is being developed by Github and which one will be obsolete.
Or better said 'others', since 'we' already lost those 10 mins.

**Comment by gr2m** [comment]
yes, will do
