### ISSUE TITLE
Errors thrown by the `octokit.hook.error` callback are not re-thrown

### ISSUE THREAD

**Issue by pvdlg** [octokit/octokit.js#734]
When an error is thrown by the `octokit.hook.error` callback it's not forwarded to the client consumer. Instead the original error is thrown.
Here is the code to reproduce:
```js
const Octokit = require('@octokit/rest');
function plugin(octokit) {
  octokit.hook.error('request', (error, options) => {
    throw new Error('Should be returned by the API');
  })
}

const github = new Octokit();
github.plugin(plugin);

github.repos.get({repo:'unknown', owner:'octokit'}).catch(console.log);
```

The error thrown by the call to `github.repos.get` is an http error `404`, which is the original error that triggered the call to the `octokit.hook.error` callback. The `new Error('Should be returned by the API')` is swallowed and the Octokit user never gets it.

I don't know if this is a bug or the intended behavior. I tend to think an error thrown in the hook implementation should be forwarded, as we can assume that users throwing the error in their implementation expect to do something with it when they call the client.

Also errors thrown by the `octokit.hook.before` and `octokit.hook.after` hook are forwarded to the user. To test replace `octokit.hook.error('request', (error, options) => {` by `octokit.hook.before('request', (options) => {` `octokit.hook.after('request', (options) => {` in the example above. I guess all the hooks should be consistent regarding errors management.

See https://github.com/semantic-release/github/pull/37#issuecomment-365170780 in which the problem when trying to use the `octokit.hook.error` to retry the request.

**Comment by pvdlg** [comment]
Ref this comment in [before-after-hook](https://github.com/gr2m/before-after-hook/blob/master/lib/register.js#L41-L44):
> 3. If an error occurs in 1. or 2. run the "error hooks" which may mutate the error object. If one of them does not return an error then set the result to that. Otherwise throw (mutated) error.

Is seems it's expected the users can mutate the original error, but not throw a new one, as the code doesn't handle such case and always throw the original error.

Not sure if it's a bug or not ¯\\\_(ツ)\_/¯

**Comment by gr2m** [comment]
Yeah I agree this is rather confusing. Right now I plan to get rid of the before-after-hook altogether so people can replace the request/response with custom logic altogether instead of adding before/after/error handlers. That would allow for simple mocking, retries, etc.

The reason why the current error object can be mutated is that there maybe be multiple error handlers. I agree that mutating an error instead of throwing a new one is not very intuitive though. I don’t see a simple fix right now so I’ll leave it as is and get back to it as part of the next milestone when we revise the API

**Comment by gr2m** [comment]
This seems to be have been fixed meanwhile: https://runkit.com/gr2m/octokit-rest-js-734/1.0.0
