### ISSUE TITLE
replace constructor option.{protocol,host,port,pathPrefix} with options.baseUrl

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#740]
deprecate old options to ease migration.

While at it, replace `options.requestMedia` with `options.headers.accept`. If I'm not mistaken, the current `options.requestMedia` is not even implemented correctly

**Comment by anshumanv** [comment]
Are you working on this @gr2m? If not, could you please tell me as to where the changes are to be made, I don't seem to get it exactly. :worried:

**Comment by gr2m** [comment]
this issue is all yours if you like :) 

So, the way it works is when you do something like this

```js
const octokit = require('@octokit/rest')({
  protocol: 'https',
  host: 'github.acme-inc.com',
  pathPrefix: '/api/v3'
})
```

Then the passed `options` will be passed to `parseClientOptions` at 
https://github.com/octokit/rest.js/blob/bf2f550557bfed7499ef197d22c4c58f71754f02/index.js#L17

In `lib/parse-client-options.js` you already see a few examples for depercations, which is what we want to do for all four options if they have been passed: `protocol`, `host`, `port`, `pathPrefix`

https://github.com/octokit/rest.js/blob/bf2f550557bfed7499ef197d22c4c58f71754f02/lib/parse-client-options.js#L24-L30

We already construct a `baseUrl` for internal usage, you can reuse that:

https://github.com/octokit/rest.js/blob/bf2f550557bfed7499ef197d22c4c58f71754f02/lib/parse-client-options.js#L41-L50

Then we have to update the README and `lib/defaults.js`. And of course add tests for the new `baseUrl` option as well as the deprecations, see https://github.com/octokit/rest.js/blob/bf2f550557bfed7499ef197d22c4c58f71754f02/test/integration/deprecations-test.js

**Comment by aryannarora** [comment]
@gr2m  @anshumanv  Seems doable. Should i also try?

**Comment by gr2m** [comment]
feel free to both send pull request. You can review each others pull requests and maybe come up with  a shared solution? That’d be Open Source at its best :) And GitHub [supports co-authors now](https://blog.github.com/2018-01-29-commit-together-with-co-authors/)

**Comment by aryannarora** [comment]
@gr2m I didn't quite get about the update in `lib/defaults.js `, could you please tell more about that?

**Comment by gr2m** [comment]
This issue is about removing these options: `protocol`, `host`, `port`, `pathPrefix`

Right now, if these are not passed, they are set to default values, which are configured in `lib/defaults.js`

https://github.com/octokit/rest.js/blob/bf2f550557bfed7499ef197d22c4c58f71754f02/lib/defaults.js#L4-L7

Instead of these defaults, we want to set a default for `baseUrl`

**Comment by gr2m** [comment]
this was done via https://github.com/octokit/rest.js/pull/807
