### ISSUE TITLE
Delete branch

### ISSUE THREAD

**Issue by ivandrofly** [octokit/octokit.js#768]
Help please.

How can I delete a branch using this api.
see: https://developer.github.com/v3/git/refs/#delete-a-reference

**Comment by gr2m** [comment]
Hi Ivandro, you are looking for `octokit.gitdata.deleteReference({owner, repo, ref})`:
https://octokit.github.io/rest.js/#api-Gitdata-deleteReference

Does that work for you?

**Comment by ivandrofly** [comment]
> Does that work for you?

yeah, thanks :)

**Comment by jackson-sandland** [comment]
I'm seeing `ref does not exist` except the branch does exist...

**Comment by gr2m** [comment]
Can you create a separate issue? Make sure you are authenticated correctly. If it's a private repository and you don't authenticate with the necessary permissions, you will get a 404
