### ISSUE TITLE
Edit gist : Body should be a JSON Hash

### ISSUE THREAD

**Issue by JBX028** [octokit/octokit.js#77]
Hi,

First of all, thank you very much for this great library.

Unfortunately I got a error message (body should be a JSON Hash) when I try to update a gist and when the content to update is a source code. If i put content: "test" it's ok but as soon as instead of "test" i put a variable and when the content of this variable is basically a source code, i am always face to this error.

How can i update a gist which is a source code such as a javascript content.

Thanks in advance
Jbx028 from France

**Comment by kaizensoze** [comment]
Should be fixed: https://mikedeboer.github.io/node-github/#api-gists-edit
