### ISSUE TITLE
Edit repo metadata for organizational repository?

### ISSUE THREAD

**Issue by kylecordes** [octokit/octokit.js#773]
There is a different API "create" versus "createForOrg", to create a repository for user versus an organization.

But the parallel for this appears to be missing for "edit": edit appears to be user specific, there is no "editForOrg".

(My use case, though it probably doesn't matter, is that I want to make API calls to edit the description field for some organizational repositories.)

**Comment by gr2m** [comment]
Thanks @kylecordes for bringing that up. Timing is great, we will thoroughly review all the endpoint API methods as part of the next milestone. I'd hold on to investigate further right but I’ll make sure to have a look at this while we do the review. I guess we will start working on it in 1-2 weeks

**Comment by kylecordes** [comment]
One thing I noticed while digging around, the API is surprisingly big. I don't know if this is too large of a deviation from the REST API, but one could consider having the JS not expose so many calls. As a user of the JS API it seems unnecessary that I have to care about making a different call to do something on an organizational repository versus a user repository. I can certainly interact with Github both as a user and as a programmer (i.e. using Git) without caring about that.

**Comment by gr2m** [comment]
The original issue was resolved by #822. Not that the new version is a pre-release right now: https://github.com/octokit/rest.js/releases/tag/v15.3.0 – install with `@next` or `@15.3.0`

**Comment by gr2m** [comment]
> One thing I noticed while digging around, the API is surprisingly big

I agree, I want this to become more modular, especially for usage in browser. Feel free to open a separate issue, ideally with more background information / your motivation
