### ISSUE TITLE
repos.getCommits( { user: 'xxxx', repo: 'xxxxx' }) -> NOT FOUND

### ISSUE THREAD

**Issue by d1b1** [octokit/octokit.js#78]
I am having an issue getting the commits for a private repo. Some work and some do not. Any help would be great. This repos I am trying access are private. The OAuth has a scope: user, repo etc.

  var github = new githubAPI({
    version: "3.0.0"
  });

  github.authenticate({
    type: "oauth",
    token: req.session.user.access_token
  });

  var since = moment().subtract('months', 24).format('YYYY-MM-DDTHH:mm:ssZ');

  github.repos.getCommits({ user: 'd1b1', 'until': since, repo: 'composer' }, function(err, data) {

```
console.log(err, data);

res.send(data, 200);
```

  });

**Comment by kaizensoze** [comment]
Should be fixed: https://mikedeboer.github.io/node-github/#api-repos-getCommits
