### ISSUE TITLE
[Feature Request] Get list of github users mentioned in an issue comment

### ISSUE THREAD

**Issue by itaditya** [octokit/octokit.js#789]
Currently, Github Api allows to get details of a comment (https://developer.github.com/v3/issues/comments/#get-a-single-comment). The comment body shows the whole content of the message.
It would be really helpful if the **GitHub REST API client** parses the comment body and collects the list of all the users mentioned in the comment.

Intended Working
```js
const result = await octokit.issues.getComment({owner, repo, id})
```

```json
{
  "id": 1,
  "url": "https://api.github.com/repos/octocat/Hello-World/issues/comments/1",
  "html_url": "https://github.com/octocat/Hello-World/issues/1347#issuecomment-1",
  "body": "@gr2m what do you think about the feature @itaditya  suggested",
  "mentions": ["gr2m", "itaditya"],
  "user": {},
  "created_at": "2011-04-14T16:00:49Z",
  "updated_at": "2011-04-14T16:00:49Z"
}
```

**Comment by gr2m** [comment]
This is out of scope of `@octokit/rest`, but it is something that you can build out as a plugin very soon yourself. The APIs are already there, they are just not public yet, so they might change in future. But you can start experimenting with them already, see https://github.com/octokit/rest.js/tree/ad04557fcc4397259b5edbeacf85f3a606459a95/lib/plugins

**Comment by itaditya** [comment]
Thanks @gr2m I didn't knew there was a way of adding a plugin, I am making one right away. Also would it be beneficial if I make a PR for adding the plugin

**Comment by gr2m** [comment]
The ones at https://github.com/octokit/rest.js/tree/ad04557fcc4397259b5edbeacf85f3a606459a95/lib/plugins are core plugins, if you create one yourself then create an own repository and npm package. We didn’t establish conventions yet, but maybe prefix the package name with `octokit-plugin-` and add `octokit-plugin` as keyword in the package.json file

**Comment by itaditya** [comment]
Ok so in the end the intended use of plugin would be like this ?

```js
const octokit = require('@octokit/rest')();
const mentionsPlugin = require('octokit-plugin-getMentions');

octokit.plugin(mentionsPlugin)

(async () => {
  const comment = await octokit.issues.getComment({ owner, repo, id });
  const mentions = octokit.getMentions({ comment });
  console.log('mentions', mentions);
})()
```

**Comment by gr2m** [comment]
that would work, yes :)

**Comment by itaditya** [comment]
@gr2m thanks for helping me out. I have made a working plugin. If you could take a moment please check this out. 
https://www.npmjs.com/package/octokit-plugin-mentions.
