### ISSUE TITLE
Update route.json, automate future updates

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#790]
All REST API endpoint methods such as `octokit.repos.get()` are currently generated from the [routes.json](https://github.com/octokit/rest.js/blob/60bdd7ab5e1eff100ada28b1847c52577c5fdbe5/lib/routes.json) file which was so far manually updated and hence is out of date.

To make this more maintainable, we will look into ways to keep the routes.json updated automatically, based on [GitHub’s latest REST API documentation](https://developer.github.com/v3/).

**Comment by gr2m** [comment]
This is now done via #822 🎉

**Comment by laughedelic** [comment]
Hi! I'm very glad that you decided to use octokit/routes in this library 👏 

I'm writing a [Scala.js](https://www.scala-js.org/) wrapper for this library with the same approach as you use for Flow and TypeScript, i.e. generating type definitions based on the `lib/routes.json` . I already have a prototype: [scalajs-octokit](https://github.com/laughedelic/scalajs-octokit), but I'd like to ask some questions to decide how to proceed with the development.

At first I started using `routes-for-api-docs.json` because I wanted to generate code with doc-comments, but then I realised that it misses some parameters that are present in `routes.json`, so I switched to it. I see that in `scripts/generate-routes.js` you change some things in the generated routes, but I didn't dig too deep into that code, I thought it's better to ask first.

Why do you need 2 separate files: `lib/routes.json` and `scripts/routes-for-api-docs.json`? I understand if you just wanted to keep existing code as is and fit the new data (coming from octokit/routes) to it. If that's the case, do you have any plans to change that? Would it be possible to include documentation information in the generated `lib/routes.json`? I understand that this would require changing the docs generation code, but if it's a desired change, I could probably try my hand on it.

The same kind of question goes to the possibility to change the code dependent on `lib/routes.json`, to use octokit/routes instead as the signle source of truth. I guess that's a much bigger change, so I'm just wondering if it would be possible.

P.S. I'm also looking forward to start using #732!

**Comment by gr2m** [comment]
> I'm writing a Scala.js wrapper for this library

That is amazing! Thank you @laughedelic :) Make sure to subscribe to https://github.com/octokit/rest.js/issues/620, I’ll announce pre-releases and bigger changes there :)

> Why do you need 2 separate files: lib/routes.json and scripts/routes-for-api-docs.json?

To reduce bundle size, as `@octokit/rest` is meant to be used in browsers, too. That’s why I keep its size to an minimum. That’s why there will always be a build step from `@octokit/routes`, but it’s all automated now: https://www.dropbox.com/s/0fftf0guiokhpz7/automating-routes-updates-for-javascript-octokit-v2.mov?dl=0

> I realised that it misses some parameters that are present in routes.json

The reason for that is to make the transition simpler. You will se a lot of alias and deprecations in `lib/routes.json`. We will remove the deprecated method & parameter names as part of the next release.

I think you should be fine using `routes-for-api-docs.json`. The only thing it won’t have are currently deprecated method and parameter names

> P.S. I'm also looking forward to start using #732!

Me too! This one will be tricky, we’d love your help with it

**Comment by laughedelic** [comment]
Thanks, I understand the motives now. 

> I think you should be fine using `routes-for-api-docs.json`. The only thing it won’t have are currently deprecated method and parameter names

Yes, I'd be fine without deprecated API, but I found some other differences. For example:

* `enterprise` namespace is missing (probably some other too?)
* All parameters with `mapTo` in `routes.json` are missing in `routes-for-api-docs.json`. For example [`user.addEmails`](https://developer.github.com/v3/users/emails/#add-email-addresses) has  `emails` parameter (an essential one, I suppose):

    ```json
    "addEmails": {
      "method": "POST",
      "params": {
        "emails": {
          "mapTo": "input",
          "required": true,
          "type": "string[]"
        }
      },
      "url": "/user/emails"
    },
    ```
    But in `routes-for-api-docs.json` this method has no parameters:

    ```json
    "addEmails": {
      "description": "You can post a single email address or an array of addresses:",
      "documentationUrl": "https://developer.github.com/v3/users/emails/#add-email-addresses",
      "enabledForApps": false,
      "method": "POST",
      "name": "Add email address(es)",
      "params": [],
      "path": "/user/emails"
    },
    ```
    I see that `mapTo` always maps to `input` and it's always missing in the `routes-for-api-docs.json`, so probably it's a bug? 

I need to generate types for the underlying library using exactly the same schema as this library uses itself. So I can't use `routes-for-api-docs.json` at the moment. 

What I'd like to suggest though is to change `routes-for-api-docs.json` format to be a superset of `routes.json`, i.e. exactly the same common data + docs and any other extra information. This way I will be able to use `routes-for-api-docs.json` and the octokit/rest.js docs will be in perfect sync with the actual API (look, [addEmails docs](https://octokit.github.io/rest.js/#api-Users-addEmails) don't give the user any chance 😅).

By the way, I think that the generated TypeScript types could also get doc-comments this way. It's should be very helpful with the proper IDE support (e.g. autocomplete would show these docs explaining each expected parameter).

> This one will be tricky, we’d love your help with it

How could I be helpful?

**Comment by gr2m** [comment]
> enterprise namespace is missing (probably some other too?

The reason is that `enterprise` docs have been removed from https://developer.github.com/v3/. Instead they only live at the docs for the respective enterprise version now, e.g. https://developer.github.com/enterprise/2.13/v3/. I will remove the enterprise routes with the next major version (or maybe the one after that if it becomes to complicated). Instead I’ll move the enterprise routes into a separate npm module that you can require as needed. 

Does that make sense? It’s really only me thinking about this right now, happy to discuss :) I created an issue for that at https://github.com/octokit/routes/issues/11

> All parameters with mapTo in routes.json are missing in routes-for-api-docs.json. For example user.addEmails has emails parameter (an essential one, I suppose):

This one is being worked on by GitHub. Some routes such as [Add email address(es)](https://developer.github.com/v3/users/emails/#add-email-addresses) require us to send an array without a namespace in the request body:

```json
[
  "octocat@github.com",
  "support@github.com"
]
```

Once they fix it, it will also accept 

```json
{
  "emails": [
    "octocat@github.com",
    "support@github.com"
  ]
}
```

Then we can get rid of the `mapTo`s

> But in routes-for-api-docs.json this method has no parameters

That’s because they are not correctly documented in the API docs which we parse automatically. I’ve reported that to the docs team, I hope they will fix it soon

> What I'd like to suggest though is to change `routes-for-api-docs.json` format to be a superset of `routes.json`, i.e. exactly the same common data + docs and any other extra information. This way I will be able to use `routes-for-api-docs.json` and the octokit/rest.js docs will be in perfect sync with the actual API (look, [addEmails docs](https://octokit.github.io/rest.js/#api-Users-addEmails) don't give the user any chance 😅).

I wonder if maybe as a first step you merge the two JSON files in your script? You should be able to combine them by looking up the http verb & method. 

You see this is all not super stable yet, but we are getting there. The advantage is that we collaborate much closer with the GitHub API & Documentation teams now and help them improve their code & docs, which then automatically tickles down to our Octokit libraries :)

**Comment by laughedelic** [comment]
Thanks for the explanation about `mapTo`. I don't have any opinion about enterprise stuff as I'm not using it myself. On the first sight it's not obvious why it needs some special treatment and be split into a separate npm module. Splitting things may be good for modularity, but then why not have a module per each namespace? (could this be good for minimizing in-browser dependencies?)

> I wonder if maybe as a first step you merge the two JSON files in your script?

Sure, this was exactly my plan. I just wanted first to ask around to understand better why things are as they are and see how and if it's going to change. Docs are not essential for me at this moment (as the API is exactly the same, users can refer to the JS docs), so I'll leave this for later.

> The advantage is that we collaborate much closer with the GitHub API & Documentation teams now and help them improve their code & docs, which then automatically tickles down to our Octokit libraries :)

This is just great! 💯 Thanks for your hard work 👍

**Comment by laughedelic** [comment]
By the way, there's one thing which confuses me a bit: is this library an official GitHub REST API client for JS or not? I don't see it explicitly mentioned anywhere in the repo (except of "It was adopted and renamed by GitHub in 2017"), but it's in the octokit org. The [Octokit website](http://octokit.github.io/) says:

> Octokit is the simple and **official** way to build amazing experiences using the GitHub API.

But then there's only Ruby, Obj-C and .NET there...

**Comment by gr2m** [comment]
> is this library an official GitHub REST API client for JS or not

Yes it is :) I’ll make it more clear in the README. All libraries in the @octokit org are official. The Octokit website is desperately out of date :/
