### ISSUE TITLE
How to update team repositories / memberships?

### ISSUE THREAD

**Issue by corydorning** [octokit/octokit.js#801]
I'd like to edit teams and be able to pass in an array of `maintainers` and `repo_names` the same way I can when creating a team.

With `createTeam` I can do the following:
```
octokit.orgs.createTeam({org, name, description, maintainers, repo_names, privacy, parent_team_id}).then(result => {})
```

`editTeam` however, only includes the `id`, `name`, `description`, `privacy` and `parent_team_id` fields.

I'm assuming this is a limitation with the GitHub API itself, so not sure if I should post it there or not.

**Comment by gr2m** [comment]
For reference, here are the REST API docs

- create team: https://developer.github.com/v3/teams/#create-team
- edit team: https://developer.github.com/v3/teams/#edit-team

Unfortunately there is nothing we can do in `@octokit/rest` itself, we want to stay as close as possible to the REST API with all its design flaws to keep things simple. So you will need to use the other methods such as [`octokit.orgs.addTeamRepo`](https://octokit.github.io/rest.js/#api-Orgs-addTeamRepo) or [`octokit.orgs.addTeamMembership`](https://octokit.github.io/rest.js/#api-Orgs-addTeamMembership). 

I’d be curious to know what the thinking behind not allowing `maintainers` or `repo_names` is so if you end up asking the support, please let us know :) 

Moving forward, there is something we can do though. `@octokit/rest` already has a plugin architecture, the APIs are just not "public" yet, they still might change between major releases. But what we want to do is to create "How do I ..." guides for common scenarios and build plugins that codify a solution for easy reusability.

If you like you can play around with that already, we are looking for feedback. Here are some docs and you can also have a look at the core plugin implementations: https://github.com/octokit/rest.js/tree/master/lib/plugins

**Comment by gr2m** [comment]
I’ve edited the issue title to make it more useful to others, hope you don’t mind?

**Comment by corydorning** [comment]
Not at all

**Comment by gr2m** [comment]
@corydorning did you reach out to the support, could they help you out? If not I can reach out to them too and keep you posted here

**Comment by gr2m** [comment]
that’s fixed now
