### ISSUE TITLE
Add instructions for getting a pull request locally for testing

### ISSUE THREAD

**Issue by cg-cnu** [octokit/octokit.js#805]
Hey @gr2m,

As discussed in https://github.com/octokit/rest.js/pull/792 am writing the instructions for testing a specific pull request from github locally.

## How to test a pull request in github locally:

* You can install a specific pull request of a module from github using the bellow command

`npm install owner/reponame#pullrequestId/branchname`

* For example to test https://github.com/octokit/rest.js/pull/792 locally run...

`npm install octokit/rest.js#791/error-headers`

`octokit/rest.js` is the `owner/repo` of the github repository, `791/error-headers` is the `pullrequestId/branchname`. If you leave the branchname it would default to `master`

* After the installation is done, you can double check with npm ls @octokit/rest which will show something like

└── @octokit/rest@0.0.0-semantically-released  (git+https://github.com/octokit/rest.js.git#505ed1f57671480b625131abb00c277c67cae40a)

* Once you are done testing, you can revert back to the default module `@octokit/rest` from npm with `npm i @octokit/rest`

Let me know if you have any comments. Will create the pr once approved. Thanks 😄

**Comment by gr2m** [comment]
Let’s start a PR with this now, it will be easier to discuss there :) Thanks again!
