### ISSUE TITLE
Counting requests made by a client

### ISSUE THREAD

**Issue by zeke** [octokit/octokit.js#816]
Is there a built-in way to track the requests made by a client?

Context: working on a probot that's taking a super-long time to resolve certain requests. Knowing all the requests that were made might help me figure out where to optimize.

**Comment by gr2m** [comment]
there is undocumented API that you can use for that. Just make sure to pin your `@octokit/rest` version if you use it as it might change between major versions.

```js
const trackedRequests = []
octokit.hook.before('request', (options) => {
  trackedRequests.push(options)
})
```

Does that work for you?

**Comment by zeke** [comment]
Perfecto!
