### ISSUE TITLE
create-react-app build fails due to ES6 syntax

### ISSUE THREAD

**Issue by rsullivan00** [octokit/octokit.js#828]
Adding `@octokit/rest` to a `create-react-app` app causes builds to fail during minification with:

```
yarn run v1.5.1
$ yarn run build
$ NODE_PATH=./src react-app-rewired build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/@octokit/rest/lib/plugins/pagination/get-page-links.js:10:26

Read more here: http://bit.ly/2tRViJ9

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c NODE_PATH=./src react-app-rewired build
```

This appears to be because the NPM package uses ES6 syntax (in this case a `=>` function). React scripts expect dependencies to be already compiled to ES5.

Related to https://github.com/octokit/rest.js/issues/485

**Comment by hzoo** [comment]
This kind of issue would be solved by compiling node_modules in CRA 2 via https://github.com/facebook/create-react-app/pull/3776

**Comment by gr2m** [comment]
@Rsullivan00 can you confirm?

**Comment by rsullivan00** [comment]
It appears to be building successfully with `react-scripts@2.0.0-next.b2fd8db8`.

Thanks for the heads up @hzoo!

**Comment by gaearon** [comment]
https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

**Comment by rsullivan00** [comment]
Sweet! We’ll give v2 a go with our react apps tomorrow.
