### ISSUE TITLE
activity.getNotifications date parsed into incorrect format

### ISSUE THREAD

**Issue by JuanCaicedo** [octokit/octokit.js#833]
I'm calling `octokit.getNotifications({ since: '2018-04-06T20:04:47.000Z'})` and am finding that it makes a request to 
> <https://api.github.com/notifications?since=Fri%20Apr%2006%202018%2015%3A04%3A47%20GMT-0500%20(-05)>
 
As far as I can tell, this is incorrect, the request should be made to 
> <https://api.github.com/notifications?since=2018-04-06T20:04:47.000Z>

I say that because in the [api docs](https://developer.github.com/v3/activity/notifications/#list-your-notifications) it says `since` should be an ISO string.

I think the root cause is the same as https://github.com/octokit/rest.js/issues/716, but a regression was introduced at some point. My reasoning is if you add this code 
```js
  console.log('options', options.since instanceof Date)
``` 
on line 15 at https://github.com/octokit/rest.js/blob/master/lib/plugins/endpoint-methods/method.js#L15, it will evaluate to true.

I'm still tracking down the root cause of that problem. I think `since` should be a string, but it remains a date even if I change `routes.json`

**Comment by gr2m** [comment]
Thanks for looking into it @JuanCaicedo. If you could start a pull request that reproduces the error, that’d be a great start.

**Comment by JuanCaicedo** [comment]
@gr2m Do you mean to add a failing test based on this error? If so sure 🙂

**Comment by JuanCaicedo** [comment]
Looking at how other date parameters work, like `due_on` for `issues.createMilestone()`, it looks like they should be an instance of `Date`, not a string.

I suspect that the difference is that in the `due_on` case, that date value is stringified and put into the body, while in the `since` case, it is url encoded and put into the url

**Comment by JuanCaicedo** [comment]
Sorry, I think this is my error in how I was calling the library. I was passing a date object, and what you should pass is an ISO string like 
```js
const date = new Date('2018-04-06T20:04:47.000Z')
octokit.getNotifications({ 
  since: date.toISOString()
})
```
I think the real fix for the problem I experienced would be to validate that the date parameter is a valid ISO string. In https://github.com/octokit/rest.js/pull/719, I just removed the validation completely. Not sure of how to validate an ISO string, but it might be as easy as just trying to make a new date object with it and throwing an error if that fails.

Let me know if you think that's a good path forward and I can open up another issue about it and work on implementing it

**Comment by gr2m** [comment]
Hey @JuanCaicedo, we have a pretty big refactoring coming up via https://github.com/octokit/rest.js/pull/822 where we will loose the information on wether a string is a an ISO date string as of now, I’ll revise it once #822 is shipped?

**Comment by JuanCaicedo** [comment]
Sure, that works for me!
