### ISSUE TITLE
Add support for required_signatures

### ISSUE THREAD

**Issue by FabianFrank** [octokit/octokit.js#835]
https://developer.github.com/v3/repos/branches/#add-required-signatures-of-protected-branch

**Comment by gr2m** [comment]
hey @FabianFrank, this should be fixed via #822. I’ll leave the issue open as a reminder to make sure that it does

**Comment by gr2m** [comment]
quick update: #822 was merged but we didn’t yet add new methods, only updated the existing ones. Adding new methods is a little more complicated but we should get to it soon. 

If this is a blocker for you then we can add the endpoint by hand before we make it part of the automated update process

**Comment by FabianFrank** [comment]
this isn't a blocker, I'm making that call manually with fetch for now. thank you!

**Comment by gr2m** [comment]
It’s now implemented as `client.repos.addProtectedBranchRequiredSignatures()`:
https://octokit.github.io/rest.js/#api-Repos-addProtectedBranchRequiredSignatures

Thanks for your patience :)
