### ISSUE TITLE
Paginate example code errors with TypeError: method is not a function

### ISSUE THREAD

**Issue by toymachiner62** [octokit/octokit.js#837]
I'm trying to copy your pagination example (https://github.com/octokit/rest.js#pagination) and it's failing with "TypeError: method is not a function".

Here's an example runkit: https://runkit.com/toymachiner62/5ad52685772a1e00129f1d76

**Comment by gr2m** [comment]
The problem is that you pass in `octokit.repos.getAll({affiliation: affiliation})` which executes the method and returns the result. Can you try passing in `() => octokit.repos.getAll({affiliation: affiliation})` instead?

```diff
- paginate(octokit.repos.getAll({affiliation: affiliation}))
+ paginate(() => octokit.repos.getAll({affiliation: affiliation}))
```

**Comment by toymachiner62** [comment]
Yea that worked. Thanks for updating the docs.

Tom Caflisch
507.202.0087
TomCaflisch@gmail.com
http://allthingswebdesign.com
