### ISSUE TITLE
`pathPrefix` is still in examples/tests despite deprecation

### ISSUE THREAD

**Issue by Mr-Wallet** [octokit/octokit.js#840]
My team's first stab at using this package with GitHub Enterprise failed when we followed the example in [examples/enterpriseUploadAsset.js](https://github.com/octokit/rest.js/blob/master/examples/enterpriseUploadAsset.js) and tried to use `pathPrefix` during construction. It turns out that `pathPrefix` is deprecated, and the only way to make enterprise work seems to be concatenating the host and "path prefix" as a single string, and use that as the `host` option.

**Comment by gr2m** [comment]
The `pathPrefix` option is deprecated but should still work. Could you share your code please?

**Comment by Mr-Wallet** [comment]
The difference couldn't be simpler:
```javascript
const x = new octokit({
  baseUrl: 'https://myEnterprise.example.com',
  headers: {
    'user-agent': 'octokit/rest.js v15.2.6'
  },
  pathPrefix: '/api/v3', // nothing works
  timeout: 5000
});

const y = new octokit({
  baseUrl: 'https://myEnterprise.example.com/api/v3', // everything works
  headers: {
    'user-agent': 'octokit/rest.js v15.2.6'
  },
  timeout: 5000
});
```

We're in Electron, so we can see the outbound traffic using the Chromium devtools, and in the first example, `/api/v3` is not in any of the URIs for the API requests.

Notably, `pathPrefix` is [never mentioned](https://github.com/octokit/rest.js/search?utf8=%E2%9C%93&q=pathprefix) except for examples, tests, `templates` (which I assume are only for type-checking), and the deprecation warning itself.

**Comment by gr2m** [comment]
Ah got it, what happened is that before you had to set 4 options:

1. protocol
2. host
3. protocol
4. pathPrefix

we replaced them all with `baseUrl`. But you cannot combine `baseUrl` with one of the above, it’s either or. The example at https://github.com/octokit/rest.js/blob/master/examples/enterpriseUploadAsset.js sets `host` and `pathPrefix`, but not `baseUrl`.

Hope that makes sense?

I’m closing the issue as I think it’s a misunderstanding, but please let me know if you have any further questions.

**Comment by Mr-Wallet** [comment]
Thanks, it took a while but I think I get it now. Mostly I was confused by `endpoint/index` and the way it juggles values around and infers what was defined when the options were parsed but not passed down to it when it's constructing the URL. Hopefully when things settle down those README files can be reconciled. 😆
