### ISSUE TITLE
Please help us test v15.3.0 (especially if you use Typescript)

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#844]
👋 Hello friends, after [a rather big pull request](https://github.com/octokit/rest.js/pull/822) we now have an automatically generated [`lib/routes.json`](https://github.com/octokit/rest.js/blob/master/lib/routes.json) file based on https://github.com/octokit/routes (`ocotkit/routes` is [updated automatically](https://github.com/octokit/routes/pull/87) based on latest https://developer.github.com/v3/).

The `routes.json` files had quite a few changes but not should be breaking your code. If you are interested, I attached both the old and new `routes.json` file to the [v15.3.0 release](https://github.com/octokit/rest.js/releases/tag/v15.3.0).

`v15.3.0` is published to npm using the `@next` dist-tag, please install it with `npm install @octokit/rest@next` and run your tests. If you run into any trouble, please comment below 🙇

**Comment by gr2m** [comment]
☝️🛎 ping @philschatz @tcbyrd @ocombe

**Comment by joseym** [comment]
@gr2m is it just me, or are typescript definitions missing?

**Comment by philschatz** [comment]
Thanks @gr2m! I am running an event this week but will try to take a look this weekend.

**Comment by gr2m** [comment]
@joseym the file is in the npm release at least: https://unpkg.com/@octokit/rest@15.3.0/index.d.ts

**Comment by ocombe** [comment]
I get the typescript definitions for my part. I've tested the new version and it seems to be working fine for me.

**Comment by gr2m** [comment]
@philschatz did you have a chance to look into it?

I would like to publish a `latest` release today or tomorrow to ship [the new checks api](https://blog.github.com/2018-05-07-introducing-checks-api/), see #852

**Comment by orta** [comment]
TypeScript support feels 👍 to me, ran `yarn add @octokit/rest@next` which is on `15.3.0`

```
success Saved 1 new dependency.
info Direct dependencies
└─ @octokit/rest@15.3.0
info All dependencies
└─ @octokit/rest@15.3.0
```

<img width="1039" alt="screen shot 2018-05-07 at 10 43 06 pm" src="https://user-images.githubusercontent.com/49038/39735137-259e8a46-5248-11e8-8dac-d892109ba102.png">

**Comment by gr2m** [comment]
All right, thanks for testing y’all, v15.4.0 is on its way to latest
