### ISSUE TITLE
Is there actually a way to get a file in a repo and it's contents?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [octokit/octokit.js#845]
Don't see anything like a documentation for something like this, would be very helpful!
(Also, is there an example on how to make a PR and change files and such? Having some trouble...)

**Comment by ThatNerdyPikachu** [comment]
Alright, I'll do that.
Instead of making something like an FAQ, maybe make examples? I'd be happy to contribute!
And thanks, this helps a lot!

**Comment by ThatNerdyPikachu** [comment]
Also, why do I pass, for example, context.repo (probot) to something? Does that auto fill parameters?

(By the way, some formatting is messed up in your post. Might wanna change that if you want to help other people ;))

**Comment by gr2m** [comment]
> why do I pass context.repo

That is outside of Octokit. Probot provides the method as convenience. Instead of doing

```js
octokit.gitdata.getReference({owner, repo, ref})
```

You can do 

```js
octokit.gitdata.getReference(context.repo({ref})
```

`context.repo()` will set the repository slug (`owner/repo`) for you

**Comment by ThatNerdyPikachu** [comment]
Ah, gotcha

Sorry for all these questions, but why a buffer exactly?

**Comment by ThatNerdyPikachu** [comment]
Thanks for all your help!

**Comment by ThatNerdyPikachu** [comment]
@gr2m is `.data` always the raw response from github?

**Comment by gr2m** [comment]
> @gr2m is .data always the raw response from github?

Yes

> Also, maybe in the docs, you can show what will be returned, or the type, or an example, or something since it's quite vague atm

I thought we do with

```js
octokit.repos.getForOrg({
  org: 'octokit',
  type: 'public'
}).then(({data}) => {
  // handle data
})
```

Besides `.data` there is also `.meta` which are the response headers (we will rename it to `.headers` soon for clarity)

Would you change the example to make it more clear? I’m open to suggestions :)

**Comment by ThatNerdyPikachu** [comment]
Do you currently do that with everything?

**Comment by zeke** [comment]
> Do you currently do that with everything?

Can you clarify what you're asking here?

**Comment by ThatNerdyPikachu** [comment]
If you do an example like that in the docs...
If not, maybe even add a basic interaction with the `data` object so people can know what to expect what is responded for that specific thing? Well, the API doc's cover that, so maybe one thing?

**Comment by ThatNerdyPikachu** [comment]
@gr2m off topic, but where do you host all of your probot apps?

**Comment by gr2m** [comment]
> @gr2m off topic, but where do you host all of your probot apps?

@ThatNerdyPikachu https://zeit.co/now

**Comment by jeffin143** [comment]
is there any way to read contents of multiple files ? 

like something src/* -  `all files start from src/` ?

**Comment by gr2m** [comment]
I don't think so. I'm sure there is no REST API for that, and I couldn't find anything in the GraphQL docs either.

This might be a good question for https://support.github.com/contact. Either they find out a way to do that or they will mention your usecase to the API team so they can consider implementing an API for it.

**Comment by jeffin143** [comment]
@gr2m I really appreciate you have taken time out to answer my query :) 

I will contact the support :)

Anyways thanks for all the hardwork done with octokit :)

**Comment by jeffin143** [comment]
@gr2m  , Please note this is not related to any topic so you are free to hide this comment , but I came accross this article -  https://github.blog/2020-04-09-from-48k-lines-of-code-to-10-the-story-of-githubs-javascript-sdk/ and didn't know you were such a great asset and couldn't resist from myself commenting here for a person who worked in `nodeV0.1`

Thanks for all the open source work :tada: :100:

**Comment by gr2m** [comment]
Thanks Jeffin :) You can always create a new issue just to say thanks and then close it right away. Every maintainer loves these kind off issues. Thanks for your kind words!
