### ISSUE TITLE
Setting only the deprecated protocol URL constructor option throws an exception

### ISSUE THREAD

**Issue by malept** [octokit/octokit.js#848]
If you put a `protocol` option into the Octokit contructor (which I gathered was deprecated in 15.2.0), the base URL seems to be overwritten with `undefined` and so, for example, retrieving a list of releases throws an exception.

Reproducible test case: https://runkit.com/malept/octokit-deprecated-options-bug

This caused a regression in Electron Forge, which we fixed by removing `protocol` from the constructor options.

**Comment by gr2m** [comment]
Thanks @malept for reporting the bug, I’m sorry for the trouble. I’ll have a look into it.

Just to be sure: this is no longer a problem for Electron forge as you removed the `protocol` option?

**Comment by malept** [comment]
That's correct. You can reproduce it by removing `protocol` from the testcase linked in the issue summary.

**Comment by gr2m** [comment]
For future reference, here is the code with passing in a `host` option, too. No error: https://runkit.com/gr2m/5aecb07ba3c91a00124a1be9
