### ISSUE TITLE
Add Checks API Support

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [octokit/octokit.js#856]
The Checks API is a feature that will allow us to make more detailed reports for users.

**Comment by gr2m** [comment]
It shipped in [v15.4.0](https://github.com/octokit/rest.js/releases/tag/v15.4.0) :) 

Does that work for you?

**Comment by ThatNerdyPikachu** [comment]
Whoops, didn't see!
Don't know if I should close on Probot as well, since they have to implement the webhooks...
