### ISSUE TITLE
index.d.ts params that has alias types are incorrect.

### ISSUE THREAD

**Issue by hiradimir** [octokit/octokit.js#872]
I can not compile with typescript.
If params has alias, it says need also alias param, but in the fact it is not needed.

Now I am avoiding this compile error, using the "any" keyword.
index.d.ts is wasted.

### example

[getProject definition](https://github.com/octokit/rest.js/blob/master/lib/routes.json#L5079) says Id setted alias for project_id.

```json
    "getProject": {
      "headers": {
        "accept": "application/vnd.github.inertia-preview+json"
      },
      "method": "GET",
      "params": {
        "id": {
          "alias": "project_id"
        },
        "page": {
          "type": "integer"
        },
        "per_page": {
          "type": "integer"
        },
        "project_id": {
          "required": true,
          "type": "string"
        }
      },
      "url": "/projects/:project_id"
    },
```

but, in generated index.d.ts, ProjectsGetProjectParams says also needed id and project_id.

![image](https://user-images.githubusercontent.com/1043276/40031099-07902442-5829-11e8-95df-b65630aa4b7b.png)

### I am thinking correct index.d.ts

```ts
...
  export type ProjectsGetProjectParams =
    & {
      "page"?: number;
      "per_page"?: number;
      "project_id": string;
    };
  export type ProjectsGetProjectParamsWithAliasId =
    & {
      "id": string;
      "page"?: number;
      "per_page"?: number;
    };
...
declare class Github {
  projects: {
...
    getProject(params: Github.ProjectsGetProjectParams | Github.ProjectsGetProjectParamsWithAliasId, callback?: Github.Callback): Promise<Github.AnyResponse>;
...
  }
...
}

```

**Comment by gr2m** [comment]
Yeah I feared things might break, I asked for help at https://github.com/octokit/rest.js/issues/844. Does Typescript support aliasing?

**Comment by hiradimir** [comment]
@gr2m thenks for reply.

No, I think typescript does not support aliasing.

But, I think you can use [union-type](http://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types) 

please see code pattern on desc.
> I am thinking correct index.d.ts

> getProject(params: Github.ProjectsGetProjectParams | Github.ProjectsGetProjectParamsWithAliasId, callback?: Github.Callback): Promise<Github.AnyResponse>;
...
