### ISSUE TITLE
Transform ES2015 to ES5

### ISSUE THREAD

**Issue by axetroy** [octokit/octokit.js#879]
I got some issue when I pack it with ``webpack``

because octokit write in ``ES2015`` and uglify plugin does not support it.

Now I have to write a script to transform it by myself.

before I build project and run it

```json
    "transform:rest:lib": "NODE_ENV=production npx babel-cli ./node_modules/@octokit/rest/lib -d ./node_modules//@octokit/rest/lib",
    "transform:rest:index": "NODE_ENV=production npx babel-cli ./node_modules/@octokit/rest/index.js -o ./node_modules//@octokit/rest/index.js",
    "transform": "npm run transform:rest:lib && npm run transform:rest:index"
```

It works

**Comment by gr2m** [comment]
Glad you found a workaround 👍 

We will transform to es6 modules in a future release to take advantage of smaller bundle sizes for browsers. I don’t think it's worth transforming to es5 first
