### ISSUE TITLE
Browsers: response.meta doesn't contain the key x-github-media-type

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#885]
follow up for https://github.com/octokit/rest.js/issues/882#issuecomment-391268967 +@hoducha

- [ ] test pagination scenario in browser

I assume that `x-github-media-type` is not correctly exposed, I’ll look into it. If the API team needs to make changes then it might take some time, but I’ll keep you posted. I’ll create a follow up issue for now

**Comment by hoducha** [comment]
It seems that this is a bug of the API, it does not list the `X-Github-Media-Type` in the [Access-Control-Expose-Headers](https://fetch.spec.whatwg.org/#http-access-control-expose-headers) of the response.

The code bellow print all headers entries of the response:
```js
window
      .fetch("https://api.github.com/users/octocat/orgs", {
        method: "get"
      })
      .then(res => {
        for (let entry of res.headers.entries()) {
          console.log(entry);
        }
      })
      .catch(err => console.error(err));
```

..and it does not contain the `x-github-media-type` entry as expected
```
curl -i https://api.github.com/users/octocat/orgs
```

**Comment by gr2m** [comment]
Same with `Location`. Both need to be added to the `Access-Control-Expose-Headers` Header by the API team. What would be helpful is to create test cases independent of Octokit, just using native fetch in the browser. Then we could share the URL with the test cases with the API team. This is something that the security team will won’t to have close look at, too, to make sure that exposing the new headers does not open an new attack vectors.

Do you think you could create such test cases? It could be a static HTML page with a button that runs a fetch request and an explanation besides it.

**Comment by hoducha** [comment]
The sample code above is independent of Octokit, it uses native fetch in the browser. I created a CodePen snippet test case for this issue: https://codepen.io/hoducha/pen/GGORrK

**Comment by gr2m** [comment]
I’ve pinged the API team again

**Comment by gr2m** [comment]
`X-Github-Media-Type` is now exposed, your example code from https://github.com/octokit/rest.js/issues/882#issuecomment-391268967 is now working in the browser 👌
