### ISSUE TITLE
Rename routes to align better with docs on https://developer.github.com/v3/

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#889]
We are putting a lot of effort into making `@octokit/rest` a natural extension of the REST API docs. The goal is that when new REST routes are released in future they will become available in `@octokit/rest` immediately. 

The way the methods are called is being standardized now so they become more predictable. The downside of it is that we will need to rename a lot of method names. The current stat is 228 out of 474 methods will be renamed. 

In order to make the transition as painless as possible we will make sure to deprecate all methods that have been renamed. So none of your code will be broken and in order to upgrade to the next major release all you’ll need to do is to get rid of all the deprecation notices in your code. v16 won’t have any breaking changes besides the removal of deprecations.

The new method names are not set in stone yet. We are having a wider discussion with GitHub’s Documentation team as well as other Octokit maintainers. If you have any input on the name changes, now is the time :) I’ll take all your input to our upcoming octokit summit where we’ll hopefully make a decision on the method naming.

### How it works

[octokit/routes](https://github.com/octokit/routes) creates JSON files from the current documentation at https://developer.github.com/v3/. It runs a nightly cron job on Travis and each time it finds a change it creates a pull request ([example](https://github.com/octokit/routes/pull/147)). When merged, a new version gets released automatically and a pull request gets created for `@octokit/rest` ([example](https://github.com/octokit/rest.js/pull/876)). When that gets merged a new version of `@octokit/rest` gets released automatically. So we review the changes just to be sure, but the rest is automated.

The method names are based on the new `id-name` property introduced in https://github.com/octokit/routes/pull/158. It's calculated based on the section titles and the routes. As titles might change in future we will make sure that the titles themselves follow certain rules and are validated with a custom linter. That way everyone benefits.

Some of these rules are

1. If the response is paginated, start the title with “List …”
2. If the response returns an array but is not paginated, start the title with “Get all …” or just “Get …”, depending on wether all entities are returned or just a subset, like ["Get top referrers"](https://developer.github.com/v3/repos/traffic/#list-referrers).
3. If the response has no body (204), start the title with “Check …”
4. If the endpoint returns data for the currently authenticated user, don’t refer to them as “a user’s …”. That term is used in titles for endpoints that require a :username parameter.

### List of changed routes as of today (<a id="list-of-changes" href="#list-of-changes">#</a>)

moved to https://github.com/octokit/rest.js/blob/889/generate-routes-for-real/scripts/tmp-route-changes.md

**Comment by sgvictorino** [comment]
Are these routes already changed on a different branch, or is this a proposal for future names?
They look good. 👍

**Comment by gr2m** [comment]
they are proposed for name changes that will happen soon, before v16.0.0. Thanks for reviewing them :)

**Comment by zeke** [comment]
@stale I think this issue is still relevant.

**Comment by gr2m** [comment]
that’s done via https://github.com/octokit/rest.js/pull/1052
