### ISSUE TITLE
How to disable cache

### ISSUE THREAD

**Issue by LijuanZ** [octokit/octokit.js#890]
Hello, I'm using octokit in my node.js SPA and have trouble to disable cache in the requests. 

I tried to get the whole branch list and then create a new branch and fetch branch list again in one of my work flows and these requests happen in less than 1min. The new branch does not exist in my second call of fetching branch list because browser cached the results. I find there is header of Cache-Control: public, max-age=60, s-maxage=60 in the response and believe this is the cause. It works fine if I disable cache in my browser or slow down the work flow to take more than 1min.

I've tried set Cache-Control header in my request to disable cache but failed because of error "Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response."

Is there a way to force octokit to make the request no matter there is cache or not?

Thanks!

**Comment by gr2m** [comment]
Hi @lijuanz thanks for opening the issue!

I’m out right now and can’t help much, but you can pass custom headers to every method, maybe try to pass a header that prevents caching, I thing GitHub’s Rest API docs have some info on that. I’ll have a look tomorrow if you are still stuck on it

**Comment by LijuanZ** [comment]
Hi @gr2m I'm still stuck...Didn't find any cache related custom header in API docs or maybe I'm looking at wrong place. Can you help take a look when have time?

Thanks!

**Comment by gr2m** [comment]
Okay I'm on it

**Comment by gr2m** [comment]
is your code public somewhere?

**Comment by LijuanZ** [comment]
No it's not public. But basically it calls octokit.repos.getBranches(callContext) to get branch list, and then octokit.gitdata.createReference(callContext) to create new branch, and then calls octokit.repos.getBranches(callContext) again. All these requests are from my client side code.

The new branch is created successfully but the second getBranches call doesn't have it because browser reads it from cache.

**Comment by gr2m** [comment]
Usually one would do something like this

```js
  await client.repos.getBranches({
    owner: 'gr2m',
    repo: 'sandbox',
    headers: {
      'cache-control': 'no-cache'
    }
  })
```

But turns out that header is not allowed for cross origin requests. You will see an error like this:

![image](https://user-images.githubusercontent.com/39992/40567076-a99f82d0-6028-11e8-9428-e68ef9f14ab0.png)

I’ll check on that with the AP team. For the time being you can use the `If-None-Match` header as described here: https://developer.github.com/v3/#conditional-requests. If you leave the value empty then it will never match and the server will never return a cached response:

```js
  const {data: branches2} = await client.repos.getBranches({
    owner: 'gr2m',
    repo: 'sandbox',
    headers: {
      'If-None-Match': ''
    }
  })
```

Does that work for you?

**Comment by LijuanZ** [comment]
Yeah, cache-control header was my first attempt but failed on preflight. If-None-Match header with empty eTag does the trick for me! Thank you very much for the help!

**Comment by gr2m** [comment]
Thanks for checking it, glad it works now. Feel free to add comments if you have any follow up questions :)

**Comment by mddanishyusuf** [comment]
@gr2m Thanks for the solution. It's saved my day. :) 

Yes, 'If-None-Match': '' is worked.

**Comment by kabalage** [comment]
I found, that `fetch` accepts a `cache` parameter in `options` that overrides how the browser will use the cache for the request: https://developer.mozilla.org/en-US/docs/Web/API/fetch#cache

`@octokit/request.js` accepts a `request` object in `options` that's getting passed to `fetch` as options:
https://github.com/octokit/request.js/blob/v6.2.2/src/fetch-wrapper.ts#L45

This is my solution to bypass the cache in my case (I'm using `@octokit/request.js` directly, but I believe this should work with the higher level wrappers as well) :

```js
request('GET /user/installations', {
  headers: {
    authorization: `Bearer ${user.token}`
  },
  request: {
    cache: bypassCache ? 'reload' : 'default'
  }
});

```

**Comment by setchy** [comment]
This approach also seems to work 

```
const response =
    await octokit.rest.activity.listNotificationsForAuthenticatedUser({
      headers: {
        'Cache-Control': 'no-cache', // Prevent caching
      },
    });
```
