### ISSUE TITLE
Downloading a tarball of a migration archive

### ISSUE THREAD

**Issue by sgvictorino** [octokit/octokit.js#916]
@gr2m, in response to https://github.com/octokit/rest.js/issues/881#issuecomment-397080133, below I have written a little user story for myself.
Using my #914 branch, I wanted to fetch the download link (to later write into a file) for a user migration in the "exported" state.
Executing the following code (I have authenticated already)
```javascript
octokit.migrations.getUserMigrationArchiveLink(
    {
      migration_id: id
    }, (error, result) => {console.log(result)})
```
displays
```
{ data: <Buffer 1f 8b 08 00 67 58 21 5b 00 03 ec 5b 07 5c 14 d7 d6 c7 04 23 58 10 13 7b f4 39 ac 1d d8 dd 29 db 51 a3 62 89 82 e2 13 44 05 14 67 77 87 dd 81 dd 99 75 ... >,
  status: 200,
  headers:
   { 'accept-ranges': 'bytes',
     'cache-control': 'max-age=2592000',
... 
```
while I expected a URL of this format to be included within `result`: `https://s3.amazonaws.com/github-cloud/migration/...`

How can I successfully fetch this link?

**Comment by gr2m** [comment]
Can you elaborate on why you need the link? The `data` is the content of the archive, you can write it directly into a file

**Comment by bitsol** [comment]
@gr2m Oh, so that's what `data` is. I was confused 😕 .

**Comment by sgvictorino** [comment]
@gr2m Oh, so that's what `data` is. I was confused 😕 . Thanks for clearing that up.

For anyone who's wondering, the intended behavior can be achieved by following the second method of [this tutorial](http://stackabuse.com/writing-to-files-in-node-js/):
```js
fs.open(destination_path, "w", function(err, fd) {
            if (err) {
              throw "could not open file: " + err;
            }
            var buffer = result.data;
            fs.write(fd, buffer, 0, buffer.length, null, function(err) {
              if (err) throw "error writing file: " + err;
              fs.close(fd, function() {
                console.log("wrote the file successfully");
              });
            });
          });
```
where `result` is simply the response from the library's (at PR #914) `octokit.migrations.getUserMigrationArchiveLink` function, `destination_path` is a self-explanatory argument, and `fs` is the Node module that can be required with `require("fs")`.

I'm closing this issue now.

**Comment by gr2m** [comment]
You can simplify the code a little if you like. `result.data` is already a buffer, and instead of using `fs.open` you can use [`fs.writeFile()`](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback).

```js
octokit.migrations.getUserMigrationArchiveLink({migration_id: id}, (error, result) => {
  if (error) {
    // handle request error
  }

  fs.writeFile(destination_path, result.data, (error) => {
      if (error) {
      // handle request error
    }

    console.log("wrote the file successfully");
  })
})

**Comment by sgvictorino** [comment]
😆 I don't know why I kept the instantiation statement in the declaration of the `buffer` variable. 

Thanks for the helpful comments @gr2m! 👍

**Comment by sgvictorino** [comment]
It looks like I have to reopen this issue:

I was testing how my app handles edge cases and came across the fact that when writing the buffer of a migration archive with 40 repositories in it, JavaScript does this: "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory". Did I fill up the heap because of the sheer size of the archive? Is there a way around this issue @gr2m?

**Comment by gr2m** [comment]
It sounds like the file size is to big for the memory available to the node process. In that case you really need to get the URL only and then stream the response directly into a file that you create.

So now the problem is that you can’t use `node-fetch` because it won’t give you the `location` response header for `HEAD` requests until the GitHub API folks expose it correctly, you’ll need to use another request library I’m afraid, like https://www.npmjs.com/package/got or https://www.npmjs.com/package/axios. You’ll have to construct the request yourself. Sorry :(

**Comment by sgvictorino** [comment]
Sorry for the lame question, but what's the proper way to authenticate using `axios` while expecting multiple types (such as "oauth", "basic", etc.)?

Right now I'm doing:

```js
  console.log(authParam); // outputs { type: 'oauth', token: '87ea...' }
  axios
    .get("https://api.github.com/user/migrations/:migration_id/archive", {
      auth: {
        authParam
      },
      headers: {
        Accept: "application/vnd.github.wyandotte-preview+json"
      }
    })
    .then(function(response) {
      console.log(response);
    })
    .catch(function(error) {
      console.log(error);
    });
```
and I get:
```
 data:
      { message: 'Requires authentication',
        documentation_url: 'https://developer.github.com/v3/#authentication' }
```

Thanks again @gr2m!

**Comment by gr2m** [comment]
don’t set the auth option, set the Authorization header to `token ${authParam.token}`

**Comment by sgvictorino** [comment]
@gr2m with
```js
axios
    .get("https://api.github.com/user/migrations/:migration_id/archive", {
      headers: {
        Accept: "application/vnd.github.wyandotte-preview+json",
        Authorization: "token ${authParam.token}"
      }
    })
    .then(function(response) {
      console.log(response);
    })
    .catch(function(error) {
      console.log(error);
    });
```
I now get
```
data:
      { message: 'Bad credentials',...
```
Why is that?

**Comment by sgvictorino** [comment]
The token is a personal access token I generated here: http://github.com/settings/tokens/new

**Comment by sgvictorino** [comment]
@gr2m that's okay. If you would like to help whenever you have time:

I have updated the script to this:
```js
axios.defaults.headers.common = {}
  axios
    .get("https://api.github.com/user/migrations/"+id+"/archive", { // I know the id is valid, as the other octokit calls work to fetch its data
      headers: {
        "Accept": "application/vnd.github.wyandotte-preview+json",
        "Authorization": "token " + authParam.token // This is the personal access token
      }
      })
    .then(function(response) {
      console.log(response);
    })
    .catch(function(error) {
      console.log(error);
    });
```
I receive:

```
Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified
```

I'm not sure why it's saying I'm using multiple auth mechanisms, as this is the only time I even call `axios` in the source code, and in the first line I attempted to reset some headers. Additionally, I have dropped any octokit authentication calls just in case.

**Comment by sgvictorino** [comment]
@gr2m is there a page on the GitHub REST v3 API Docs that talks about authentication headers (by building the request manually)? I can't seem to find one.

**Comment by gr2m** [comment]
It’s described on the landing page of the v3 REST API: https://developer.github.com/v3/#authentication

Then there are also https://developer.github.com/v3/oauth_authorizations/ and https://developer.github.com/v3/auth/

**Comment by sgvictorino** [comment]
Why would it tell me I'm trying to use multiple authentication mechanisms? Removing the "Authorization" header just prompts the response 'Requires authentication'.

**Comment by gr2m** [comment]
I don’t think that this is a GitHub error. `X-Amz-Algorithm` looks like a header for Amazon’s AWS

**Comment by sgvictorino** [comment]
So it's not my code's fault @gr2m?

**Comment by gr2m** [comment]
I really don’t know Solomon. Happy debugging :)

**Comment by sgvictorino** [comment]
I resolved this last Saturday by simply calling `curl` with arguments described in the API docs. The code can be found here: bitsol/migrate-github.js#1. I'm closing this issue now.

If anyone wants to debug the action making this link request with another package with me (perhaps to not have to worry as much about input validation as [I am](https://github.com/bitsol/migrate-github.js/pull/1#issuecomment-399541333) with the current state of bitsol/migrate-github.js#1), they can feel free to open a new issue or reopen this one.

Thank you so much @gr2m for answering all my noob questions about getting this to work. 😄

**Comment by gr2m** [comment]
Great that you got it working now 👍 thanks for sharing your code!
