### ISSUE TITLE
How does authentication work for the tests?

### ISSUE THREAD

**Issue by sgvictorino** [octokit/octokit.js#917]
I have a question about how the `rest.js/test/scenarios` tests work with authentication.

I'm talking about this statement in particular from `rename-repository-test.js`:
```js
        github.authenticate({
          type: 'token',
          token: '0000000000000000000000000000000000000001'
        })
```

How does this pass? Is "0000000000000000000000000000000000000001" a public test key?

Thanks in advance!

**Comment by gr2m** [comment]
It’s working against fixtures, which are coming from https://github.com/octokit/fixtures. We share these fixtures across the Octokits for different languages. The fixtures are served by a static server which you can start with "npm run start-fixtures-server" as described at https://github.com/octokit/rest.js#tests

If you’d like to help record fixtures for migrations I’d be happy to walk you trough it.

**Comment by sgvictorino** [comment]
So the fixtures server is acting as the GitHub API? In this case, accepting "0000000000000000000000000000000000000001" as a key and providing mock responses?

**Comment by gr2m** [comment]
yes, exactly. When recording the fixtures, we normalized them. That way we can run the recording every night with a cron job and see if something changed and act on it. Here is a list of things that get normalized: https://github.com/octokit/fixtures/blob/master/HOW_IT_WORKS.md#normalizations

**Comment by sgvictorino** [comment]
That's cool! Thank you so much @gr2m.
