### ISSUE TITLE
Confusing `createTree` parameter naming

### ISSUE THREAD

**Issue by hiimbex** [octokit/octokit.js#919]
https://github.com/octokit/rest.js/blob/27f334fbf1e206d2ae6d7432d730a6e7bcbd1aa8/lib/routes.json#L2354-L2373

These names with the brackets are pretty confusing to me, especially in the docs: https://octokit.github.io/rest.js/#api-Gitdata-createTree. Is this necessary? [The GitHub API docs for this endpoint](https://developer.github.com/v3/git/trees/#create-a-tree) do not include this.

**Comment by gr2m** [comment]
Yes you are not the first to be confused by it, the better way would be to define the above with

```json
{
  "tree": {
    ...
    "isArray": true,
    "members": {
      "content": {
        "type": "string"
      },
      "mode": {
        "enum": [ 
          "100644", 
          "100755", 
          "040000", 
          "160000", 
          "120000" 
        ], 
        "type": "string" 
      }
    }
  }
}
```

It all grew organically, I plan to change it but it's not a priority right now.

The `content` and `mode` members are defined below the first parameter table in the API docs

![image](https://user-images.githubusercontent.com/39992/41493140-2df0f816-70b9-11e8-8efb-1ce38e29ad6e.png)

**Comment by laughedelic** [comment]
If you're going to change the format the `lib/routes.json`, please consider using JSON Schema (or probably a custom format based on it). This would align it better with #732 which also uses JSON Schema and could simplify TypeScript/Flow/Scala.js types generation (by reusing existing tools).

I think `tree` parameter type would look then like this:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "content": {
        "type": "string"
      },
      "mode": {
        "type": "string",
        "enum": [ "100644", "100755", "040000", "160000", "120000" ]
      },
      "path": {
        "type": "string"
      },
      "sha": {
        "type": "string"
      },
      "type": {
        "type": "string",
        "enum": [ "blob", "tree", "commit" ]
      }
    },
    "required": []
  }
}
```

**Comment by gr2m** [comment]
@laughedelic we are working on using OpenAPI / JSON Schema for octokit/routes, you can follow our progress for it at https://github.com/octokit/routes/pull/168. 

For the JavaScript Octokit the JSON Schema spec is to verbose, the bundle size matters for browsers as well as environments such as lambda, so we will keep some kind of custom format for it.

I think the original question is answered so I’ll close this issue

**Comment by laughedelic** [comment]
I see your point. Great to know that the routes will use JSON Schema though 👍
