### ISSUE TITLE
markdown#render tries to parse HTML as JSON

### ISSUE THREAD

**Issue by goffrie** [octokit/octokit.js#92]
When the method succeeds, the server returns an HTML fragment. Then we try to parse it as JSON, giving an error:

```
{ defaultMessage: 'Internal Server Error',
  message: 'Unexpected token <',
  code: '500' }
```

**Comment by kaizensoze** [comment]
This should hopefully be fixed now: https://mikedeboer.github.io/node-github/#api-misc-renderMarkdown
