### ISSUE TITLE
Refs should not be encoded.

### ISSUE THREAD

**Issue by akosyakov** [octokit/octokit.js#927]
For example looking up all pull requests generate the following URL right now: 
https://api.github.com/repos/theia-ide/theia/pulls?head=theia-demo-plugins%3Amaster&per_page=1

Which returns nothing. Changing `theia-demo-plugins%3Amaster` to `theia-demo-plugins/master` returns a proper result.

In this case it seems that `head` and `base` get encoded.

**Comment by akosyakov** [comment]
My fault, i was using the wrong delimiter `:`, not `/`.

**Comment by akosyakov** [comment]
Actually `:` is correct. It is just if a forked repo is renamed then `ref` apparently should reflect it, e.g `theia-demo-plugins/wiptheia:master`.

**Comment by gr2m** [comment]
Could you share a full code example, the expected outcome and the actual outcome? Ideally a runkit testcase like this https://runkit.com/gr2m/octokit-rest-js-748
