### ISSUE TITLE
Retrieving oauth access tokens via this library

### ISSUE THREAD

**Issue by pastudan** [octokit/octokit.js#936]
It appears that there are some inconsistencies in the Oauth documentation regarding access tokens. When reading through https://developer.github.com/v3/guides/basics-of-authentication/#providing-a-callback, it states:

> Note that you'll probably never access the API through REST. For a more serious application, you should probably use a library written in the language of your choice.

However, https://github.com/octokit/rest.js/issues/500#issuecomment-277021645 states that this library does not handle the oauth callback.

So, am I supposed to make my own request just for the access_token, but for everything else, use this library? If so, could we update the documentation on the web to reflect that? Thanks!

**Comment by gr2m** [comment]
is this for a frontend application where you do the OAuth redirect to github.com? 

This library is currently not accessing anything in the DOM, so we don’t read out any query parameters. You app will have to put together the redirect URL with scopes, client_id and state and then read out the `?code` and `?state` query parameters from `window.location.search`. You will also have to implement the server part where you can request a token for the user based on the `code`, `state`, `client_id` and `client_secret`

What part of the OAuth workflow do you need help with? We plan to create an `@octokit/oauth` package for helping to build both OAuth servers and clients, but it’s not a priority yet. Your input will help us setting the right priorities

**Comment by pastudan** [comment]
I've got the entire OAuth flow implemented and working, however my question was around the docs which suggest API users should probably "never access the API through REST". It seemed odd to provide a client library for every call in the API except the part which handles the code / access_token exchange part.

I think its understandable that this is not a priority, but may I suggest modifying the documentation to make it clear that the octokit libraries do everything _except_ code / access_token exchange, which must be handled by the user?

To help explain, here's my server-side oauth callback route, which has to handle the request to `https://github.com/login/oauth/access_token` on its own using the `request` library, but makes other API calls using octokit.

```js

app.post('/api/access_token', (req, res) => {
  if (!req.body.sessionCode) {
    return
  }

  request.post({
    url: 'https://github.com/login/oauth/access_token',
    json: true,
    form: {
      client_id: clientId,
      client_secret: clientSecret,
      code: req.body.sessionCode
    }
  }, async function (requestError, githubResponse, {error, error_description, access_token}) {
    if (error === 'bad_verification_code') {
      res.status(401).send({error, error_description})
      return
    }

    if (!access_token) {
      res.status(401).send({
        error: 'github_api_error',
        error_description: 'No access token returned from GitHub'
      })
      return
    }

    octokit.authenticate({
      type: 'oauth',
      token: access_token
    })

    const {data: {login, avatar_url}} = await octokit.users.get({})
    res.send({access_token, avatar_url, username: login})
  })
})
```

**Comment by gr2m** [comment]
> May I suggest modifying the documentation to make it clear that the octokit libraries do everything except code / access_token exchange, which must be handled by the user?

We will cover this in another package in future, probably `@octokit/oauth`

**Comment by swhitf** [comment]
While this issue is closed I have just had the same issue OP has.  The documentation literally tells you not to use the API and to download the client library but said library does not support the endpoint being described.

https://developer.github.com/v3/guides/basics-of-authentication/

**Comment by gr2m** [comment]
You can do the `POST https://github.com/login/oauth/access_token` request using [`octokit.request()`](https://github.com/octokit/rest.js#custom-requests)

```js
octokit.request('POST https://github.com/login/oauth/access_token', {
      client_id: clientId,
      client_secret: clientSecret,
      code: req.body.sessionCode
})
```

I agree that it’s odd that there is no REST API method like for all the other REST API endpoints. 

The current methods are all generated automatically based on the current documentation. And the `POST https://github.com/login/oauth/access_token` is currently not documented, besides in the guides. I assume it’s treated differently because it’s not an `api.github.com` endpoint. 

I’ll ask around and let you know what I find out
