### ISSUE TITLE
repos.getContent() 'ref' argument ignored

### ISSUE THREAD

**Issue by michael-riess** [octokit/octokit.js#944]
The getContent function uses the default ref value regardless of what is passed in as an argument.
To recreate the problem, call octokit.repos.getContent() with any hash or branch other than the default.
https://runkit.com/mriess260/5b43a80ab034eb0012c5a245

**Comment by gr2m** [comment]
> Arguably getContent could handle this better though rather than silently ignoring the ref argument.

I think that should be better handled in the REST API, not worked around in the clients. It would be great if you could send a message at https://github.com/contact, maybe they are up for the change. That way everyone benefits :)

Cheers!

**Comment by RupW** [comment]
Thanks - I'd guessed this was an issue with the client assembling the URL, but you're right it's the REST API. Digging a bit, what's happening is that this URL

> https://api.github.com/repos/mriess260/octokit-bug-test/contents/./test.txt/?ref=13a161e8d4ade4444fdb1d945c4c7526a05faf10

redirects to this one

> https://api.github.com/repositories/140327621/contents/test.txt

but drops the ?ref in the process. If you add that back in you get the right version back. (You don't get the redirect with just the 'test.txt' path component.)

I have submitted this on the contact form - thanks.

**Comment by gr2m** [comment]
> I have submitted this on the contact form - thanks.

Thank you! If you get any update on it, I’d appreciate if you would let me know :)
