### ISSUE TITLE
deleteLabel under the issues namespace?

### ISSUE THREAD

**Issue by gautamarora** [octokit/octokit.js#951]
The `issues.deleteLabel` _deletes_ the label from the repo entirely and should probably be under `labels` or `repos` namespace (or documented differently in rest.js) so its clearer in its effect of deleting the label and effectively removing it from all issues.

This will also help differentiate if from the `issues.removeLabel` method that performs label removal from a single issue.

**Comment by gr2m** [comment]
Currently the method scoping aligns with the v3 REST API documentation. There are some pending changes to further align in https://github.com/octokit/rest.js/issues/889 but the *label methods are not affected. For example, the label routes are under the "issues" section: https://developer.github.com/v3/issues/labels/

It’s not perfect and it all has its tradeoffs, but at least we try to be consistent across existing and future octokit libraries. I think create/delete vs add/remove is pretty clear: you _create_ a new label, or you _add_ an existing label to an issue/pr. You _delete_ a label, or you _remove_ a label from an issue/pr. 

Maybe the documentation could be made more clear? The right place to fix it would be the REST API docs though so everyone would benefit.

**Comment by gautamarora** [comment]
i see your point on the label routes being listed under the issues section in the docs. However, the API endpoint itself is just under the repos namespace: `DELETE /repos/:owner/:repo/labels/:name`, which was the basis of my recommendation for having it as `repos.deleteLabel`. Its ok, now I got the hang of why its so in rest.js 😄you're right in that its consistent with the docs.

regarding the delete vs remove, it was above issue of having it under issues was what mainly threw me off at start, makes sense.

I'll close this issue for now, my main motivation was to share my feedback with the team.

p.s. octokit is awesome, i've been loving building apps with probot/octokit. great work!!
