### ISSUE TITLE
Can I remove default user-agent header?

### ISSUE THREAD

**Issue by LijuanZ** [octokit/octokit.js#961]
Hello, I'm using octokit rest client to make GitHub Enterprise API calls in my web app. The client adds user-agent header by default. However, for the APIs of the GitHub Enterprise instance, user-agent is not included in  Access-Control-Allow-Headers response header list returned from preflight request so my API call is blocked. So I'm wondering if it's possible to remove the user-agent header in this case.

Thanks,
Jane

**Comment by gr2m** [comment]
Hi Jane, thanks for letting us know about the issue. I’d suggest to let GitHub support know about it, you can refrence this issue, too: https://github.com/contact

It sounds to me like a bug worth fixing at the source (GitHub Entereprise) so others will benefit, too. 

For the time being, can you try this?

```js
const octokit = require('@octokit/rest')({
  headers: {
    'user-agent': ''
  }
}
```

I assume that won’t work, but wort a try.

Another thing you can do is to use an non-public API: `octokit.hook.before`. Note that this API may change without bumping the major version, so make sure to pin your `@octokit/rest` version until it becomes public

```js
  octokit.hook.before('request', (options) => {
    delete options.headers['user-agent']
  })
```

**Comment by LijuanZ** [comment]
Hi Gregor,


Thank you for the help! However, none of the solutions remove the User-Agent header. It's interesting that the user-agent header of request is still "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134" event after I set

```
headers: {
    'user-agent': ''
  }
```

User-Agent header remains the same when adding octokit.hook.before() api. But it's possible that I didn't call it correctly. My code is like:

```js
octokit.authenticate(authContext);
octokit.hook.before('request', (options: any) => {
delete options.headers['User-Agent']
});
await octokit.users.get({});
```

Is it the right way to call octokit.hoot.before()?

A good thing is the issue only happens in Edge. I tested in Chrome and it works fine.

**Comment by gr2m** [comment]
> A good thing is the issue only happens in Edge. I tested in Chrome and it works fine.

I do not believe that `@octokit/rest` behaves different in edge or chrome. Can you try to send the request directly with the native `fetch()` and see what happens in both browsers? I assume it’s a different handling of CORS in Edge/Chrome

**Comment by LijuanZ** [comment]
Yes, Octokit behaves the same in Edge and Chrome, both of them have User-Agent in request header. It's a different handling of CORS across browsers but the cause is that the access-control-allow-headers returned by preflight request doesn't contain User-Agent. And I could not remove User-Agent header using the solutions you provided previously. Are there any other options I can try?


Thanks,

Jane


________________________________

**Comment by gr2m** [comment]
> the cause is that the access-control-allow-headers returned by preflight request doesn't contain User-Agent

Could you report that to support at https://github.com/contact and keep us posted here? Is that the same on github.com and GitHub Enterprise?

**Comment by LijuanZ** [comment]
I know the cause is user-agent missing in response of preflight. As I said in my initial post, github.com works totally fine in Chrome and Edge because user-agent does exist in the response, GitHub Enterprise doesn't work in Edge.


I've contacted GitHub support about 1 week ago.


Thanks,

Jane


________________________________

**Comment by LijuanZ** [comment]
Hi Gregor, thank you for follow up, below is the response from GitHub recently:

It looks like User-Agent was added to Access-Control-Allow-Headers in GitHub Enterprise 2.14.0 and above.

We are looking into possibly back porting this fix to the earlier supported versions of GitHub Enterprise, however I do not have an ETA on when that would be available. I recommend keeping an eye on our release notes<https://enterprise.github.com/releases> for mention of this landing in a future release of GitHub Enterprise 2.13.


Thanks,

Jane


________________________________

**Comment by gr2m** [comment]
Thank you! Sounds like upgrading GHE to the latest version could resolve the issue for you, is that an option?

**Comment by LijuanZ** [comment]
Well, not exactly. I can upgrade my test GHE to the latest version but could not force my customers to do that. I guess I'll have to tell them it's a known issue in GHE and they need to upgrade to 2.14 to use it in Edge. Thank you for the help!


Thanks,

Jane


________________________________

**Comment by gr2m** [comment]
I fear that will be your best bet. If you could make the point that you have several customers that are blocked by using your service due to the bug in GHE < 2.14, it might further encourage them to backport a fix to previous versions. A fix for their current GHE version might be simpler to apply for your customers than an upgrade to the next version.

Good luck!
