### ISSUE TITLE
Get private repos

### ISSUE THREAD

**Issue by joakimleijon** [octokit/octokit.js#968]
I'm trying to get all private repos for a user through octokit. 

I have tried the function documented in the link below, but it only fetches the public repos for the user.

https://octokit.github.io/rest.js/#api-Repos-getForUser

How can I get a list of the private repos?

**Comment by gr2m** [comment]
Hi Joakim, thanks for the question!

The underlying REST API is https://developer.github.com/v3/repos/#list-user-repositories, I just checked and indeed it does not return private repositories, even when authenticated correctly.

Could you contact support and ask them if this is a bug or a feature? Either way it would be good to amend the documentation for clarity. Changes to the v3 REST API docs will automatically update docs of `@octokit/rest`. You can contact support at https://github.com/contact and reference this issue.

Did you try `octokit.repos.getAll({type: 'private'})`? I just did myself but something didn’t work, it wouldn’t show any repos. I think I miss something but can’t investigate further right now, hope you have more luck!

**Comment by JamesMGreene** [comment]
I believe you would want to use:
`octokit.repos.getAll({visibility: 'private', affiliation: 'owner'})`

https://octokit.github.io/rest.js/#api-Repos-getAll

**Comment by JamesMGreene** [comment]
@joakimlustig Is the user in question the same user that is authenticated with Octokit? I am guessing not.

**Comment by JamesMGreene** [comment]
@gregor The argument would be `visibility: 'private'` (not `type`):

`octokit.repos.getAll({visibility: 'private'})`

**Comment by JamesMGreene** [comment]
Right, it looks like that endpoint is not currently part of the available set for GitHub Apps: 
 - https://developer.github.com/v3/apps/available-endpoints/

If the repos you are trying to find/list are participating in the GitHub App's installation, then you could find them as a subset of the "List installation repositories" call (you would have to filter the list afterward):
 - https://developer.github.com/v3/apps/installations/#list-repositories
 - https://octokit.github.io/rest.js/#api-Apps-getInstallationRepositories

**Comment by JamesMGreene** [comment]
@joakimlustig According to internal sources, the aforementioned [`octokit.repos.getAll({type: 'private'})`](https://octokit.github.io/rest.js/#api-Repos-getAll) call is actually available for GitHub Apps now as of August 9th (1 day after you tried 😆), although the published API documentation does not yet reflect that change.

Feel free to try it again!  If it still does not work, there is a chance that you may be authenticating the request incorrectly.

**Comment by gr2m** [comment]
`octokit.repos.getAll` has been deprecated and renamed to `octokit.repos.list`: https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations

**Comment by gr2m** [comment]
Actually the method to list private repositories is `octokit.repos.list({type: 'private'})`, can you please give that a try?

**Comment by gijswijs** [comment]
`octokit.repos.list({type: 'private'})` works, and `octokit.repos.list({visibility: 'private'})` works as well.

**Comment by danielsimao** [comment]
I'm only able to return public repos. Can't even return my private repo.

**Comment by gr2m** [comment]
@danielmoore can you open a new issue with a minimal test case to reproduce the problem?

**Comment by danielmoore** [comment]
@gr2m I think you meant @danielsimao?

**Comment by gr2m** [comment]
indeed, sorry!

**Comment by gijswijs** [comment]
@danielsimao 
> I'm only able to return public repos

Please check that you have your scopes set correctly.
To have access to the private repos, you have to specifically request repo scope.

More info: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

**Comment by jjxtra** [comment]
I have repo (full access to private repo) in my http header, still only getting public rspos...

**Comment by gr2m** [comment]
You are not correctly authenticated then. Make sure the token you use has the `repo` scope enabled: https://github.com/settings/tokens/new?scopes=repo

**Comment by jonenst** [comment]
Hi,
sorry for posting here as it's not directly related to this project, but some people here mentioned they had internal information. How can we get all the repos (including the private ones) of a user OR an org using the github v3 api (assuming the token provides access to it) ?
/users/:userOrOrg/repos gives public and private repos for users, but only public repos for orgs
/orgs/:userOrOrg/repos gives publi and private repos for orgs, but nothing for users
(I tested everything with the same token, trying for my user and for an org I own)

Thanks in advance

**Comment by gr2m** [comment]
That question is better asked on https://github.community/

**Comment by jonenst** [comment]
https://github.community/t/how-to-get-list-of-private-repositories-via-api-call/120175 had an answer:
https://api.github.com/search/repositories?q=user:USERNAME  works for users and orgs for private and public repos
