### ISSUE TITLE
Handle v3 REST API path changes & GHE versions

### ISSUE THREAD

**Issue by gr2m** [octokit/octokit.js#983]
Case in point: https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

That change will make it impossible to make `@octokit/rest` work for both, github.com and GHE 2.13 and below at the same time.

I’ve no idea how to handle this right now, I’m open to ideas

**Comment by bkeepers** [comment]
> Case in point: https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

@kytrinyx just informed me that the new route has actually been available for over a year, so it should also be available on GHE.

So we should be fine releasing this change. As for the future, I don't think we have a strict policy on how endpoint deprecation gets handled as it relates to GHE (@kytrinyx, @tarebyte correct me if I'm wrong), but I think we can continue to deal with it on a case-by-case basis.

cc @ryangribble

**Comment by gr2m** [comment]
fixed via  https://github.com/octokit/rest.js/pull/982
