### ISSUE TITLE
Method for getting authenticated "user" data

### ISSUE THREAD

**Issue by stephenmathieson** [octokit/octokit.js#990]
Digging thru both this package's API documentation and its `routes.json` file, it doesn't look like there's a way to get data on the authenticated user (see API doc: https://developer.github.com/v3/users/#get-the-authenticated-user). Am I missing something, or is the API missing? If it's missing, would you be up for adding it?

Thanks!

**Comment by gr2m** [comment]
I think the API you are looking for is [`octokit.users.get()`](https://octokit.github.io/rest.js/#api-Users-get)?

**Comment by stephenmathieson** [comment]
Ah, yep, there it is. Thanks!
