### ISSUE TITLE
Github checks api changed

### ISSUE THREAD

**Issue by edvinerikson** [octokit/octokit.js#995]
GitHub checks api has changed params.
https://developer.github.com/changes/2018-08-16-changes-to-the-checks-rest-api/

`filename` is `path`
`warning_level` is `annotation_level`

**Comment by BPScott** [comment]
Will be fixed by the `@octokit/routes` update in #982

**Comment by edvinerikson** [comment]
Thank you! And sorry for a badly structured issue, I realized now that it might not have been forwarded in the most constructive way.
